### ISSUE TITLE
water glitches.

### ISSUE THREAD

**Issue by Luke-Nukem** [Novum/vkQuake#101]
There are two water glitches I can see: first set `r_wateralpha` to anything other than 0 or 1.

* Water has no alpha unless the view is making contact with the water
* Water alpha causes parts of level to be visible depending on depth of the view

The best way I can illustrate this is with a ![screenshot.](https://user-images.githubusercontent.com/2015870/27161418-6ace8ef6-51cf-11e7-9470-4807f47469f2.png)

System is Linux, openSUSE Tumbleweed. Build from [here](https://build.opensuse.org/package/show/home:luke_nukem/vkquake)

**Comment by Novum** [comment]
This happens in glQuake & QuakeSpasm as well. Original levels are not compiled for transparent water.

**Comment by Novum** [comment]
http://vispatch.sourceforge.net/

**Comment by Luke-Nukem** [comment]
@Novum Ah yes, I had completely forgotten about that. Sorry about the late acknowledgement.
