### ISSUE TITLE
Dynamic lights/shadows don't work on GTX 750 ti?

### ISSUE THREAD

**Issue by pat0gen** [Novum/vkQuake#102]
Dynamic lights won't show on my machine in every version since 0.92.0, even though r_dynamic is surely set to "1". 0.91.0 and below seem to work fine.

Also, I can't notice any shadows with r_shadows "1", regardless of version.

Configuration is: Windows 7 x64, GeForce GTX 750  ti, driver version 382.53.

**Comment by Novum** [comment]
You are right about the dynamic lights. I accidentally removed too much code. Fixed in f121e864c11b373849108ee423ecc9c909e0318a

As for the shadows, I don't consider this a working Quake feature and I won't support it.

**Comment by Novum** [comment]
Thanks for the bug report btw. For some reason I completely missed it for a long time.

**Comment by Novum** [comment]
Fixed in version 0.96.1
