### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by appdurov** [Novum/vkQuake#103]
exhaust  OpenSUSE 
cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -I/include -DLINUX -DVK_USE_PLATFORM_XCB_KHR -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -I/usr/include/SDL2 -D_REENTRANT -o snd_mp3.o snd_mp3.c
snd_mp3.c:35:17: fatal error: mad.h: Нет такого файла или каталога
 #include <mad.h>
                 ^
compilation terminated.
Makefile:197: ошибка выполнения рецепта для цели «snd_mp3.o»
make: *** [snd_mp3.o] Ошибка 1
appdurov@linux-wc7s:~/vkQuake/Quake>

**Comment by sezero** [comment]
Looks like you don't have libmad installed on your system.

**Comment by Novum** [comment]
What sezero said. You have to install the library dependencies on Linux.

**Comment by sezero** [comment]
Or, he can invoke make with USE_CODEC_MP3=0 on the command line to disable mp3 support.
