### ISSUE TITLE
Staging buffer synchronization

### ISSUE THREAD

**Issue by cforfang** [Novum/vkQuake#106]
Hi, I'm wondering about the synchronization strategy for the staging buffers. 

My current understanding is that they work like this:
1. `R_StagingAllocate()` returns a pointer into a host-mapped staging buffer and a command buffer.
2. Users, e.g. `GLMesh_LoadVertexBuffer()`, writes their data into the mapped buffer and records commands to copy this data into device-local buffers in the returned command buffer.
3. The staging command buffers are submitted either when the buffer is full or before the main frame command buffer is submitted.
4. Commands in the main frame command buffer use the device-local buffers that have been copied into.

What I'm wondering if there is some synchronization missing here. Without a pipeline-barrier or semaphore it seems like there's no guarantees that a `vkCmdCopyBuffer()` submitted to the staging command buffer will have finished before the copied-to buffer is used in the main frame command buffer. Am I missing something?

As a further example, another user of `R_StagingAllocate()` is ``TexMgr_LoadImage32()``. Here a pipeline-barrier *is* submitted to the staging command-buffer to do a layout transition for the copied-to image, but ``dstStageMask`` is set to ``VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT``:

> vkCmdPipelineBarrier(command_buffer, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, 0, 0, NULL, 0, NULL, 1, &image_memory_barrier);

This alone does not seem to result in an execution dependency and memory barrier between the layout transition and potential use of the image later, because the dependency is between ``ALL_COMMANDS`` and an action command using the image *finishing* (reaching `BOTTOM_OF_PIPE`) and not a stage that would actually use the image (like `FRAGMENT_SHADER`).

Does this sound correct?

(Also, while I'm here just also wanted to say thanks for for writing this! I'm learning a lot studying the code. :)

**Comment by Novum** [comment]
Yes, thanks for reminding me. I wanted to give this attention. Fixed in 7a7ff343d97beb88bba837ff60342e20237002fa

**Comment by cforfang** [comment]
Awesome, that looks good to me. =) Cheers!
