### ISSUE TITLE
Refresh rate bug. Fixed in latest github quakespasm - link inside

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#110]
https://github.com/ericwa/Quakespasm/commit/36dab3581f1056c1af178a0cb1cd2f63044c0ce5
Could we please implement a slider here now, so this bug can be fixed? Thanks :P

Again the bug in question is the refresh rate resetting on changing settings in borderless window and just flat out locking to 60 at startup in fullscreen.
If it changes to 60 in borderless window i have to manually change it in my windows display settings.

Oh and thanks for making vkquake btw. I always dreamed of somthing like vulkan or opengl 4.5/4.6 being used in retro games. :D

**Comment by LethalManBoob** [comment]
vid_desktopfullscreen 1 i have found also fixes this but a refresh rate slider would be a big help :)

**Comment by Novum** [comment]
2a196a71b359353bb06f022581a07c2638249a48
