### ISSUE TITLE
[Question] Support mods

### ISSUE THREAD

**Issue by Nerus87** [Novum/vkQuake#111]
Hi, as in thread, 
- vkQuake will support mods for it?
- I will be able to run Hexen, Hexen 2, Heretic and Kingpin on vkQuake?

**Comment by LethalManBoob** [comment]
Yep. tested it on mods. Its all good.

**Comment by LethalManBoob** [comment]
Seeing as im here. hey can you implement triple buffering?

**Comment by leilei-** [comment]
>I will be able to run Hexen, Hexen 2, Heretic and Kingpin on vkQuake?
Never.

**Comment by Novum** [comment]
Same support for mods than QuakeSpasm.
