### ISSUE TITLE
gl_vidsdl.c:32:24: fatal error: SDL_vulkan.h: No such file or directory

### ISSUE THREAD

**Issue by fade2black244** [Novum/vkQuake#117]
When I try to make the file, it gives me a no such file or directory fatal error. So I literally put the file SDL_vulkan.h in every single directory in the vkQuake directory and it still gives me the same error.

[fatalerror.txt](https://github.com/Novum/vkQuake/files/1308073/fatalerror.txt)

This shows at the end of my terminal session:
gl_vidsdl.c:32:24: fatal error: SDL_vulkan.h: No such file or directory
 #include "SDL_vulkan.h"
                        ^
compilation terminated.
make: *** [gl_vidsdl.o] Error 1

I'm using Debian 9 "Stretch". Any help would be appreciated.

**Comment by LethalManBoob** [comment]
Had same error. You have to grab the latest Vulkan SDK from their website. https://vulkan.lunarg.com/sdk/home

**Comment by Novum** [comment]
You probably want to build a version before 2b503b584dc4485d54a6dccbcd5681b3dfb3f781. Code after that requires SDL 2.0.6 which is not released yet, therefore you probably don't have the necessary headers in sdl-devel.

**Comment by LethalManBoob** [comment]
But i just compiled the lates version just an hour ago and its fine?

**Comment by fade2black244** [comment]
@LethalManBoob I got the latest version of the Vulkan SDK from the link that you sent me: same issue.

**Comment by fade2black244** [comment]
@Novum I tried building with the version above, same issue.

**Comment by sezero** [comment]
vkQuake started using the vulkan functionality from soon-to-be-released SDL2-2.0.6:
That started with commit a69c20b34

If one is compiling for windows, there will be no issues because SDL2-2.0.6 is
included here. However, if one is compiling for Linux, then:
- Either compile SDL2-2.0.6 from latest SDL development tree by yourself
 and build and run vkQuake against it.
- Or: revert vkQuake to revision to commit ee221fac9 or older, and build
 against any SDL2 version.

**Comment by Novum** [comment]
It's not related to the Vulkan SDK at all.

**Comment by fade2black244** [comment]
@sezero Thanks for the explaination. So I chose to compile the source code for SDL2-2.0.6 and installing it from these instructions:
https://wiki.libsdl.org/Installation#Linux.2FUnix

I had no issues with this part.

However, when making the installation for vkQuake ready to be installed it gave me plenty of errors.

Errors are attached on a file:
[errors.txt](https://github.com/Novum/vkQuake/files/1319918/errors.txt)

Any help on getting that to would work be worth a beer.

**Comment by sezero** [comment]
You need Vulkan SDK 1.0.54 or newer: VK_KHR_dedicated_allocation extension began with 1.0.54.

**Comment by fade2black244** [comment]
@sezero 
This is the version that I have installed:

Version / Released | File / SHA 256
-- | --
1.0.61.1              20-Sep-2017 | vulkansdk-linux-x86_64-1.0.61.1.run (20MB)  Latest           0dce8ec27ce74b153483db3cfb210cf974d37c5f637515e1ad5841191e051c79

Source:
https://vulkan.lunarg.com/sdk/home

So that can't be it.

**Comment by Novum** [comment]
You are clearly compiling against an outdated Vulkan header, sezero is completely correct. As for the SDL problem, 2.0.6 has been released.

**Comment by fade2black244** [comment]
I figured it out. I forgot to set the environmental variable path before using the new version of the SDK, thus updating it. Now I'm good with this.

Thanks for all of your help.
