### ISSUE TITLE
QUAKE ERROR: Couldn't create Vulkan device

### ISSUE THREAD

**Issue by fade2black244** [Novum/vkQuake#119]
I use optirun to run all of my graphics-heavy applications. It detects my discreet graphics card in my laptop but it still gives me this error.

Command line: ./vkquake
Found SDL version 2.0.6
Detected 4 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.93.0 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 0.96.2 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 22:44:34 Sep 23 2017
256.0 megabyte heap

**Vulkan Initialization
Xlib:  extension "NV-GLX" missing on display ":0".
Vendor: NVIDIA
Device: GTX 950M
Xlib:  extension "NV-GLX" missing on display ":0".**

ERROR-OUT BEGIN

QUAKE ERROR: Couldn't create Vulkan device

**Comment by Novum** [comment]
Please ask NVIDIA. There is nothing I can do.
