### ISSUE TITLE
Sound Seems to keep cutting out on alt tab.

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#123]
Alt tabbing again sometimes revives it. States in the in game messages that its building stuff like the pipelines or something.

I built it yesterday from the latest master build.

**Comment by Novum** [comment]
From fullscreen? That's expected.

**Comment by Novum** [comment]
Is that really something that's an issue or just an observation? I could probably fix the swap chain issues differently, but it's more work and code.

**Comment by Novum** [comment]
What platform is that? Linux?

**Comment by Novum** [comment]
Is the sound really not coming back?

**Comment by LethalManBoob** [comment]
Windows 10. And it only comes back when i alt tab and even then only 50/50
ever time i tab in will i get a chance to have the sound load in.

**Comment by LethalManBoob** [comment]
and yes fullscreen

**Comment by Novum** [comment]
Fine, I'll fix it differently.

**Comment by Novum** [comment]
Try c8906260d6061d31d4890c813ec720592586d329

**Comment by Novum** [comment]
@LethalManBoob Did that fix the problem?

**Comment by LethalManBoob** [comment]
Yep. Can't seem to trigger the bug anymore. Nice work. :)
