### ISSUE TITLE
Transparent textures glitch?

### ISSUE THREAD

**Issue by dezo2** [Novum/vkQuake#124]
When using vkQuake with Arcane Dimensions mod, there are some glitches in transparent textures. They are visible while using the default "smooth" filtering method and they were also present in previous version. Is it some Vulkan specific thing? They are rendered OK in latest OpenGL Quakespasm. Picture was taken in the beginning of the AD 1.5 update hub, more of it is present in AD Sepulcher map.

![vkquake_alpha_texture](https://user-images.githubusercontent.com/33813081/32995139-b4738490-cd70-11e7-99c9-c6c1c09c0ae0.jpg)

**Comment by dezo2** [comment]
Forgot to add some info: win7x64, nvidia GTX1080, latest drivers 388.31 with default settings, vkQuake with default settings, no AA, AF active.

**Comment by Novum** [comment]
Disable MSAA.

**Comment by Novum** [comment]
There is a potential fix, but I don't know if it will work correctly in all cases. Anyway, this should also happen with OpenGL with driver forced MSAA.

**Comment by Novum** [comment]
This is very curious, I have no idea what's going on. It really doesn't show up like that in GL.

**Comment by dezo2** [comment]
It may be as well a bug in Vulkan or some specific combination of filtering flags with respect to texture size. I can imagine that GL acquired some hacks for this over the years in GPU drivers.

**Comment by LethalManBoob** [comment]
is nothing else dezo. at least having 4xssaa will be just as good and for
my 1080, 16xssaa is almost no hit. Im suprised how little it uses my gpu
with that meny pixels.

**Comment by Novum** [comment]
@dezo2 unlikely that QuakeSpasm will hit any driver workarounds. It must be some specified difference in sampling between GL and Vulkan, but so far I can't find any documentation indicating that.

**Comment by dezo2** [comment]
Its not a big deal, really. Using the pixelated look eliminates this problem anyway. I was just curious if someone else can see that or something is screwed up on my end. Thank you for the reply and all your work on this port.

**Comment by cforfang** [comment]
> It must be some specified difference in sampling between GL and Vulkan, but so far I can't find any documentation indicating that.

GL_LINEAR and GL_NEAREST minification using is at least different, but I don't know if that would cause this. Search for "Mapping of OpenGL to Vulkan filter modes" in the spec, which also describes a way to emulate it.

**Comment by Novum** [comment]
It's not the filter mode. It's an offset of the texture coordinates.

**Comment by dezo2** [comment]
Recent versions seem to be OK, so I am closing this. Thanks.

**Comment by Novum** [comment]
This must be something NVIDIA fixed in their drivers, I didn't change anything. Good to know it's gone.
