### ISSUE TITLE
QUAKE ERROR: Couldn't create window

### ISSUE THREAD

**Issue by BlackSoulxxx** [Novum/vkQuake#126]
Hi, Im running Ubuntu 17.10 with Intel HD4000 (Padoka PPA). Compiled but doesnt run. Previous version working good (the one with SDL files missing when compile, had to revert some files to make it work) on the same setup.

Command line: ./vkquake
Found SDL version 2.0.6
Detected 4 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.93.0 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 0.97.0 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 20:07:29 Nov 24 2017
256.0 megabyte heap

ERROR-OUT BEGIN

QUAKE ERROR: Couldn't create window

vulkaninfo dump:
===========
VULKAN INFO
===========

Vulkan API Version: 1.0.61

INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_unique_objects.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_parameter_validation.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_threading.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_standard_validation.json, version "1.1.1"
INFO: [loader] Code 0 : Encountered meta-layer VK_LAYER_LUNARG_standard_validation
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_object_tracker.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_core_validation.json, version "1.1.0"
INFO: [loader] Code 0 : Meta-layer VK_LAYER_LUNARG_standard_validation all 5 component layers appear to be valid.
INFO: [loader] Code 0 : Found ICD manifest file /etc/vulkan/icd.d/intel_icd.i686.json, version "1.0.0"
ERROR: [loader] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: cannot open shared object file: No such file or directory
INFO: [loader] Code 0 : Found ICD manifest file /etc/vulkan/icd.d/radeon_icd.x86_64.json, version "1.0.0"
INFO: [loader] Code 0 : Found ICD manifest file /etc/vulkan/icd.d/radeon_icd.i686.json, version "1.0.0"
ERROR: [loader] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: cannot open shared object file: No such file or directory
INFO: [loader] Code 0 : Found ICD manifest file /etc/vulkan/icd.d/intel_icd.x86_64.json, version "1.0.0"
INFO: [loader] Code 0 : Found ICD manifest file /usr/share/vulkan/icd.d/radeon_icd.x86_64.json, version "1.0.0"
INFO: [loader] Code 0 : Found ICD manifest file /usr/share/vulkan/icd.d/intel_icd.x86_64.json, version "1.0.0"

Instance Extensions:
====================
Instance Extensions	count = 10
	VK_KHR_external_memory_capabilities : extension revision  1
	VK_KHR_external_semaphore_capabilities: extension revision  1
	VK_KHR_get_physical_device_properties2: extension revision  1
	VK_KHR_surface                      : extension revision 25
	VK_KHR_wayland_surface              : extension revision  6
	VK_KHR_xcb_surface                  : extension revision  6
	VK_KHR_xlib_surface                 : extension revision  6
	VK_EXT_debug_report                 : extension revision  8
	VK_KHR_external_fence_capabilities  : extension revision  1
	VK_KHR_get_surface_capabilities2    : extension revision  1
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete

Layers: count = 6
=======
VK_LAYER_GOOGLE_unique_objects (Google Validation Layer) Vulkan version 1.0.61, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 2
		GPU id       : 0 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 0
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 0

VK_LAYER_LUNARG_parameter_validation (LunarG Validation Layer) Vulkan version 1.0.61, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_GOOGLE_threading (Google Validation Layer) Vulkan version 1.0.61, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 0
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 0

VK_LAYER_LUNARG_standard_validation (LunarG Standard Validation) Vulkan version 1.0.61, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_object_tracker (LunarG Validation Layer) Vulkan version 1.0.61, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_core_validation (LunarG Validation Layer) Vulkan version 1.0.61, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

Presentable Surfaces:
=====================
GPU id       : 0 (Intel(R) Ivybridge Mobile)
Surface type : VK_KHR_xcb_surface
Formats:		count = 2
	B8G8R8A8_SRGB
	B8G8R8A8_UNORM
Present Modes:		count = 3
	IMMEDIATE_KHR
	MAILBOX_KHR
	FIFO_KHR

VkSurfaceCapabilitiesKHR:
=========================

	minImageCount       = 2
	maxImageCount       = 0
	currentExtent:
		width       = 256
		height      = 256
	minImageExtent:
		width       = 256
		height      = 256
	maxImageExtent:
		width       = 256
		height      = 256
	maxImageArrayLayers = 1
	supportedTransform:
		VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
	currentTransform:
		VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
	supportedCompositeAlpha:
		VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR
		VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR
	supportedUsageFlags:
		VK_IMAGE_USAGE_TRANSFER_SRC_BIT
		VK_IMAGE_USAGE_TRANSFER_DST_BIT
		VK_IMAGE_USAGE_SAMPLED_BIT
		VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT
GPU id       : 1 (Intel(R) Ivybridge Mobile)
Surface type : VK_KHR_xcb_surface
Formats:		count = 2
	B8G8R8A8_SRGB
	B8G8R8A8_UNORM
Present Modes:		count = 3
	IMMEDIATE_KHR
	MAILBOX_KHR
	FIFO_KHR

VkSurfaceCapabilitiesKHR:
=========================

	minImageCount       = 2
	maxImageCount       = 0
	currentExtent:
		width       = 256
		height      = 256
	minImageExtent:
		width       = 256
		height      = 256
	maxImageExtent:
		width       = 256
		height      = 256
	maxImageArrayLayers = 1
	supportedTransform:
		VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
	currentTransform:
		VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
	supportedCompositeAlpha:
		VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR
		VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR
	supportedUsageFlags:
		VK_IMAGE_USAGE_TRANSFER_SRC_BIT
		VK_IMAGE_USAGE_TRANSFER_DST_BIT
		VK_IMAGE_USAGE_SAMPLED_BIT
		VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT

Device Properties and Extensions :
==================================
GPU0
VkPhysicalDeviceProperties:
===========================
	apiVersion     = 0x400039  (1.0.57)
	driverVersion  = 71315555 (0x4403063)
	vendorID       = 0x8086
	deviceID       = 0x0166
	deviceType     = INTEGRATED_GPU
	deviceName     = Intel(R) Ivybridge Mobile
	VkPhysicalDeviceLimits:
	-----------------------
		maxImageDimension1D                     = 16384
		maxImageDimension2D                     = 16384
		maxImageDimension3D                     = 2048
		maxImageDimensionCube                   = 16384
		maxImageArrayLayers                     = 2048
		maxTexelBufferElements                  = 0x8000000
		maxUniformBufferRange                   = 0x8000000
		maxStorageBufferRange                   = 0x40000000
		maxPushConstantsSize                    = 128
		maxMemoryAllocationCount                = 4294967295
		maxSamplerAllocationCount               = 65536
		bufferImageGranularity                  = 0x40
		sparseAddressSpaceSize                  = 0x0
		maxBoundDescriptorSets                  = 8
		maxPerStageDescriptorSamplers           = 16
		maxPerStageDescriptorUniformBuffers     = 64
		maxPerStageDescriptorStorageBuffers     = 64
		maxPerStageDescriptorSampledImages      = 16
		maxPerStageDescriptorStorageImages      = 64
		maxPerStageDescriptorInputAttachments   = 64
		maxPerStageResources                    = 250
		maxDescriptorSetSamplers                = 256
		maxDescriptorSetUniformBuffers          = 256
		maxDescriptorSetUniformBuffersDynamic   = 8
		maxDescriptorSetStorageBuffers          = 256
		maxDescriptorSetStorageBuffersDynamic   = 8
		maxDescriptorSetSampledImages           = 256
		maxDescriptorSetStorageImages           = 256
		maxDescriptorSetInputAttachments        = 256
		maxVertexInputAttributes                = 28
		maxVertexInputBindings                  = 28
		maxVertexInputAttributeOffset           = 0x7ff
		maxVertexInputBindingStride             = 0x800
		maxVertexOutputComponents               = 128
		maxTessellationGenerationLevel          = 64
		maxTessellationPatchSize                        = 32
		maxTessellationControlPerVertexInputComponents  = 128
		maxTessellationControlPerVertexOutputComponents = 128
		maxTessellationControlPerPatchOutputComponents  = 128
		maxTessellationControlTotalOutputComponents     = 2048
		maxTessellationEvaluationInputComponents        = 128
		maxTessellationEvaluationOutputComponents       = 128
		maxGeometryShaderInvocations            = 32
		maxGeometryInputComponents              = 64
		maxGeometryOutputComponents             = 128
		maxGeometryOutputVertices               = 256
		maxGeometryTotalOutputComponents        = 1024
		maxFragmentInputComponents              = 128
		maxFragmentOutputAttachments            = 8
		maxFragmentDualSrcAttachments           = 1
		maxFragmentCombinedOutputResources      = 8
		maxComputeSharedMemorySize              = 0x8000
		maxComputeWorkGroupCount[0]             = 65535
		maxComputeWorkGroupCount[1]             = 65535
		maxComputeWorkGroupCount[2]             = 65535
		maxComputeWorkGroupInvocations          = 1024
		maxComputeWorkGroupSize[0]              = 1024
		maxComputeWorkGroupSize[1]              = 1024
		maxComputeWorkGroupSize[2]              = 1024
		subPixelPrecisionBits                   = 4
		subTexelPrecisionBits                   = 4
		mipmapPrecisionBits                     = 4
		maxDrawIndexedIndexValue                = 4294967295
		maxDrawIndirectCount                    = 4294967295
		maxSamplerLodBias                       = 16.000000
		maxSamplerAnisotropy                    = 16.000000
		maxViewports                            = 16
		maxViewportDimensions[0]                = 16384
		maxViewportDimensions[1]                = 16384
		viewportBoundsRange[0]                  =-32768.000000
		viewportBoundsRange[1]                  = 32767.000000
		viewportSubPixelBits                    = 13
		minMemoryMapAlignment                   = 4096
		minTexelBufferOffsetAlignment           = 0x1
		minUniformBufferOffsetAlignment         = 0x10
		minStorageBufferOffsetAlignment         = 0x4
		minTexelOffset                          = -8
		maxTexelOffset                          =  7
		minTexelGatherOffset                    =-32
		maxTexelGatherOffset                    = 31
		minInterpolationOffset                  =-0.500000
		maxInterpolationOffset                  = 0.437500
		subPixelInterpolationOffsetBits         = 4
		maxFramebufferWidth                     = 16384
		maxFramebufferHeight                    = 16384
		maxFramebufferLayers                    = 2048
		framebufferColorSampleCounts            = 13
		framebufferDepthSampleCounts            = 13
		framebufferStencilSampleCounts          = 13
		framebufferNoAttachmentsSampleCounts    = 13
		maxColorAttachments                     = 8
		sampledImageColorSampleCounts           = 13
		sampledImageDepthSampleCounts           = 13
		sampledImageStencilSampleCounts         = 13
		sampledImageIntegerSampleCounts         = 1
		storageImageSampleCounts                = 1
		maxSampleMaskWords                      = 1
		timestampComputeAndGraphics             = 0
		timestampPeriod                         = 80.000000
		maxClipDistances                        = 8
		maxCullDistances                        = 8
		maxCombinedClipAndCullDistances         = 8
		discreteQueuePriorities                 = 1
		pointSizeRange[0]                       = 0.125000
		pointSizeRange[1]                       = 255.875000
		lineWidthRange[0]                       = 0.000000
		lineWidthRange[1]                       = 7.992188
		pointSizeGranularity                    = 0.125000
		lineWidthGranularity                    = 0.007812
		strictLines                             = 0
		standardSampleLocations                 = 1
		optimalBufferCopyOffsetAlignment        = 0x80
		optimalBufferCopyRowPitchAlignment      = 0x80
		nonCoherentAtomSize                     = 0x40
	VkPhysicalDeviceSparseProperties:
	---------------------------------
		residencyStandard2DBlockShape            = 0
		residencyStandard2DMultisampleBlockShape = 0
		residencyStandard3DBlockShape            = 0
		residencyAlignedMipSize                  = 0
		residencyNonResidentStrict               = 0

Device Extensions	count = 23
	VK_KHR_bind_memory2                 : extension revision  1
	VK_KHR_dedicated_allocation         : extension revision  1
	VK_KHR_descriptor_update_template   : extension revision  1
	VK_KHR_external_fence               : extension revision  1
	VK_KHR_external_fence_fd            : extension revision  1
	VK_KHR_external_memory              : extension revision  1
	VK_KHR_external_memory_fd           : extension revision  1
	VK_KHR_external_semaphore           : extension revision  1
	VK_KHR_external_semaphore_fd        : extension revision  1
	VK_KHR_get_memory_requirements2     : extension revision  1
	VK_KHR_image_format_list            : extension revision  1
	VK_KHR_incremental_present          : extension revision  1
	VK_KHR_maintenance1                 : extension revision  1
	VK_KHR_maintenance2                 : extension revision  1
	VK_KHR_push_descriptor              : extension revision  1
	VK_KHR_relaxed_block_layout         : extension revision  1
	VK_KHR_sampler_mirror_clamp_to_edge : extension revision  1
	VK_KHR_sampler_ycbcr_conversion     : extension revision  1
	VK_KHR_shader_draw_parameters       : extension revision  1
	VK_KHR_storage_buffer_storage_class : extension revision  1
	VK_KHR_swapchain                    : extension revision 68
	VK_KHR_variable_pointers            : extension revision  1
	VK_KHX_multiview                    : extension revision  1

VkQueueFamilyProperties[0]:
===========================
	queueFlags         = GRAPHICS | COMPUTE | TRANSFER
	queueCount         = 1
	timestampValidBits = 36
	minImageTransferGranularity = (1, 1, 1)

VkPhysicalDeviceMemoryProperties:
=================================
	memoryTypeCount       = 1
	memoryTypes[0] :
		heapIndex     = 0
		propertyFlags = 0xf:
			VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
			VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
			VK_MEMORY_PROPERTY_HOST_COHERENT_BIT
			VK_MEMORY_PROPERTY_HOST_CACHED_BIT

	memoryHeapCount       = 1
	memoryHeaps[0] :
		size          = 1610612736 (0x60000000) (1.50 GiB)
		flags:
			VK_MEMORY_HEAP_DEVICE_LOCAL_BIT

VkPhysicalDeviceFeatures:
=========================
	robustBufferAccess                      = 1
	fullDrawIndexUint32                     = 1
	imageCubeArray                          = 1
	independentBlend                        = 1
	geometryShader                          = 1
	tessellationShader                      = 1
	sampleRateShading                       = 1
	dualSrcBlend                            = 1
	logicOp                                 = 1
	multiDrawIndirect                       = 1
	drawIndirectFirstInstance               = 1
	depthClamp                              = 1
	depthBiasClamp                          = 1
	fillModeNonSolid                        = 1
	depthBounds                             = 0
	wideLines                               = 1
	largePoints                             = 1
	alphaToOne                              = 1
	multiViewport                           = 1
	samplerAnisotropy                       = 1
	textureCompressionETC2                  = 0
	textureCompressionASTC_LDR              = 0
	textureCompressionBC                    = 1
	occlusionQueryPrecise                   = 1
	pipelineStatisticsQuery                 = 1
	vertexPipelineStoresAndAtomics          = 0
	fragmentStoresAndAtomics                = 1
	shaderTessellationAndGeometryPointSize  = 1
	shaderImageGatherExtended               = 1
	shaderStorageImageExtendedFormats       = 1
	shaderStorageImageMultisample           = 0
	shaderStorageImageReadWithoutFormat     = 0
	shaderStorageImageWriteWithoutFormat    = 1
	shaderUniformBufferArrayDynamicIndexing = 1
	shaderSampledImageArrayDynamicIndexing  = 1
	shaderStorageBufferArrayDynamicIndexing = 1
	shaderStorageImageArrayDynamicIndexing  = 1
	shaderClipDistance                      = 1
	shaderCullDistance                      = 1
	shaderFloat64                           = 0
	shaderInt64                             = 0
	shaderInt16                             = 0
	shaderResourceResidency                 = 0
	shaderResourceMinLod                    = 0
	sparseBinding                           = 0
	sparseResidencyBuffer                   = 0
	sparseResidencyImage2D                  = 0
	sparseResidencyImage3D                  = 0
	sparseResidency2Samples                 = 0
	sparseResidency4Samples                 = 0
	sparseResidency8Samples                 = 0
	sparseResidency16Samples                = 0
	sparseResidencyAliased                  = 0
	variableMultisampleRate                 = 0
	inheritedQueries                        = 1

**Comment by Novum** [comment]
You probably need a newer SDL version

**Comment by BlackSoulxxx** [comment]
Im running the latest SDL provided by Debian/Ubuntu. Not sure what version u specify on?

**Comment by Novum** [comment]
2.0.6 works on Windows, but I don't know if they fixed stuff in 2.0.7 for Linux

**Comment by procedural** [comment]
Compiled it right now - same problem. `vkquake-0.96.2_linux_64.tar.gz` works fine, though! :)

**Comment by procedural** [comment]
Both print same run log with a `Found SDL version 2.0.7` line, but replace a `vkquake` binary from `vkquake-0.96.2_linux_64.tar.gz` with one you get with `make` - boom, doesn't work now :) Maybe some SDL global state shenanigans happening...

**Comment by procedural** [comment]
Given this issue is opened in November, SDL 2.0.6 with Vulkan support was released in September (https://discourse.libsdl.org/t/sdl-2-0-6-released/23109) and vkQuake 0.96.2 running `draw_context = SDL_CreateWindow (caption, SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, width, height, flags);` without returning error code and manually loading Vulkan fine, I can conclude only one thing:

SDL2 is not Vulkan ready yet, it's been only 4 months, not all Linux driver detection could've been tested. :)

I also tried to type the path to loader directly:

```c
  int code = SDL_Vulkan_LoadLibrary("/usr/lib/x86_64-linux-gnu/libvulkan.so");
  printf("SDL_Vulkan_LoadLibrary(): %d\n", code);
```

But it returns an error code `-1`, so yeah. :)

**Comment by procedural** [comment]
Yep, recompiled `vkQuake-0.96.2.zip` with the same SDL 2.0.7: it works.

**Comment by Novum** [comment]
Can you report this to the SDL2 guys?

**Comment by procedural** [comment]
@Novum I don't want to! This is not a beneficial activity for me given that I don't use this library nor do I think it's a good library to begin with. :)

**Comment by Novum** [comment]
Well, then I can't help you. I'm not going to switch back to the old way of doing things. Also I strongly disagree about SDL2. It's extremely well engineered.

**Comment by BlackSoulxxx** [comment]
Well, I tried on my new PC with Nvidia GPU and latest driver with Vulkan.
Same Ubuntu 17.10. Same problem. Guess its not me alone with this...

**Comment by goodjaerb** [comment]
Nope, not alone. I actually just installed 17.10 just so I could try vkQuake and then got this error. Funny enough, since I didn't see any open issues the other day when I looked, I was about to check for closed issues, and then boom, this old issue is re-opened!

Anyway, I just downloaded and compiled the 0.96.2 version mentioned earlier and it worked. Hopefully something changes in the library and the newer version starts working someday.

**Comment by Novum** [comment]
Installed Ubuntu & I can repro this. I'm going to have a look

**Comment by Novum** [comment]
With SDL logging on I'm getting this "Vulkan support is either not configured in SDL or not available in video driver".

I suspect the shipped SDL2 version doesn't have Vulkan support.

**Comment by Novum** [comment]
I compiled SDL 2.0.7 from source with Vulkan support and it does work
![screenshot from 2017-12-27 15-23-18](https://user-images.githubusercontent.com/112222/34393697-f755a812-eb19-11e7-9234-070733b313ef.png)

**Comment by laanwj** [comment]
Yep, can confirm that the Ubuntu 17.10 SDL2 library has this problem. It is version 2.0.6 which has the support but it looks like Ubuntu builds the package without vulkan support.
