### ISSUE TITLE
A scene at the start of E4M7 doesn't look correctly

### ISSUE THREAD

**Issue by pat0gen** [Novum/vkQuake#127]
An invisible shambler chamber at the start of E4M7 is actually rendered:

https://imgur.com/DGRHiVa

Tested it with 0.97.0 Windows x64 executable, NVidia GTX 750Ti graphics, 384.76 driver.

**Comment by Novum** [comment]
83201907f77d4a44f5adf3d8a2701610e1bb3c02

**Comment by Novum** [comment]
Oh and thanks for the report, I wasn't aware.
