### ISSUE TITLE
Classic water warp effect really slow

### ISSUE THREAD

**Issue by mankeli** [Novum/vkQuake#128]
When going under water with the classic water warp effect enabled, the fps drops down to something like 10-20. I'm running 0.97.2 Binaries on Windows 8.2 and my GPU is NVidia GTX 960.

Since the compute shader itself seems to be very simple, maybe the pipeline barriers are causing a some sort of synchronization?

**Comment by Novum** [comment]
No, this must be a driver issue of some sort. Barriers are in the order of microseconds, not milliseconds.

**Comment by Novum** [comment]
Is that a laptop with Optimus?

**Comment by mankeli** [comment]
No, it's a desktop computer with NVidia GTX 960.

**Comment by Novum** [comment]
Then I don't know. There is nothing weird with the barriers which would cause this. Maybe the GPU doesn't raise its clock rate correctly.

**Comment by mankeli** [comment]
Yup, upgrading to 390.65 drivers did indeed fix this.
