### ISSUE TITLE
"Previous Weapon" doesn't work

### ISSUE THREAD

**Issue by FireNX70** [Novum/vkQuake#131]
No mattrer what I bind to it, "Previous Weapon" doesn't work. I'm using 0.97.3 and the original "quake.pak"s.

**Comment by Novum** [comment]
There has been no changes to the input system from QuakeSpasm. Please report this upstream. Also it works fine here.

**Comment by FireNX70** [comment]
Done. It is in fact a quakespasm bug. Weird that it's not happenning to you, I'll wait and see what people say about it.

**Comment by sezero** [comment]
It is not a bug: the previous weapon impulse was added in quake-1.06,
and you are probably using original 1.01 pak files. This should be closed
as invalid.
