### ISSUE TITLE
Show FPS

### ISSUE THREAD

**Issue by ROCKNROLLKID** [Novum/vkQuake#133]
Is there a way to show fps without having to record a demo? If not, I would like to request such a feature to be added.

**Comment by dezo2** [comment]
Open console (~ key) and type scr_showfps 1.

Or better yet - install MSI Afterburner with RTSS and you can toggle displaying FPS in every game you want, including frametimes, charts and all your sensors readings in fully customizable OSD. Precise frame limiting option for all todays APIs included. /end of advertisement :-)

**Comment by ROCKNROLLKID** [comment]
Thank you. I did remember there use to be a console command, but I thought it was like vid_fps 1, which wasn't working. I must have been thinking of Doom. It is weird because even when I looked at quake wiki, this command was not on there: http://quake.wikia.com/wiki/Console_Commands_(Q1)

Anyways, I will close as this has been resolved.
