### ISSUE TITLE
Unable to start (0xc000007b)

### ISSUE THREAD

**Issue by mzryz** [Novum/vkQuake#138]
Just FYI I am new to compiling software and was doing this so that I could learn. I followed the instructions exactly to the letter, but I have a sneaking suspicion as to what the problem is.
My OS: Windows 8.1 x64
But I was forced to compile with the Windows 10 SDK inside visual studio as the Windows 8.1 SDK threw out heaps of 'file cannot be found' errors and wouldn't compile the program. After selecting the Win10 SDK it compiled fine, but then when running the program it crashes with the below error. 

I don't know whether my intuition is right or not, but I thought windows binaries were cross compatible so I don't fully understand the issue.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	vkQuake.exe
  Application Version:	0.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.18969
  Fault Module Timestamp:	5aa29ff0
  Exception Code:	c000007b
  Exception Offset:	00000000000ecf30
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	3081
  Additional Information 1:	ac05
  Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional Information 3:	ac05
  Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900

**Comment by Novum** [comment]
Make sure you install everything in the Visual Studio installer related to C++.
