### ISSUE TITLE
QUAKE ERROR: Couldn't create window

### ISSUE THREAD

**Issue by AlonzoTG** [Novum/vkQuake#139]
[Linux], obviously better error reporting is needed... 

#################
atg@tortoise ~/gamez/quake $ ./run 
Command line: ./vkquake
Found SDL version 2.0.8
Detected 16 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.93.0 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 0.97.3 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 22:25:30 May  8 2018
256.0 megabyte heap

ERROR-OUT BEGIN

QUAKE ERROR: Couldn't create window

**Comment by Novum** [comment]
I added code to print the SDL error (e1cfe4bdff5332154569f8466b063d68a03be288), but I doubt it will help you much. This just means Vulkan isn't working on your system.
