### ISSUE TITLE
sampleRateShading not being enabled at Device creation time

### ISSUE THREAD

**Issue by chronokun** [Novum/vkQuake#140]
API validation layer is reporting:

ParameterValidation (ERROR / SPEC): object: 0x0 type: 0  msgNum: 268437024 - vkCreateGraphicsPipelines(): parameter pCreateInfos[0].pMultisampleState->sampleShadingEnable: The spec valid usage text states 'If the sample rate shading feature is not enabled, sampleShadingEnable must be VK_FALSE' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkPipelineMultisampleStateCreateInfo-sampleShadingEnable-00784)
ParameterValidation (ERROR): object: 0x0 type: 0 location: 1654 msg_code: 268437024: Object: 0x0 | vkCreateGraphicsPipelines(): parameter pCreateInfos[0].pMultisampleState->sampleShadingEnable: The spec valid usage text states 'If the sample rate shading feature is not enabled, sampleShadingEnable must be VK_FALSE' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkPipelineMultisampleStateCreateInfo-sampleShadingEnable-00784)

when creating pipelines with supersampling enabled because: 
device_features.sampleRateShading needs to be assigned the value from vulkan_physical_device_features.sampleRateShading before calling vkCreateDevice()

**Comment by Novum** [comment]
Noticed this as well just an hour later independently 

https://github.com/Novum/vkQuake/commit/1315cad497ff6ce29a2bd09d1a89ae502b4c31cb
