### ISSUE TITLE
No Crosshair

### ISSUE THREAD

**Issue by koogar** [Novum/vkQuake#141]
Crosshair is not visable even when using "crosshair 1"

Thanks for your time :)

**Comment by LethalManBoob** [comment]
I don't have this issue. I know that doesn't help but just to assure everyone that It does work normally.

**Comment by Novum** [comment]
The crosshair goes through the normal UI rendering code, I doubt there is an issue specific to it?

**Comment by Novum** [comment]
Closing this, because I don't think there is an issue.
