### ISSUE TITLE
Crash: "cannot allocate staging buffer space"

### ISSUE THREAD

**Issue by PtrB78** [Novum/vkQuake#143]
vkQuake crashes when loading particular maps with Quake Retexturing Project addon.
To recreate the crash for example run hipdemo3 (hipnotic) or demo2 (rogue). It is important to have new textures install both for Quake and Mission Packs.
Im using latest x64 Windows release of vkQuake.

**Comment by PtrB78** [comment]
I forgot to mention that quakespasm works fine.

**Comment by Novum** [comment]
How big are those textures? Staging buffer is 16MB at the moment.

**Comment by PtrB78** [comment]
the largest textures i found:
window03.tga -  9 437 228 bytes
window03_luma.tga - 9 437 228 bytes
lgmetal.tga - 11 796 524 bytes
Quake texturepack: 813 962 552 bytes
Hipnotic texturepack: 224 308 372 bytes
Rogue texturepack: 339 548 126 bytes.

**Comment by Novum** [comment]
2c3427e080d92239be13cbf5265e214b039b62e8
