### ISSUE TITLE
Viewmodel position issues

### ISSUE THREAD

**Issue by leilei-** [Novum/vkQuake#144]
The implementation of r_viewmodel_quake (added since https://github.com/ericwa/Quakespasm/issues/5 ) doesn't match Quakespasm behavior with scr_sbaralpha 1 and scr_sbarscale 4
![vkmodel](https://user-images.githubusercontent.com/6590431/41378723-7d5aedfa-6f4f-11e8-9285-d0fc410f50c7.jpg)

**Comment by Novum** [comment]
Can't repro, works fine here.

**Comment by Novum** [comment]
Thanks, fixed in 2be1a6a22453c3f7a46323e38536543fb25f797c
