### ISSUE TITLE
multiple vulkan ready GPUs

### ISSUE THREAD

**Issue by mhanor** [Novum/vkQuake#146]
Hello,

This a feature request. In a system where there are multiple vulkan ready GPUs/multiple monitors, vkQuake initializes the first enumerated device. In my case, a Radeon RX480 is attached to the first monitor (as seen by the OS, Windows 10 64-bit 1709), while the Intel 530 onboard GPU is attached to the second monitor. Both monitors are in extended mode, the first is the main screen. The vkQuake, when set to screen resolution or full screen is enabled, initializes itself on the second screen. I have found a workaround, by setting VK_ICD_FILENAMES - read [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md).

**Comment by Novum** [comment]
You can use -device 0, -device 1 etc in the command line to select a different GPU.
