### ISSUE TITLE
Replacement content issue and questions

### ISSUE THREAD

**Issue by Taiyoumaru** [Novum/vkQuake#147]
First off, thank you for your awesome source port. I had the inkling to play some Quake and after trying out some of the engines out there I found vkQuake to be a truly great experience. I absolutely love it.

However once I started fiddling with replacing textures and whatnot I ran into some issues I was hoping you could help me elucidate. So I took a gander at what was available in terms of graphical mods and found this great list here http://quakeone.com/forum/quake-help/general-help/11015-the-definitive-hd-replacement-content-list

I realize most of those were meant for the Darkplaces engine but I gave it a try anyway on vkQuake 1.0.

Now I am completely unsure which of those are supported by vkQuake and I tried finding out as much as I could about quakespasm's feature support but I mostly came up empty-handed as I couldn't find any good documentation.

I am not familiar with coding and all of that so I just winged it. What I did find out is that I could use for instance the Quake Revitalization Project's pk3 textures if I just unzipped them and repacked them into pakX.pak files. This works great in some levels but other levels crash vkQuake and give me the following "Quake Error - Cannot allocate staging buffer space".

I also found out that quakespasm (or vkquake?) doesn't support jpg texture files but that wasn't a problem as I was able to convert seven's lava texture to tga and that worked out great as well with no issues.

So my questions are, how can I fix that error? and what other graphical mods from that quakeone list are supported (with or without minor converting) by vkQuake? Thank you again and sorry for the wall of text.

**Comment by Novum** [comment]
vkQuake is compatible to everything QuakeSpasm is compatible. If you want anything else supported you should poke them. It's not the scope of this project to modify things outside of the renderer.
