### ISSUE TITLE
Makefile:310: recipe for target 'vkquake' failed

### ISSUE THREAD

**Issue by ptrb78** [Novum/vkQuake#148]
When i try to compile vkQuake (latest git) on Ubuntu 18.04 i get this error:
(...)
showtris_frag.o:(.data+0x0): multiple definition of `showtris_frag_spv_size'
showtris_frag.o:(.data+0x0): first defined here
showtris_frag.o:(.data+0x20): multiple definition of `showtris_frag_spv'
showtris_frag.o:(.data+0x20): first defined here
gl_rmisc.o: In function `R_CreatePipelines':
gl_rmisc.c:(.text+0x26c0): undefined reference to `showtris_vert_spv_size'
gl_rmisc.c:(.text+0x26c7): undefined reference to `showtris_vert_spv'
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'vkquake' failed
make: *** [vkquake] Error 1
I am using Nvidia drivers ver 396.24.02 with new spirv compiler.

**Comment by FilipVaverka** [comment]
There seems to be a mistake in Makefile at lines 237 and 238:
showtris_frag.o \
showtris_frag.o

should be:
showtris_frag.o \
showtris_vert.o

**Comment by goodjaerb** [comment]
Fix worked. Thanks.

**Comment by PtrB78** [comment]
Worked for me too.
@FilipVaverka  send a pull request.

**Comment by Novum** [comment]
e4daddfe9abfd36abd026a69ae65c7bdbcda4184
