### ISSUE TITLE
host_maxfps above 72 breaks physics

### ISSUE THREAD

**Issue by Spirrwell** [Novum/vkQuake#149]
So, I downloaded this to give it a try and I couldn't quite figure out why setting my refresh rate to 144 didn't feel like 144 Hz. 

I saw the FPS was limited to around 70, and so I upped the max FPS. This of course gave me the warning that I'm referring to in the title. I definitely noticed the physics felt stuttery after this.

Will this be fixed? Seeing the game run at like 70 FPS on a high refresh rate monitor really hurts.

**Comment by Novum** [comment]
This is an upstream bug. Please forward to QuakeSpasm.

**Comment by ClaymorePT** [comment]
@Spirrwell The 72fps limit is a very old issue with the quake physics engine. 
QuakeSpasm does not decouple the physics from the visual rendering, which creates issues if the FPS is raised above the 72 limit. Players can jump higher, doors and platforms sometimes do not work properly, and other misc issues.

**Comment by ClaymorePT** [comment]
Yes... These new engines really need to decouple the physics from the graphics.

**Comment by Novum** [comment]
ffc9adf2ec52d3b786f6e80c61f3eabea697eacf fixes this
