### ISSUE TITLE
Fedora 29 Linux compiling issue with mp3

### ISSUE THREAD

**Issue by Rugaliz** [Novum/vkQuake#151]
HI

I have both libman and libmpg123 installed however when i try compiling VKQuake v 1.0
i get this error:
`cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -I/include -DLINUX -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -I/usr/include/SDL2 -D_REENTRANT -o snd_mp3.o snd_mp3.c
snd_mp3.c:35:10: fatal error: mad.h: No such file or directory
 #include <mad.h>
          ^~~~~~~
compilation terminated.
make: *** [Makefile:192: snd_mp3.o] Error 1
`

**Comment by Novum** [comment]
You need the dev package installed, not just the library.
