### ISSUE TITLE
Segmentation fault when using "-dedicated" flag on Linux

### ISSUE THREAD

**Issue by nnnn20430** [Novum/vkQuake#152]
When trying to host a dedicated server on linux using the "-dedicated" flag vkQuake crashes with a segfault:

./vkquake -dedicated
Command line: ./vkquake -dedicated
Found SDL version 2.0.8
Detected 4 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.93.0 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 1.00.0 (c) Axel Gneiting & others
Host_Init
Playing registered version.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 16:12:35 Nov  6 2018
256.0 megabyte heap

========= Quake Initialized =========

couldn't exec autoexec.cfg
Segmentation fault

**Comment by Novum** [comment]
I can't debug right now, but you can just use QuakeSpasm as a dedicated server, it is 100% compatible.

**Comment by nnnn20430** [comment]
Yes, i know, it's still a bug, so i reported it.

**Comment by Novum** [comment]
Fixed 82d1a25dbd6a7ab582c3012bbc086de2c91d6578
