### ISSUE TITLE
Blinking screen on IvyBridge when changing resolutions using Vulkan

### ISSUE THREAD

**Issue by cherrysnake** [Novum/vkQuake#153]
I faced following issues with resolution changing:
resolution 1600*1200; fullscreen on -> apply changes- bottom edge of screen is blinking with some random content and game won't start after reentering;
resolution 800*600, fullscreen on -> apply changes, exit game - sometimes changes user settings resolution of the screen when game is exited and also crashes the game after restart;
resolution 680*400; fullscreen on -> apply changes and restart the game - game crashes on start showing its console or just black screen. 

Fullscreen OFF mode is working much more better for mentioned resolutions. 

No game or other dmesg message while it's happening. Also tried to launch it using gdb but also no error messages.
Here is output:
[test@test-pc Quake]$ gdb vkquake
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from vkquake...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/test/Work/vkQuake/Quake/vkquake 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Command line: /home/test/Work/vkQuake/Quake/vkquake
Found SDL version 2.0.8
Detected 4 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.93.0 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 1.00.0 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 11:07:02 Nov 13 2018
256.0 megabyte heap
[New Thread 0x7fffe2dfb700 (LWP 21618)]

Vulkan Initialization
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete
[New Thread 0x7fffe14e1700 (LWP 21619)]
Vendor: Intel
Device: Intel(R) Ivybridge Desktop
Using VK_KHR_DEDICATED_ALLOCATION
Using A2B10G10R10 color buffer format
Using X8_D24 depth buffer format
Creating command buffers
Initializing staging
Creating descriptor set layouts
Initializing dynamic vertex buffers
Initializing dynamic index buffers
Initializing dynamic uniform buffers
Initializing samplers
Creating pipeline layouts
Using IMMEDIATE present mode
fpCreateSwapchainKHR
Creating color buffer
AA disabled
Creating depth buffer
Creating render passes
Creating frame buffers
Creating pipelines

Sound Initialization
[New Thread 0x7fffbf3dd700 (LWP 21621)]
[New Thread 0x7fffbf39c700 (LWP 21622)]
SDL audio spec : 44100 Hz, 1024 samples, 2 channels
SDL audio driver: pulseaudio - Built-in Audio Analog Stereo, 65536 bytes buffer
Audio: 16 bit, stereo, 44100 Hz
CDAudio disabled at compile time

========= Quake Initialized =========

execing quake.rc
execing default.cfg
execing config.cfg
couldn't exec autoexec.cfg
3 demo(s) in loop
Shutting down SDL sound
[Thread 0x7fffbf39c700 (LWP 21622) exited]
[Thread 0x7fffbf3dd700 (LWP 21621) exited]
[Thread 0x7fffe2dfb700 (LWP 21618) exited]
[Thread 0x7fffe14e1700 (LWP 21619) exited]
[Inferior 1 (process 21612) exited normally]
(gdb)

Also screen is blinking while game is starting and while entering Options menu. 

Environment: Linux Manjaro; kernel 4.18.12-1-MANJARO; IvyBridge CPU: Intel Core i5-3470; GPU: Intel® HD Graphics 2500; Vulkan 1.1.80
Blinking while game launching is also observed on KBL but not the mentioned resolution problem.
Could you please look at it?

**Comment by cherrysnake** [comment]
I've investigated this behavior a little bit more and looks like that was not a crash but game UI gets not visible. Just filled with some color (lime in my case) screen is shown.
In case of "1600x1200 resolution + fullscreen on" game cannot be started from time to time.

**Comment by Novum** [comment]
I'm pretty sure this is a driver issue.

**Comment by Novum** [comment]
Closing this as it's not app related.
