### ISSUE TITLE
vkQuake on Linux Ubuntu 18.04.1 64-bit doesn't work.

### ISSUE THREAD

**Issue by Soreo** [Novum/vkQuake#154]
I create folders Quake - id1 and and put in and put in pak0.pak. Nothing happens!
Quakespasm works fine! vkQuake for Linux is dead. Does not work.

I have Nvidia GeForce GTX 1050 ti 4 Gb with driver 415.13 from PPA.

https://cdn1.savepice.ru/uploads/2018/11/26/af7fb00a6549d4b6ac65e7eb4efb556d-full.png
https://cdn1.savepice.ru/uploads/2018/11/26/6f9613f5a50196a52825b6cfc6e24b53-full.png

vkQuake for Linux needs to fix. My video card support API Vulkan.

Sorry for my bad english.

**Comment by Novum** [comment]
vkQuake works fine.
