### ISSUE TITLE
You wrote: "Ubuntu ships an SDL2 version that does not support Vulkan."

### ISSUE THREAD

**Issue by Soreo** [Novum/vkQuake#155]
You wrote: "Ubuntu ships an SDL2 version that does not support Vulkan."

I have Dota 2, Serious Sam 2017 Fusion and Doom (2016). These games work great with API Vulkan.

You have posted vkQuake on Application Center Ubuntu. But vkQuake does not work.
https://cdn1.savepice.ru/uploads/2018/11/28/0931c7e4f274c5ebbb7377d3f07fd83f-full.png

Please help how to run vkQuake on Ubuntu 18.04.1 64-bit?

**Comment by Novum** [comment]
Those games are not using the system SDL2 library.
