### ISSUE TITLE
underwater fx classic bug

### ISSUE THREAD

**Issue by thokis** [Novum/vkQuake#156]
Im running the latest master compiled on my machine. My gpu is RX580 with opensource amdgpu driver. The underwater fx is bugged when the statusbar alpha is set to 0. i uploaded an unlisted [video](https://youtu.be/I15qt2w2EpA) to youtube. Also a quick report of gamma settings are interpreted to high in vkquake. quakespasm with value gamma "1" looks right. But vkquake is way too bright and washed out. I have to increase gamma to 1.5 to make it look right.

**Comment by Novum** [comment]
Gamma is identical to QuakeSpasm. Please report that to the amdgpu guys, this is a driver bug.
