### ISSUE TITLE
Please consider forking the yamagi quake instead of this.

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#157]
The amount of modernisation features like binds that actually save and an actually usable console as well as mouse wheel weapon swapping make this completely unplayable to someone like me. 

The config file doesnt even seem to be obtainable. Its not in the main file nor the documents or app data folders.

Theres not even a dedicated apply button to changing settings.

**Comment by Novum** [comment]
Are you talking about vkQuake 2? That has nothing to do with me.

**Comment by LethalManBoob** [comment]
Accident. Sorry.
