### ISSUE TITLE
VkDescriptorSet leak / descriptor pool reset needed

### ISSUE THREAD

**Issue by chronokun** [Novum/vkQuake#160]
R_CreateDescriptorPool() only reserves a single VK_DESCRIPTOR_TYPE_STORAGE_IMAGE yet each warp image created by TexMgr_LoadImage32() allocates a new descriptor set with type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE and since vkResetDescriptorPool() is never called, validation reports immediately on level load:

>  [ VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307 ] Object: 0x13 (Type = 22) | Unable to allocate 1 descriptors of type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE from pool 0x13. This pool only has 0 descriptors of this type remaining. The Vulkan spec states: descriptorPool must have enough free descriptor capacity remaining to allocate the descriptor sets of the specified layouts (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307)

**Comment by chronokun** [comment]
I think GL_DeleteTexture() needs:

> vkFreeDescriptorSets(vulkan_globals.device, vulkan_globals.descriptor_pool, 1, &texture->warp_write_descriptor_set);

and the else clause for "if (warp_image)" in TexMgr_LoadImage32() should ensure that 
>glt->warp_write_descriptor_set = VK_NULL_HANDLE;

and setting pool descriptorCount for VK_DESCRIPTOR_TYPE_STORAGE_IMAGE slightly larger it should then work.

**Comment by Novum** [comment]
Seems like old validation layers didn't catch this for some reason. Thanks.
89f0979b1c86b7923b5ddeebde06791018fd3eea
