### ISSUE TITLE
Choppy, very unstable frame rate in Windows.

### ISSUE THREAD

**Issue by gerryhernandez** [Novum/vkQuake#162]
Hello there. I've turned to this project to use as a tinkering/learning/sandbox environment for me to learn graphics programming in general, but specifically Vulkan. I'd like to get everything working correctly before I start to tinker.

**Symptom**: 
Doing absolutely nothing, other than loading the "new game" map and sitting there, the frame rate is choppy and stutters. Visually, you can see the skybox animation getting stuck a few times per second. Turning on the FPS counter, it fluctuates between the default 72 FPS cap and 14 FPS. Just to be clear, with or without the FPS counter enabled, the frame rate is still unstable. During gameplay, this manifests as random hiccups where the game essentially freezes for split seconds at a time, anywhere on any map with or without any activity.

**My environment**:
Hardware is more than capable: 32 gb RAM, i7-3770k, Nvidia 980ti. Vanilla QuakeSpasm (OpenGL) runs just fine. To reduce variables, I'm running at default settings with nothing changed. Using shareware pak0, if that matters. I've built this in Windows using Visual Studio 2017, Windows 10 SDK v10.0.17763.0, Vulkan/LunarG SDK v1.1.97.0. The device initialization code is correctly picking the 980 Ti GPU (just in case). I've built in release and debug builds, with and without diagnostics monitoring attached and the results are the same.

Interestingly, I do see this in the debug output when enabling the FPS counter:

```
The thread 0x3f40 has exited with code 0 (0x0).
The thread 0x3168 has exited with code 0 (0x0).
The thread 0x2110 has exited with code 0 (0x0).
The thread 0x9c0 has exited with code 0 (0x0).
The thread 0x3d88 has exited with code 0 (0x0).
..
...
.....
....... etc
```

Please let me know if there's any other useful information I could provide. Thank you for publishing this project; it's a fantastic education tool!

**Comment by gerryhernandez** [comment]
Total noob here, so bare with me. I'm just trying to figure this out and hopefully provide more helpful information.

I ran RenderDoc and captured a frame. I got tons of performance warnings during the sky and water/lava rendering, where the textures are getting warped and blitted. I went ahead and removed rendering of these altogether, but the issue still persists.

I put everything back and profiled the front-end code as much as I could, which is semi-random since the performance spikes tend to be semi random. It looks like I found spiky correlation with the call to `fpQueuePresentKHR` inside of `GL_EndRendering`. Out of, say, 10 profile captures, that call tends to take either very little time, or a vast majority of CPU time. This leads me to believe that `fpQueuePresentKHR` (`vkQueuePresentKHR` in most other example code) is blocking for long periods of time under certain circumstances. If this is true, and what those circumstances are, I have no clue.

So I went ahead and forced FIFO and Mailbox presentation modes (immediate mode is not supported by Nvidia at the moment) to see if that would make a difference. It did not.

I hope this helps. I'll try to tinker some more later.

**Comment by Novum** [comment]
It's a system problem. I can run vkQuake on a complete potatoe at 60FPS easily.

**Comment by gerryhernandez** [comment]
Closed already, without any discussion?

I’m on the latest drivers, QuakeSpasm runs perfectly (OpenGL), and vkQuake2 runs perfectly. Unreal Engine with Vulkan runs perfectly. 

I got into the Vulkan Discord and someone else with a similar system volunteered to build and run vkQuake and got the same results that I got. 

I can understand you not wanting to fix this, but can you at least point me in the general direction?

**Comment by gerryhernandez** [comment]
Can you list exact versions of your Vulkan SDK and Windows SDK?

**Comment by Novum** [comment]
There is no discussion, because this is certainly not a vkQuake bug.

**Comment by LethalManBoob** [comment]
You can always try display driver uninstaller.

**Comment by Novum** [comment]
I literally have tested this on 5 different Windows 10 installation with Intel, AMD & NVIDIA cards and none of them have any issues.
