### ISSUE TITLE
Out of dynamic vertex buffer space

### ISSUE THREAD

**Issue by shoober420** [Novum/vkQuake#164]
I'm playing the "Scourge of Armagon" mission pack, and encountered an error on the map "Research Facility" (HIP1M4).

QUAKE ERROR: Out of dynamic vertex buffer space, increase DYNAMIC_VERTEX_BUFFER_SIZE_KB

This occurs when I pick up the quad damage in the map. Its reproducable everytime.

**Comment by rg3** [comment]
Can you see if patch https://github.com/rg3/vkQuake/commit/0dff4bafd68d24e4ba95ae2d012676790a4f6306 fixes the problem? If it does I can submit a pull request.

**Comment by Novum** [comment]
I don't want to just bump the sizes. There should probably be a dynamic increase if necessary like I did for texture staging memory.

**Comment by shoober420** [comment]
Hey, sorry I haven’t checked this. I will first thing tomorrow.

**Comment by shoober420** [comment]
I compiled vkquake with the changes to gl_rmisc.c and this did indeed fix the crash.

**Comment by rg3** [comment]
> I don't want to just bump the sizes. There should probably be a dynamic increase if necessary like I did for texture staging memory.

I've read the code a bit and it doesn't look complicated. I may give it a try in the next few days and submit a PR with that if I find the time. :+1:

**Comment by rg3** [comment]
I just submitted a pull request for this (#165). Let me know what you think.

**Comment by Novum** [comment]
a2ea879a1e7f4253da84e653ed56494667b64687
