### ISSUE TITLE
update to quakespasm 0.93.1

### ISSUE THREAD

**Issue by montvid** [Novum/vkQuake#166]
Hi, quakespasm-0.93.1 released 2018-06-06 - maybe a good idea to upgrade from 0.93.0?

**Comment by fagoatse** [comment]
it's literally only 1 commit behind right now.

**Comment by montvid** [comment]
https://github.com/Novum/vkQuake/blob/55755e6ece871b037899b1e9bd0fb52aa673abb7/Quake/quakedef.h

Well it is 0.93.0, it should be 0.93.1 if the 0.93.1 is merged.

**Comment by Novum** [comment]
deacf7ca9c8b9c847954632b5d602ffe27305a87
