### ISSUE TITLE
r_lightmap 1 not working

### ISSUE THREAD

**Issue by Rikoshet-234** [Novum/vkQuake#168]
![vkquake0003](https://user-images.githubusercontent.com/34555340/55226815-339a0200-5216-11e9-990d-9576ea66b72a.png)
r_lightmap 1 is not working correctly. when the value is 1 I get a black sky and a lightmap with textures. I. e. all that changes is the sky, and there is no way to view the lightmap correctly

**Comment by Novum** [comment]
Not supported. Please use QuakeSpasm for development purposes.
