### ISSUE TITLE
Getting stuck on some ramps

### ISSUE THREAD

**Issue by Greenwood72** [Novum/vkQuake#170]
Hello, Axel.

I wanted to let you know that on occasion there is a glitch where the player gets stuck going down a ramp. It happens on E1M1 when you try to run down, away from the exit teleport, to go back to get something. It is almost like the point where the bend is creates a wall. It can be easily avoided by jumping or trying to go back and forth and again it only happens sporadically. I also noticed it on a map in Dimensions of the Past. This particular oddity doesn't occur with regular Quakespasm or Quakespasm Spiked. It just seems like a brush with a 120 degree angle sometimes doesn't play nice.

It's probably a minor thing and you might already be aware of it. I just wanted to point it out. I really like vkQuake and in general have zero problems with it. Texture and models work too. I appreciate your contribution to the Quake community!

**Comment by Novum** [comment]
This is extremely odd because I made zero changes to the game code or physics. Are you running at comparable frame rates?

**Comment by Greenwood72** [comment]
Axel, I double checked: Quakespasm has the issue too. I downloaded it again
and checked frame rates via scr_showfps. Both (yours and regular) played at
approx. 70 fps.

I actually misstated earlier. *Quakespasm Spiked* was the source port that
worked flawlessly. No hiccups. Whoever built that port added some extra
magic including "High framerates no longer affect physics." It also accepts
PNG textures and other nice features.

Maybe you might want to consider switching over to the "spiked" version. It
looks and acts like regular Quakespasm, just with some nice extra features.
Here's their website: http://triptohell.info/moodles/qss/

Again, I am sorry if I troubled you. I just think your source port is quite
nice. I love the idea of using Vulkan; however, that ramp bug ... well, it
bugs me. It can be especially annoying during the heat of battle.

**Comment by LethalManBoob** [comment]
not gonna lie it would be awsome to run vkquake at 250fps @240hz stable.

**Comment by Novum** [comment]
ffc9adf2ec52d3b786f6e80c61f3eabea697eacf

**Comment by Greenwood72** [comment]
Alex,

I noticed that vkQuake doesn't render transparency within 3D models. Areas
meant to be transparent are filled in black. Oddly enough, regular
Quakespasm does. Again this is transparency within 3D models, not regular
geometry textures. Either than that, your port is performing well!
