### ISSUE TITLE
Missing memoryBarrierCount?

### ISSUE THREAD

**Issue by per-mathisen-arm** [Novum/vkQuake#171]
https://github.com/Novum/vkQuake/blob/deacf7ca9c8b9c847954632b5d602ffe27305a87/Quake/gl_rmisc.c#L406

A memory barrier is passed in here, but its memory barrier count is passed as zero. I assume that is not intended?

**Comment by Novum** [comment]
Yes. 95b938836493cba26cc110e341343c1de59af00e.
