### ISSUE TITLE
No proper Vulkan shutdown

### ISSUE THREAD

**Issue by per-mathisen-arm** [Novum/vkQuake#174]
In gl_vidsdl.c function VID_Shutdown(), shouldn't there be calls to
```
        vkDestroyDevice(vulkan_globals.device, NULL);
        vkDestroyInstance(vulkan_instance, NULL);
```
to cleanly shut down Vulkan? I do not see such cleanup calls anywhere.

**Comment by Novum** [comment]
I don't care. OS and driver will clean up whatever is left behind.
