### ISSUE TITLE
Loading a quicksave from startup results in no mouse movement with -fitz

### ISSUE THREAD

**Issue by MrEWhite** [Novum/vkQuake#177]
Whenever you load a quicksave right after booting the game with mouselook enabled, the mouse doesn't work. You have to open and close the menu to get the mouse to work again.

This seems to only happen when I use the -fitz parameter to get the demo to play in the background of the menu and get the regular console, getting rid of it stops this from happening.

This doesn't happen with Quakespasm Spiked, but does seem to happen with regular Quakespasm.

**Comment by mjr4077au** [comment]
I've observed this as well. Opening the menu and escaping back to the game allows the mouse to work again (only a workaround).

**Comment by mjr4077au** [comment]
I've done further testing on this, only protocol 666 is affected. If I change to protocol 15 prior to loading the save (or call vkquake.exe with "-protocol 15" in addition to "-fitz"), there is no issue.

**Comment by Novum** [comment]
I suggest reporting this to QuakeSpasm instead, I don't want to diverge too much from them.

**Comment by mjr4077au** [comment]
Is upstream even active though? Their bug tracker on SourceForge seems dead to me, or is that not their primary bug tracker?

**Comment by mjr4077au** [comment]
> QuakeSpasm is alive and well, just a bit slow moving.

The reason I say that is although I see SVN commits here and there, they don't really seem to answer or use their bug tracker ([https://sourceforge.net/p/quakespasm/bugs/](url)).

Personally I've just stopped using '-fitz' as I only added it so the demos play (I just got over it). Really appreciate all your efforts though :). Probably just close this one off unless @MrEWhite objects.

**Comment by MrEWhite** [comment]
> 
> 
> > QuakeSpasm is alive and well, just a bit slow moving.
> 
> The reason I say that is although I see SVN commits here and there, they don't really seem to answer or use their bug tracker ([https://sourceforge.net/p/quakespasm/bugs/](url)).
> 
> Personally I've just stopped using '-fitz' as I only added it so the demos play (I just got over it). Really appreciate all your efforts though :). Probably just close this one off unless @MrEWhite objects.

If it's because the author of vkQuake wants to remain similar to QuakeSpasm, that's fine.
