### ISSUE TITLE
libmikmod really needed?

### ISSUE THREAD

**Issue by shoober420** [Novum/vkQuake#178]
Quakespasm doesn’t use libmikmod for any audio playback, or doesn’t need it to do so. Why does vkquake need this package then? vkquake won’t even compile without the libmikmod package installed...

Can you simply opt for audio playback the exact same way quakespasm does?

**Comment by Novum** [comment]
There are no code changes related to this vs QuakeSpasm

**Comment by Novum** [comment]
I checked the makefiles as well, there is really no difference. Closing this.

**Comment by shoober420** [comment]
Awesome, it was a compile setting in the PKGBUILD. Thanks for clarifying that.
