### ISSUE TITLE
Game using my second monitor refresh rate instead of main monitor if something is running in the background.

### ISSUE THREAD

**Issue by vocaab** [Novum/vkQuake#182]
My main monitor is 240hz, and my second monitor is 60hz. If I have something like a stream open on my second monitor, vkQuake will be running at 60hz. As soon as I close a stream it will be running fine again., This does not happen with Quakespasm. I have noticed vkQuake doesn't use true fullscreen like Quakespasm and might have something to do with the behavior I'm observing.

**Comment by Novum** [comment]
There is no "true fullscreen" with OpenGL. Its all in the control of the driver.

**Comment by Novum** [comment]
That being said, there is `VK_EXT_full_screen_exclusive` which addresses this issue, but no mainstream driver supports that yet.

**Comment by LethalManBoob** [comment]
If using that _ext could help with the input lag i experience, i would say you should do so whenever the drivers support it.

**Comment by Novum** [comment]
c89ddcf254e441e1636b7a3d0cd0cc433933f014
