### ISSUE TITLE
no good performance with new SDL

### ISSUE THREAD

**Issue by andreluizgit** [Novum/vkQuake#187]
I recompiled with new commits (new SDL) but when I run it seems vkquake gets many lag's ...

I found the issue in other Report (FullScreen mode is the problem) : 
[discourse.libsdl.org/t/application-framerate-drops-significantly-in-fullscreen](https://discourse.libsdl.org/t/application-framerate-drops-significantly-in-fullscreen/26416)

When I change to NO fullscreen the lag's go away !

**Comment by Novum** [comment]
Doubtful this is related to SDL updates. SDL2 doesn't do more than give me a surface handle for the Window, everything else is vkQuake code.
