### ISSUE TITLE
vkQuake crashes if set "-particles" to high value and cause lots of particles like blood etc (doesn't crash in normal Quakespasm)

### ISSUE THREAD

**Issue by Swallagoon** [Novum/vkQuake#188]
Increasing -particles value in normal Quakespasm allows more particles to be displayed at one time (blood/explosions etc etc). You can set it really high and literally have thousands of particles on-screen. The monster spawn particle effect (teleport effect) doesn't crash.

vkQuake crashes if you set the -particles value to about 6000 or above in my testing and then trigger a monster spawn in-game. The teleport effect particles that generate when a monster spawns crashes the game.

Edit:
Just any time there are loads of particles on screen it crashes. Rocket a dozen or so monsters and it often crashes. Any time the "Reallocating dynamic VBs" messages pop up in-game over 1MB.

My logs show these entries:

**Reallocating dynamic VBs (1048576 KB)**

**QUAKE ERROR: vkAllocateMemory failed**

**Comment by Novum** [comment]
What driver and OS is this? Allocating 1MB shouldn't fail.

**Comment by Swallagoon** [comment]
I’m running Win10 Enterprise 2019 LTSC (1809) with a GTX 1080 and NVIDIA driver 436.30.

**Comment by Novum** [comment]
Thanks, there was a bug in the realloc
0a6540aeb69d40ccb240f19a3521d50a271b1eab

**Comment by Novum** [comment]
https://github.com/Novum/vkQuake/releases/tag/1.03.0
