### ISSUE TITLE
Transparency within 3D models doesn't render

### ISSUE THREAD

**Issue by Greenwood72** [Novum/vkQuake#191]
Alex,

I noticed that vkQuake doesn't render transparency within 3D models. Areas meant to be transparent are filled in black. Oddly enough, regular Quakespasm renders this fine. Again this is just transparency within 3D models, not regular geometry textures. Either than that, your port is performing well!

**Comment by Novum** [comment]
Can you give an example where this happens?

**Comment by Greenwood72** [comment]
Sure! If you install Redfield's map,*The Deepness Below*, you will see
black boxes around the seaweed. In regular Quakespasm this does not exist.
https://www.quaddicted.com/reviews/deepness.html

Coincidentally, Redfield made some custom animated 3D sails for the ghost
ship in my entry to the upcoming Halloween Jam (see attached). The tears do
not render correctly in vkQuake (Quakespasm was used for the screenshot).

- Greenwood

**Comment by Swallagoon** [comment]
I noticed this too. With the latest nvidia drivers on Win10 with a gtx1080 it does this. Any model that uses palette colour 255 for transparency just shows as opaque black.

On the slightly older AMD RX 480 card the entire model actually goes mostly invisible and jittery with graphical glitches. The sails in your new Halloween map are literally mostly invisible.

**Comment by Novum** [comment]
![image](https://user-images.githubusercontent.com/112222/68096507-b9e68880-fe76-11e9-8907-e3e298b407ad.png)
Fixed b04765ef72c3320d29f18ad8f2a5d1cf09797c1f

**Comment by Novum** [comment]
https://github.com/Novum/vkQuake/releases/tag/1.03.0
