### ISSUE TITLE
Fullscreen on Mac immediately stuttering when using Game menu

### ISSUE THREAD

**Issue by tomgreen66** [Novum/vkQuake#192]
When running `vkquake` in macOS Mojave in fullscreen the game stutters - its hard to navigate the game menu and this persists into the game itself.  However running `./vkquake -window` this works with no problem in a window.  Having taken a bit of time looking into the issue it may be related to a bug when using fullscreen applications.  Strangely enough if I use the `FrameMeter` in "Quartz Debug" application it seems to make the stuttering go away at fullscreen.  With `vkquake2` there is no stuttering at fullscreen but maybe I noticed `vkquake` using SDL so maybe the method SDL uses to go into fullscreen mode is causing this.

Anyone else experience this?

**Comment by kondrak** [comment]
This issue sounds very familiar to what I had in vkQuake2 with my first window handling implementation on Mac. Problems started happening with Vulkan SDK 1.1.97.0 - not sure if MoltenVK started handling things differently there, if that particular version introduced a bug or if it's the WM's fault, either way I managed to fix this by updating created window's style: https://github.com/kondrak/vkQuake2/commit/d4c3a2557bfb378e0e5a98425283f35cb073a556

Not quite vkQuake related, could be an issue with SDL2 or maybe there's an option to modify window style (I never used SDL2 on a Mac, so I'm not sure).

**Comment by tomgreen66** [comment]
Just compiled with Vulkan SDK 1.1.92.1 and it seems to fix the issue so it does look like a similar issue.  This would fit with the fact I was sure I compiled vkQuake without issue at some point in the past but had deleted it. I have taken a look at SDL code so might be a few things I can try there.  Thanks for the pointer.

**Comment by Novum** [comment]
Please file a bug with the MoltenVK guys
