### ISSUE TITLE
Any chance of implementing support for OpenAL Soft?

### ISSUE THREAD

**Issue by lazycrypt** [Novum/vkQuake#195]
Question in the title. [OpenAL Soft](https://openal-soft.org/) has support for both surround sound and HRTF/binaural audio, if using headphones. Current SDL audio backend seems to only support stereo sound. OpenAL Soft is supported by a number of sourceports of id's games (gzdoom, yamagi quake 2, ioquake3/spearmint, dhewm3).

**Comment by LethalManBoob** [comment]
Considing its a fork of quakespasm, i think maybe it would be a better idea to ask the people at quakespam on sourceforge. Thats how i got a refresh rate selector in the game.

**Comment by Novum** [comment]
Definitely outside the scope of vkQuake, ask QuakeSpasm guys.
