### ISSUE TITLE
Control + ESC  =>  vkQueuePresentKHR failed

### ISSUE THREAD

**Issue by j4reporting** [Novum/vkQuake#196]
system is NUC6i5SYH  windows 10 1909 
iGPU INtel Iris Graphics  540
Intel driver version 26.20.100.7463

1. start vkquake with fullscreen mode on
2. hit  Control + ESC to get back to desktop 
3. vkquake throws the error message: 
   vkQueuePresentKHR failed

**Comment by Novum** [comment]
Tell Intel.
