### ISSUE TITLE
Black triangle drawn underwater during TileClear

### ISSUE THREAD

**Issue by pawel3275** [Novum/vkQuake#197]
Hi,

There is an issue regarding vkCmdPushConstants(), when character goes into liquid (lava or water), a giant black triangle is drawn. This occurs only when screen size is lowered.

![Renderdoc Issue](https://user-images.githubusercontent.com/50518398/69949330-948a8000-14f1-11ea-8e78-3c624a5afd46.jpg)
![vkQuake Issue](https://user-images.githubusercontent.com/50518398/69949332-95231680-14f1-11ea-837a-d9d7bdcacdd2.jpg)

Push constants are used and bound to compute pipeline, yet used in vertex shader. This causes corruptions in draw when Draw_TileClear() is performed for left screen area. It's perfectly visible on intel graphics, on nVidia and AMD graphics it's visible using external tool like renderdoc in erroneous draw at the beginning of renderpass.

**Comment by Novum** [comment]
What vertex shader? I can't repro this. Not in RenderDoc nor otherwise.

**Comment by Novum** [comment]
I'm pretty sure there are supposed to be two different states for graphics and compute push constants. Therefore constants pushed for `VK_SHADER_STAGE_COMPUTE_BIT` shouldn't be applied to graphics pipelines. This seems to be a driver bug?

**Comment by Novum** [comment]
I'm talking to Khronos about this, I'm a bit confused by the spec on this.

**Comment by Novum** [comment]
So I'm still trying to repro this and I don't understand why the first draw call after the dispatch doesn't have a `vkCmdPushConstants`. 
![image](https://user-images.githubusercontent.com/112222/70205785-e5b19400-16ea-11ea-8a70-544d2d185e0c.png)

**Comment by Novum** [comment]
Okay, now I understand, it only happens if you set the output size smaller than the window. Should be fixed with b0574a49f7ee4151f4a2954a791e42013c58b074
