### ISSUE TITLE
Entities always appear in front of explosions.

### ISSUE THREAD

**Issue by TheFerries** [Novum/vkQuake#198]
Overall, my experience with vkQuake has been a blast and that Supersampling is amazing, probably the best part of this Quakespasm branch in my opinion. Almost no issue except for this one 

The issue in particular isnt game breaking at least, but It can give you some weird images. For some reason enemies will always appear in front of explosions, this is specially noticeable when playing Quoth and seeing the rocketeer throw a rocket in your face and yet you still can see the enemy in front of the explosion.

To put an image, here's the issue in particular.
In vanilla quakespasm, the entities dont appear in front of the explosion. 
![vkquake0002](https://user-images.githubusercontent.com/56562058/70188432-75494980-16cf-11ea-8574-da1ab9a8db14.png)

**Comment by Novum** [comment]
I can't repro this. What driver and OS is this?

**Comment by Novum** [comment]
I got it, thanks for the report.

**Comment by Novum** [comment]
5a4cfadda7b08663ef8dd97f8772139140f86a28
