### ISSUE TITLE
Latest build needs 10 seconds to boot.

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#199]
Ive built with many different settings. Vanilla or with plenty of modifications. I use the most up to date vs 2019 with all its sdks and what not. But until around 2 builds ago i had completely no issues. It wouldn't even go past the title screen if i used vanilla settings to build.

**Comment by LethalManBoob** [comment]
Okay so litteraly right after i applied a bunch of launch options, some i know work, some i dont know.
-fitz -mousethread -primarysound -noforcemparms -noforcemaccel -noforcemspd -nojoy -nodirectblit -num_edicts 16384 -heapsize 10240000 -zone 65535 
and somehow it got fixed but it. Maybe a heapsize issue??

**Comment by LethalManBoob** [comment]
-nojoy is what fixes it. I have no clue.

**Comment by Novum** [comment]
This is likely an issue with SDL2
