### ISSUE TITLE
Visible borders of some textures.

### ISSUE THREAD

**Issue by AntonieS** [Novum/vkQuake#200]
Hi!
In the attached file, the area with the artifact is marked with a red ellipse. Transparent borders became visible (see picture at full size or zoom it). It looks like thin red lines at the edges of objects. Please fix it.

Win 7 SP1 x64
GTX 1080
vkQuake 1.0.3 win64
graphic settings doesn't matter (AA, AF and etc) - in any case artifacts looks like at screenshot
![vkquake0000](https://user-images.githubusercontent.com/58735249/70570628-53f3cc00-1bad-11ea-953b-3cde0e4d618d.png)

Thank you.

**Comment by AntonieS** [comment]
Additional information:
This only happens if in Options - Video Options - Filter stand "Smooth".

Same thing happen in screen after level ends and other places.

**Comment by Novum** [comment]
What driver version are you using?

**Comment by AntonieS** [comment]
I'm using 390.65-desktop-win8-win7-64bit-international-whql - 08.01.2018
And I haven't problems in Arcane Dimensions like in #124 
I do not have the described problem in other games.
How can I help You?

**Comment by AntonieS** [comment]
In Quakespasm 0.93.2_win64 and quakespasm-0.93.2ish_spiked_win64 also no problem. But they have problems with FSAA, AF and water .

**Comment by Novum** [comment]
Driver is too old.

**Comment by AntonieS** [comment]
Just tried 441.66-desktop-win8-win7-64bit-international-whql
Clean install
Same thing.
