### ISSUE TITLE
Mipmap Issues.

### ISSUE THREAD

**Issue by TheFerries** [Novum/vkQuake#201]
I've noticed that vkQuake has a much more intense mipmapping than Quakespasm, at first I thought it was the Supersampling however it wasn't that, changing it to multisampling (as Quakespasm does) shows the difference in mipmapping between the two engines.

I'm using a compiled build for windows x64. I compiled it so I could get the fix for the explosions I mentioned before.

![vkquake0001](https://user-images.githubusercontent.com/56562058/70858240-5cb20e00-1edd-11ea-8f45-7d446e5539c3.png)
Here's in vkQuake.

![spasm0001](https://user-images.githubusercontent.com/56562058/70858252-879c6200-1edd-11ea-9a7a-726fdc6da1a1.png)
Here's in QuakeSpasm.

Zoom in to notice the difference, that lamp looks way more blocky in vkQuake, I cant find which option can change this to make it be like in Quakespasm (plus the benefit of Supersampling) Anisotropic filtering is activated if you wonder.

**Comment by TheFerries** [comment]
Well it seems I could fix it myself, to put it shortly, there was something in the config file that made the mipmapping more intense for some reason. so to anybody who had that issue, there's the fix.

**Comment by TheFerries** [comment]
Well actually no! after I changed the FOV from 90 to 105, then the mipmapping became more notable, sorry for bothering but yeah, In quakespasm, which I also had at 105 FOV, the mipmapping is way less notable (wow the water looks ugly), I dunno what to do to make the mipmapping look like it does in Quakespasm since some commands are different thanks to the change to vulkan

**Comment by LethalManBoob** [comment]
I remember having a similar issue with serious sam. i changed texture quality on nvidia to high quality and it was fixed.

**Comment by Novum** [comment]
Driver issue. Mipmaps are fine.

**Comment by TheFerries** [comment]
One question, what level of anisotropic does the option gives? because in QS you can choose from X2 up to X16 in the config files, here its just no or yes.

**Comment by Novum** [comment]
It enables the maximum anisotropy level available. Glad the driver setting fixed it for you.
