### ISSUE TITLE
Visible borders of some textures. Please reopen #200

### ISSUE THREAD

**Issue by AntonieS** [Novum/vkQuake#202]
Visible borders of some textures. Please reopen #200

https://github.com/Novum/vkQuake/issues/200

Just tried 441.66-desktop-win8-win7-64bit-international-whql
Clean install
Same thing.

**Comment by Novum** [comment]
Please provide screenshots of what you actually see. I can't repro this.

**Comment by Novum** [comment]
I looked through the code and I'm not sure there is anything I can do. The texcoords that are passed to the API are identical, yet int he Vulkan path there is the border in the GUI.

**Comment by Novum** [comment]
Okay I get it now, parts of the UI is actually rendered with alpha testing, not alpha blending. Are you only referring to the UI, or are there other issues in the world?

**Comment by Novum** [comment]
Fixed with eaae3b40c808bba92c02bcf21ea3ee3af0cbe874

**Comment by AntonieS** [comment]
I apologize for not responding for a long time.
Yes, the problem ony in text UI.
How can I test fix?
Thank You Very Much. %)))

**Comment by Novum** [comment]
You can compile it yourself or wait until I upload a new release.
