### ISSUE TITLE
Alt-tab causes failure of vkQueuePresent()

### ISSUE THREAD

**Issue by pawel3275** [Novum/vkQuake#203]
Hi,

There is an issue in vkQuake, when alt-tab is pressed during gameplay it causes vkQueuePresentKHR() to fail and close the game.
Intel returns status VK_SUBOPTIMAL_KHR when alt tab is pressed, which is not handled by vkQuake. Hence I've made proposal in code to handle it alongside with VK_ERROR_OUT_OF_DATE_KHR and VK_ERROR_SURFACE_LOST_KHR to recreate the video. After this issue is no longer seen. 

This issue can be tested on any intel graphics with newest intel graphics driver 
(https://downloadcenter.intel.com/download/29195)

To obtain repro of the issue, please:
1. Run the game
2. Alt-tab
3. Issue should be seen with error of vkQueuePresentKHR()

**Comment by Novum** [comment]
Thanks cd7e7b95fefc34774b1166197aad8353698258d5
