### ISSUE TITLE
re-open old issue (particle alpha blending)

### ISSUE THREAD

**Issue by Rikoshet-234** [Novum/vkQuake#204]
![image](https://user-images.githubusercontent.com/34555340/71326573-02c4d000-24fd-11ea-8bc3-44f4c223dce3.png)
Hi ! please, check that ( recently closed ) issue. Thank you in advance :)

**Comment by Tintin-Asterix** [comment]
Use "r_particles 2" and it should make the particles squares. It looks like you have r_particles set to 1.

**Comment by Tintin-Asterix** [comment]
Oh yeah, that is weird. If r_particles is set to 1 so the particles are circles, they show as circles within transparent squares. If you set r_quadparticles to 0 they show as circles within big triangles like before.

![vkquake0001](https://user-images.githubusercontent.com/32944138/71357274-026c1980-257d-11ea-941b-8a82992b8f42.jpg)

**Comment by Rikoshet-234** [comment]
yea, this half-transparent quads looks weird. and i think we have a blending problem in shader

**Comment by Rikoshet-234** [comment]
ha, i fixed it ) 
![image](https://user-images.githubusercontent.com/34555340/71361164-677e3a00-2592-11ea-99ac-73d888364a07.png)

**Comment by Rikoshet-234** [comment]
![image](https://user-images.githubusercontent.com/34555340/71361205-8e3c7080-2592-11ea-81bf-1ab5fd6c30e8.png)
problem was in fragment shader. when i tweak this value to 0.0, it starts looks like in quakespasm engine

**Comment by Novum** [comment]
I can't repro this. What mod is this?

**Comment by Rikoshet-234** [comment]
alpha - no, just color. my tweak make no sense, because then it looks different than in qs. there is a map i taken a screenshot from https://www.quaddicted.com/reviews/bindingtower2.html

**Comment by Rikoshet-234** [comment]
in vanilla quake (id1)

**Comment by Rikoshet-234** [comment]
i can make some snapshots for you in renderdoc if you want

**Comment by Rikoshet-234** [comment]
by the way, how can I rebuild shaders ? I tried through .bat and .sh - they don't work in my case

**Comment by Rikoshet-234** [comment]
so, looks like i found what is going wrong
![image](https://user-images.githubusercontent.com/34555340/71448765-9d612100-2740-11ea-91bf-8844f078bbed.png)
when we create a new vector consisting of xyzw components, it is assumed that the alpha channel is also used in mathematical operations. but when we write vec4(fog), the compiler seems to take it as vec4 (fog, fog, fog, w ). we don't have the w component initially, but we need it for operations on a 4-dimensional array. in this case, the compiler substitutes the standard value for us in the place w of the component (w = 0.5 based on my observations)

**Comment by Rikoshet-234** [comment]
I think we need to review the shaders for the presence of such defects as this

**Comment by Rikoshet-234** [comment]
So, I found how to compile shaders and tested my fix. What else... its work the same as in quakespasm :)
![image](https://user-images.githubusercontent.com/34555340/71449988-356b0480-2759-11ea-90d4-d84d0e4a8845.png)

**Comment by Rikoshet-234** [comment]
![image](https://user-images.githubusercontent.com/34555340/71450012-9561ab00-2759-11ea-9396-dc1ff3b89892.png)

**Comment by Novum** [comment]
@Rikoshet-234 To recompile the shaders, you will have to have the Vulkan SDK installed and make sure to log out afterwards to get the environment variables set up correctly.

**Comment by Rikoshet-234** [comment]
Yes, quakespasm doesn't have shader code. everything written in C using the gl function etc. but I fixed your mistake. and if you don't know how qs shaders work, then who wrote these shaders ? for vkquake I mean of course. for me its looks the same as in qs engine, i was compared it in many maps i was played before - the same fog and particle blending.

**Comment by Rikoshet-234** [comment]
you're right, though. it is better to make sure that everything works exactly the same as in qs. still, this is a transfer to another api, not a reimplementation:) I hope to soon be able to solve these problems with the differences in vkQuake and quakespasm

**Comment by Novum** [comment]
Why are you trying to lecture me?

**Comment by Rikoshet-234** [comment]
sorry :) I'm a little confused myself XD. just forget this misunderstanding ;)

**Comment by Novum** [comment]
1ddea619923d99f6c10e73b3fcdb78f8134f5673
