### ISSUE TITLE
vkQuake doesn't work with new GPU/sound drivers

### ISSUE THREAD

**Issue by andreluizgit** [Novum/vkQuake#205]
The vkQuake (Latest version) doesn't work with new drivers AMD 19.20 (via Windows Update) or from AMD site 19.2.2/3 (via manual installation). The error : 

`Sound Initialization ... 

Exception thrown at 0x0000000000000000 in vkQuake.exe: 0xC0000005: Access violation executing location 0x0000000000000000.`

image : [Error of "access violation" via Visual Studio debug](https://pasteboard.co/IO6KhmO.png)

same issue with vulkan sample : [Acess violation](https://community.khronos.org/t/access-violation-exception-vc/65990/4)

**Comment by Novum** [comment]
Uh, tell AMD?

**Comment by Novum** [comment]
Wait, so older versions do work? Which ones?

**Comment by andreluizgit** [comment]
@Novum sorry ... I enabled Reshade global vulkan option and everything stop work (Cemu and vkQuake), then after to disable and Restart everything go back to work. Thanks for answering.
