### ISSUE TITLE
Make it possible to turn model overbrighting off

### ISSUE THREAD

**Issue by c-d-a** [Novum/vkQuake#207]
In Quakespasm/Fitzquake, gl_overbright_models can be used to control model lighting. When on, it is meant to emulate the way software renderers artificially brightened the models. Even with that in mind, it was not entirely consistent with WinQuake (see [thread](http://celephais.net/board/view_thread.php?id=61351&start=121&end=122)).
It's possible that the original intent was to make the enemies stand out from environment on lower resolutions, something less relevant when playing above 480p. Regardless, GLQuake did not overbright the models, and some custom content was produced with lack of overbrighting in mind ([example](https://i.imgur.com/8rwlLb2.png))
As far as I can see, in vkQuake the overbrighting is baked into the pre-compiled shaders. So I'm not sure it's even possible to make it a user-side toggle. Would be nice if it was.

**Comment by Novum** [comment]
By design.
