### ISSUE TITLE
r_showbboxes doesn't work

### ISSUE THREAD

**Issue by c-d-a** [Novum/vkQuake#208]
As it says in the title. Supposed to show entity bounding boxes.

**Comment by Novum** [comment]
Not supported

**Comment by c-d-a** [comment]
The command shouldn't be there, then.
For example, I wouldn't expect r_scale to work since it doesn't exist in the first place.

**Comment by Novum** [comment]
There are plenty of broken console commands in vanilla Quake too. Console is a debug interface, not for enabling supported features.
