### ISSUE TITLE
Long map titles don't show up in status bar

### ISSUE THREAD

**Issue by c-d-a** [Novum/vkQuake#209]
In Quakespasm, titles that don't fit on screen instead scroll sideways. In vkQuake the title bar is just empty.

**Comment by Novum** [comment]
What are titles?

**Comment by c-d-a** [comment]
The worldspawn "message" field.
Compare: jam2_skacky in vkQuake and in Quakespasm
![vkquake0000](https://user-images.githubusercontent.com/55441216/75329568-a0dc6a00-58a1-11ea-9a2f-a3f82a61ab42.png)
![spasm0000](https://user-images.githubusercontent.com/55441216/75329572-a20d9700-58a1-11ea-8c33-682fbec42c32.png)

**Comment by Novum** [comment]
d9763049e71635aef6a94d91538ddc44a5df23ae
