### ISSUE TITLE
Issue with geometry being visible when traversing water.

### ISSUE THREAD

**Issue by ConHuevosGuey** [Novum/vkQuake#210]
Hello.  I recently compiled a copy of vkQuake and immediately noticed an issue with the renderer having a 'see through walls' effect when bobbing in and out of water.  It's reproducible in E1M1.

Attached are screenshots of the issue.
![unknown](https://user-images.githubusercontent.com/445334/76630048-5bf53c00-650d-11ea-8623-fe4afd2d0dd9.png)
![unknown2](https://user-images.githubusercontent.com/445334/76630054-5d266900-650d-11ea-8986-07e59938a032.png)

**Comment by Novum** [comment]
Original levels were built with opaque water for occlusion culling reasons. This is not a vkQuake bug, the same happens in all other source ports.

**Comment by ConHuevosGuey** [comment]
Ah strange, I tested this in Mark V immediately after discovering it and I could not reproduce it.  QI couldn't reproduce the effect in Quakespasm as well.  I assume they applied that fix then.

**Comment by ConHuevosGuey** [comment]
Just verified.  I cannot reproduce this behavior in Quakespasm and Mark V.  Are you certain the opaque issue is related to this?

**Comment by Novum** [comment]
![image](https://user-images.githubusercontent.com/112222/76697008-a981be00-665f-11ea-91ba-e55a10eeb087.png)

**Comment by ConHuevosGuey** [comment]
Okay, just wanted to be sure.  I don't recall ever touching any alpha settings when trying out vkQuake or the others.  Thanks for your time and efforts.
