### ISSUE TITLE
Ambient sounds and host_maxfps

### ISSUE THREAD

**Issue by c-d-a** [Novum/vkQuake#213]
With host_maxfps above a certain value*, the world ambient sounds (wind, water) will not start. Easily tested on start map that has sky right above spawn point and water to the left.
There seems to be some interaction with whether vsync is on or off, but I have not figured it out for certain. Same issue affects FitzQuake and Quakespasm, but not Quakespasm-Spiked (though definitely none of them with default configs).

\* Tested on two PCs, on one the cut-off point is 111, on the other it's 124. At these values the sounds still start, but not at any higher.

As a sidenote (or not), I realized I don't quite get what separating physics from rendering achieves. It is my understanding that to get a smooth rendering framerate, the server needs to run at the same framerate or at a multiple of it. Is there any practical difference between that and setting high maxfps in Quakespasm, in context of singleplayer? vkQuake defaults to maxfps 200. What about the "broken physics"?

**Comment by Novum** [comment]
Physics always ticks at 72Hz, rendering is independent of that rate. Note that the patch came from QuakeSpasm-Spiked, so you better ask Spike about it.

**Comment by c-d-a** [comment]
Right, it's [there](https://github.com/Shpoike/Quakespasm/commit/b6db01b18d5e0bbbb97976981aa766697797bf89#diff-2d6c6dfebf9f309ab6b6433206e21a45), under S_UpdateAmbientSounds, caused by volume being an integer.

**Comment by Novum** [comment]
3a51cd0ce11b5a7fa0655c103c437a99a3eb6628
