### ISSUE TITLE
This does not compile on Ubuntu 18.04 (solution inside!!)

### ISSUE THREAD

**Issue by Hurricos** [Novum/vkQuake#214]
Issue: Title

Solution: Don't yell at Ubuntu, just post the solution (listed below, works on my install of Ubuntu MATE 18.04):

Two components need to be updated for Vulkan support:
 
- New enough version of libvulkan-dev (etc)

- New enough version of libsdl2-dev (etc)

For the first, there is a [bionic (18.04) Backports PPA](https://launchpad.net/%7Ecybermax-dexter/+archive/ubuntu/sdl2-backport) for newer SDL2 built in with vulkan support:

For the second, LunarG provides builds of the Vulkan SDK, including an updated libvulkan-dev that [doesn't require an insanely updated libc6](https://packages.ubuntu.com/focal/libvulkan-dev).

As per https://vulkan.lunarg.com/sdk/home#linux:

    wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
    sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.135-bionic.list http://packages.lunarg.com/vulkan/1.2.135/lunarg-vulkan-1.2.135-bionic.list
    sudo apt update
    sudo apt install vulkan-sdk

Please don't just enter in those commands. Go to the LunarG site and find how to link yourself up to the most recent sources.

And Novum? Please don't just close this issue; while Focal is coming out very soon with updated libraries, it makes more sense for your Ubuntu-dominated potential userbase to actually provide this solution in the readme.

**Comment by Hurricos** [comment]
Final build output:

    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o gl_vidsdl.o gl_vidsdl.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o gl_texmgr.o gl_texmgr.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o gl_mesh.o gl_mesh.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o gl_heap.o gl_heap.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o r_sprite.o r_sprite.c
    gl_vidsdl.c: In function ‘GL_InitDevice’:
    gl_vidsdl.c:747:11: warning: unused variable ‘found_debug_marker_extension’ [-Wunused-variable]
      qboolean found_debug_marker_extension = false;
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    At top level:
    gl_vidsdl.c:288:17: warning: ‘VID_GetVSync’ defined but not used [-Wunused-function]
     static qboolean VID_GetVSync (void)
                     ^~~~~~~~~~~~
    gl_texmgr.c: In function ‘TexMgr_LoadPalette’:
    gl_texmgr.c:335:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
      fread (pal, 1, 768, f);
      ^~~~~~~~~~~~~~~~~~~~~~
    gl_texmgr.c: In function ‘TexMgr_ReloadImage’:
    gl_texmgr.c:1305:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
       fread (data, 1, size, f);
       ^~~~~~~~~~~~~~~~~~~~~~~~
    At top level:
    gl_texmgr.c:549:18: warning: ‘TexMgr_ResampleTexture’ defined but not used [-Wunused-function]
     static unsigned *TexMgr_ResampleTexture (unsigned *in, int inwidth, int inheight, qboolean alpha)
                      ^~~~~~~~~~~~~~~~~~~~~~
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o r_alias.o r_alias.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o r_brush.o r_brush.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o gl_model.o gl_model.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o in_sdl.o in_sdl.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_dma.o snd_dma.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_mix.o snd_mix.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_mem.o snd_mem.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o bgmusic.o bgmusic.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_codec.o snd_codec.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_flac.o snd_flac.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_wave.o snd_wave.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_vorbis.o snd_vorbis.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_opus.o snd_opus.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_mp3.o snd_mp3.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_mp3tag.o snd_mp3tag.c
    snd_wave.c: In function ‘S_WAV_CodecReadStream’:
    snd_wave.c:231:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
      fread(buffer, 1, bytes, stream->fh.file);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    snd_wave.c: In function ‘FGetLittleLong’:
    snd_wave.c:41:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
      fread(&v, 1, sizeof(v), f);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
    snd_wave.c: In function ‘FGetLittleShort’:
    snd_wave.c:55:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
      fread(&v, 1, sizeof(v), f);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_mikmod.o snd_mikmod.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_xmp.o snd_xmp.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_umx.o snd_umx.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o snd_sdl.o snd_sdl.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cd_sdl.o cd_sdl.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o net_bsd.o net_bsd.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o net_udp.o net_udp.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o net_dgrm.o net_dgrm.c
    cd_sdl.c:35:9: note: #pragma message: Warning: SDL CDAudio support disabled
     #pragma message("Warning: SDL CDAudio support disabled")
             ^~~~~~~
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o net_loop.o net_loop.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o net_main.o net_main.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o chase.o chase.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cl_demo.o cl_demo.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cl_input.o cl_input.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cl_main.o cl_main.c
    cl_demo.c: In function ‘CL_GetDemoMessage’:
    cl_demo.c:117:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
      fread (&net_message.cursize, 4, 1, cls.demofile);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cl_parse.o cl_parse.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cl_tent.o cl_tent.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o console.o console.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o keys.o keys.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o menu.o menu.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o sbar.o sbar.c
    console.c: In function ‘Con_DebugLog’:
    console.c:470:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
      write(log_fd, msg, strlen(msg));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o view.o view.c
    menu.c: In function ‘M_ScanSaves’:
    menu.c:441:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
       fscanf (f, "%i\n", &version);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    menu.c:442:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
       fscanf (f, "%79s\n", name);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o wad.o wad.c
    sbar.c: In function ‘Sbar_UpdateScoreboard’:
    sbar.c:469:40: warning: ‘%s’ directive writing up to 31 bytes into a region of size between 7 and 15 [-Wformat-overflow=]
       sprintf (&scoreboardtext[i][1], "%3i %s", s->frags, s->name);
                                            ^~
    In file included from /usr/include/stdio.h:862:0,
                     from q_stdinc.h:39,
                     from quakedef.h:62,
                     from sbar.c:24:
    /usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 5 and 44 bytes into a destination of size 19
       return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           __bos (__s), __fmt, __va_arg_pack ());
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cmd.o cmd.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o common.o common.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o crc.o crc.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cvar.o cvar.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o cfgfile.o cfgfile.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o host.o host.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o host_cmd.o host_cmd.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o mathlib.o mathlib.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o pr_cmds.o pr_cmds.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o pr_edict.o pr_edict.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o pr_exec.o pr_exec.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o sv_main.o sv_main.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o sv_move.o sv_move.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o sv_phys.o sv_phys.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o sv_user.o sv_user.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o world.o world.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o zone.o zone.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o pl_linux.o pl_linux.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o sys_sdl_unix.o sys_sdl_unix.c
    cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o main_sdl.o main_sdl.c
    sys_sdl_unix.c: In function ‘Sys_ConsoleInput’:
    sys_sdl_unix.c:427:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
       read (0, &c, 1);
       ^~~~~~~~~~~~~~~
    cc strlcat.o strlcpy.o alias_frag.o alias_alphatest_frag.o alias_vert.o basic_alphatest_frag.o screen_warp_comp.o screen_warp_rgba8_comp.o cs_tex_warp_comp.o basic_frag.o basic_notex_frag.o basic_vert.o sky_layer_frag.o sky_layer_vert.o postprocess_frag.o postprocess_vert.o world_frag.o world_vert.o showtris_frag.o showtris_vert.o gl_refrag.o gl_rlight.o gl_rmain.o gl_fog.o gl_rmisc.o r_part.o r_world.o gl_screen.o gl_sky.o gl_warp.o gl_vidsdl.o gl_draw.o image.o gl_texmgr.o gl_mesh.o gl_heap.o r_sprite.o r_alias.o r_brush.o gl_model.o in_sdl.o snd_dma.o snd_mix.o snd_mem.o bgmusic.o snd_codec.o snd_flac.o snd_wave.o snd_vorbis.o snd_opus.o snd_mp3.o snd_mp3tag.o snd_mikmod.o snd_xmp.o snd_umx.o snd_sdl.o cd_sdl.o net_bsd.o net_udp.o net_dgrm.o net_loop.o net_main.o chase.o cl_demo.o cl_input.o cl_main.o cl_parse.o cl_tent.o console.o keys.o menu.o sbar.o view.o wad.o cmd.o common.o crc.o cvar.o cfgfile.o host.o host_cmd.o mathlib.o pr_cmds.o pr_edict.o pr_exec.o sv_main.o sv_move.o sv_phys.o sv_user.o world.o zone.o pl_linux.o sys_sdl_unix.o main_sdl.o   -lm -lX11-xcb -lvulkan   -lvorbisfile -lvorbis -logg -lmad -lSDL2 -o vkquake

**Comment by Hurricos** [comment]
(the build was obviously successful.)

**Comment by Novum** [comment]
How is this my problem that Ubuntu ships old Vulkan and SDL versions?

**Comment by Hurricos** [comment]
This is not your problem. I'm providing a solution which you can distribute to your users. I am also providing a merge request for you [here](https://github.com/Novum/vkQuake/pull/215).

Please merge this. Thanks for your time, and sorry for the disturbance; I just want people not to come and ask for my help when they try to build your software and inevitably fail.
