### ISSUE TITLE
Could not allocate memory for texture

### ISSUE THREAD

**Issue by dumptruckDS** [Novum/vkQuake#217]
I am beta testing a Quake mod and cannot get it to load. vkQuake crashes to desktop with this error. The mod readme says to use `-heapsize 521000` which I am doing.

Using Windows 10 and Quakespasm-Spiked will load the map.

**Comment by Novum** [comment]
Need more info. What mod?

**Comment by c-d-a** [comment]
Fairly sure it's about the start map from ["Adoria"](http://celephais.net/board/view_thread.php?id=3&start=16372&end=16372)
vkQuake can't load a 288 MB skybox (six 4k .tgas).
Even without the sky, both QS and vkQ then can't load the actual first map anyway.

**Comment by Novum** [comment]
Sorry, max texture size is 32MB. I don't see the point in supporting 4k texture in Quake 1. This is ridiculous.

**Comment by dumptruckDS** [comment]
Thanks for the reply. I didn't see this until now. I wasn't aware the skybox was so large!
