### ISSUE TITLE
Preserve Fullscreen aspect ratio.

### ISSUE THREAD

**Issue by smgorden** [Novum/vkQuake#218]
Feature Request: support for preserving aspect ratio of selected resolution in Fullscreen mode. 
Normally I select this rendering override in my gfx card settings, but I realized that with vulkan rendering- this option doesn't seem to work. So it would be handy to have it built in as an option in this port.

**Comment by Novum** [comment]
I don't quite understand what you mean?

**Comment by smgorden** [comment]
When I attempt to play in low resolution, such as 320x240 or 640x480... the image is stretched to my 16:10 widescreen monitor instead of maintaining the aspect ratio of 4:3. I would like the option to leave blank/black space on the side instead of stretching the image.

**Comment by Novum** [comment]
Set this in the driver settings
![image](https://user-images.githubusercontent.com/112222/80871475-78daff80-8c72-11ea-9dbe-9102db8204b4.png)
AMD has similar options. This works fine with Vulkan.

**Comment by smgorden** [comment]
Arg... it works on one of my machines, but not the other. (both are nvidia setups). I guess it's on my end. Thanks for the response, anyway :)

**Comment by Novum** [comment]
Try setting it to GPU instead of display scaling.
