### ISSUE TITLE
Building on Mac OS X

### ISSUE THREAD

**Issue by paulicka** [Novum/vkQuake#220]
I'm happy to help, but it might take me while to ramp up...
Apparently, there's been some type of code update with Vulkan Headers:
https://github.com/KhronosGroup/Vulkan-Headers/issues/117

This is the exact error I got when trying to build on Mac OS X.

Let me know if I can be of service in resolving this...
;-)

**Comment by Novum** [comment]
I don't understand what you're talking about. vkQuake doesn't use VK_DYNAMIC_STATE_RANGE_SIZE?

**Comment by Novum** [comment]
Uh, I was wrong, I don't know why find in files wasn't working properly. Fixed with a869a22d9b51c68e57646fa20e4c40fc6db36760
