### ISSUE TITLE
FLAC music not playing on Linux Fedora

### ISSUE THREAD

**Issue by Rugaliz** [Novum/vkQuake#221]
So in my setup, using Linux Fedora 32 FLAC files do not work. If I convert to ogg or wav it works.
Is this some sort of issue related to flac library names in different distros?
I can assure I have all required dev libs and flac playback libs installed.
The console output when using flac files states:

`Couldn't find a cdrip for track 6`

**Comment by Novum** [comment]
I don't maintain the audio subsystems. Please report this bug on the upstream QuakeSpasm bug tracker https://sourceforge.net/p/quakespasm/bugs/
