### ISSUE TITLE
Getting error when compiling on Arch Linux

### ISSUE THREAD

**Issue by micwoj92** [Novum/vkQuake#222]
tested git version and 1.04.1
`gl_rmisc.c: In function ‘R_CreatePipelines’:
gl_rmisc.c:1429:32: error: ‘VK_DYNAMIC_STATE_RANGE_SIZE’ undeclared (first use in this function); did you mean ‘VK_DYNAMIC_STATE_LINE_WIDTH’?
 1429 |  VkDynamicState dynamic_states[VK_DYNAMIC_STATE_RANGE_SIZE];
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                VK_DYNAMIC_STATE_LINE_WIDTH
gl_rmisc.c:1429:32: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:200: gl_rmisc.o] Error 1
make: Leaving directory '/home/micwoj92/.cache/yay/vkquake/src/vkquake/Quake'
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by PopeRigby** [comment]
Also having this issue.

**Comment by Novum** [comment]
a869a22d9b51c68e57646fa20e4c40fc6db36760

**Comment by micwoj92** [comment]
Thanks for quick fix
@PopeRigby  I updated package on aur, it builds for me now.
