### ISSUE TITLE
Potential AI Issue (X-Men: The Ravages of Apocalypse)

### ISSUE THREAD

**Issue by Hooperla** [Novum/vkQuake#224]
So I've been on a kick playing Quake 1 and have been doing so with QSS for a while now. However, as I was playing through X-Men: The Ravages of Apocalypse I learned about this source port from Dwars' video on some of the Quake source ports. After looking up some things about the port, and even seeing that it allowed for higher frame rates like QSS, I felt the need to try it out and play through the rest of Xmen on that instead. 

Pretty much everything worked just as well, but I eventually figured out something that was bothering me. Cannonball, one of the enemies, was acting even weirder than usual. I say "usual" because the AI isn't all that good to begin with, being pretty dumb at the best of times. However, I realized that Cannonball was just flying around and around rather than damaging me like he had on QSS. The only times he seemed capable of hitting me was when I intentionally jumped as they connected with me or when he was going up a hill once (maybe the Ai can't figure out the elevation or something?). I went back to QSS to test and (while doing MANY dumb things like getting stuck in walls, getting stuck in me, stopping and going, etc) when the AI eventually figured out how to fly at me it did indeed hit me unlike in vkQuake. 

I don't really know if this was because I used saves from QSS and put them in vkQuake (don't know if different source ports affect things like save files), but I wanted to let you know in case this was an issue with the source port. I haven't played this on a more "old school" source port, so maybe both are doing strange things. In any case, I recorded some videos and put my autoconfig and config files (plus save files but I did that in case the source ports changing save files was indeed a thing) in folders for you to look at with a mega link to them. Sorry in advanced for how big it is, but I didn't want to give you garbage quality stuff. I can rerecord it in lower resolutions if you need me too though.

Mega link: https://mega.nz/file/NccCjKyL#dCyhNExW6i7GXuRiHdPyUIMJ4cbQMouJJdiIisfZ8UI

PS. The save files are from a while after I started playing on vkQuake, having done a few missions before fully realizing the possible issues Cannonball. Don't know if that would affect anything but I wanted to mention that in case it did.

PSS. This is my first time doing this sort of thing, so I hope I gave a detailed enough explanation.

**Comment by micwoj92** [comment]
I dont know if this is related but for example demos recorded in vkquake dont play in winquake. Best you could do to test with normal quakespasm to see if this issue reoccurs since qss and vkquake share it as ancestor.

**Comment by Hooperla** [comment]
Thank you for that suggestion, probably should have thought to do that along with the others. Both quakespasm and quakespasm-sdl12 seem to do the same thing that vkQuake does with Cannonball flying around and around unless he magically gets lucky or I jump into his attack. Wonder why QSS is different and if that is more or less accurate to the original.

**Comment by micwoj92** [comment]
If you read at http://triptohell.info/moodles/qss/
you can see that it is actually very different than 'original' quake. Different projects have different scopes so their compatibility may differ.

**Comment by Hooperla** [comment]
Oh I know that all three are very different from original Quake, as default QuakeSpasm itself is very different. I was just wondering if in this specific case QSS was closer than the other two in terms of how the Ai behaves if played on OG Quake or if it was the outlier in having the ai act the way it did. Sorry for not being very clear on that. One note though on the page you linked mentions Model BBoxes possibly having issues when replaced, so maybe that could explain the weird quirks if I'm understanding the terms correctly? Thanks for the comment, wouldn't have noticed that otherwise.

**Comment by Novum** [comment]
I have not touched AI code at all.

**Comment by Hooperla** [comment]
Huh, guess that rules it down the QSS having changed the Ai code in some way. Oh well, if you didn't change anything you didn't change anything. I'll keep the link up for a bit longer just for posterity's sake. Sorry this didn't help much.
