### ISSUE TITLE
Correct aspect ratio for GUI.

### ISSUE THREAD

**Issue by KainXVIII** [Novum/vkQuake#225]
So instead of this https://www.old-games.ru/forum/attachments/quake01-png.208116/ we get this https://www.old-games.ru/forum/attachments/quake00-png.208115/ (screenshots from other port, but that does not matter). Same for main menu.

**Comment by micwoj92** [comment]
I think you should rather report this to quakespasm devs as far as I know vkquake is just quakespasm + vulkan

**Comment by Novum** [comment]
Correct, please report to QuakeSpasm.

**Comment by KainXVIII** [comment]
Can somebody direct me to quakespasm forum or something similar to github?

**Comment by micwoj92** [comment]
quakespasm in on sourceforge
https://sourceforge.net/projects/quakespasm/
