### ISSUE TITLE
X Error of failed request: BadDrawable

### ISSUE THREAD

**Issue by Starconstructor** [Novum/vkQuake#227]
On Ubuntu 20.04. I compiled the engine and put the data where it's supposed to go, and upon attempting to load the app I get the above error. I'm using a GTX 1050 Ti. My drivers are up-to-date and I've ran glxgears without a single issue or error message. 
Here's the whole thing:
X Error of failed request: BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request: 149 ()
Minor opcode of failed request: 4
Resource id in failed request: 0x720000c
Serial number of failed request: 325
Current serial number in output stream: 329

Is this one of NVIDIA's many Linux driver issues or is there something I need to fiddle with to fix?

**Comment by Novum** [comment]
I'm sorry, but you probably want to ask the SDL2 guys about this. That fails even before Vulkan initialization.
