### ISSUE TITLE
File permission for linux to save games

### ISSUE THREAD

**Issue by gariac** [Novum/vkQuake#228]
I can run vkquake. I can't save the game and Ogre keeps killing me! When I try to save the gameI get a message that it can't write to some file. I wish I could be more helpful but the text of the message is very small, 

I built the game in /usr/local/src/vkQuake. Should the id3 directory be in the user account?

edit: From the terminal window I get the message "Couldn't write config.cfg."

**Comment by neogeographica** [comment]
The original Quake programs, and lots of the ports like vkQuake, by default want to save stuff inside the "id1" directory (and other mod folders) and will look for those folders in the same place as the Quake executable. If your executable is not in a user-writable directory this can cause problems.

If that's your issue, and you want to leave the vkQuake executable where it is, then one solution is to use the "-basedir" argument that can tell vkQuake to look for id1 and the mod folders in some other location. For example if you had your "id1" directory at /home/jimbob/Games/Quake/id1 then you could do "vkQuake -basedir /home/jimbob/Games/Quake" and things should work.

**Comment by Novum** [comment]
Please file a bug with QuakeSpasm, not the scope of this project.
