### ISSUE TITLE
Feature Request:  Resolution scaling.

### ISSUE THREAD

**Issue by ConHuevosGuey** [Novum/vkQuake#229]
Hi.  Would it be possible to implement the 'r_scale' function that was present in the original Quakespasm?  It's pretty enjoyable to replicate the classic quake look by pixelating the image.

https://github.com/Shpoike/Quakespasm/blob/master/quakespasm/Quake/gl_rmain.c#L1037

Thank you.

**Comment by JuanchoES** [comment]
I'd love to see that in the source port! Why would that command have been removed if it was already in quakespasm?

**Comment by Novum** [comment]
Because the renderer is quite different than QuakeSpasm.

**Comment by ZecChelovek** [comment]
3rding this request.

**Comment by LethalManBoob** [comment]
If perhaps for the retro appeal, having the game render at something like 640x480 then yeah i could get behind that. For super sampling though, it is irrelevant.

**Comment by Novum** [comment]
Good point, doing it post rendering is actually much easier.

**Comment by AnotherLife** [comment]
I would like such an option, too, it is great in GZDoom. Whether it's "fake" downscaling or not, it's nice to be able to play in low resolution while the actual resolution is the desktop one.

**Comment by Novum** [comment]
ac45bda7503132a76d786cd4b3b8a9ab08a5b07b
