### ISSUE TITLE
Multiple gamedir support

### ISSUE THREAD

**Issue by neogeographica** [Novum/vkQuake#230]
With more and more releases for Arcane Dimensions and Copper, the approach of "merge these files into your existing AD or Copper directory" is annoying. It's error-prone and is a stumbling block for less technically-minded users. If we could instead deal with them like Quoth releases, i.e. in their own isolated gamedir, it makes a lot of stuff easier: installation, launching, and proper cleanup (including savegames and config).

FTE, QSS, and DarkPlaces already support multiple "-game" arguments on the command line to handle this. The FTE and QSS implementations have the same semantics (unsurprisingly) and also add support for a "-basegame" parameter. These arguments function as follows:

* Multiple "-game" directories can be specified, building in priority from left to right. The console "game" command also now accepts an arbitrary number of gamedir arguments; dash-prefixed arguments like "-hipnotic" get higher priority over non-dash-prefixed.

* The new "-basegame" parameter can be used to optionally replace id1 as the foundational directory and also optionally add even more directories that will not be affected by use of the "game" console command. These also build in priority from left to right, and are always of higher priority than any "-game" directory.

(Note that this does not affect multiplayer in any particular way, as far as I can tell. It's still the case in Netquake that the client has responsibility to set up its own gamedirs correctly for the server that it is connecting to.)

A while back I isolated this feature from the QSS codebase and patched it into my own Quakespasm build. I recently also cherrypicked it over to my own vkQuake build, at https://github.com/neogeographica/vkQuake/commit/0d91eadd60ba7d39842c04b53cbd4b2aeafcada3

If this looks like something you would be interested in accepting a PR for, I can run it through more tests and then make the PR.

**Comment by Novum** [comment]
Pull request is welcome.

**Comment by Novum** [comment]
8b52a5ba316d4b41fb2d778257b686d4389a006f

**Comment by vsonnier** [comment]
Hi, thanks for the addition. Still, it doesn't seem to work for me. If I test it with the  [Copper mod](http://lunaran.com/copper/download/ ), the following command lines do not work:
- `-basegame copper` : complains that IDI paks are not found, and that I need a registered Quake game at startup
-  `-basegame id1 copper`  :  launch, but it starts as ID1, not Copper, as seen in the menu apparence.
-  `-basegame copper id1` : same thing as the first case.

What am I doing wrong here ?

**Comment by neogeographica** [comment]
Yah, a bit of confusion there. There's a couple of different things you could/should do.

To run copper itself and nothing else, you would just use `-game copper` as usual.

But let's say you have another mod folder named "ctsj" that depends on Copper. You could run that using the arguments `-game copper -game ctsj`.

Note that you **don't** need to use "basegame" in either case. Basegame is used if you need to replace id1, really, although there might be some case where you would use it just for its side effect of making a gamedir immune to the "game" console command. So it would also be possible to run copper using the arguments `-basegame id1 -game copper` for example, or to run ctsj using `-basegame id1 -basegame copper -game ctsj`. But that's probably just being more complicated than necessary.

**Comment by vsonnier** [comment]
@neogeographica Thanks for your quick answer and explanation. Now it works.
