### ISSUE TITLE
The new version of Slayer Testament doesnt work in vkquake 

### ISSUE THREAD

**Issue by JuanchoES** [Novum/vkQuake#233]
The mod doesnt work

**Comment by micwoj92** [comment]
Did you check if it works with quakespasm?

**Comment by Novum** [comment]
How about providing a link to the mod and anything else than "it doesn't work". Does it crash? Is the rendering broken?

I'm about to close all of those low effort bugs without comment.

**Comment by Ds886** [comment]
I've tested the mod using both latest git commit and latest release and get the same result
`Found SDL version 2.0.12
Detected 24 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.93.2 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 1.04.1 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 11:17:50 Sep 20 2020
256.0 megabyte heap

Vulkan Initialization
Using VK_KHR_get_surface_capabilities2
Using VK_KHR_get_physical_device_properties2
Vendor: NVIDIA
Device: GeForce GTX 1060 6GB
Using VK_KHR_dedicated_allocation
Using A2B10G10R10 color buffer format
Using X8_D24 depth buffer format
Creating command buffers
Initializing staging
Creating descriptor set layouts
Reallocating dynamic VBs (256 KB)
Reallocating dynamic IBs (1024 KB)
Reallocating dynamic UBs (256 KB)
Initializing samplers
Creating pipeline layouts
Using IMMEDIATE present mode
Creating color buffer
AA disabled
Creating depth buffer
Creating render passes
Creating frame buffers
Creating pipelines

Sound Initialization
SDL audio spec  : 44100 Hz, 1024 samples, 2 channels
SDL audio driver: pulseaudio - Gaming Headset [Kraken USB] Analog Stereo, 65536 bytes buffer
Audio: 16 bit, stereo, 44100 Hz
CDAudio disabled at compile time

========= Quake Initialized =========

execing quake.rc
execing default.cfg
execing keybinds.cfg
execing config.cfg
execing doom_defaults.cfg
Unknown command "gl_texturemode"
Unknown command "seta"
Unknown command "seta"
Unknown command "seta"
Unknown command "seta"
Unknown command "seta"
couldn't exec autoexec.cfg
Couldn't spawn server maps/menu.bsp
Couldn't spawn server maps/demo_map.bsp
1 demo(s) in loop
`
The mod is published through discord for some reason but it is attainable through:
[base](https://drive.google.com/file/d/1Lht-DBgldnA9G7W2IAJdCT4HkBhdD6Lo/view?usp=sharing)
[patch2](https://drive.google.com/file/d/1LqM7whhNx2v0qPB7CGyFJRfrfxjfwVCL/view?usp=sharing)
[patch3](https://drive.google.com/file/d/1HceC3VFDMljL-AhknlLWnOvp_l1hcO6F/view)

**Comment by JuanchoES** [comment]
This is the link to the mod https://drive.google.com/file/d/1Lht-DBgldnA9G7W2IAJdCT4HkBhdD6Lo/view

when you try to run the mod this error appears 
![image](https://user-images.githubusercontent.com/70743149/93714279-da3c3600-fb61-11ea-8f67-f9dccc4c5dff.png)

**Comment by JuanchoES** [comment]
> How about providing a link to the mod and anything else than "it doesn't work". Does it crash? Is the rendering broken?
> 
> I'm about to close all of those low effort bugs without comment.

**Comment by Ds886** [comment]
Quake run for me but it can't load the map, I am not sure how you utilize debugging outside of the compiling flag.

the mod requires increased heap size I believe

that the original bat file launcher settings 
"quakespasm-spiked-win64.exe -game SlayerTest -heapsize 524288"

It is utilizing certain rendering features from quakespasm-spiked
disabling gl_flashblend in the config of the mod remove the latter gl_errors but the map doesn't load.
I've tried backporting gl_flashband  but I am not too familiar with the codebase and have the time right now for the debugging process and couldn't really get the debug starting.

**Comment by Novum** [comment]
Invalid. I'm not going to support 8k textures in vkQuake, that's just silly.

**Comment by JuanchoES** [comment]
Sad to think that I won't be able to play the best quake mod ever on my favorite sourceport

**Comment by eGax** [comment]
There are no 4K textures used in Slayer's Testaments that I am aware of?? SO ST works fine in Quakespasm AND Quakespasm-spiked? It feels odd it won't run in vkq?

**Comment by Novum** [comment]
This error means either there is a texture larger than 32MB or the total texture set is over 1GB. Both are nuts for a Quake mod.

**Comment by JuanchoES** [comment]
I have talked to the ST dev and he has confirmed that there are no 4K textures, I am going to send him your email to see if you guys can fix this.

![image](https://user-images.githubusercontent.com/70743149/94643989-5cf28d00-02e8-11eb-86cc-7e4df20466c2.png)

If you want to speak with him this is his Discord ID "BloodShot#5574"

**Comment by Novum** [comment]
This is fixed with 2bcd4ef65abc44684ff6a49ed531f877c300c87c. It was vertex buffers, not textures and I still think it's extremely silly for a Quake mod to use more than 64MB for vertex data.

**Comment by eGax** [comment]
Thank you!

**Comment by JuanchoES** [comment]
:D thanks!
