### ISSUE TITLE
Suggestion: include Quake shareware pak so it works out of the box

### ISSUE THREAD

**Issue by matcarfer** [Novum/vkQuake#234]
Like vkquake2.

**Comment by mjr4077au** [comment]
I personally hate that. Everytime a new version comes out and I extract it over the top, it overwrites valid PAK files with shareware files and the game doesn't work.

**Comment by matcarfer** [comment]
Well, I always do a clean install each version, but I understand you. Thing is that bundling a shareware pak is easier for less tech savy people to try quake, check if vulkan is working, or a really fast way to play deathmatch. In my office, we often download the latest vkquake2, and play right away, as many of my coworkers dont know what to do or how to set up basic things. Of course, this is a suggestion.

**Comment by mjr4077au** [comment]
Best of both worlds would be to include it in a zip file with the engine itself, gives it to the people but it's opt-in at that point. Wasn't knocking your suggestion as such, just putting my two cents in about how it can be a detriment as I honestly just about always forget about it and then have to get the PAK files out of the ISO again

**Comment by matcarfer** [comment]
> Best of both worlds would be to include it in a zip file with the engine itself, gives it to the people but it's opt-in at that point. Wasn't knocking your suggestion as such, just putting my two cents in about how it can be a detriment as I honestly just about always forget about it and then have to get the PAK files out of the ISO again

I understand you, but your problem its avoidable and has a really easy fix, on the other hand, if the shareware pak is included, it becomes just "download and play" and many people that do not know stuff like we do, get to play the game in an instant. On top of that it becomes so fast that it helps to demonstrate correct vulkan functionality.

**Comment by mjr4077au** [comment]
Sounds good to me, there's no right or wrong here. It's basically a ”chocolate is better than vanilla" argument 😁

**Comment by Novum** [comment]
Na. Also I'm pretty sure that's not allowed by the license.
