### ISSUE TITLE
Problem with .pak identification

### ISSUE THREAD

**Issue by MrAlcoholicFox** [Novum/vkQuake#235]
I discovered (when ripping my own .pak files) that they were called PAK0.PAK and PAK1.PAK instead of all lowercase. When this happens the game cannot identify them and you have to change the capitalization to all lowercase.
You don't have to fix this just include it in the readme. Here are some screenshots with proof
![Screenshot_20200915_025631](https://user-images.githubusercontent.com/24240220/93039004-84b3e500-f69a-11ea-85e5-c22e86d2688c.png)
![Screenshot_20200915_025557](https://user-images.githubusercontent.com/24240220/93039009-867da880-f69a-11ea-90d9-a8877d2fa1c3.png)

**Comment by Novum** [comment]
Yes, Linux has a case sensitive file system.
