### ISSUE TITLE
Advance Notice of New Validation Errors

### ISSUE THREAD

**Issue by karl-lunarg** [Novum/vkQuake#236]
(Follow-up to withdrawn PR #231)

LunarG is [adding additional validation checks](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2168) for checking that the appropriate push constants are set for the pipelines that reference them.  These checks will likely be active in the next SDK coming out near the end of this month.

We've found two areas where vkQuake isn't setting some push constants properly:

1: Fog.  In the opening menus, before selecting "New Game", a pipeline is selected that has 16 bytes of fog data at byte offset 64 in the push constant range.  But there are no commands issued to set these constants.  The issue goes away when entering the game because it switches to full 3D rendering where it sets the fog data.  The issue also doesn't exist when exiting the game to the end menu because the "game" screens are still being rendered behind the menu.

One suggested fix is to add a call to `Fog_DisableGFog()` after the call to `GL_SetCanvas()` in function `GL_Set2D()` in file `gl_draw.c`.   This seems to be a logical place because 2D rendering generally doesn't have fog.

A more comprehensive fix would probably be to use pipelines that don't have fog data in the push constants for the initial menu set.  But this is a more complex change and beyond my understanding of the code.

---

2: Alpha.  At least one pipeline has a reference to a 4-byte floating alpha value at byte offset 80 in the push constant data.  This push constant is set only when alpha blending is enabled, which appears to be off by default.  So there are validation errors as soon as the game starts.

The "need" for a fix here is a bit debatable since the access to the alpha value is controlled by a specialization constant and the specialization constant can be set to a value that would cause the shader to not access the value.  The rules for specialization constants say that an implementation is not obligated to remove dead code.  If the code that accesses the push constant is still present, even if not reachable, then that still constitutes the "statically used" condition that is referred to in VU [02698](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-None-02698). 

There is no clear statement about what the validation layer should do here.  LunarG is discussing a fix that will essentially "apply" the specialization constants to the shader and then use the resulting shader to determine what push constants it is still referencing.

Since it is unclear when/if the validation layers will do this extra work, it may be worthwhile to add code to set this alpha push constant, even if known that it won't be used.  I found that setting it in `Fog_DisableGFog()` appears to work.  Although unconditionally setting it in `R_DrawTextureChains_Multitexture()` may work too, but I did not try it.

Clearly, it would be better if the validation layer didn't report an error for this usage, so another path would be to wait and see if the layer does the preferred thing here.

**Comment by Novum** [comment]
I still don't see how this should even be a validation error. If the value is unused why would implementations care?

**Comment by Novum** [comment]
This should be fixed for good with eda8ace909c220ab0812fc93bde2d7b1f24b2f6b
