### ISSUE TITLE
Feature Request: Quakespasm Spiked HUD

### ISSUE THREAD

**Issue by Zaratul555** [Novum/vkQuake#239]
https://twitter.com/SimsOCallaghan/status/1312005429032095744
https://twitter.com/SimsOCallaghan/status/1305894896449003522

Its possible to add QSS HUD like in that screenshots?

**Comment by Novum** [comment]
Maybe. Need to check what the changes are exactly.

**Comment by dumptruckDS** [comment]
No those are specific to Arcane Dimensions. I would not bother adding them.

**Comment by Novum** [comment]
No what? Of course it's possible to add this. Speak for yourself.

**Comment by AnotherLife** [comment]
Ah, it would be nice to have fullscreen HUD with elements in the corners. The higher the resolution and the aspect ratio get, the more unwieldy the old center bottom HUD is. It is hard to see the ammo counts quickly because the numbers are too small and at the same time it takes up too much useful real estate lol

**Comment by Novum** [comment]
This isn't a simple thing. As pointed out this needs the full client side QC code including the UI interface that was added to QSS. I need to look through this, I don't like some of the QSS code to be honest.

**Comment by dumptruckDS** [comment]
I didn't mean to come off rude above but I see that as a mod thing. Do you want to add more features from AD to Quake like projectile shotgun pellets? Where do you stop? Is it worth the effort? Mod authors could take care of this or players can play vanilla maps in AD to get the same result. As far as I know it's backwards compatible.

**Comment by dumptruckDS** [comment]
> Ah, it would be nice to have fullscreen HUD with elements in the corners. The higher the resolution and the aspect ratio get, the more unwieldy the old center bottom HUD is. It is hard to see the ammo counts quickly because the numbers are too small and at the same time it takes up too much useful real estate lol

Not sure if you are aware you can scale your console, HUD and menu with these commands:
`scr_conscale "3"
scr_sbarscale "3"
scr_menuscale "3"
`

**Comment by AnotherLife** [comment]
Scaling the HUD to see the ammo counts better makes it take too much real estate.

Also, it would be nice to have a modern fullscreen HUD (I mean elements at screen corners) as an engine feature, regardless of mods. For example, I want to play the original game + mission packs with a nice HUD on my brand new big curned HD screen :D

**Comment by SimsOCallaghan** [comment]
Adding SCQC support would be an awesome idea, especially for the quake community. Being able to change the hud around, add new elements or create different layouts has been missing from many quake engines for a long time. The feature has been part of DP/FTE for a long time (5+ yrs) and was only recently added to QSS. I added it to AD on spike's recommendation and having more engines support CSQC would benefit everyone.

**Comment by Novum** [comment]
I agree Simon, that's why I haven't closed the request. It's quite involved though.

**Comment by Novum** [comment]
@SimsOCallaghan Initial implementation is done:
![image](https://user-images.githubusercontent.com/112222/122142516-48720880-ce15-11eb-98e5-1627076596bc.png)
Some bits missing, it's currently not running in "full" csqc mode, e.g. it doesn't call "renderscene"

**Comment by Novum** [comment]
I decided that I'll just support the HUD stuff for now 89f01da6371cc2fadb185a48da2d718e1741b2d2

**Comment by SimsOCallaghan** [comment]
> 
> 
> @SimsOCallaghan Initial implementation is done ([4993ee3](https://github.com/Novum/vkQuake/commit/4993ee35de5f139e3b44b1db3edbdb5d3be20c6d)):
> ![image](https://user-images.githubusercontent.com/112222/122142516-48720880-ce15-11eb-98e5-1627076596bc.png)
> Some bits missing, it's currently not running in "full" csqc mode, e.g. it doesn't call "renderscene"

Awesome, thanks for doing this. Having another engine support csqc is great for the community.

**Comment by carloshpsilva** [comment]
Hi, where can I get an example of a minimal CSQC HUD in vkQuake ?

**Comment by Novum** [comment]
Not minimal but Arcane Dimensions and Alkaline have code on GitHub
https://github.com/SimsOCallaghan/ArcaneDimensions
https://github.com/fabiolimamp/alkaline
