### ISSUE TITLE
basedir should contain search paths, such as /usr/share/quake

### ISSUE THREAD

**Issue by ProfessorKaos64** [Novum/vkQuake#24]
I'm currenlty looking into this. But somehow,  vs. quakespasm, the basedir isn't quite set correctly or linked to the right expected directory of /usr/share/quake.

Steps 

1. install vkquake to /usr/games
2. try to launch, get generic "can't find gfx.wad" error

To make it work

1. `cd /usr/share/quake` (where id1 is placed)
2. run `vkwuake` 
3. game runs.

```
The "base directory" is the path to the directory holding the quake.exe and all
game directories.  The sys_* files pass this to host_init in quakeparms_t->basedir.
This can be overridden with the "-basedir" command line parm to allow code
debugging in a different directory.  The base directory is only used during
filesystem initialization. I
```

There should be a way to pass some defaults or search paths. In comparison [FTE Quake](https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk/) functions this way. Also, this is how quakespasm works, so I don't believe it was any code committed here thus far.  believe FTE does this in [fs.c](https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk/engine/common/fs.c)

My workaround in situations like this, is a simple [launcher/wrapper](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/vkquake/build-vkquake.sh).

**Comment by Novum** [comment]
I didn't change any code related to this from QuakeSpasm

**Comment by ProfessorKaos64** [comment]
I guess it was more of a request. Since I e show the engine differ a bit, I'll just close.
