### ISSUE TITLE
Mirror for episode files not reachable

### ISSUE THREAD

**Issue by rmiklautz** [Novum/vkQuake#241]
> Quake has 4 episodes that are split into 2 files:

>pak0.pak: contains episode 1
> pak1.pak: contains episodes 2-4
> These files aren't free to distribute, but pak0.pak is sufficient to run the game and it's freely available via the [shareware version of Quake. ](http://bit.ly/2aDMSiz) Use 7-Zip or a similar file archiver to extract quake106.zip/resource.1/ID1/PAK0.PAK. Alternatively, if you own the game, > you can obtain both .pak files from its install media.

Unfortunately the link above it not reachable. Do you know any other mirror?

**Comment by micwoj92** [comment]
Just searched for ftp id software, took 30 seconds https://ftp.gwdg.de/pub/misc/ftp.idsoftware.com/idstuff/quake/

**Comment by Novum** [comment]
How is this my problem?
