### ISSUE TITLE
[Feature request] .vis file support

### ISSUE THREAD

**Issue by NightFright2k19** [Novum/vkQuake#242]
It would be great if .vis files were supported for transparent water. Like this, the lit/vis packs from Mark V could be used directly and full water transparency would be possible without having to use r_novis 1 or vis-patched maps.

**Comment by Novum** [comment]
Had to revert the fix because it broke the arcane dimensions start map

**Comment by sezero** [comment]
If there is still interest in this, attached a new patch for this at https://github.com/Novum/vkQuake/pull/283#issuecomment-882031397

**Comment by Novum** [comment]
@sezero Yes, that looks good. Feel free to just commit it.

**Comment by sezero** [comment]
OK, patch applied as https://github.com/Novum/vkQuake/commit/5bff2903b13bcf58af5a51060b492ade0a49d94b with a TODO note:
If `<mapname>.vis` isn't found, search for `<gamedir>.vis`
(such as `id1.vis`, etc.), maybe?

**Comment by sezero** [comment]
Pushed https://github.com/Novum/vkQuake/commit/b891ecbd1d66146ad611cb2a4d5d159d67243c36 as a follow-up patch
