### ISSUE TITLE
[Feature request] Activate mouselook by default

### ISSUE THREAD

**Issue by NightFright2k19** [Novum/vkQuake#243]
I think there is nobody left who would want to play this game with keyboard only these days, so it makes perfect sense to set +mlook in the config file right away at the first startup.

**Comment by LethalManBoob** [comment]
Yeah this is in glquake from my understanding. Also for the sake of declutter i wont make this its own issue but howcomes quakespams shadow support is broken in vkquake?

**Comment by NightFright2k19** [comment]
Even though it's unrelated: It seems r_shadows is not supported in vkQuake, just don't know why. There were at least 2 tickets closed already regarding the topic.

**Comment by Novum** [comment]
The shadows in Quake are beyond broken, I see no point in supporting them.

**Comment by Novum** [comment]
I checked and mouselook has always been enabled by default. There is +mlook in default.cfg from vkquake.pak. Same as QuakeSpasm.

**Comment by Novum** [comment]
Note that e.g. the GoG Quake release by mistake includes a config.cfg in the id1 folder which will the vkQuake defaults. But even that one doesn't disable mouselook, just assigns keys weirdly.

**Comment by Novum** [comment]
Also make sure you copied vkquake.pak to the Quake folder, otherwise it will not work. This is likely the issue.
