### ISSUE TITLE
[Feature request] Fast forward/rewind for demos, like in Mark V

### ISSUE THREAD

**Issue by Greenwood72** [Novum/vkQuake#246]
Probably the biggest thing that I find nifty about Mark V is its ability to rewind/fast forward demos.
As a mapper, this is a nice feature to have when reviewing playtester's demos.
It's simple to use: the arrow keys at the bottom right of the keyboard act as the controls.

P.S. Love this source port!

**Comment by Novum** [comment]
I believe this has been implemented @temx ?

**Comment by temx** [comment]
It's not the same as Mark V's continuous backward playback (which is more involved to support, especially with QSS' additions), but hopefully close enough, yes.
