### ISSUE TITLE
Episode 2 of Slayer Testament crashes.

### ISSUE THREAD

**Issue by JuanchoES** [Novum/vkQuake#247]
When you try to go to the portal of episode 2 the game crashes.

Crash error: 
![image](https://user-images.githubusercontent.com/70743149/96194283-57cd4900-0f4a-11eb-9ee7-bdcede4291bb.png)

The mod:
https://drive.google.com/file/d/1Lht-DBgldnA9G7W2IAJdCT4HkBhdD6Lo/view

The patches that i did use:
https://drive.google.com/file/d/1LqM7whhNx2v0qPB7CGyFJRfrfxjfwVCL/view
https://drive.google.com/file/d/1HceC3VFDMljL-AhknlLWnOvp_l1hcO6F/view
https://drive.google.com/file/d/1TZmM5ZCeE2d3MixsCtA7wzvJemOk3V-1/view

at least the mod doesn't crashes when it launches haha.

**Comment by Novum** [comment]
Probably fixed with cb02137df1a18d2edf423f5498099f8e241b4f63

**Comment by JuanchoES** [comment]
Yup! I  can confirm that i can now enter in to the 2 episode without crashing, good job :)
