### ISSUE TITLE
Anti-aliasing won't work in Ubuntu 20.04

### ISSUE THREAD

**Issue by amiga1985** [Novum/vkQuake#251]
My version of vkQuake works well except for the fact that anti aliasing doesn't do anything. In the console, it just says "AA disabled", and I can't seem to figure out what the problem is. I tried reinstalling, and that didn't work, and I don't know what the root of the problem is. Is this a bug that can be patched?

**Comment by LethalManBoob** [comment]
this applies to all forms of multisampling and super sampling right? Can we get a look at what the game says upon booting in the console?

**Comment by micwoj92** [comment]
Could you verify if aa works with any other game or is just vkQuake problem? Are you sure you clicked on "apply changes" in the video settings menu? It might be hard to spot because of bad graphics.

**Comment by amiga1985** [comment]
Doesn't work when I hit apply changes. In the console, it still says AA disabled in the console when booting, and after changing video settings.

**Comment by Ds886** [comment]
maybe it is an issue with permissions, are you able to change any other options?

**Comment by amiga1985** [comment]
I ran it with sudo, still didn't work. My guess is that it is a problem with the drivers. Maybe 20.10 has better ones, but I still have to find out. I guess this is a small issue that really doesn't matter that much.

**Comment by Novum** [comment]
Clearly a driver issue.
