### ISSUE TITLE
FEAR mod 2.0 crashes when attempting to load into the start map

### ISSUE THREAD

**Issue by awksie** [Novum/vkQuake#252]
The mod is the ancient FEAR20.ZIP from the old idgames2 directory:
http://www.gamers.org/pub/idgames2/quakec/compilations/

The error message is: 
![image](https://user-images.githubusercontent.com/8469453/97108060-eb182400-1698-11eb-8a40-a3fc243a4a11.png)

Quakespasm-Spiked crashes in exactly the same fashion. However, it works in DOS Quake in DOSBox!

**Comment by Ds886** [comment]
Changing gl_model.h:339 from
```
#define MAX_SKINS       32
```
to

```
#define MAX_SKINS       36
```
or above make it going past the loading.

the sound rendering seems to be broken.

**Comment by Novum** [comment]
I don't really aim to support things that don't run on QuakeSpasm either.
