### ISSUE TITLE
Styled lightmaps on dynamic bmodels are broken

### ISSUE THREAD

**Issue by ZecChelovek** [Novum/vkQuake#254]
Someone has found this on the /vr/ fps thread, directly linked here:
https://desuarchive.org/vr/thread/7033095/#7040230
including which commit did it:
https://github.com/Novum/vkQuake/commit/253a706f8907866ae7ab664e092cdcb6ae43cfc2

**Comment by JuanchoES** [comment]
![image](https://user-images.githubusercontent.com/70743149/97766537-0bbc0000-1b17-11eb-8f2c-515d9ee70e31.png)

It's happening to me too.

**Comment by Novum** [comment]
cae39a8fb08149571be9a6f95546bb1fa9043a82
