### ISSUE TITLE
r_fullbright 1 and r_lightmap 1 don't work in vkQuake

### ISSUE THREAD

**Issue by bstordeur** [Novum/vkQuake#255]
The "r_fullbright 1" and "r_lightmap 1" console commands don't work in vkQuake, these are pretty handy for debugging while mapping.
I looked around for some alternate commands (like I know the filtering doesn't work with same commands as previously) but couldn't find anything.

**Comment by Novum** [comment]
By design.

**Comment by bstordeur** [comment]
What's the reasoning behind this, are there alternatives that I'm missing?
These 2 commands are pretty essential to the lighting process while mapping.

**Comment by Novum** [comment]
Hey @bstordeur. The reason is that it would be quite a bit of extra code because of how Vulkan works and I removed those non user facing features to make it simpler tbh. Same thing with wireframe (although I added that partially) etc.

**Comment by bstordeur** [comment]
Ok thanks for the explanation, that makes sense.
It's always nice to have one engine to handle everything, so that's a bit unfortunate, will stick to QS/QSS for mapping for now, although it was reassuring to see the higher fps in vkQ. :)

**Comment by Novum** [comment]
@bstordeur r_lightmap has been recently implemented
