### ISSUE TITLE
Arcane Dimensions: Stuttering on elevators

### ISSUE THREAD

**Issue by dezo2** [Novum/vkQuake#256]
Hi, I noticed that there is some ugly stuttering when moving on elevators - especially in Arcane Dimensions "The Crucial Error" map but also in some others. As if the camera sinks bellow the elevator plate randomly. I thought this is due to my 144Hz refresh but it behaves the same at 60 or 72 FPS. It is also present in vanilla Quakespasm but the Spiked fork (QSS) is completelly smooth in this regard. Is there some tweak that can be ported from QSS to vkQuake? QSS runs OK most of the time but has performance/resources utilization problems on large maps just like vanilla Quakespasm. vkQuake runs absolutelly stunning with everything I throw at it!

Here are saves from the map before an elevator (Arcane Dimensions 1.8 patch 1).
[s18.zip](https://github.com/Novum/vkQuake/files/5480449/s18.zip)
[s19.zip](https://github.com/Novum/vkQuake/files/5480192/s19.zip)

**Comment by Novum** [comment]
Are you sure you don't have some cvars set differently? This should be the same as with QSS?

**Comment by dezo2** [comment]
I changed only some scr_* cvars for scaling, nothing else. No changes in timing or something. It behaves the same even with default clean installation of Quakespasm or vkQuake. Maybe QSS has some additional tweaks for this. Frankly it happens only when elevator is moving up, not down. It is not a big deal or something, just looks weird if everything else is so smooth at 144 FPS.

**Comment by Novum** [comment]
Yeah, I can repro. You are right. I wonder if that is a regression, I feel like this worked before.

**Comment by Novum** [comment]
Nope, happens with 1.02.1 as well

**Comment by ericwa** [comment]
This sounds like an issue I've investigated before in Quakespasm.

Is the progs.dat doing a `stuffcmd('fog x x x x')` fog transition every frame when on this elevator? From what I recall, this sends a reliable packet to clients which causes `cl.onground` to be cleared every frame, which leads to the stuttering. Not sure the details of why but my understanding is it's a limitation in the original engine/netquake protocol.

Spike avoid this in his new network protocol in QSS.

**Comment by Novum** [comment]
Oh, that's good to know. Thanks.

**Comment by Novum** [comment]
Well, I have been working on a rebase of vkQuake on top of QSS instead of QuakeSpasm, but it's not completely trivial and I don't know if I want to take all the changes, so this might take a while.

**Comment by dezo2** [comment]
That's actually great news, looking forward to the new version. Thanks!

**Comment by ZecChelovek** [comment]
^^That's some swell news. Please take your time.

**Comment by Novum** [comment]
The amount of changes to fix this is pretty absurd. It basically drags in the entire net changes from QSS. I started merging but I'm not sure if I'm comfortable with all of those changes.

**Comment by Yellenten** [comment]
Perhaps fork development? vkQuake-QSS, and then your vkQuake proper. Granted that's a matter of time investment and how much you have.

**Comment by micwoj92** [comment]
> Perhaps fork development? vkQuake-QSS, and then your vkQuake proper. Granted that's a matter of time investment and how much you have.

There already is "qss-rebase" branch, if that's what you mean https://github.com/Novum/vkQuake/tree/qss-rebase

**Comment by Yellenten** [comment]
Nah what I mean is if he ever got around to finishing this merging, it's not as if vkQuake 1.05.1 would disappear, know what I mean? He oughta finish this, and then see how he and the end users feel about it, eh? And if it doesn't work out, vkQuake 1.05.1 is still there.

**Comment by dezo2** [comment]
I would be happy even with a simple hack to bypass that packet sending ericwa wrote about - if that's the culprit.
Don't really need everything from QSS, but its up to Novum now.

**Comment by Novum** [comment]
It's not that simple. Even in single player Quake is acting like a client and server. You can't just not send movement packages. The new protocol makes those packets different to fix a bunch of things.

**Comment by Riccardoman** [comment]
Amazing news Novum! Can't wait to test your branch of QSS!

**Comment by Novum** [comment]
QSS won't happen. Too many changes that I don't want.

**Comment by Riccardoman** [comment]
Do you plan to fix the elevators?

**Comment by Novum** [comment]
As I said the elevator fix basically drags in the entire QSS net code. So maybe not.

**Comment by Novum** [comment]
d9d4be488436c50afcc75b2aacdb50127f6546ab
