### ISSUE TITLE
Mouse gets stuck in the top left corner upon alt+tabbing

### ISSUE THREAD

**Issue by ZecChelovek** [Novum/vkQuake#257]
Using the latest release, hadn't happened in 1.04. Unbinding alt from +strafe doesn't solve the issue.

**Comment by AnotherLife** [comment]
It's fine for me with stable 1.05.1 on fully updated Windows 8.1 x64 and latest stable Nvidia drivers. Upon alttabbing the mouse is at coords 0,0 but it is not stuck.

**Comment by Novum** [comment]
What OS?

**Comment by ZecChelovek** [comment]
^Windows 10, x64.

**Comment by Novum** [comment]
Are you sure you are running with the SDL2.dll that is bundled with the download?

**Comment by ZecChelovek** [comment]
^Yes indeed about the SDL2 part. Disabling fullscreen resolves the issue for some reason, so I suppose that's that.

**Comment by Novum** [comment]
And you are running latest drivers?

**Comment by ZecChelovek** [comment]
Most definitely. Perhaps it's an isolated incident?

**Comment by Novum** [comment]
Well, I can't reproduce it for sure.

**Comment by AnotherLife** [comment]
No, the OP has the problem on win 10. For me on win 8.1 it's fine!

**Comment by Novum** [comment]
Oh, gotcha.

**Comment by ZecChelovek** [comment]
^Hey thanks for the continued effort. Running a Radeon RX 480, latest drivers. W10 64it just to reiterate.

**Comment by AluminumHaste** [comment]
I have the same problem with fullscreen, alt+tabbing, mouse gets stuck on the left corner, 0,0. I can move it away but it's constantly moving back to 0,0.

         Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
                     BIOS: BIOS Date: 07/22/20 16:34:17 Ver: 05.0000E (type: BIOS)
                Processor: AMD Ryzen 9 3900X 12-Core Processor  (24 CPUs), ~3.8GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16308MB RAM
                Page File: 7618MB used, 11122MB available

Card name: AMD Radeon RX 5700 XT
Driver File Version: 27.20.14501.28009 (English)

   Driver: C:\WINDOWS\System32\DriverStore\FileRepository\u0361901.inf_amd64_204a65b18f2a904a\B361909\amdvlk32.dll, 27.20.14501.28009 (English), 12/7/2020 15:44:00, 34801976 bytes
   Driver: C:\WINDOWS\System32\DriverStore\FileRepository\u0361901.inf_amd64_204a65b18f2a904a\B361909\amdvlk64.dll, 27.20.14501.28009 (English), 12/7/2020 15:44:02, 40364856 bytes
   Driver: C:\WINDOWS\System32\DriverStore\FileRepository\u0361901.inf_amd64_204a65b18f2a904a\B361909\amd-vulkan32.json, 12/7/2020 14:18:34, 703 bytes
   Driver: C:\WINDOWS\System32\DriverStore\FileRepository\u0361901.inf_amd64_204a65b18f2a904a\B361909\amd-vulkan64.json, 12/7/2020 14:18:34, 703 bytes


==========
VULKANINFO
==========

Vulkan Instance Version: 1.2.154


I recorded a video:
https://youtu.be/05xee9P2MY0

Looks like the mouse is moving back up every frame update on the desktop (144hz)

**Comment by Novum** [comment]
I decided to turn full screen exclusivity off for anything but NVIDIA drivers for now to work around this 724d03cf5ea74f84f388f9088fe308dabf9d6851
