### ISSUE TITLE
missing first person animation interpolation 

### ISSUE THREAD

**Issue by Riccardoman** [Novum/vkQuake#259]
While shooting the screen shake skips a lot of frames
Also the interpolation on some buttons is absent

**Comment by LethalManBoob** [comment]
set the command to interp animations value to 2. it interps everything but causes some oddities.

**Comment by Riccardoman** [comment]
cannot find the command, are they r_lerpmove and r_lerpmodels? they don't seem to work

**Comment by AnotherLife** [comment]
r_lerpmodels

Set it to 2

**Comment by Riccardoman** [comment]
tried it.... doesn't work
it interpolates even the fire, but not the screen movement when you shoot (for example the shotgun, which it's really noticeable

Ok I tried to compare QS, QSS and VKQ... now I'm certain of it. VKQ has the same issue that QS vanilla has, but QSS had it fixed

**Comment by AnotherLife** [comment]
Wow, much smoother now, why isn't it the default?

**Comment by LethalManBoob** [comment]
v_viewkick 0
try that

**Comment by LethalManBoob** [comment]
v_gunkick 0
not viewkick my bad

**Comment by Novum** [comment]
By design. QuakeSpasm and vkQuake want to be faithful to the original Quake.
