### ISSUE TITLE
map Egyptoagula does not load

### ISSUE THREAD

**Issue by Riccardoman** [Novum/vkQuake#260]
Egyptoagula loads correctly with QS/QSS, not in vkquake
the error is: host_error: mod_loadmodel: progs/trap_sawblade.mdl not found
Also the port has difficulties with the Keep mod, doesn't load many models (portals etc...)
The progs folder in the keep mod has many subfolders, maybe that's the issue

**Comment by ZecChelovek** [comment]
Where did you download it, quaddicted or celephais? I've yet to finish that map, but it ran just now as I write this. If you got it on one website, try the other.
https://www.quaddicted.com/reviews/egyptoagula_final.html
https://www.celephais.net/board/view_thread.php?id=61683

**Comment by Riccardoman** [comment]
Whe I reinstalled I forgot to patch the keep main folder, now it works
Still, very bizarre that it worked without errors in the console on QSS without the tweaks...
