### ISSUE TITLE
Flashing texture in E2M1 secret passage (fake wall)

### ISSUE THREAD

**Issue by AnotherLife** [Novum/vkQuake#263]
![vkquake0010](https://user-images.githubusercontent.com/7148117/100478780-ed84f800-30f4-11eb-9e83-31a60cfd7a41.png)
This is a flashing texture in that fake wall secret in E2M1 in the room you get when you cross the path in the flooded room just after the start of the map. The flashing light reveals the secret. I have watched Youtube videos of other ports and of the DOS version and this glitch shouldn't happen, I believe.

I think this isn't the usual z-fighting issue. The zfix console variable has no effect on this glitch while it fixes the flashing texture very close to this where the enemy is revealed.

**Comment by ZecChelovek** [comment]
Can conquer that it's there on the latest release. Rolled back to 1.04.1 just to check if it wasn't there then, and it is not.

**Comment by Riccardoman** [comment]
Same issue for me

**Comment by JuanchoES** [comment]
On my pc i dont see nothing wrong

![image](https://user-images.githubusercontent.com/70743149/102764460-75b88f00-437b-11eb-99ee-6bf8bbc046eb.png)

**Comment by Novum** [comment]
Yeah, I also can't reproduce this. Strange.

**Comment by maikmerten** [comment]
I can confirm this on Linux with AMD Radeon integrated graphics (Device: AMD RAVEN (DRM 3.35.0, 5.4.0-58-generic, LLVM 10.0.0)).

The affected surface belongs to a func_illusionary (AFAIK) that is affected by a light with a strong strobing effect. It appears that lightmap updates are applied to the bmodel of the func_illusionary with at least (or perhaps exactly?) one frame delay:

- if one basically freezes game time (host_timescale 0.0001), then the QuakeC code will not change the light style. The camera can still be moved around (mouselook) and no flickering whatsoever occurs.
- from playing around with low values for host_maxfps I got the impression that the lightmap update delay is one frame.

**Comment by JuanchoES** [comment]
is this how it's supposed to look? When i play at 1000 fps i see nothing, but when playing at the original framerate of quake a black square appears.

https://user-images.githubusercontent.com/70743149/103139046-944ebb00-46d8-11eb-92f5-c041f55460b5.mp4

**Comment by maikmerten** [comment]
Yeah, that's exactly the problem I'm seeing. Thanks for doing a video capture. It appears that the lightmap update on the func_illusionary is not delayed but actually *leading* the lightmap update for the rest of the world.

![slowmo](https://user-images.githubusercontent.com/2611432/103139477-de39a000-46dc-11eb-8a7a-f0469d2f4fb4.gif)

**Comment by Novum** [comment]
I think there is a delay of one frame in one of the code paths

**Comment by Novum** [comment]
c781043c4fa28b278a5566bd8c939915fd80ab00
