### ISSUE TITLE
[Feature Request] All things that Quakespasm Spiked can offer

### ISSUE THREAD

**Issue by Toadfield** [Novum/vkQuake#265]
The things like unlimited fps,particles etc. but with the vulkan api.

**Comment by mjr4077au** [comment]
QSS won't happen. Too many changes that I don't want.

_Originally posted by @Novum in https://github.com/Novum/vkQuake/issues/256#issuecomment-737666301_

**Comment by Novum** [comment]
Unlimited FPS has been in vkQuake since several months.
