### ISSUE TITLE
latest 1.05.1 can't load AD 1.81

### ISSUE THREAD

**Issue by AluminumHaste** [Novum/vkQuake#268]
Trying to run Arcane Dimensions 1.81, and when I click New Game, I get a crash that shows.

Quake Error
Could not allocate memory in 'Textures' heap

Increasing the memory heap all the way up to 2GBs does not help. (-heapsize 2048000)

**Comment by Novum** [comment]
The latest version of AD is 1.80 patch 1. Is that what you mean? What hardware driver and OS?

**Comment by AluminumHaste** [comment]
Yeah sorry, with patch 1.

Win 10 20H2 (build 19042.630)
Ryzen 3900X
AMD Radeon 5700XT Latest Drivers (Adrenalin 2020 Edition 20.12.1 Optional (WHQL))

Vulkan Instance Version: 1.2.154
Presentable Surfaces:
=====================
GPU id : 0 (AMD Radeon RX 5700 XT):
        Surface types: count = 1
                VK_KHR_win32_surface
        Formats: count = 25
                SurfaceFormat[0]:
                        format = FORMAT_B8G8R8A8_UNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[1]:
                        format = FORMAT_B8G8R8A8_SRGB
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[2]:
                        format = FORMAT_A2R10G10B10_UNORM_PACK32
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[3]:
                        format = FORMAT_R16G16B16A16_SFLOAT
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[4]:
                        format = FORMAT_B8G8R8A8_UNORM
                        colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
                SurfaceFormat[5]:
                        format = FORMAT_B8G8R8A8_SRGB
                        colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
                SurfaceFormat[6]:
                        format = FORMAT_A2R10G10B10_UNORM_PACK32
                        colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
                SurfaceFormat[7]:
                        format = FORMAT_R16G16B16A16_SFLOAT
                        colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
                SurfaceFormat[8]:
                        format = FORMAT_R16G16B16A16_SFLOAT
                        colorSpace = COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
                SurfaceFormat[9]:
                        format = FORMAT_R4G4B4A4_UNORM_PACK16
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[10]:
                        format = FORMAT_B4G4R4A4_UNORM_PACK16
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[11]:
                        format = FORMAT_R5G6B5_UNORM_PACK16
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[12]:
                        format = FORMAT_B5G6R5_UNORM_PACK16
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[13]:
                        format = FORMAT_A1R5G5B5_UNORM_PACK16
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[14]:
                        format = FORMAT_R8G8B8A8_UNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[15]:
                        format = FORMAT_R8G8B8A8_SNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[16]:
                        format = FORMAT_R8G8B8A8_SRGB
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[17]:
                        format = FORMAT_B8G8R8A8_SNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[18]:
                        format = FORMAT_A8B8G8R8_UNORM_PACK32
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[19]:
                        format = FORMAT_A8B8G8R8_SNORM_PACK32
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[20]:
                        format = FORMAT_A8B8G8R8_SRGB_PACK32
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[21]:
                        format = FORMAT_A2B10G10R10_UNORM_PACK32
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[22]:
                        format = FORMAT_R16G16B16A16_UNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[23]:
                        format = FORMAT_R16G16B16A16_SNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[24]:
                        format = FORMAT_B10G11R11_UFLOAT_PACK32
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
        Present Modes: count = 3
                PRESENT_MODE_IMMEDIATE_KHR
                PRESENT_MODE_FIFO_KHR
                PRESENT_MODE_FIFO_RELAXED_KHR
        VkSurfaceCapabilitiesKHR:
        -------------------------
                minImageCount       = 1
                maxImageCount       = 16
                currentExtent:
                        width  = 256
                        height = 256
                minImageExtent:
                        width  = 256
                        height = 256
                maxImageExtent:
                        width  = 256
                        height = 256
                maxImageArrayLayers = 1
                supportedTransforms:
                        SURFACE_TRANSFORM_IDENTITY_BIT_KHR
                currentTransform:
                        SURFACE_TRANSFORM_IDENTITY_BIT_KHR
                supportedCompositeAlpha:
                        COMPOSITE_ALPHA_OPAQUE_BIT_KHR
                supportedUsageFlags:
                        IMAGE_USAGE_TRANSFER_SRC_BIT
                        IMAGE_USAGE_TRANSFER_DST_BIT
                        IMAGE_USAGE_SAMPLED_BIT
                        IMAGE_USAGE_STORAGE_BIT
                        IMAGE_USAGE_COLOR_ATTACHMENT_BIT
                        IMAGE_USAGE_INPUT_ATTACHMENT_BIT
        VkSurfaceCapabilities2EXT:
        --------------------------
                supportedSurfaceCounters:
                        VK_SURFACE_COUNTER_VBLANK_EXT
        VkSurfaceCapabilitiesFullScreenExclusiveEXT:
        --------------------------------------------
                fullScreenExclusiveSupported = true

**Comment by AluminumHaste** [comment]
Hmmm, I put it back to 1.4 vkQuake, still having the same problem.
I'll try a clean Quake install and AD only I guess see if that helps.

**Comment by AluminumHaste** [comment]
Was in the wrong folder, I have multiple installations for testing mods, I was in the broken one.
It's working fine.
