### ISSUE TITLE
Fedora build fails witn error: ‘VK_API_VERSION_1_0’ undeclared

### ISSUE THREAD

**Issue by xyz32** [Novum/vkQuake#27]
I am trying to build the code on fedora 24.

I got all the dependencies set up:
#>sudo dnf copr enable ajax/vulkan
#>sudo dnf install SDL2-devel vulkan-devel

But now make fails with the following error:

gl_vidsdl.c: In function ‘GL_InitInstance’:
gl_vidsdl.c:546:32: error: ‘VK_API_VERSION_1_0’ undeclared (first use in this function)
application_info.apiVersion = VK_API_VERSION_1_0;

Any idea?

Thanks

**Comment by Novum** [comment]
You need a newer Vulkan SDK
