### ISSUE TITLE
Error when compiling. "VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT"

### ISSUE THREAD

**Issue by Arkl1te** [Novum/vkQuake#270]
Using Debian 10.7. 
Using Quake from Steam.

I installed the Ubuntu dependencies and compiled the [SDL2](https://www.libsdl.org/download-2.0.php) (v2.0.12).

I hope I'm not missing something else worth knowing.

```makefile
user@machine:~/.steam/debian-installation/steamapps/common/Quake/vkQuake/Quake$ make
cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/local/include/SDL2 -D_REENTRANT -o gl_vidsdl.o gl_vidsdl.c
gl_vidsdl.c: In function ‘GL_InitDevice’:
gl_vidsdl.c:745:11: warning: unused variable ‘found_debug_marker_extension’ [-Wunused-variable]
  qboolean found_debug_marker_extension = false;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
gl_vidsdl.c: In function ‘GL_AcquireNextSwapChainImage’:
gl_vidsdl.c:2084:89: error: ‘VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT’ undeclared (first use in this function)
  if ((err == VK_ERROR_OUT_OF_DATE_KHR) || (err == VK_ERROR_SURFACE_LOST_KHR) || (err == VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT))
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gl_vidsdl.c:2084:89: note: each undeclared identifier is reported only once for each function it appears in
gl_vidsdl.c: In function ‘GL_EndRendering’:
gl_vidsdl.c:2173:120: error: ‘VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT’ undeclared (first use in this function)
 OF_DATE_KHR) || (err == VK_ERROR_SURFACE_LOST_KHR) || (err == VK_SUBOPTIMAL_KHR) || (err == VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT))
                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

At top level:
gl_vidsdl.c:286:17: warning: ‘VID_GetVSync’ defined but not used [-Wunused-function]
 static qboolean VID_GetVSync (void)
                 ^~~~~~~~~~~~
make: *** [Makefile:200: gl_vidsdl.o] Error 1
```

**Comment by tcsabina** [comment]
Same issue here.
I am on Linux Mint 19.2

**Comment by tcsabina** [comment]
I figured something out:
The OS delivered vulkan-sdk is kind of outdated. There is a /usr/include/vulkan/vulkan_core.h, which does not contain a definition for VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT.

1) Download the latest VULKAN SDK (https://vulkan.lunarg.com/sdk/home#linux), and extract it to some directory. Let's say /home/myUser/workspace/vulkan-1.2.162.0/
2) use the following command to build:
make VULKAN_SDK=/home/myUser/workspace/vulkan-1.2.162.0/x86_64/

Hope this helps...

**Comment by Arkl1te** [comment]
Yep, that worked out for me!

Also vkquake seems to not find the Id1 subfolder, nor the PAK0.PAK and PAK1.PAK. 
I solved it by renaming the files to lowercase:
```bash
mv Id1/ id1/
cd id1
mv PAK0.PAK pak0.pak
mv PAK1.PAK pak1.pak
cd ..
./vkquake
```

**Comment by AnotherLife** [comment]
Linux shenanigans. That OS is case-sensitive when it comes to files/folders.

**Comment by Arkl1te** [comment]
Also i've been trying to launch the game without having to enter full path. I tried creating a symlink from `/usr/games/`
but asks for the id1 subdirectory (I said 'folder' previously, oops). I just want to open the game by typing "vkquake" from the i3 window manager (or terminal).

**Comment by Novum** [comment]
This has nothing to do with case sensitivity. 3111618108c53dc9f7e518341468f4a732698ad0
