### ISSUE TITLE
vkQuake doesn't prioritize external files over "paked" files

### ISSUE THREAD

**Issue by bstordeur** [Novum/vkQuake#271]
When adding new files to replaces files that are in a .pak, vkQuake will continue using the files in the pak instead of prioritizing the external files.

Noticed this while preparing Xmasjam 2020, which uses the Arcane Dimensions 1.8 pak files. We added conback.lmp and qplaque.lmp as external files, which made them show up fine in other engines (QS, QSS, FTE), but for vkQuake we had to also remove the original files from inside the AD pak to get them working.

**Comment by ericwa** [comment]
This is annoying, but it's the original Quake behaviour.

> which made them show up fine in other engines (QS, QSS, FTE)

QS has not changed this AFAIK, maybe double check these results because I expect it acts the same as vkQuake (and winquake): files in .pak override loose files.

**Comment by bstordeur** [comment]
Hmm, I double checked, I can confirm that QS ans vkQ do not behave the same, QS will prioritize the external files over the paked ones.

Here are some alternative lmps to stick in gfx to test if you want.
[lmps.zip](https://github.com/Novum/vkQuake/files/5720111/lmps.zip)

**Comment by ericwa** [comment]
Using the Quakespasm 0.93.2 32-bit Windows:
https://sourceforge.net/projects/quakespasm/files/Windows/quakespasm-0.93.2_windows.zip/download

![qs](https://user-images.githubusercontent.com/239161/102699529-b50fa000-4202-11eb-82d2-b681124ce500.PNG)

Using the latest stable QSS:
Git URL:      https://github.com/Shpoike/Quakespasm.git
Git Revision: 679d45bd9da2c9d7790d88a31936df3f019801cd
Compile Date: Sat Aug 29 19:54:20 UTC 2020

![qss](https://user-images.githubusercontent.com/239161/102699533-b93bbd80-4202-11eb-8c57-e6584ca188c7.PNG)

Spike mentioned changing the behaviour in QSS, it's not been touched in QS to my knowledge.

**Comment by neogeographica** [comment]
Yep that's correct.

**Comment by Novum** [comment]
I have not touched this code. It's identical to QS. Closing this. If you want this to change please ask QS to change it first.

**Comment by bstordeur** [comment]
Yeah sorry about that Novum, I got my versions mixed up and thought this was how QS (and even the original quake executables) always behaved (as it does makes a bit more sense in my opinion).
