### ISSUE TITLE
Config file keeps saving to my desktop?

### ISSUE THREAD

**Issue by Ryabetic** [Novum/vkQuake#272]
New to github, new to Quake sourceports, new to command line stuff so please excuse me...

Every time I close the game, the config file gets saved to my desktop, but when I try to delete it Windows tells me it doesn't exist. I'm sure there's an easy fix but I'm not that smart! Help :D

**Comment by Ryabetic** [comment]
It also places an empty vkquake folder on my desktop that I can't delete.

**Comment by AnotherLife** [comment]
Which folder did you extract vkQuake to? And how do you launch the game?

**Comment by Ryabetic** [comment]
C:\Program Files (x86)\vkQuake, I copied pak0 and pak1 from my Steam folder. So far I've just launched vkquake.exe from that folder

**Comment by micwoj92** [comment]
Maybe it does it because it can't change content inside vkQuake folder? If you created that folder manually it may have inherited rights from  Program Files. No idea what is the default on Windows. Check rights of that folder.
