### ISSUE TITLE
Dynamic lights reveal secret walls/doors (e.g. in e2m1)

### ISSUE THREAD

**Issue by maikmerten** [Novum/vkQuake#276]
When firing a weapon near secret walls (func_illusionary most likely), dynamic lights are rendered differently (or just delayed?) compared to normal world geometry. This can revel secrets.

This might be related to #263 (thanks for fixing!) - but this time it's not lightmap updates, but dynamic lights.

![dlight-secret](https://user-images.githubusercontent.com/2611432/103485327-d624e300-4df5-11eb-94a3-869c3d37299c.png)

In e2m1 there's a secret within a secret where one can fetch a pentagram of protection - there it's visible as well:

![pentsecret](https://user-images.githubusercontent.com/2611432/103485436-990d2080-4df6-11eb-8b82-2a23d3c9b2e3.png)

**Comment by Novum** [comment]
Dynamic lights update the lightmap in Quake. It's the same issue.

**Comment by maikmerten** [comment]
Yeah, dlights are applied to the lightmap. It's just that the fix for #263 does not fix the problems shown in the provided screenshots. I guess there's another source for a mismatch.

When comparing quakespasm and vkquake on firing the shotgun, the dynamic light on world geometry seems to appear later and shorter:

![qs-vk](https://user-images.githubusercontent.com/2611432/103528784-d5875d80-4e84-11eb-8b85-9681a7a014a1.gif)

Note how in quakespasm (left hand side), the dynamic light appears with the particle effect and stays for at least two frames, while in vkquake (right hand side, current git version) the dynamic light appears later and stays for a single frame.

On func_illusionary etc. I do not perceive such a delay.

**Comment by maikmerten** [comment]
Just confirming that as of now (2021-01-16), current git master still shows this problem. I cannot re-open this issue and don't want to spam the issue tracking system by creating a new issue, so I'm posting this here.

**Comment by Novum** [comment]
Which one?

**Comment by vsonnier** [comment]
Confirmed on on latest master 6366346a38b0345acd1fd02cc3e5a047d71f8990 :

If I revert the commit:
 -  c781043c4fa28b278a5566bd8c939915fd80ab00 Fix world dynamic light update lagging one frame behind brushes 
 
I get the expected behaviour of a proper longer illumination of a texture when shooting, and it looks exactly like QSS then.

**Comment by maikmerten** [comment]
> Which one?

The issue that flickering lightstyles reveal secret walls is fixed. But now lightmap updates by e.g. weapon fires (dynamic lights) on world geometry seem to be out of sync with lightmap updates on bmodels.

https://user-images.githubusercontent.com/2611432/104838151-5d279000-58b9-11eb-810e-0b9cac460439.mp4

**Comment by JuanchoES** [comment]
Yea lighting in vkquake 1.05.2 is broken, even worse with high frame rate.

**Comment by JuanchoES** [comment]
https://user-images.githubusercontent.com/70743149/107474494-b90cce00-6b72-11eb-89b4-1970ea3a93a2.mp4

Is this gonna get fixed soon?

**Comment by Novum** [comment]
You are in no position to make demands how I use my time.

**Comment by Novum** [comment]
Finally got time to look at this. Fixed in e2d6c49b2333ae77015a034931a0f6dcaa850280
