### ISSUE TITLE
Feature Request: Is it possible to add 8 bit software style rendering?

### ISSUE THREAD

**Issue by Quakman** [Novum/vkQuake#280]
Hi! I love the look of quake with a software rendering look. Other source ports have it (FTE, qbism Super8), but i prefer vkquake. It would be nice if a 8 bit software like style option would be added. And while we're at it, it would go well with a resolution scaling option (like markv winquake has), ie rendering@640x480, while keeping my native desktop resolution active.

**Comment by Novum** [comment]
duplicate #229

**Comment by onetruepurple** [comment]
It's not the same, though, this issue was about color depth.

**Comment by LethalManBoob** [comment]
> It's not the same, though, this issue was about color depth.

You could try messing around with some reshade shaders.
