### ISSUE TITLE
Default fog values messed up in Ruined Nation (dis_sp6)

### ISSUE THREAD

**Issue by Riccardoman** [Novum/vkQuake#284]
vkQuake 1.05.1 , QSS does not have this issue (the fog has another color and much less density)
![Screenshot (1322)](https://user-images.githubusercontent.com/74624503/106022224-e616a680-60c5-11eb-9cf0-69a99ff40cc8.jpg)

**Comment by Novum** [comment]
People will really hit all the corner cases. Fog color is completely out of range in this level. b87f98b4b4e99265e2262d4251aef554b5f0e599
