### ISSUE TITLE
separate deadzones

### ISSUE THREAD

**Issue by rampancy777** [Novum/vkQuake#286]
it would be great if we could have separate deadzones for each axis vs one shared by both sticks.  

also, would be cool if the movement stick had option of being treated as digital, meaning youre either walking or not (unless you press the run button). would be more like how the game plays with kb/m. as it is, crawling forward is unneeded and walking takes too much concentration.

thanks for the hard work, best port out there.

**Comment by Novum** [comment]
I would like to get this fixed in upstream (QuakeSpasm or QuakeSpasm Spiked) first.

**Comment by rampancy777** [comment]
thats fair, i get it. i was just throwing it out there in the event that you might be a lazy couch gamer ( aka controller user) like I am. 
thanks for your work man i get a lot of enjoyment out of it.
