### ISSUE TITLE
Limited model support

### ISSUE THREAD

**Issue by Riccardoman** [Novum/vkQuake#287]
Getting this error while loading r2m8 in Vkquake
![109369985-e067d880-789e-11eb-9809-01843f407a99](https://user-images.githubusercontent.com/74624503/109385128-cd322880-78f1-11eb-9543-85db892eeb9f.jpg)

**Comment by vsonnier** [comment]
I also have the same issue, while using the Authentic Model Pack for Quake ( https://github.com/NightFright2k19/quake_authmdl ) with the latest vkQuake `master`.

On the other hand, r2m8 works OK without quake_authmdl though so I assume we are indeed hitting some kind of model size limitation here.

**Comment by Novum** [comment]
I have the exactly same limits as QuakeSpasm and have not touched this code.
