### ISSUE TITLE
Real Time lighting

### ISSUE THREAD

**Issue by appetrosyan** [Novum/vkQuake#288]
I know that this is probably beyond the scope of the project (by a lot), but it'd be nice to see some of the features already present in Darkplaces be added to VKquake. 

Right now, this is the most promising source port, and it'd be really nice to have some of the killer apps of other source ports be added here retroactively.

**Comment by Novum** [comment]
No

**Comment by appetrosyan** [comment]
Thank you for a well-considered and detailed response.
