### ISSUE TITLE
Screen tearing on Nvidia hardware / SteamOS

### ISSUE THREAD

**Issue by ProfessorKaos64** [Novum/vkQuake#29]
Performance is of course great. I have screen tearing on Nvidia hardware / SteamOS. Running a GTX 1080 with driver release 367.27.

I noticed that even though many directories and files were renamed from quakespasm to vkquake. The dotfile (~/.quakespasm) is not renamed.

**Comment by bviktor** [comment]
Re:2nd part: there are several occurences of QuakeSpasm remnants, I've asked Axel if he wants a PR for some rebranding stuff.

**Comment by Novum** [comment]
NVIDIA driver issues. Nothing I can do. Renaming is fine.

**Comment by ProfessorKaos64** [comment]
Ok. No tearing ok Vulkan ports like Talos Principle or tearing on GL ports of quake.

**Comment by Kithop** [comment]
Slightly off-topic, but yes, this is an nVidia driver bug - I have VSync / tearing issues that I can *usually* work around with the following nvidia-settings script ( 'ForceFullCompositionPipeline = On' ):

$ cat /usr/local/bin/fix-screen.sh 
#!/bin/sh
/bin/sleep 3
# /usr/bin/xrandr --output HDMI-0 --right-of DVI-I-1
/usr/bin/nvidia-settings --assign CurrentMetaMode="DFP-0:1680x1050 +0+0 { ForceFullCompositionPipeline = On }, DFP-1:1920x1080 +1680+0 { ForceFullCompositionPipeline = On }"

(obviously changing the monitors around as per your setup) - calling this while most other games are running works and fixes the issue, but causes vkQuake to segfault and crash ('Couldn't create swap chain').  I've noticed that if I've run this _before_ starting vkQuake as well, it will crash attempting to set fullscreen the first time.  Relaunching then works for fullscreen, but it seems to have then reverted to the Composition pipeline being 'off' again as we're back to tearing.
