### ISSUE TITLE
Feature request: ignore alpha cvars if map not compiled for transparency

### ISSUE THREAD

**Issue by neogeographica** [Novum/vkQuake#291]
Transparent water (and slime etc.) has a long-standing annoying issue with getting it configured correctly on the player end.

Several modern engines support specifying this alpha value in the map itself. But for engines that don't support that, or maps that were not compiled with that info, the way to get transparent water is to set a cvar.

However if the map wasn't compiled to have transparent liquids (e.g. a lot of the old content), then having r_wateralpha set to some value below 1 will get you visual artifacts.

So with that situation, there's no fire-and-forget way to set yourself up so that you can get transparent water (slime, etc.) when it is present in the map but still have glitch-free visuals when it's not supported. (Using r_novis is not a great solution for various reasons.)

To help address this problem, some engines -- I'm aware of Quakespasm-Spiked, Fitzquake Mark V, and qbsim Super8 -- have added functionality so that they ignore alpha cvars if the map was not compiled for transparent liquids. This is quite nice from a user's perspective.

For reference:

Quakespasm-Spiked (https://github.com/Shpoike/Quakespasm) sets a contentstransparent flag in qmodel_t, and then references that.

Mark V sets a water_vis flag in level_info_t that it can reference. The original Mark V source is at http://quakeone.com/markv/ but there's also an essentially unmodified clone of that code at https://github.com/victorbstan/mark_vi

Not sure how Super8 does it!

**Comment by Novum** [comment]
Happy to take patches for this.

**Comment by Novum** [comment]
ba83200d85d6398dc1077c8e13d4bf33d1cc7eae

**Comment by neogeographica** [comment]
Fantastic. Thanks man. :-)
