### ISSUE TITLE
Refresh rate forced to 60Hz ignoring internal variable

### ISSUE THREAD

**Issue by mgtroyas** [Novum/vkQuake#293]
Windows 10, latest vkQuake release, ATI Radeon RX580 with latest drivers (20.12.1). As soon as I start on fullscreen it resets the refresh rate to 60Hz from the 75Hz I have configured on the desktop, and in vkQuake both via menu and console variable.

On borderless fullscreen is the oppsite: it stays at 75Hz that I have configured on desktop, independently of the configuration on the menu or console variable.

**Comment by Novum** [comment]
Driver issue. Talk to AMD.

**Comment by mgtroyas** [comment]
I've tried to replicate the problem again but I haven't been able to. I was having a similar issue with GZDoom (a Vulkan based Doom source port) and I'm unable to reproduce it either. Perhaps the video drivers were on a strange status and a reboot or similar fixed it. I'm closing the issue, thank you very much for your time.
