### ISSUE TITLE
gl_nearest alternative

### ISSUE THREAD

**Issue by buvk** [Novum/vkQuake#294]
I was wondering whether there is a command that will give vkQuake the appearance that gl_nearest gives in other source ports.  I am aware of vid_filter 1, but this looks more like gl_nearest_mipmap_linear.

**Comment by Novum** [comment]
I don't understand why you would want to turn off mip maps. That's worse than original software Quake.

**Comment by buvk** [comment]
I might be asking for the wrong thing.  I was hoping to achieve a look more similar to software Quake without any smoothing.

**Comment by Novum** [comment]
Okay, we have to disagree on this. I find no mip mapping unacceptable. Won't implement.
