### ISSUE TITLE
r_shadows doesn't work

### ISSUE THREAD

**Issue by NineKain** [Novum/vkQuake#296]
Yeah, just that, tried console, autoexec, config file, it jus't wont work, but it does on QSS

**Comment by LethalManBoob** [comment]
It was broken for a long time so he removed the cvar in new builds. 
it's not too bad anyway, the shadows don't help with anything and they're not realistic.
Id like them back but what can you do.

**Comment by NineKain** [comment]
Real shame, they look cool

**Comment by Novum** [comment]
By design
