### ISSUE TITLE
Linux: Add .config vkquake folder o vkquake folder in home after make install 

### ISSUE THREAD

**Issue by CamJRP** [Novum/vkQuake#297]
The vkquake binarie is successfully executed with the terminal after "make install".
The source port runs great, congratulations and thanks for your work.
However i can't see a vkquake folder in .config or in the home folder, nor .cfg file.
It would be great to have one.

**Comment by Novum** [comment]
Build script is taken from QuakeSpasm. You should ask them if they can make improvements.

**Comment by CamJRP** [comment]
I understand, thanks again.
