### ISSUE TITLE
r_lightmap not implemented

### ISSUE THREAD

**Issue by KillPixelGames** [Novum/vkQuake#298]
r_lightmap currently toggles nonsolids rather than textures

**Comment by Novum** [comment]
Not supported

**Comment by Novum** [comment]
Sorry about the spam, I was deliberating what to do with this, because I had this come up before.

**Comment by KillPixelGames** [comment]
> Sorry about the spam, I was deliberating what to do with this, because I had this come up before. Guess I can keep it on the enhancements list.

awesome, love the port btw

**Comment by Novum** [comment]
fixed 04615be2f54d2648e4ec65b463cb3f9a0ff0af87
