### ISSUE TITLE
Render window is all black on AMD GPUs (Ubuntu xenial, 16.30 drivers)

### ISSUE THREAD

**Issue by jfroy** [Novum/vkQuake#3]
According to the validation layers, there are a bunch of missing image transitions, including the swapchain images. 
[validation.txt](https://github.com/Novum/vkQuake/files/378865/validation.txt)

**Comment by Novum** [comment]
Define "doesn't run".
Also I doubt the validation layer errors are the issue. Those are harmless on PC. Will fix them later.

**Comment by Novum** [comment]
SC(WARN): object: 0x0 type: 0 location: 1775 msgCode: 2: FS writes to output location 0 with no matching attachment

This is more likely the problem. Need to investigate, but I'm not able to debug until August.

**Comment by jfroy** [comment]
I fixed most of the warnings having to do with missing barriers. Fairly trivial fixes in gl_texmgr.c. I'll cleanup and set a PR.

I looking at that last one from SC about missing the output attachment.

And by doesn't run, I meant the window is all black :p

**Comment by jfroy** [comment]
So the issue was that GL_CreateRenderPasses is called before GL_CreateRenderTargets, which means `vulkan_globals.swap_chain_format` is UNDEFINED at that point. It's going to be a bit more complex to fix that because GL_CreateRenderTargets can be called multiple times to reshape the output, but not too bad.

With the barrier fixes and the format fix, it seems to run fine.

**Comment by Novum** [comment]
Right. To be entirely correct need to re-create the render passes in this case (even though swap chain format should always be R8G8B8A8). Also make sure to call GL_WaitForDeviceIdle before that.

**Comment by Novum** [comment]
I would suggest just to check that the returned format is R8G8B8A8 and otherwise fail. Every driver supports that. Otherwise also need to recreate pipelines on swap chain change.

**Comment by fabry92** [comment]
how can i start this game on linux? i see only win and macos launcher

**Comment by mrcmunir** [comment]
@Fabry92 Makefile is in Quake/ and the launcher when is compiled you run by ./quakespasm (Not forget copy  folder quake files  )

**Comment by jfroy** [comment]
@fabry92 Please stay on topic for this issue.

**Comment by Hobby-boy** [comment]
I am also getting a black screen after compiling it on Windows with Visual Studio 2016. I can hear the sounds and interact though.

**Comment by Novum** [comment]
Please try again with latest code.

**Comment by jfroy** [comment]
Thanks Novum, will do soon. I haven't been able to get through my company's OSS release process yet, so I'm glad you just went ahead and did the fixes yourself :)

**Comment by Novum** [comment]
Closing this because I think it's fixed. Please let me know if it's not.
