### ISSUE TITLE
recent SIMD optimizations  may reveal map bugs?

### ISSUE THREAD

**Issue by j4reporting** [Novum/vkQuake#300]
on  e3m2 a texture gets stuck at the very beginning.  binary (64bit) compiled on win10  using  msys2. 
Disabling  SIMD  by commenting out  line      R_SIMD_f(&r_simd);   makes this bug disappear.

![2021-06-02 18_02_22-vkquake0006 png - IrfanView](https://user-images.githubusercontent.com/45177907/120514819-fb7e4300-c3cd-11eb-80a1-624c88741de8.png)

**update**:  cannot reproduce using a x86 binary!

**Comment by Novum** [comment]
How old is that compiler? I don't test GCC on Windows.

**Comment by j4reporting** [comment]
it's a very recent   gcc10 release

>  MINGW64 ~
> $ gcc --version
> gcc.exe (Rev2, Built by MSYS2 project) 10.3.0
> 

> $ pacman -Qs  gcc
> local/gcc-libs 10.2.0-1 (msys2-devel)
>     Runtime libraries shipped by GCC
> local/mingw-w64-i686-gcc 10.3.0-2 (mingw-w64-i686-toolchain)
>     GNU Compiler Collection (C,C++,OpenMP) for MinGW-w64
> local/mingw-w64-i686-gcc-libs 10.3.0-2 (mingw-w64-i686-toolchain)
>     GNU Compiler Collection (libraries) for MinGW-w64
> local/mingw-w64-x86_64-gcc 10.3.0-2 (mingw-w64-x86_64-toolchain)
>     GNU Compiler Collection (C,C++,OpenMP) for MinGW-w64
> local/mingw-w64-x86_64-gcc-libs 10.3.0-2 (mingw-w64-x86_64-toolchain)
>     GNU Compiler Collection (libraries) for MinGW-w64
> 

Today I tried using an older gcc-8.1 mingw64 compiler with  mozillabuild  and result is the same. The amd64/x86_64 binaries do have this bug. The i686 binaries seem to be ok. 

> 
> D:\src\quake\vkQuake\Quake>gcc --version
> gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
> Copyright (C) 2018 Free Software Foundation, Inc.

**Comment by andrei-drexler** [comment]
I was unable to reproduce this issue myself (with either MSVC, msys2/gcc 10.3 or mozzillabuild/mingw64/gcc 8.1, all 64-bit builds)... until I tried r_novis 1 on a hunch. #302 should fix it.

**Comment by j4reporting** [comment]
Yes  I have configured   r_novis  1.  The pull-up has fixed this,  thanks

**Comment by Novum** [comment]
c9d29e21143251a5ed0de2cbdcadbed58bdf32d5
