### ISSUE TITLE
default SDL hint  SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS  changed in SDL 2.0.14

### ISSUE THREAD

**Issue by j4reporting** [Novum/vkQuake#301]
please consider resetting SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS   to pre SDL 2.0.14  default

SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS   changed from 1  to 0  in SDL 2.0.14, and this has a negative impact on Windows  and perhaps some Linux desktop environments. It's no longer possible to switch back to desktop by alt+tab  or  left windows key,  etc. 

adding 
 ```
//  https://github.com/libsdl-org/SDL/issues/4039
SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "1"
```
before line   
`draw_context = SDL_CreateWindow (caption, SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, width, height, flags);  `
in gl_vidsdl.c  seems to work.  

<s>too bad that it's not possible to change SDL_HINTS  default settings with ENV variables on windows.</s>
set SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=1  seems to work

**Comment by Novum** [comment]
SDL2 docs state: "Before SDL 2.0.14, this defaulted to true! In 2.0.14, we're seeing if "true" causes more problems than it solves in modern times"

I'm reluctant to not believe them.

**Comment by j4reporting** [comment]
Flipping the HINT was definitely a very bad idea just because some Unix desktop environments put a minimized application at the end of the stack of running applications. So another ALT-TAB would not bring back the previous application. (Issue 3656 )

On Windows, this change now makes this feature completely unusable unless the user enforces the previous behavior by setting the appropriate environment variable. This was also acknowledged by the SDL developers  (issue  4039)

**Comment by Novum** [comment]
I tested a couple modern games and a lot of them have the same behavior (staying full screen on meta/win key).

**Comment by Novum** [comment]
I fixed the issue with losing focus with exclusive fullscreen bfac088a4b05d9c856233a407911d0add7b6657d
