### ISSUE TITLE
loading savegame assigns wrong bitmaps to  entities

### ISSUE THREAD

**Issue by j4reporting** [Novum/vkQuake#305]
tested with git  79eaab2   and 91379d9 
steps to reproduce:

1. skill 2;
2. map e3m1 
3. save game
4. load game from step 3

result:
engine draws an idbase gold key instead the enforcer enemy  etc. 
makes things interesting ;)

**Comment by Novum** [comment]
Yes, everything is hilariously busted right now, I'm aware.

**Comment by Novum** [comment]
308d2534889cd10dbaa8c0c03a497cddb952b42c
