### ISSUE TITLE
[Feature request] Nightly/dev builds like Quakespasm-spiked

### ISSUE THREAD

**Issue by JuanchoES** [Novum/vkQuake#306]
I would like to be able to download the latest vkquake builds without having to make them myself :)

**Comment by Novum** [comment]
I'm sorry, but I prefer people who don't know how to compile/debug the repository to use the official releases that have been tested.

**Comment by QUINTIX** [comment]
Do the official releases build from any sort of git-hook driven build automation?

I've found it's possible to wire up [github actions](https://docs.github.com/en/actions) so it builds something every commit. AFAIK github actions are free and unbounded for public repos. The [resulting build log alone](https://github.com/QUINTIX/blinky/runs/2754071495?check_suite_focus=true) might be useful as an automatic sanity check. Archiving and uploading binaries as a build artifact is not required and can be skipped.

Presently I have an automated build for my fork of a software-renderer only (for now) "fisheye" quake mod [configured to output binaries for every successfully compiled commit of a particular branch](https://github.com/QUINTIX/blinky/blob/qtx_meson/.github/workflows/builds-on-windows.yml), but I can see the wisdom in not doing that, so I may change mine when I figure out how to use git tags for that.

**Comment by JuanchoES** [comment]
> ~Do the official releases build from any sort of git-hook driven build automation?~
> 
> ~I've found it's possible to wire up [github actions](https://docs.github.com/en/actions) so it builds something every commit. AFAIK github actions are free and unbounded for public repos. The [resulting build log alone](https://github.com/QUINTIX/blinky/runs/2754071495?check_suite_focus=true) might be useful as an automatic sanity check. Archiving and uploading binaries as a build artifact is not required and can be skipped.~
> 
> ~Presently I have an automated build for my fork of a software-renderer only (for now) "fisheye" quake mod [configured to output binaries for every successfully compiled commit of a particular branch](https://github.com/QUINTIX/blinky/blob/qtx_meson/.github/workflows/builds-on-windows.yml), but I can see the wisdom in not doing that, so I may change mine when I figure out how to use git tags for that.~
> 
> Edit: I feel dumb. You already have a github action working https://github.com/Novum/vkQuake/actions

Wow! Before in that section you couldn't do anything but now it seems that novum has made it work! Great!

**Comment by JuanchoES** [comment]
> ~Do the official releases build from any sort of git-hook driven build automation?~
> 
> ~I've found it's possible to wire up [github actions](https://docs.github.com/en/actions) so it builds something every commit. AFAIK github actions are free and unbounded for public repos. The [resulting build log alone](https://github.com/QUINTIX/blinky/runs/2754071495?check_suite_focus=true) might be useful as an automatic sanity check. Archiving and uploading binaries as a build artifact is not required and can be skipped.~
> 
> ~Presently I have an automated build for my fork of a software-renderer only (for now) "fisheye" quake mod [configured to output binaries for every successfully compiled commit of a particular branch](https://github.com/QUINTIX/blinky/blob/qtx_meson/.github/workflows/builds-on-windows.yml), but I can see the wisdom in not doing that, so I may change mine when I figure out how to use git tags for that.~
> 
> Edit: I feel dumb. You already have a github action working https://github.com/Novum/vkQuake/actions

But it does not have any windows 32/64 bit downloads so i cant do anything
