### ISSUE TITLE
Missing intermission stats screen in Arcane Dimensions

### ISSUE THREAD

**Issue by andrei-drexler** [Novum/vkQuake#310]
After finishing a map in Arcane Dimensions (v1.80 patch 1), time/kills/secrets stats aren't drawn during intermission with the default `cl_nocsqc 0`:
<img src="https://user-images.githubusercontent.com/5121829/122813139-44ddf600-d2db-11eb-9ac9-35d4fc2703ae.jpg" width="480"/>

With `cl_nocsqc 1` the screen is drawn as expected:
<img src="https://user-images.githubusercontent.com/5121829/122813285-73f46780-d2db-11eb-9245-384bc3d9f070.jpg" width="480"/>

AD's custom HUDs do work, though, and in mods that don't have CSQC the intermission screen is drawn properly regardless of the value of `cl_nocsqc`.

I've also checked QSS+AD for reference, and there the screen is drawn with both `cl_nocsqc 0/1`.

Placing a breakpoint in `Sbar_IntermissionOverlay`, it seems that `CSQC_DrawScores` is present and called with the right arguments, but that's about as far as I got. If it helps, the source code for AD's scripts is on GitHub: [CSQC_DrawScores](https://github.com/SimsOCallaghan/ArcaneDimensions/blob/320f1cec4545563e70027450f2d6d4f08f527c69/csqc_hudad.qc#L2341), [Hud_DrawIntermission](https://github.com/SimsOCallaghan/ArcaneDimensions/blob/320f1cec4545563e70027450f2d6d4f08f527c69/csqc_hudad.qc#L2044).

**Comment by Novum** [comment]
ba15900dd5e2bcaeb1befc481bd8acf80d406000
