### ISSUE TITLE
broken hud drawing in ad

### ISSUE THREAD

**Issue by sezero** [Novum/vkQuake#312]
![0001](https://user-images.githubusercontent.com/4222725/123524997-92d96c00-d6d6-11eb-84a8-578c0c2d5bf3.png)

**Comment by Novum** [comment]
What's broken about it?

**Comment by andrei-drexler** [comment]
I think this is one of the rare cases where "it's not a bug, it's a [feature](https://www.moddb.com/mods/arcane-dimensions/features/custom-user-interface)" (custom HUD using client-side QC) is actually true. It looks the same in QSS. You can switch to a different layout by changing the `scratch1` cvar, or disable CSQC (and custom HUDs) entirely with `cl_nocsqc 1`.

**Comment by Novum** [comment]
I want to hear what @sezero means, but I also suspect that he thinks the custom HUD is "broken".

**Comment by sezero** [comment]
Well, I was used to the 'conventional' hud, but since you guys say it's intentional, it's OK. Closing.

**Comment by Novum** [comment]
You can press H to cycle through HUD variants in AD 1.8

**Comment by sezero** [comment]
OK, thanks.

**Comment by Novum** [comment]
But it might really confuse users, I also thought about it. Sadly there is no good way to add an option to the menu because it would require a map restart
