### ISSUE TITLE
Vkquake is not showing the weapons in my HUD

### ISSUE THREAD

**Issue by JuanchoES** [Novum/vkQuake#313]
Latest release
As you can see, i write impulse 9 to unlock all weapons and they are not showing no matter what
![Sin título](https://user-images.githubusercontent.com/70743149/123530779-8701a000-d6fe-11eb-98e6-31e3161a7b0f.png)

It does work with arcane dimensions various HUDs 
![image](https://user-images.githubusercontent.com/70743149/123530751-49047c00-d6fe-11eb-8ae4-f6377acae2bc.png)

**Comment by LethalManBoob** [comment]
Can confirm this happens on my end as well.

**Comment by Novum** [comment]
Bisected this and first bad commit is d9d4be488436c50afcc75b2aacdb50127f6546ab

**Comment by Novum** [comment]
f26bc6e49f90221fac23eb8dfb5c6c25db5e555f
