### ISSUE TITLE
Some AD saves from QSS fail to load

### ISSUE THREAD

**Issue by bubbleguuum** [Novum/vkQuake#314]
I'm using the latest beta1.

I have many Arcane Dimensions 1.80 saves made with recent QuakeSpasm-Spiked .
These are saves for many completed levels.

Most load just fine in vkQuake, except 2 saves:  one in Grendel's Blade and the other in "tears of the the false god" failing with:

```
Grendels' Blade
Using protocol fte999
 ABI set not supported
CALL1      2157(particleeffectnum)particleeffectnum()
part_generate.qc : emitdpp_particle
<NO FUNCTION>
unimplemented builtin #335 - particleeffectnum
Host_Error: Program error
```

I'm reporting it for reference, in case it can be easily fixed.

**Comment by Novum** [comment]
Bot supported. vkQuake doesn't implement the full set of QSS extensions.
