### ISSUE TITLE
Resolution scaling does not work on Intel UHD 630 on Linux

### ISSUE THREAD

**Issue by bubbleguuum** [Novum/vkQuake#315]
Using beta1, manually compiled by myself on Linux, on openSUSE Tumbleweed.

vkQuake works fine on the Intel UHD 630 on my laptop (Using latest Mesa version: 21.1.3).
But resolution scaling does not: it is not applied, and results in the screen being corrupted (no crash).
Resolution scaling works fine if I switch graphics to the NVIDIA Quadro P600 of my laptop. 

Here's the console details:

```
Vulkan Initialization
Using Vulkan 1.1
Using VK_KHR_get_surface_capabilities2

Using VK_KHR_get_physical_device_prope
rties2
Using subgroup operations
Vendor: Intel
Device: Intel(R) UHD Graphics 630 (CFL
 GT2)
Using VK_KHR_dedicated_allocation
Using A2B10G10R10 color buffer format
Using D24_S8 depth buffer format
```

Probably a driver bug, but mentioning it for reference.

**Comment by Novum** [comment]
It's very likely an app issue. It's notoriously hard to make sure subgroup stuff works correctly everywhere.

**Comment by bubbleguuum** [comment]
Understood! If you think of a possible fix in the future, I can test it.

**Comment by vsonnier** [comment]
Works for me with both GPUs on Windows x64 with latest Intel drivers 27.20.100.9466. Machine is HD 630 + GTX 1050Ti.

Here is the console output with HD 630 :

```
Vulkan Initialization
Using Vulkan 1.1
Using VK_KHR_get_surface_capabilities2
Using VK_KHR_get_physical_device_properties2
Using subgroup operations
Vendor: Intel
Device: Intel(R) HD Graphics 630
Using VK_KHR_dedicated_allocation
Using VK_EXT_full_screen_exclusive
Using A2B10G10R10 color buffer format
Using D24_S8 depth buffer format
Creating command buffers
Initializing staging
Creating descriptor set layouts
Reallocating dynamic VBs (256 KB)
Reallocating dynamic IBs (1024 KB)
Reallocating dynamic UBs (256 KB)
Initializing samplers
Creating pipeline layouts
Using IMMEDIATE present mode
Creating color buffer
AA disabled
Creating depth buffer
Creating render passes
Creating frame buffers
Creating pipelines

Sound Initialization
SDL audio spec  : 44100 Hz, 1024 samples, 2 channels
SDL audio driver: wasapi - HP ENVY 32 (Son Intel(R) pour écrans), 65536 bytes buffer
Audio: 16 bit, stereo, 44100 Hz
CDAudio disabled at compile time

========= Quake Initialized =========

execing quake.rc
execing default.cfg
execing config.cfg
Disabling renderer/network isolation.
execing autoexec.cfg
3 demo(s) in loop

vkQuake 1.10.0-beta1 Server (13092 CRC)



Introduction
Using protocol fte999
player entered the game
...
```

Tested with both `master` and beta1.

**Comment by Novum** [comment]
@bubbleguuum Can you try 080c369225f9d84c3e6a4c378d9fd8ba426f14b1?

**Comment by bubbleguuum** [comment]
No change. Here's how it it looks after switching to 1/8 resolution: 

https://imgur.com/a/njRXxS8

And after displaying/hiding the console once:

https://imgur.com/a/eeKmCfW

Interestingly, on Windows 10 the resolution scale works, but framerate is constant 30fps (instead of 60 without resolution scaling). NVIDIA again does not have this issue there.

**Comment by Novum** [comment]
Then I strongly suspect a driver bug. This should work now.

**Comment by bubbleguuum** [comment]
Confirming `r_usesops 0` fixes it although the framerate (with scaling) tanks (35 vs 60 on the start map).

Yup, Windows drivers is different and performance tanks as well with scaling enabled.

Without scaling, the UHD 630 has rather OK performance at 4K on this laptop, so good work !

**Comment by Novum** [comment]
Seems like the UHD has incredibly bad shared memory atomics performance.

**Comment by Novum** [comment]
@bubbleguuum Could you file a bug at https://gitlab.freedesktop.org/mesa/mesa/-/issues for this? I still believe this is likely a driver issue. I can provide more information there for the driver devs, but I don't have the necessary information about your system to create the bug.

**Comment by bubbleguuum** [comment]
Sure! I will report it and post the link to the issue here.

As far as performance goes at 4K, it is excellent, with probably the whole base game being able to sustain stable 60fps, and AD dipping in the 50-45's for some maps (which is understandable given the complexity of the maps). So excellent performance on this iGPU present in many laptops, some of them not having the luxury to also have a dGPU.

**Comment by bubbleguuum** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5000

**Comment by Novum** [comment]
@bubbleguuum Could you try eeb203fba58d70d894da7885b96753ca4a78dc9a and also paste the log output in case it works?

**Comment by bubbleguuum** [comment]
Confirming it's working. There's a performance hit but I suppose it is expected for this feature (also happens on NVIDIA).

```
Vulkan Initialization
Using Vulkan 1.1
Using VK_KHR_surface
Using VK_KHR_xlib_surface
Using VK_KHR_get_surface_capabilities2
Using VK_KHR_get_physical_device_properties2
Vendor: Intel
Device: Intel(R) UHD Graphics 630 (CFL GT2)
Using subgroup operations
Using VK_KHR_swapchain
Using VK_KHR_get_memory_requirements2
Using VK_KHR_dedicated_allocation
Using VK_EXT_subgroup_size_control
Using A2B10G10R10 color buffer format
Using D24_S8 depth buffer format
Creating command buffers
Initializing staging
Creating descriptor set layouts
Reallocating dynamic VBs (256 KB)
Reallocating dynamic IBs (1024 KB)
Reallocating dynamic UBs (256 KB)
Initializing samplers
Creating pipeline layouts
Using IMMEDIATE present mode
Creating color buffer
AA disabled
Creating depth buffer
Creating render passes
Creating frame buffers
Creating pipelines
```

**Comment by Novum** [comment]
Ok, thanks eeb203fba58d70d894da7885b96753ca4a78dc9a

**Comment by Novum** [comment]
You probably want to close the MESA bug too.
