### ISSUE TITLE
Broken huds in the majority of map packs

### ISSUE THREAD

**Issue by El-Juancho** [Novum/vkQuake#316]
**RAVENKEEP**
![image](https://user-images.githubusercontent.com/70743149/123552815-3b8bd800-d778-11eb-93f2-792a0274b929.png)
**XMEN**
![image](https://user-images.githubusercontent.com/70743149/123552832-565e4c80-d778-11eb-899e-36c598993e48.png)
**Q25LIMIT**
![image](https://user-images.githubusercontent.com/70743149/123552852-7d1c8300-d778-11eb-9ac4-4744d7e96087.png)
**DWELL**
![image](https://user-images.githubusercontent.com/70743149/123552875-98878e00-d778-11eb-808c-9716d5c6df36.png)

The end screen is broken too
![image](https://user-images.githubusercontent.com/70743149/123552960-0df35e80-d779-11eb-8b57-9af6ae350362.png)

**Comment by Novum** [comment]
Duplicate  #313

**Comment by JuanchoES** [comment]
> Duplicate #313

I did not know that is the same bug, sorry

**Comment by Novum** [comment]
I cannot reproduce this on either AMD nor NVIDIA drivers on Windows. What configuration is this?

**Comment by JuanchoES** [comment]
Oops, i tested the new cvar "cl_nocsqc 1" in arcane dimensions, it does work but breaks the hud when playing other map packs, my problem is fixed when i write "cl_nocsqc 0" in the console

**Comment by Novum** [comment]
Okay, that's still kind of a bug then. Reopening

**Comment by JuanchoES** [comment]
I hope this helps

https://drive.google.com/file/d/1KxhVGaLQ63xfN3Uuj32b4y1BE7r_uqJR/view?usp=sharing

**Comment by JuanchoES** [comment]
When using these launch parameters my hud is still broken, this is really weird

![image](https://user-images.githubusercontent.com/70743149/123560798-cedb0280-d7a4-11eb-9569-0680439b86a8.png)
![image](https://user-images.githubusercontent.com/70743149/123560801-d7cbd400-d7a4-11eb-983c-b934c94bee5b.png)

**Comment by Novum** [comment]
First bad commit is 4993ee35de5f139e3b44b1db3edbdb5d3be20c6d

**Comment by Novum** [comment]
42522db3b255bcc921b3d8b55a858bd3a3687b3d

**Comment by andrei-drexler** [comment]
It looks like this one isn't quite dead yet - starting vkQuake with `-game ad` and typing in the console
> map start
> game id1
> map start
> game ad
> map start

still breaks the HUD:
![vkquake0034](https://user-images.githubusercontent.com/5121829/124995829-a2e73900-e050-11eb-882c-af24dc8bd9e3.jpg)

Doesn't happen with ravenkeep or alkaline, and setting `cl_nocsqc 1` seems to fix it.
Couldn't reproduce it in QSS.
