### ISSUE TITLE
Wrong liquid texture coordinates

### ISSUE THREAD

**Issue by c-d-a** [Novum/vkQuake#319]
vkQuake's warptextures are flipped vertically compared to Quakespasm.
But Quakespasm's own coordinates inherit the incorrect behavior from GLQuake (shifted by 1/2 on both axes, as compared to DOS Quake & WinQuake).

WinQuake:
![winq](https://user-images.githubusercontent.com/55441216/123977423-6aa08480-d9d8-11eb-99a8-f72e0655408f.png)
GLQuake:
![glq](https://user-images.githubusercontent.com/55441216/123977451-6d9b7500-d9d8-11eb-928a-8350dcad7108.png)
Quakespasm:
![qs](https://user-images.githubusercontent.com/55441216/123977459-6ffdcf00-d9d8-11eb-9283-479853e32ea5.png)
vkQuake:
![vk](https://user-images.githubusercontent.com/55441216/123977470-71c79280-d9d8-11eb-8f00-fa54afee3a23.png)

[Test map](https://github.com/Novum/vkQuake/files/6741622/warp_co.zip).

**Comment by LethalManBoob** [comment]
This is very interesting. I hope this was sent to quakespasm as well

**Comment by Novum** [comment]
Is there actually a practical map where this is visible?

**Comment by c-d-a** [comment]
Well, I discovered this while trying to do a Doom-style wall of faces.
But I can't name any existing maps using discernible patterns as liquids, no.

**Comment by Novum** [comment]
I'm usually trying to match QuakeSpasm

**Comment by c-d-a** [comment]
Well, following QS would at least make the direction consistent, better than nothing.

Anyway, I have fiddled with this some more. The issue goes deeper than a simple half-shift. WinQuake can project the texture more or less seamlessly across faces with roughly the same direction. Meanwhile, GLQ/QS seem to come up with a different set of disjointed coordinates for each face. But TyrGLQuake, for example, seems to have this solved.
So this affects anyone who had ever tried making a fancy exit portal, or a circular force field, or a glass tube with water, or a floating lava ball.

https://user-images.githubusercontent.com/55441216/124144737-a9e8d700-daa5-11eb-86ec-5aa1bcdd8791.mp4

https://user-images.githubusercontent.com/55441216/124144785-b40ad580-daa5-11eb-8b0b-beab4e947c82.mp4

https://user-images.githubusercontent.com/55441216/124144813-ba00b680-daa5-11eb-8876-2a2e3ffc0d52.mp4

[Test map.](https://github.com/Novum/vkQuake/files/6749055/warp_co2.zip)

**Comment by Novum** [comment]
The only problem I see is that most mods will be made with QuakeSpasm as the standard these days and might expect its behavior. So even if this is fixable to be like WinQuake, I probably will match QS instead. Thanks for the test map btw.

**Comment by c-d-a** [comment]
I can hazard a guess, since my previous tickets from a couple years ago are still sitting there, untouched.
Still, I'll file the reports. I do understand your rationale behind not diverging too much.

**Comment by Novum** [comment]
40435e3da87085cac93a59aa822fb882a74b250e matches QuakeSpasm now.
