### ISSUE TITLE
Half-pixel UV offset on .MDLs

### ISSUE THREAD

**Issue by c-d-a** [Novum/vkQuake#320]
Another casualty of GLQuake transition, the texture coordinates on "alias models" are interpreted differently (middle of the pixel vs its corner) compared to DOS Quake / WinQuake

DOS Quake:
![dosq](https://user-images.githubusercontent.com/55441216/123978163-14801100-d9d9-11eb-9a43-ecce1ced867f.png)
vkQuake:
![vkq](https://user-images.githubusercontent.com/55441216/123978214-1f3aa600-d9d9-11eb-9a80-5924083a57c2.png)

In the example, the E1M1 elevator grunt gets two extra half-pixels on both sides of the seam.

I'll also take this opportunity to again nag about the ability to toggle model overbright on/off. Original grunt blends in, overbright guard stands out slightly.

**Comment by Novum** [comment]
So you are saying GLQuake is correct or incorrect?

**Comment by c-d-a** [comment]
Incorrect starting from and including GLQuake

**Comment by Novum** [comment]
WNF
