### ISSUE TITLE
Feature request:  use replacement textures for guns and items

### ISSUE THREAD

**Issue by pppbb** [Novum/vkQuake#321]
I use textures from Quake Retexturing project.

**Comment by Novum** [comment]
Does QuakeSpasm?

**Comment by micwoj92** [comment]
Duplicate https://github.com/Novum/vkQuake/issues/271 ?

**Comment by pppbb** [comment]
> 
> 
> Does QuakeSpasm?

No aparrently it doesnt.

**Comment by Novum** [comment]
Then WNF
