### ISSUE TITLE
vkQuake not compiling.

### ISSUE THREAD

**Issue by WhyIsntTouhouBuntuRealYet** [Novum/vkQuake#322]
I'm running this on a Raspberry PI 4, and I get this message.

sudo make install
cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/local/include/SDL2 -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -D_REENTRANT -o gl_rmisc.o gl_rmisc.c
gl_rmisc.c: In function \u2018R_CreatePipelines\u2019:
gl_rmisc.c:2212:32: error: \u2018VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT\u2019 undeclared (first use in this function); did you mean \u2018VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT\u2019?
   compute_shader_stage.flags = VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT | VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT;
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT
gl_rmisc.c:2212:32: note: each undeclared identifier is reported only once for each function it appears in
gl_rmisc.c:2212:102: error: \u2018VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT\u2019 undeclared (first use in this function); did you mean \u2018VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT\u2019?
 _PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT | VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT;
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT
make: *** [Makefile:198: gl_rmisc.o] Error 1

Is there a way to properly compile this?

**Comment by QUINTIX** [comment]
I smell an incoming WNF. 

What is the latest version of LunarG’s SDK available on the Pi4? Does my little compute shader example compile? https://github.com/QUINTIX/vkCompute

I’ll try to find out for myself when I am home.

**Comment by Novum** [comment]
Your Vulkan SDK is too old

**Comment by Novum** [comment]
I added #ifdef guards so it compiles if the SDK doesn't have this extension. That's not usually something I do, but in this case I'll make an exception. a00c932bd1f9499a7c7619e6bafa64e3f7697a26
