### ISSUE TITLE
Problem loading ambient sounds in the latest betas?

### ISSUE THREAD

**Issue by ZecChelovek** [Novum/vkQuake#323]
Both beta1 and beta2 do not play ambient noises, the console seemingly showing nothing regarding this. 1.05.3 does not have this issue. Small test map: 
https://www.mediafire.com/file/w78b21rmt67eh0i/soundtest.bsp/file

**Comment by Novum** [comment]
f48b492409b8415333a6a6677ffcd944564d87aa
