### ISSUE TITLE
Vkquake crashing when playing the famous rally mod and x-men mod

### ISSUE THREAD

**Issue by JuanchoES** [Novum/vkQuake#325]
Im using **1.10.0-beta2**

When you try to play the mod vkquake crashes, this happens with the x-men mod too.

Rally mod: https://www.moddb.com/mods/quake-rally/downloads/quake-rally

xmen mod: https://www.zerogravity.com.au/xmen/

Rally crash
![image](https://user-images.githubusercontent.com/70743149/124609435-e6cf1800-de6f-11eb-8cc3-f8a356db8cbf.png)
X-men crash
![image](https://user-images.githubusercontent.com/70743149/124609796-3f061a00-de70-11eb-9955-89711e92252d.png)

**Comment by Novum** [comment]
Do they work in QuakeSpasm?

**Comment by JuanchoES** [comment]
> Do they work with QuakeSpasm?

Yup

**Comment by andrei-drexler** [comment]
They work in both QS and QSS. It looks like the check in `Draw_PicFromWad2` generating these errors was added in QSS after `W_LoadWadFile` was changed to sanitize the lump info, so I've replaced `W_LoadWadFile` with the QSS version.
