### ISSUE TITLE
Intro demos do not start automatically/ -fitz causes issues with some shadows.

### ISSUE THREAD

**Issue by FreshRoyal** [Novum/vkQuake#327]
I know that the intro demos problem is an issue in Quakespasm, too, but I would like to have the intro demos start automatically and continue into each other at startup. I know the -fitz commandline parameter fixes it, but it causes issues with certain shadows, namely one near the quad-damage in E1M1.

**Comment by Novum** [comment]
Not the scope of this project to change QuakeSpasm behavior.
