### ISSUE TITLE
Slayer's Testaments doesn't run with 1.10

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#328]
Complains about QuakeC stuff related to particles. 1.05 runs but also sometimes crashes in QuakeC.

I wouldn't be surprised if it's not correctly querying for available QuakeC extensions though, the author only seems to test against QSS.

**Comment by Novum** [comment]
Not clear if this is actually a bug on vkQuake side, so marking this enhancement for now

**Comment by NineKain** [comment]
Can confirm, it still doesn't work

**Comment by Novum** [comment]
It actually runs now, there are issues like missing crosshairs (probably needs CSQC UI support).
