### ISSUE TITLE
Differences in sound, and distant dithering in Ter_Shibboleth_Drake when compared to FTEQW

### ISSUE THREAD

**Issue by ZecChelovek** [Novum/vkQuake#332]
Dithering, first screenshot is vkQuake:
https://imgur.com/a/04LFd4A

I don't have time to record the sound right now, but when shib1_drake is fired up in the latest vkQuake, the ambient noise seems to be running twice over itself. This issue isn't present in FTEQW.

**Comment by Novum** [comment]
Please check against QuakeSpasm/QSS, not FTEQW.

**Comment by ZecChelovek** [comment]
Top is QS, bottom is QSS. No distant dithering.
https://imgur.com/a/VzQvmEu

Still no time to record sound, but the double sound is present in QS and QSS. I suppose it's something to do with the map itself.

**Comment by Novum** [comment]
Where can I download this map?

**Comment by Novum** [comment]
Okay got it to run. This is because the skybox geo and the map geo are coplanar and there is z-fighting.

Won't fix. This would only be fixable by reverting a pretty substantial optimization for skybox rendering on the GPU. Not worth it for one map.

**Comment by andrei-drexler** [comment]
@Novum any thoughts on switching to a reversed-z projection matrix? I gave it a quick try and it seemed to eliminate the distant z-fighting on that map even with the default D24_S8 buffer. We could even switch to an infinite far plane and get rid of `gl_farclip` altogether (TerShibboleth's quake.rc sets it to 512K!), and if we made D32F_S8 the preferred format we probably wouldn't have to worry about this ever again <sup>1</sup>

<sup>1</sup> famous last words

**Comment by Novum** [comment]
As far as I know reverse depth shouldn't really help if not using a float z buffer?

**Comment by andrei-drexler** [comment]
I haven't done any rigorous precision tests myself, but according to [this blog post](https://dev.theomader.com/depth-precision/#:~:text=Reverse%20depth%20seems%20to%20perform%20slightly%20better%20than%20standard%20depth%2C%20especially%20towards%20the%20far%20plane.)
> with integer buffers [...] reverse depth seems to perform slightly better than standard depth, especially towards the far plane

and in this case *slightly better* is apparently enough to eliminate the problem.
