### ISSUE TITLE
[Feature request] PNG support

### ISSUE THREAD

**Issue by NightFright2k19** [Novum/vkQuake#333]
It would be nice if vkQuake also supported PNG images like QSS since this file format saves far more disk space compared to TGA.

**Comment by LethalManBoob** [comment]
WebP Is much better to support than png.

**Comment by NightFright2k19** [comment]
Possibly. But is anybody using that already?

**Comment by LethalManBoob** [comment]
an adult game called collage bound does.

**Comment by micwoj92** [comment]
Ah yes, some random game, totally relevant for quake engine.

**Comment by LethalManBoob** [comment]
It is relvent for the question NightFright posed me, keep up.

**Comment by Novum** [comment]
I don't want to support things that would encourage mods that are not compatible with vanilla QuakeSpasm.
