### ISSUE TITLE
overbrights / fullbrights broken

### ISSUE THREAD

**Issue by shoober420** [Novum/vkQuake#335]
From latest git commit as of this post (https://github.com/Novum/vkQuake/commit/509f75f3babefd0a8f14cf7ae32cb22947661e0d), the overbrights and fullbrights are not working. Pictures and system information provided.

https://github.com/shoober420/rootscripts/blob/main/home/shoober420/sysinfoamd

![20210802_19h36m41s_grim](https://user-images.githubusercontent.com/5150898/127964007-10f0c773-a3b9-4059-8580-05db0e737b56.png)

![20210802_19h37m15s_grim](https://user-images.githubusercontent.com/5150898/127964022-724fb41f-c3b2-4cb2-bc05-43fe696845a5.png)

![20210802_19h38m03s_grim](https://user-images.githubusercontent.com/5150898/127964099-98a5f0c4-df48-48f0-b71a-5b61971f7d22.png)

**Comment by Novum** [comment]
That commit has nothing to do with the actual code or shaders. Something else must be wrong on your side.

**Comment by shoober420** [comment]
My system information I posted states I use Gentoo Linux, but besides that, I'm compiling with GCC 11.2.

**Comment by shoober420** [comment]
Just compiled vkquake from https://github.com/Novum/vkQuake/commit/579a7eca58e6c9855d599acad4410455e1c85193 with default build flags, and started with a fresh config. My overbrights / fullbrights are still borked.

**Comment by eGax** [comment]
Maybe a mesa/driver issue? I just built vkquake from the same commit:
```
git clone --recursive https://github.com/Novum/vkQuake.git
cd vkQuake/Quake
make
```
I'm running a Radeon RX 5600XT with the amdgpu driver on Manjaro Linux and it seems fine on my end.
![image](https://user-images.githubusercontent.com/9817245/128409551-c0049bcb-2e1c-4630-a38a-11095f3f2917.png)
My specs for reference:
```System:    Host: retro-den Kernel: 5.11.22-2-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.22.4 Distro: Manjaro Linux 

CPU:       Info: 12-Core AMD Ryzen 9 3900X [MT MCP] speed: 4000 MHz min/max: 2200/4000 MHz 

Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] driver: amdgpu v: kernel 
           Display: x11 server: X.Org 1.20.12 driver: loaded: amdgpu,ati unloaded: modesetting,radeon resolution: 1: 2560x1440 
           2: 1920x1080~60Hz 3: 1920x1080~60Hz 
           OpenGL: renderer: AMD Radeon RX 5600 XT (NAVI10 DRM 3.40.0 5.11.22-2-MANJARO LLVM 12.0.1) v: 4.6 Mesa 21.1.5

gcc --version (GCC) 11.1.0```

**Comment by shoober420** [comment]
@eGax

I do use Mesa+LLVM git master, that's a possibility. Could you please test with GCC 11.2 instead of GCC 11.1 and see if it still works?

**Comment by bubbleguuum** [comment]
No bug here on Intel UHD 630 and NVIDIA Quadro P600.
GCC 11.1.1 and Mesa 21.1.6.

**Comment by shoober420** [comment]
As of this commit (https://github.com/Novum/vkQuake/commit/1749dedb548cb49cab936f206eacfd53488c7dc0), overbrights and fullbrights and fixed! Thank you guys so much.
