### ISSUE TITLE
Mod Causes Crash To Desktop

### ISSUE THREAD

**Issue by Hansukie** [Novum/vkQuake#338]
Using 1.10.0-beta3 x64 on Windows 10.

Using the Katria Mod found here:

https://mega.nz/folder/lIpzACxK#1r4vDhi0wwyKWhTqJn8xOQ

Causes a crash to desktop, the mod works fine in Quakespasm Spiked.

**Comment by vide0hanz** [comment]
@Hansukie - Curious, what is the Katria mod? Is it a new playermodel? I can't find a whole lot of information about this.

**Comment by Novum** [comment]
Can't repro anymore with latest code.

**Comment by Hansukie** [comment]
> @Hansukie - Curious, what is the Katria mod? Is it a new playermodel? I can't find a whole lot of information about this.

Just a player voice and graphic mod.
