### ISSUE TITLE
In coop, players already on the server when client joins appear as all-white

### ISSUE THREAD

**Issue by Blorgx3** [Novum/vkQuake#342]
https://github.com/Shpoike/Quakespasm/issues/43 This QSS bug seems to apply to vkquake (1.10.0-beta3 win64) also, but in a  different way.  In a listen server started in-game, every player who was already on the server when the client joins shows as all-white, but other players who join after the client have correct colors.  I messed around on a dedicated server and this continued to be true, but also if the all-white players re-establish their colors by doing the "color" console command and suiciding once, when they respawn they will have correct colors henceforth, even across map changes.  (Notably, the color command must be used, just suiciding does nothing, and in QSS this trick does not work.)

**Comment by Novum** [comment]
I don't really test MP, so I need someone else to look at this.

**Comment by andrei-drexler** [comment]
Fixed in https://github.com/Novum/vkQuake/commit/fc320b8ed7d5caaf2da0239663d3bcd7fe09f919.
