### ISSUE TITLE
Steam re-release Text Display & Console Errors

### ISSUE THREAD

**Issue by d10sfan** [Novum/vkQuake#343]
I tried running the new steam rerelease pak files with vkquake. It seems to generally work well other than two things I noticed:

On the start of any level, a stream of these messages come out in the console and you can see them on the screen:

```Cvar_Set: variable campaign not found```

The other issue is that the text on the screen does not display correctly, instead showing what appears to be the variable for it. 

The release has a QuakeEX.kpf from the kex engine, and it contains a localization/loc_english.txt file in it, with many of these strings in it.

![20210820084436_1](https://user-images.githubusercontent.com/4337981/130242982-580ac9e3-b80b-45ed-bb83-7d6c3214ee0f.jpg)

**Comment by Novum** [comment]
Not supported and undocumented file formats. If upstream QuakeSpasm bothers with supporting it, I'll merge it.

**Comment by sezero** [comment]
Also see PR #345

**Comment by bangstk** [comment]
> 
> 
> Not supported and undocumented file formats. If upstream QuakeSpasm bothers with supporting it, I'll merge it.
> 
> Note also that Zenimax has chosen not to release the source code of the re-release.

.kpf is just a renamed zip.  Code probably does no more than searches for a match of $map_skill_easy within the appropriate text file, and prints the string from that line instead.

It is probably not reasonable to support reading the zip/kpf file, but the string lookup should be much more feasible. Worst case the english strings could potentially be hardcoded if we don't care to support language selection localization yet.

**Comment by micwoj92** [comment]
> Note also that Zenimax has chosen not to release the source code of the re-release.

Isn't that breaking of GPL2 license?

**Comment by Novum** [comment]
> > Note also that Zenimax has chosen not to release the source code of the re-release.
> 
> Isn't that breaking of GPL2 license?
No, it's not. Zenimax is the sole owner of the entire original source code so they are free to re-license it with whatever license they want.

**Comment by Novum** [comment]
Re-opened this because people are actively working on a fix

**Comment by NightFright2k19** [comment]
At least the new DOPA can be made to work with other ports, they didn't change its structure too much. Deleting the integrated progs.dat from its pak file and updated ent files for the message strings restore (almost) full functionality, except for that "Congrats" screen at the end.

**Comment by vide0hanz** [comment]
> For the time being, you could try renaming `vkquake.pak` to something like `vkquake.pak.old`, it has some entity files (for e1m1, e1m2, e1m4, e2m2, e2m3 and e2m7) that were created for the old versions of the maps and are now interfering.

Ah, I was wondering why I wasn't having the issues @dezo2 was describing. I've never used the vkquake.pak file and only recently learned that it exists. On Arch, I've only ever installed vkQuake/QSS via the AUR and I don't think it does anything with this file if installed that way. 

Hoping your code regarding all of this gets merged soon @andrei-drexler :)

**Comment by micwoj92** [comment]
> On Arch, I've only ever installed vkQuake/QSS via the AUR and I don't think it does anything with this file if installed that way.

If you are using vkquake then that file gets installed as `usr/share/games/vkquake/vkquake.pak`. But it's compiled with DO_USERDIRS=1 so it searches inside `.vkquake` folder in your home directory by default.

**Comment by Steve-Gibbs** [comment]
I was curious to see whether it would be possible to make use of the vkquake.pak on the rerelease id1 maps, for their z-fighting fixes but also restore the fog and water transparency.

I found that typing fog into the console gives the fog density and rgb values for the currently loaded map.

I’ve been through the maps found in vkquake.pak and found the fog settings used in the rerelease and matched the water transparency by eye.
 
E1M1
fog 0.025000 0.670588 0.662745 0.917647
r_wateralpha 0.65

E1M2, E1M4, E2M2, E2M3, E2M7
fog 0.025000 0.576471 0.266667 0.431373
r_wateralpha 0.65

I was wondering if there’s a way that these settings could be loaded automatically when a map is loaded?

**Comment by d10sfan** [comment]
Thanks for all that, just tried it with the latest and it works great! I've added the option of using the rerelease assets for all the different mission packs and automated the extraction and placement of the localization file in luxtorpeda-dev.
