### ISSUE TITLE
Can't select "Join game at:"

### ISSUE THREAD

**Issue by malvarenga123** [Novum/vkQuake#346]
Using vkQuake 1.10 beta 3 W64 on Windows 7 x64.
I cannot select "Join game at:" in Multiplayer->Join Game->TCP/IP, either with the arrow keys or mouse.
I can open the console and join a game using "connect hostname:port"

I don't know if it's relevant, but I can select the option in the latest W64 build of Quakespasm-Spiked.

**Comment by andrei-drexler** [comment]
Thanks for reporting this! Fixed in commit 606d455562b4eb4600bf820fd5c5fd3d93e9f8d3.
