### ISSUE TITLE
build_cross_win64.sh script builds w64 vkQuake.exe bin with run time errors

### ISSUE THREAD

**Issue by typedefn** [Novum/vkQuake#348]
Build machine info:

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

x86_64-w64-mingw32-gcc -v

Using built-in specs.
COLLECT_GCC=x86_64-w64-mingw32-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/lto-wrapper
Target: x86_64-w64-mingw32
Thread model: win32
gcc version 9.3-win32 20200320 (GCC)

After cross-compiling the vkQuake.exe  binary on my Ubuntu build machine I copy the .dll files and the vkQuake.exe file to the my Win10 machine under the original quake1/  game folder.  When I execute the vkQuake.exe on my Windows 10 machine, I get the following error dialog box.

vkQuake.exe - Entry Point Not Found
The procedure entry point vkAllocateCommandBuffer could not be located in the dynamic link library vkQuake.exe.

So I opened up the vkQuake.exe with a program called Dependency Walker, and received the following output:

![image](https://user-images.githubusercontent.com/39973557/131171291-d3c5dfcb-f9d3-42f3-9b6b-cdc6f56b0ae7.png)

It looks like a lot of the vk Extensions are missing or something...

I have the latest nVidia 471.68 drivers on my Win10 machine for the RTX 2060 Super GPU.
Any help appreciated, thanks.

**Comment by sezero** [comment]
Well, whatever the reason for the failure is, I may have to regenerate all x64 import libraries.

**Comment by Novum** [comment]
@sezero Okay, keeping this open for now.

**Comment by sezero** [comment]
I _think_ I know what the issue was. @typedefn, please test:

- get a fresh git clone of vkquake and cd into it,
- extract the attached file making sure it overwrites
- do a fresh win64 build

[Windows.tar.gz](https://github.com/Novum/vkQuake/files/7071434/Windows.tar.gz)

Does it work?

**Comment by typedefn** [comment]
Yes, it works.

**Comment by sezero** [comment]
Git repo is now updated, thanks for testing!
