### ISSUE TITLE
[Feature request] scr_menudrawhud

### ISSUE THREAD

**Issue by daffymahman** [Novum/vkQuake#349]
ezQuake has a simple but visually pleasing feature, scr_menudrawhud, which allows you to hide the HUD when you're in the main menu. It makes demos running in the background more like an attract mode.

I'd love to see it in vkQuake.

![ezquake000](https://user-images.githubusercontent.com/12608067/131245363-1b78a24c-d0c3-4c5a-9ae1-25c37abbd301.jpg)

**Comment by vsonnier** [comment]
Not interested in adding this. Too liitle value.
