### ISSUE TITLE
 vkWaitForFences failed

### ISSUE THREAD

**Issue by konstmonst** [Novum/vkQuake#35]
Hi,
I've got amdgpu-pro running on Arch Linux and have the following error:
QUAKE ERROR: vkWaitForFences failed
Here is my vulkaninfo:
[vkinfo.txt](https://github.com/Novum/vkQuake/files/393850/vkinfo.txt)

**Comment by konstmonst** [comment]
I managed to setup vkQuake in eclipse. The error happens at gl_vidsdl.c:1287.

**Comment by konstmonst** [comment]
If I comment out vkWaitForFences and it works, but with horrible rendering artefacts. This seems like a general Problem with amdgpu-pro on linux. Here is a similar issue:
https://github.com/ValveSoftware/Dota-2-Vulkan/issues/154

In the following patch I added GetVulkanErrorString() for better error messages and fixed a missing Linux header (for XGetXCBConnection).
Here is the patch, I hope you will find it usefull:

diff --git a/Quake/gl_vidsdl.c b/Quake/gl_vidsdl.c
index 40eec02..13e6929 100644
--- a/Quake/gl_vidsdl.c
+++ b/Quake/gl_vidsdl.c
@@ -30,6 +30,11 @@ Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 #include "SDL.h"
 #include "SDL_syswm.h"
 
+#if VK_USE_PLATFORM_XCB_KHR
+// for XGetXCBConnection
+#include <X11/Xlib-xcb.h>
+#endif
+
 #define MAX_MODE_LIST	600 //johnfitz -- was 30
 #define MAX_BPPS_LIST	5
 #define MAXWIDTH		10000
@@ -123,6 +128,41 @@ static PFN_vkGetSwapchainImagesKHR fpGetSwapchainImagesKHR;
 static PFN_vkAcquireNextImageKHR fpAcquireNextImageKHR;
 static PFN_vkQueuePresentKHR fpQueuePresentKHR;
 
+static const char* GetVulkanErrorString(VkResult vkResult)
+{
+	static char unknownError[] = "err:0x________";
+	switch (vkResult)
+	{
+		case VK_SUCCESS: return "VK_SUCCESS";
+		case VK_NOT_READY: return "VK_NOT_READY";
+		case VK_TIMEOUT: return "VK_TIMEOUT";
+		case VK_EVENT_SET: return "VK_EVENT_SET";
+		case VK_EVENT_RESET: return "VK_EVENT_RESET";
+		case VK_INCOMPLETE: return "VK_INCOMPLETE";
+		case VK_ERROR_OUT_OF_HOST_MEMORY: return "VK_ERROR_OUT_OF_HOST_MEMORY";
+		case VK_ERROR_OUT_OF_DEVICE_MEMORY: return "VK_ERROR_OUT_OF_DEVICE_MEMORY";
+		case VK_ERROR_INITIALIZATION_FAILED: return "VK_ERROR_INITIALIZATION_FAILED";
+		case VK_ERROR_DEVICE_LOST: return "VK_ERROR_DEVICE_LOST";
+		case VK_ERROR_MEMORY_MAP_FAILED: return "VK_ERROR_MEMORY_MAP_FAILED";
+		case VK_ERROR_LAYER_NOT_PRESENT: return "VK_ERROR_LAYER_NOT_PRESENT";
+		case VK_ERROR_EXTENSION_NOT_PRESENT: return "VK_ERROR_EXTENSION_NOT_PRESENT";
+		case VK_ERROR_FEATURE_NOT_PRESENT: return "VK_ERROR_FEATURE_NOT_PRESENT";
+		case VK_ERROR_INCOMPATIBLE_DRIVER: return "VK_ERROR_INCOMPATIBLE_DRIVER";
+		case VK_ERROR_TOO_MANY_OBJECTS: return "VK_ERROR_TOO_MANY_OBJECTS";
+		case VK_ERROR_FORMAT_NOT_SUPPORTED: return "VK_ERROR_FORMAT_NOT_SUPPORTED";
+		case VK_ERROR_SURFACE_LOST_KHR: return "VK_ERROR_SURFACE_LOST_KHR";
+		case VK_ERROR_NATIVE_WINDOW_IN_USE_KHR: return "VK_ERROR_NATIVE_WINDOW_IN_USE_KHR";
+		case VK_SUBOPTIMAL_KHR: return "VK_SUBOPTIMAL_KHR";
+		case VK_ERROR_OUT_OF_DATE_KHR: return "VK_ERROR_OUT_OF_DATE_KHR";
+		case VK_ERROR_INCOMPATIBLE_DISPLAY_KHR: return "VK_ERROR_INCOMPATIBLE_DISPLAY_KHR";
+		case VK_ERROR_VALIDATION_FAILED_EXT: return "VK_ERROR_VALIDATION_FAILED_EXT";
+		case VK_ERROR_INVALID_SHADER_NV: return "VK_ERROR_INVALID_SHADER_NV";
+		default:
+			snprintf(&unknownError[6], 9, "%X", vkResult);
+			return unknownError;
+	}
+}
+
 #ifdef _DEBUG
 static PFN_vkCreateDebugReportCallbackEXT fpCreateDebugReportCallbackEXT;
 static PFN_vkDestroyDebugReportCallbackEXT fpDestroyDebugReportCallbackEXT;
@@ -541,9 +581,9 @@ static void GL_InitInstance( void )
 	application_info.engineVersion = 1;
 	application_info.apiVersion = VK_API_VERSION_1_0;
 
-	char * instance_extensions[] = { VK_KHR_SURFACE_EXTENSION_NAME, PLATFORM_SURF_EXT, VK_EXT_DEBUG_REPORT_EXTENSION_NAME };
+	char const * instance_extensions[] = { VK_KHR_SURFACE_EXTENSION_NAME, PLATFORM_SURF_EXT, VK_EXT_DEBUG_REPORT_EXTENSION_NAME };
 
-	char * layer_names[] = { "VK_LAYER_LUNARG_standard_validation" };
+	char const * layer_names[] = { "VK_LAYER_LUNARG_standard_validation" };
 
 	VkInstanceCreateInfo instance_create_info;
 	memset(&instance_create_info, 0, sizeof(instance_create_info));
@@ -618,7 +658,7 @@ static void GL_InitDevice( void )
 	uint32_t physical_device_count;
 	err = vkEnumeratePhysicalDevices(vulkan_instance, &physical_device_count, NULL);
 	if (err != VK_SUCCESS || physical_device_count == 0)
-		Sys_Error("Couldn't find any Vulkan devices");
+		Sys_Error("Couldn't find any Vulkan devices: %s", physical_device_count == 0? "" : GetVulkanErrorString(err));
 
 	VkPhysicalDevice *physical_devices = malloc(sizeof(VkPhysicalDevice) * physical_device_count);
 	err = vkEnumeratePhysicalDevices(vulkan_instance, &physical_device_count, physical_devices);
@@ -631,8 +671,11 @@ static void GL_InitDevice( void )
 
 	uint32_t device_extension_count;
 	err = vkEnumerateDeviceExtensionProperties(vulkan_physical_device, NULL, &device_extension_count, NULL);
-
-	if (err == VK_SUCCESS || device_extension_count > 0)
+	if (err != VK_SUCCESS)
+	{
+		Sys_Error("vkEnumerateDeviceExtensionProperties failed: %s", GetVulkanErrorString(err));
+	}
+	if (device_extension_count > 0)
 	{
 		VkExtensionProperties *device_extensions = malloc(sizeof(VkExtensionProperties) * device_extension_count);
 		err = vkEnumerateDeviceExtensionProperties(vulkan_physical_device, NULL, &device_extension_count, device_extensions);
@@ -710,7 +753,7 @@ static void GL_InitDevice( void )
 	queue_create_info.queueCount = 1;
 	queue_create_info.pQueuePriorities = queue_priorities;
 
-	char * device_extensions[] = { VK_KHR_SWAPCHAIN_EXTENSION_NAME };
+	char const * device_extensions[] = { VK_KHR_SWAPCHAIN_EXTENSION_NAME };
 
 	VkDeviceCreateInfo device_create_info;
 	memset(&device_create_info, 0, sizeof(device_create_info));
@@ -897,7 +940,7 @@ static void GL_CreateRenderPasses()
 
 	err = vkCreateRenderPass(vulkan_globals.device, &render_pass_create_info, NULL, &vulkan_globals.warp_render_pass);
 	if (err != VK_SUCCESS)
-		Sys_Error("Couldn't create Vulkan render pass");
+		Sys_Error("Couldn't create Vulkan render pass: %s", GetVulkanErrorString(err));
 }
 
 /*
@@ -941,11 +984,11 @@ static void GL_CreateDepthBuffer( void )
 
 	err = vkAllocateMemory(vulkan_globals.device, &memory_allocate_info, NULL, &depth_buffer_memory);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkAllocateMemory failed");
+		Sys_Error("vkAllocateMemory failed: %s", GetVulkanErrorString(err));
 
 	err = vkBindImageMemory(vulkan_globals.device, depth_buffer, depth_buffer_memory, 0);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkBindImageMemory failed");
+		Sys_Error("vkBindImageMemory failed: %s", GetVulkanErrorString(err));
 
 	VkImageViewCreateInfo image_view_create_info;
 	memset(&image_view_create_info, 0, sizeof(image_view_create_info));
@@ -962,7 +1005,7 @@ static void GL_CreateDepthBuffer( void )
 
 	err = vkCreateImageView(vulkan_globals.device, &image_view_create_info, NULL, &depth_buffer_view);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkCreateImageView failed");
+		Sys_Error("vkCreateImageView failed: %s", GetVulkanErrorString(err));
 }
 
 
@@ -994,7 +1037,7 @@ static void GL_CreateColorBuffer( void )
 
 	err = vkCreateImage(vulkan_globals.device, &image_create_info, NULL, &color_buffer);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkCreateImage failed");
+		Sys_Error("vkCreateImage failed: %s", GetVulkanErrorString(err));
 
 	VkMemoryRequirements memory_requirements;
 	vkGetImageMemoryRequirements(vulkan_globals.device, color_buffer, &memory_requirements);
@@ -1007,11 +1050,11 @@ static void GL_CreateColorBuffer( void )
 
 	err = vkAllocateMemory(vulkan_globals.device, &memory_allocate_info, NULL, &color_buffer_memory);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkAllocateMemory failed");
+		Sys_Error("vkAllocateMemory failed: %s", GetVulkanErrorString(err));
 
 	err = vkBindImageMemory(vulkan_globals.device, color_buffer, color_buffer_memory, 0);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkBindImageMemory failed");
+		Sys_Error("vkBindImageMemory failed: %s", GetVulkanErrorString(err));
 
 	VkImageViewCreateInfo image_view_create_info;
 	memset(&image_view_create_info, 0, sizeof(image_view_create_info));
@@ -1028,7 +1071,7 @@ static void GL_CreateColorBuffer( void )
 
 	err = vkCreateImageView(vulkan_globals.device, &image_view_create_info, NULL, &color_buffer_view);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkCreateImageView failed");
+		Sys_Error("vkCreateImageView failed: %s", GetVulkanErrorString(err));
 }
 
 /*
@@ -1036,7 +1079,7 @@ static void GL_CreateColorBuffer( void )
 GL_CreatePostprocessDescriptorSet
 ===============
 */
-GL_CreatePostprocessDescriptorSet()
+void GL_CreatePostprocessDescriptorSet()
 {
 	VkDescriptorSetAllocateInfo descriptor_set_allocate_info;
 	memset(&descriptor_set_allocate_info, 0, sizeof(descriptor_set_allocate_info));
@@ -1148,12 +1191,12 @@ static void GL_CreateSwapChain( void )
 
 	err = fpCreateSwapchainKHR(vulkan_globals.device, &swapchain_create_info, NULL, &vulkan_swapchain);
 	if (err != VK_SUCCESS)
-		Sys_Error("Couldn't create swap chain");
+		Sys_Error("Couldn't create swap chain: %s", GetVulkanErrorString(err));
 
 	uint32_t image_count;
 	err = fpGetSwapchainImagesKHR(vulkan_globals.device, vulkan_swapchain, &image_count, NULL);
 	if (err != VK_SUCCESS || image_count != NUM_SWAP_CHAIN_IMAGES)
-		Sys_Error("Couldn't get swap chain images");
+		Sys_Error("Couldn't get swap chain images: %s", GetVulkanErrorString(err));
 
 	VkImage *swapchain_images = (VkImage *)malloc(image_count * sizeof(VkImage));
 	fpGetSwapchainImagesKHR(vulkan_globals.device, vulkan_swapchain, &image_count, swapchain_images);
@@ -1183,11 +1226,11 @@ static void GL_CreateSwapChain( void )
 		image_view_create_info.image = swapchain_images[i];
 		err = vkCreateImageView(vulkan_globals.device, &image_view_create_info, NULL, &swapchain_images_views[i]);
 		if (err != VK_SUCCESS)
-			Sys_Error("vkCreateImageView failed");
+			Sys_Error("vkCreateImageView failed: %s", GetVulkanErrorString(err));
 
 		err = vkCreateSemaphore(vulkan_globals.device, &semaphore_create_info, NULL, &image_aquired_semaphores[i]);
 		if (err != VK_SUCCESS)
-			Sys_Error("vkCreateSemaphore failed");
+			Sys_Error("vkCreateSemaphore failed: %s", GetVulkanErrorString(err));
 	}
 
 	free(swapchain_images);
@@ -1220,7 +1263,7 @@ static void GL_CreateFrameBuffers( void )
 		framebuffer_create_info.pAttachments = attachments;
 		err = vkCreateFramebuffer(vulkan_globals.device, &framebuffer_create_info, NULL, &framebuffers[i]);
 		if (err != VK_SUCCESS)
-			Sys_Error("vkCreateFramebuffer failed");
+			Sys_Error("vkCreateFramebuffer failed: %s", GetVulkanErrorString(err));
 	}
 }
 
@@ -1284,12 +1327,12 @@ void GL_BeginRendering (int *x, int *y, int *width, int *height)
 	{
 		err = vkWaitForFences(vulkan_globals.device, 1, &command_buffer_fences[current_command_buffer], VK_TRUE, UINT64_MAX);
 		if (err != VK_SUCCESS)
-			Sys_Error("vkWaitForFences failed");
+			Sys_Error("vkWaitForFences failed: %s", GetVulkanErrorString(err));
 	}
 
 	err = vkResetFences(vulkan_globals.device, 1, &command_buffer_fences[current_command_buffer]);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkResetFences failed");
+		Sys_Error("vkResetFences failed: %s", GetVulkanErrorString(err));
 
 	VkCommandBufferBeginInfo command_buffer_begin_info;
 	memset(&command_buffer_begin_info, 0, sizeof(command_buffer_begin_info));
@@ -1298,11 +1341,11 @@ void GL_BeginRendering (int *x, int *y, int *width, int *height)
 	vulkan_globals.command_buffer = command_buffers[current_command_buffer];
 	err = vkBeginCommandBuffer(vulkan_globals.command_buffer, &command_buffer_begin_info);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkBeginCommandBuffer failed");
+		Sys_Error("vkBeginCommandBuffer failed: %s", GetVulkanErrorString(err));
 
 	err = fpAcquireNextImageKHR(vulkan_globals.device, vulkan_swapchain, UINT64_MAX, image_aquired_semaphores[current_command_buffer], VK_NULL_HANDLE, &current_swapchain_buffer);
 	if (err != VK_SUCCESS)
-		Sys_Error("Couldn't acquire next image");
+		Sys_Error("Couldn't acquire next image: %s", GetVulkanErrorString(err));
 
 	VkRect2D render_area;
 	render_area.offset.x = 0;
@@ -1363,7 +1406,7 @@ void GL_EndRendering (void)
 
 	err = vkEndCommandBuffer(vulkan_globals.command_buffer);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkEndCommandBuffer failed");
+		Sys_Error("vkEndCommandBuffer failed: %s", GetVulkanErrorString(err));
 
 	VkPipelineStageFlags wait_dst_stage_mask = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
 
@@ -1378,7 +1421,7 @@ void GL_EndRendering (void)
 
 	err = vkQueueSubmit(vulkan_globals.queue, 1, &submit_info, command_buffer_fences[current_command_buffer]);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkQueueSubmit failed");
+		Sys_Error("vkQueueSubmit failed: %s", GetVulkanErrorString(err));
 
 	device_idle = false;
 
@@ -1393,7 +1436,7 @@ void GL_EndRendering (void)
 	present_info.pImageIndices = &current_swapchain_buffer;
 	err = fpQueuePresentKHR(vulkan_globals.queue, &present_info);
 	if (err != VK_SUCCESS)
-		Sys_Error("vkQueuePresentKHR failed");
+		Sys_Error("vkQueuePresentKHR failed: %s", GetVulkanErrorString(err));
 }

**Comment by Novum** [comment]
That sounds like a driver issue.

**Comment by ethan961** [comment]
Just wanted to point out my potential solution found at [https://github.com/ValveSoftware/Dota-2-Vulkan/issues/154](ValveSoftware/Dota-2-Vulkan/issues/154) - this happened in Dota when using the upstream open source AMDGPU kernel driver on top of the AMDGPU-PRO userspace driver. If this is the same problem, using the AMD supplied AMDGPU-PRO kernel driver (which is included as the DKMS module) should resolve the issue.
