### ISSUE TITLE
Fix for sky rendering breaks fast clears

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#351]
aa13c83cf89e4dbd6230daa068ac81c90edbb200 broke fast clears on at least AMD HW. Need to find another way 

@andrei-drexler

**Comment by andrei-drexler** [comment]
Reverted - the issue it was fixing was a map error anyway, just one that was masked by the old sky rendering code.

**Comment by Novum** [comment]
Great! I'll keep this open because I need to revisit how the clear color is chosen. Code looks strange but it's apparently always black?

**Comment by andrei-drexler** [comment]
It is indeed *almost* always black, but not 100% - r_clearcolor 244 for example is blue, 253 is red, 254 white I think. I'm pretty sure the division by 255 in `R_SetClearColor_f` should actually be by 255.f, though.

**Comment by Novum** [comment]
Yeah, I think there is a bug that worked out in our favor. Wonder if there is even a use case for clears other than black?

**Comment by andrei-drexler** [comment]
Some colors do make it easier to spot map errors, I guess, but I'm not sure how much that's used in practice.

**Comment by Novum** [comment]
Yeah, I think we want to actually fix the r_clearcolor code, but make sure black is still the default.

**Comment by Novum** [comment]
Fixed r_clearcolor, but added r_fastclear to always force black by default.

977561e9d0af3993d36ded0a8d9b6e9d267a10fa
