### ISSUE TITLE
Read QuakeEX.kpf directly

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#352]
I want to add support to read the zip file directly and avoid users having to extract the data manually. E.g. with libzip.

**Comment by NightFright2k19** [comment]
Kinda ironic. My feature request to add pk3 support was recently rejected since that's not the way to go, and now it's coming through the backdoor anyway because of Quake Enhanced. Well, I guess I asked a bit too early, eh? :)

**Comment by sezero** [comment]
I can't say that I like this: adding zip support only to extract one localization file seems excessive to me.

**Comment by Novum** [comment]
> Kinda ironic. [My feature request to add pk3 support](https://github.com/Novum/vkQuake/issues/334) was recently rejected since you did not want to "support things that would encourage mods that are not compatible with vanilla QuakeSpasm" and now it's coming through the backdoor anyway because of Quake Enhanced. Well, I guess I asked a bit too early, eh? :)
This wouldn't be a general thing. I still don't want Pk3 support.

> I can't say that I like this: adding zip support only to extract one localization file seems excessive to me.
Maybe, but that is an awful installation experience right now :)

**Comment by Novum** [comment]
https://github.com/Novum/vkQuake/pull/354
