### ISSUE TITLE
[Feature Request] - SDL Desktop Fullscreen mode support / allow vkQuake to inherit desktop resolution

### ISSUE THREAD

**Issue by vide0hanz** [Novum/vkQuake#353]
**EDIT:** I think "Desktop Fullscreen" is what I'm referring to

I'm not *exactly* sure how to describe this, so forgive me if I have some things mixed up here.

Looking at QSS as an example:

If you have fullscreen disabled (windowed), the game's resolution will dynamically change to accomodate the window borders. This allows for a very nice transition from windowed to fullscreen modes, since the game doesn't take control over your input devices until the game window has focus.

Example screenshots:

![quake](https://user-images.githubusercontent.com/59800033/131430661-c5c7f4dd-d67a-4516-ac95-0fc5c3ed0eb6.png)

![quake2](https://user-images.githubusercontent.com/59800033/131430690-c1ee8441-57a0-4c7f-ae4d-b7a01e5ff859.png)

I am not sure if this is strictly an SDL2 thing, but other games using SDL2 which support inheriting the user's desktop resolution appear to behave the same way. In essence, it behaves similar to "borderless windowed mode" by that it allows for faster task switching, since the fullscreen viewport does not get shut down then the game loses focus.

I would love to see this behavior added into vkQuake as well. 

One thing to note if this is to be explored; it would probably be necessary to update the crosshair center position if `crosshair 1` is used, otherwise it will be center relevant to the resolution used at the time the map was loaded.

**Comment by ericwa** [comment]
I think `vid_desktopfullscreen 1` is what you're looking for.

The video mode is then ignored, and you can either use Alt+Enter, or switch to fullscreen through the menu, or do:

```
vid_desktopfullscreen 1
vid_fullscreen 1
vid_restart
```

It's not exposed in the video menu currently.

**Comment by vide0hanz** [comment]
> I think `vid_desktopfullscreen 1` is what you're looking for.
> 
> The video mode is then ignored, and you can either use Alt+Enter, or switch to fullscreen through the menu, or do:
> 
> ```
> vid_desktopfullscreen 1
> vid_fullscreen 1
> vid_restart
> ```
> 
> It's not exposed in the video menu currently.

@ericwa Not quite what I was after, but this definitely helps with usability on my end :) -- setting `vid_desktopfullscreen 1` at least lets me focus on my adjacent monitor without both screens going black momentarily. 

Do you know what QSS is doing differently with regards to window resizing? The above screenshots were taken running QSS on my *nix desktop with a tiling window manager. I cropped them for uploading here, but fullscreen is disabled in-menu and the in-game resolutions change according to the boundaries set by my window manager. The game will fit inside whatever window size I give it and scale accordingly (within reason, of course).

**Comment by ericwa** [comment]
>Do you know what QSS is doing differently with regards to window resizing? The above screenshots were taken running QSS on my *nix desktop with a tiling window manager. I cropped them for uploading here, but fullscreen is disabled in-menu and the in-game resolutions change according to the boundaries set by my window manager. The game will fit inside whatever window size I give it and scale accordingly (within reason, of course).

Ah, I think this might be the fact that QSS makes the window resizable when it's non-fullscreen:
https://github.com/Shpoike/Quakespasm/blob/master/quakespasm/Quake/gl_vidsdl.c#L625

**Comment by Novum** [comment]
I'm fine with enabling a resizable Window in non fullscreen. That's common behavior in other apps too.

**Comment by Novum** [comment]
Did a quick test and the window just snaps back to the size before dragging the window border. Needs more code changes than just the flag.

**Comment by vide0hanz** [comment]
> Did a quick test and the window just snaps back to the size before dragging the window border. Needs more code changes than just the flag.

`vid_desktopfullscreen` appears to be working correctly, but I'm not sure what is happening with regards to the viewport itself before the desktop resolution is updated and applied to the game. Is there a minimum SDL viewport size the game always resizes to before any other subsequent functions are called wrt resolution preferences?

**Comment by vide0hanz** [comment]
@Novum When both `vid_desktopfullscreen` and `vid_fullscreen` are enabled, I can send the game window to my adjacent monitor, which is a in a vertical orientation. Assuming no other windows are present on this display, the game will resize accordingly to fit the new dimensions, but there is a momentary pause where the entire contents of my desktop (visible windows, taskbar, etc) is displayed as a smaller window before the resize occurs. What I *think* I'm witnessing is the game's viewport being modified, albeit very momentarily. 

Perhaps I should find a way to record this. Not sure if it would be helpful, was thinking it may provide some insight on how to properly resize the game window.

**Comment by Novum** [comment]
I really don't even understand what exactly you want. Quite frankly, this whole thing would probably be used by one person, so please give me a good rationale why I would want to add more complexity to the code?

**Comment by vide0hanz** [comment]
> I really don't even understand what exactly you want.

Enabling a resizable window in non fullscreen, as you mentioned earlier. The way I originally described this was inaccurate, so my apologies for any confusion.

**Comment by Novum** [comment]
I'll check at some point if it's an easy fix, as I said just setting the SDL flag isn't enough because of some Vulkan specific code.

**Comment by Novum** [comment]
7c90af4e9a6636f2ac5b3dc74ba4dabf93d6870c

**Comment by vide0hanz** [comment]
This works beautifully! Thank you @Novum

Are there any plans to expose desktop fullscreen in-menu or nah?
