### ISSUE TITLE
Fails with Intel iGPU HD530 Mesa Vulkan driver..

### ISSUE THREAD

**Issue by oscarbg** [Novum/vkQuake#36]
compiled from code cloned today:
I use Ubuntu 16.04 latests padoka ppa 

vkQuake 0.30.0 (c) Axel Gneiting
Host_Init
Playing shareware version.
Console initialized.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 19:46:13 Aug  1 2016
256.0 megabyte heap

Vulkan Initialization
Vendor: Intel
Device: Intel(R) HD Graphics 530 (Skylake GT2)
Creating command buffers
Creating swap chain

ERROR-OUT BEGIN

QUAKE ERROR: Couldn't get swap chain images

**Comment by Novum** [comment]
Very likely a driver problem.

**Comment by bviktor** [comment]
Works fine with HD 530 on Windows 10.

**Comment by Novum** [comment]
I have a theory why this might fail (I actually require exactly two swapchain buffers). I will eventually rework this.

**Comment by mrcmunir** [comment]
In Ivy bridge vulkan mesa driver loading fine but  has otherrs problem i.e Fullscreen (segment fault) only working with Windows mode and can't change options.

**Comment by Novum** [comment]
Should be fixed with f52f09eb1f1315c4fa31a522c8d4a110900decd2

**Comment by oscarbg** [comment]
The patch **doesn't fix** the game working with Mesa drivers
can you comment if that is fixable or needs driver assistance from Mesa devs?
 now I get..
Creating command buffers
Creating swap chain
Creating render passes
Creating color buffer
Creating depth buffer
Creating frame buffers
Initializing staging
Creating descriptor set layouts
Initializing dynamic vertex buffers
Initializing dynamic index buffers
Initializing dynamic uniform buffers
Initializing samplers
Creating pipeline layouts
Creating pipelines
../../../../src/compiler/spirv/spirv_to_nir.c:2372 WARNING: Unsupported SPIR-V capability: InputAttachment
../../../../src/compiler/spirv/vtn_variables.c:1062 WARNING: Decoration not allowed for variable or structure member: InputAttachmentIndex
Violación de segmento (`core' generado)

**Comment by SaschaWillems** [comment]
> ../../../../src/compiler/spirv/spirv_to_nir.c:2372 WARNING: Unsupported SPIR-V capability: InputAttachment

That sounds like a driver issue. The Vulkan specs requires implementations to support the InputAttachment OpCapability.

**Comment by Novum** [comment]
Correct, this is definitely a driver bug.

**Comment by OlliC** [comment]
I have the same error on my laptop with Fedora 25. It has a Intel HD Graphics 520 (Skylake GT2) integrated card. vulkaninfo shows vulkan 1.0.5 is supported. 

```
spirv/spirv_to_nir.c:2475 WARNING: Unsupported SPIR-V capability: InputAttachment
spirv/vtn_variables.c:994
WARNING: Decoration not allowed for variable or structure member: InputAttachmentIndex
Segmentation fault
```

**Comment by OlliC** [comment]
Btw. its working now on Fedora 26 with Mesa 17.1.3  :-)

**Comment by Novum** [comment]
Tell Intel
