### ISSUE TITLE
CTD on timerefresh command

### ISSUE THREAD

**Issue by 0mnicydle** [Novum/vkQuake#361]
Windows 10 x64 -- Using the 1.11.0 release, but the issue has been going on for awhile apparently. Brought to my attention by someone on the Steam forums (and reproduced by me).

CTD upon issuing the timerefresh command

After quickly sifting through the released builds:

0.72 oldest build that will actually start for me where the crash hasn't started happening yet
0.90-0.94 won't even start for me
0.95 next release that starts again, crashes on timerefresh

**Comment by Novum** [comment]
a6617f7e2e0333b3628783da471f522f487fa3ec

Really not sure why anyone would use it, but it was a minor fix, so I'll leave it in
