### ISSUE TITLE
[feature request] $ function for saving command values

### ISSUE THREAD

**Issue by DefectiveByDesign** [Novum/vkQuake#363]
Quake2 has a $ command to save values of a variable in a alias. For example: alias my_sens $sensitivity would make my_sens = to the current mouse sensitivity. 

Is there an equivalent function in Quake1, if not can it be put on a todo list? This is a really helpful function when making aliases.

**Comment by Novum** [comment]
Not the scope of this project, please ask the QuakeSpasm people for things like this.
