### ISSUE TITLE
"Particles" video option not showing all possibilites when using right arrow

### ISSUE THREAD

**Issue by Hooperla** [Novum/vkQuake#364]
If you go to "Video Options" and try to select the "GLQuake" option in "Particles" by hitting the right arrow you won't be able to find it, only "Classic" and "Off". However, if you use the left arrow all three options are able to be selected.
In other words, there appears to be a bug where all three options are only available using certain methods of selection.
I can make a video if my explanation isn't the best.

**Comment by andrei-drexler** [comment]
Thanks for reporting this, and don't worry, your description your perfectly clear, no video needed. Fixed in https://github.com/Novum/vkQuake/commit/4278017873d437a0204ae394e6778963d229f091.
