### ISSUE TITLE
Render scale makes the game blurry.

### ISSUE THREAD

**Issue by JulekSTN** [Novum/vkQuake#365]
Hello,

I saw this problem while playing with the settings. _Quakespasm-Spiked's_ render scale is **rough** (i like that), and _vkQuake's_ is **blurry**. _Quakespasm-Spiked_ and _Quakespasm_ have the same filter.
I have attached photos of _Quakespasm-Spiked's_ and _vkQuake's_.
If somebody sees this, please **share** this to other people who would like this update.

QSS
![qss](https://user-images.githubusercontent.com/51170759/132133880-d60a0488-c746-40db-bd3e-6e3728d49bc1.png)
VKQ
![vkq](https://user-images.githubusercontent.com/51170759/132122813-0e58238f-ccff-4497-9b78-70b6a6c25d62.png)

Also, as you can see the gun in qss is higher up (viewmodel FOV maybe, i'm not an expert), and i haven't found a way to change that. Would like the ability to change the position. 

Kind regards,
JulekSTN

**Comment by vide0hanz** [comment]
> Also, as you can see the gun in qss is higher up (viewmodel FOV maybe, i'm not an expert), and i haven't found a way to change that. Would like the ability to change the position.

Try setting `cl_gun_fovscale` to 0

It looks as if antialiasing is being forced when using the render scaling, even if disabled otherwise in the video options. Not sure if this is intentional or not.

**Comment by Novum** [comment]
It is intentional. Just skipping pixels for render scale results in a flickery mess.

**Comment by Novum** [comment]
That being said, I probably should adjust the texture LOD bias finally

**Comment by Novum** [comment]
3876337ac6359c5bc47c7448f894e691147cd980 This should help with some of the bluriness. That being said, I don't think it's what you want.

What QSS does is def. out of the question, you can't just sample the final image and skip pixels, it's going to flicker like crazy. The right way would be to render in lower res directly. That's a bigger change and I don't even know how many people are using r_scale anyway.

**Comment by JulekSTN** [comment]
Thanks, going to check the new update.
If this still doesn't work I'll let you know.
