### ISSUE TITLE
Broken text strings when using the 2021 KEX Engine files

### ISSUE THREAD

**Issue by ViperAcidZX** [Novum/vkQuake#366]
I tried using vkQuake with my copy of the 2021 Kex Engine re-release of the game and I get text prompts like this: 

![vkQuake - 2021 PAK file](https://user-images.githubusercontent.com/19318128/132132167-2747afde-649e-4e99-93e1-b0b8b63e07db.png)

On the original version's PAK files it shows up fine.

![vkQuake - 1996 PAK file](https://user-images.githubusercontent.com/19318128/132132180-85f4c823-63b8-4263-9bb8-34fa91fac55f.png)

**Comment by andrei-drexler** [comment]
If you're seeing those strings it means that vkQuake can't load the localization data. Please check the console after starting the game, it should say something like
> Language initialization
Couldn't load 'localization/loc_english.txt'
from 'e:\games\quake'

Make sure `QuakeEX.kpf` (from the rerelease) is present in that folder mentioned after 'from' (in my case 'e:\games\quake'). If it's loaded correctly, the message should change to

> Language initialization
Loaded 1037 strings from 'localization/loc_english.txt'

and you should see the proper messages in-game.

**Comment by Novum** [comment]
Not a bug. Most likely installed to wrong folder.
