### ISSUE TITLE
Render scaling uses bilinear instead of nearest neighbor, resulting in blurred image

### ISSUE THREAD

**Issue by WoolieWool** [Novum/vkQuake#370]
Render scaling does not result in the expected old-school pixelation of the image because the scaling uses bilinear filtering to scale up, resulting in an anti-aliasing/blur effect on screen.

![vkquake0000](https://user-images.githubusercontent.com/14041765/134280033-00782e5e-1a04-49ce-9ba1-f01bcef45d15.png)
VKQuake in 1280x960 resolution, without render scaling.

![vkquake0001](https://user-images.githubusercontent.com/14041765/134280070-9f2c6406-8fdd-45bf-b83e-e101423ac27b.png)
VKQuake in 1280x960 resolution, using 4x render scaling to simulate 320x240.

![winquake_mark_v_0001](https://user-images.githubusercontent.com/14041765/134280255-dd248c8b-6099-43a9-ade7-3c7a7fa3e713.png)
Winquake Mark V in 2880x2160, using its own render scaling to upscale from 320x240 (screenshot is 320x240). There is no blur and the image appears correct.

And the example of WinQuake Mark V makes me wonder if perhaps the scaling could be redone to scale directly to common low resolutions (320x200, 320x240, 640x400, 640x480) instead of using integers, so I can run in what looks 640x480 or 320x240 while still using the native video mode.

**Comment by vide0hanz** [comment]
#365

**Comment by Novum** [comment]
It's not bilinear, it's properly averaging the values of the screen area. That is by design.
