### ISSUE TITLE
Feature request: QSS MD5 re-release compatibility

### ISSUE THREAD

**Issue by De-Seppe** [Novum/vkQuake#371]
MD5 support for the re-release has been added to QSS.
Are you planning to add this to vkQuake or will you skip this because it would encourage mods that are not compatible with vanilla QuakeSpasm?

**Comment by vide0hanz** [comment]
Support for this would be nice. As far as I know, the only way to use the rerelease models is to unpack them, convert them, and repack again.

**Comment by Meerschweinmann** [comment]
Support for rerelease models as an option would be fine, because they fit good in Quake without loosing the good old charme the game has.

**Comment by Novum** [comment]
87b39c2366a8787004795ad24688d4b738b9e814
