### ISSUE TITLE
[Bug] Problem with func_train

### ISSUE THREAD

**Issue by NightFright2k19** [Novum/vkQuake#375]
It appears vkQuake inherited an [issue from QSS regarding func_train](https://github.com/Shpoike/Quakespasm/issues/75).

Tested with: vkQuake v1.11.0 (x64)

**Comment by QUINTIX** [comment]
Just in case it's useful, by adding

```c
const char* funcName = PR_GetString(f->s_name);
if(NULL != strnstr(funcName, "train", 63)){
    Sys_Printf("calling %s\n", funcName);
}
```
before the `while` loop in `PR_ExecuteProgram`

and running map e2ue of Gotshun's "Lost Levels"  per NightFright

I've found that in vanilla quakespasm, where it works normally, `train_next` is periodically called; every 20ms or so.
however, in vkQuake (and presumably QSS, haven't pulled that yet), `train_blocked` is called just about every frame.

`PR_GetString(f->s_file)` is "plats.qc" which I presume [is this](https://quakewiki.org/wiki/plats.qc), as it has both `train_blocked` and `train_next` defined.

I'll keep poking around.

**Comment by QUINTIX** [comment]
Still not close to making a PR for this bug, but this is too weird not to share:

<img width="818" alt="Screen Shot 2021-11-18 at 7 23 25 PM" src="https://user-images.githubusercontent.com/9246060/142517832-4f48855a-87ba-475e-8aef-f61b0eb16304.png">

execute the expression
`e ((edict_t*)(((byte*)qcvm->edicts) + 266600))->v.health = -1`
at a breakpoint in the debug console, killing the shambler that's somehow blocking the invisible platform, and said invisible platform moves. You can see the platform move with `r_showbboxes` on (thanks for adding that back in).  But I do not see any shamblers near by. The key still does not move with it. 

But hey, I got the platform to move at least.

**Comment by QUINTIX** [comment]
@NightFright2k19
If `pr_checkextensions 0` is set before e2ue is loaded, the key moves as expected.

[I'm still poking around for possible fixes with qc extensions still enabled](Novum/vkQuake/compare/master...QUINTIX:fix_ortho). So far, I can get the invisible platform to move without killing off any shamblers, but the key is still both lower than expected and immobile on my branch.
