### ISSUE TITLE
[Bug] Not all HUD icons shown in DoE

### ISSUE THREAD

**Issue by NightFright2k19** [Novum/vkQuake#377]
In "Dissolution of Eternity" (MP2), the statusbar does not show icons for armor, active new powerups (Anti-Grav Belt, Power Shield) or alternate ammo (lava nails, multi rockets, plasma). It appears ID1 and SoA are not affected by this.

Tested with: vkQuake v1.11.0 x64

**Comment by Novum** [comment]
2f3809091b560b5719e018a746ff3f13beb3dc4e
