### ISSUE TITLE
New remaster update breakage with a new builtin number 91

### ISSUE THREAD

**Issue by sezero** [Novum/vkQuake#378]
As reported at https://github.com/sezero/quakespasm/issues/10, we get `bad builtin number 91` error. Haven't looked at it myself, yet.

**Comment by sezero** [comment]
Obviously not DotM-specific - happens with id1 too:
```
CALL2      385(bprint)bprint()  
quakec/client.qc : ClientConnect
<NO FUNCTION>
Bad builtin call number 91
Host_Error: Program error
```

**Comment by Novum** [comment]
Looks good, feel free to submit
