### ISSUE TITLE
Fails with "Killed: 9" after building and running on macOS.

### ISSUE THREAD

**Issue by EtherTyper** [Novum/vkQuake#383]
The latest commit on master and release both fail with the following error after I attempt to build and run.

```
Elis-MacBook-Pro:Quake ethertyper$ ./vkquake 
Killed: 9
```

**Comment by EtherTyper** [comment]
I commented out the strip command and it works now. Still leaving the issue open because why that would break the program is worth investigating imo, but you can close if you want.

**Comment by Novum** [comment]
macOS is not an officially supported platform because I can't test it.

**Comment by EtherTyper** [comment]
Apparently I was using the GNU binutils-provided `strip`, which has known problems on macOS, rather than the Apple version. Closing.

**Comment by QUINTIX** [comment]
I’m unable to get either vkQuake or Quakespasm to build on Mac for unrelated SDL linking issues. I know I had vkQuake build before, so I would love some guidance.

**Comment by EtherTyper** [comment]
@QUINTIX Open a new issue.

**Comment by QUINTIX** [comment]
> @QUINTIX Open a new issue.

I’m pretty sure it’s a me problem. As in I do not think the SDL2 I got from brew is the only SDL2 I have installed. But I might just do so for Quakespasm if I cannot get that to build tonight, as that seems to build SDL2 from source. Not an ideal way to handle external dependencies.
