### ISSUE TITLE
How do i run my built version of vkquake on linux exactly?

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#388]
How do i run my built version of vkquake on linux exactly?

**Comment by LethalManBoob** [comment]
I cant even find a way to run the rebuild version. I click the app image but nothing happens. I get this error, opening it from console. I have all the paks in the directory 


QUAKE ERROR: W_LoadWadFile: couldn't load gfx.wad

Check that this has an id1 subdirectory containing pak0.pak and pak1.pak, or use the -basedir command-line option to specify another directory.

**Comment by micwoj92** [comment]
I don't know what you mean by "your own built version" because folder `vkquake-1.11.1_linux64` suggests that you downloaded prebuilt version. Anyway, that's how the directory structure should look like
![image](https://user-images.githubusercontent.com/45581170/141472079-17e28ab5-bfe3-47a8-b6ac-eb4f01498bb7.png)

**Comment by LethalManBoob** [comment]
The error is the same with the rebuild, this only difference is with the
stated directory

**Comment by LethalManBoob** [comment]
My tree is identical to yours.

**Comment by micwoj92** [comment]
Could you show your tree output? How do you run it from terminal?

**Comment by QUINTIX** [comment]
Check out the GitHub actions build script. May want to give Docker a try and have the same preconfigured build environment produce the binary.

**Comment by micwoj92** [comment]
Or just dont use appimage and build using make.

**Comment by Novum** [comment]
Not a bug. Please put this in discussions.
