### ISSUE TITLE
[Feature request] Add r_showbboxes command

### ISSUE THREAD

**Issue by bstordeur** [Novum/vkQuake#389]
Hey, small quality-of-life request.
Having the **r_showbboxes** command that is available in Quakespasm (and other engines) would be nice, often very helpful for us mappers when debugging stuff.

![image](https://user-images.githubusercontent.com/5883104/141475087-fe6eb522-2234-40b1-b354-2b0311943b5d.png)

**Comment by Novum** [comment]
Done 64ffec359e543eb67384631d26baac8650fff5f2
![image](https://user-images.githubusercontent.com/112222/141607772-1db23723-2566-4b73-84f5-0797990d07ac.png)
