### ISSUE TITLE
How do I read Sys_Printf messages on Windows?

### ISSUE THREAD

**Issue by bviktor** [Novum/vkQuake#39]
Hi,

This may seem like a dumb question but I just can't figure this out. Once you start vkQuake.exe it detaches and there's no stdout whatsoever.

There's -condebug but it only redirects Con_Printf output.

I can't use Con_Printf either because there's no console at the time this runs - I guess.

Also, I can't use Linux because this is the Windows part :)

Any ideas, guys?

**Comment by Novum** [comment]
I don't get it, I can run vkQuake in the debugger just fine (VC++ 2013 & 2015)

**Comment by bviktor** [comment]
Actually, I was trying to run vkQuake.exe directly from the console. Tbh I didn't even try the debugger. The debug build actually crashes when I start it from cmd.exe.

If I start a debug build from VS, it gives me the missing gfx.wad error even though the pak file is there. How can I solve this?

**Comment by NPatch** [comment]
I have the same problem. The link to the pak files is broken and I found a shareware version elsewhere which only had the pak0.pak.

Placed it in id1/pak0.pak under the Debug/Release directory and get the same error. It's as if it doesn't see the pak and never unpacks it.

**Comment by bviktor** [comment]
I just checked the shareware link, it does work, but it uses FTP instead of HTTP, maybe your browser doesn't support it?

If I start the release version from CMD with id1/pak0.pak next to it, it works just fine. It's only VS debugging that doesn't work for me.

**Comment by NPatch** [comment]
I'm using Firefox..wth?!

**Comment by SaschaWillems** [comment]
The id1 folder containing the pak should be placed in Windows\VisualStudio and not inside the debug/release folders for the build configuration.

VS will run the from the same path as the solution file.

**Comment by NPatch** [comment]
Indeed. Now it works in the debugger. Please correct this in the Readme.md.

**Comment by bviktor** [comment]
@SaschaWillems thanks a lot. Now debug x64 works. x86 crashes though, but that's a separate issue.

@NPatch Firefox here as well, not sure why you can't download it. I'll open a PR with this info added to the readme tomorrow.
