### ISSUE TITLE
[Compilation Error] vkquake fails to compile

### ISSUE THREAD

**Issue by Vagankovo** [Novum/vkQuake#394]
## System info
OS - Arch Linux (rolling)
GPU - Radeon RX 5500M & AMD Renoir (integrated graphics)
CPU - Ryzen 7 4800H with Radeon Graphics

vkquake version - latest git commit

## Bug
Compilation fails at `glmodel.c`. Compilation log is provided:
[error.log](https://github.com/Novum/vkQuake/files/7574034/error.log)

**Comment by sezero** [comment]
Fixed
