### ISSUE TITLE
[Bug] Arcane Dimensions particles sometimes are way too big

### ISSUE THREAD

**Issue by Vagankovo** [Novum/vkQuake#395]
## System info
OS - Arch Linux (rolling)
GPU - Radeon RX 5500M & AMD Renoir (integrated graphics)
CPU - Ryzen 7 4800H with Radeon Graphics

vkquake version - latest git commit

## Bug
Particles in mod Arcane Dimensions are sometimes overblown in size and look like you're getting flashbanged.
![Screenshot from 2021-11-23 21-04-56](https://user-images.githubusercontent.com/90520453/143080479-e6e1ca67-c33d-4d13-a3c1-3bf04c6e717d.png)
![Screenshot from 2021-11-23 21-04-51](https://user-images.githubusercontent.com/90520453/143080485-40848065-67cb-4998-92bc-c3525c5401db.png)
![Screenshot from 2021-11-23 21-04-26](https://user-images.githubusercontent.com/90520453/143080487-b1afae0e-d164-409e-b0c8-2d5c3a6f14df.png)
![Screenshot from 2021-11-23 21-04-21](https://user-images.githubusercontent.com/90520453/143080489-0d80c359-18b8-4656-b1fe-0baf6759a978.png)

## Reproduction
What causes this bug and the reproduction steps aren't known as of now, but this is my potential method:
1. Load Arcane Dimensions.
2. Shoot with guns (particularly the shotguns).
3. If it doesn't work, restart the game.

**Comment by Novum** [comment]
I cannot reproduce this

**Comment by Novum** [comment]
e00ce03e77d98a35d55cf7d2a562272ad3b6cd75
