### ISSUE TITLE
Failed CI builds are marked as successful

### ISSUE THREAD

**Issue by alexey-lysiuk** [Novum/vkQuake#396]
GitHub Actions builds that failed to compile (like [this one](https://github.com/Novum/vkQuake/runs/4321444082)) are marked as successful. 
```
net_dgrm.c:1875:11: error: 'MAXSIZE_T' undeclared (first use in this function)
       i = MAXSIZE_T;
           ^
```
This seems to be a contradiction to the primary goal of continuous integration.

**Comment by Novum** [comment]
Okay, this needs attention, thanks.

**Comment by Novum** [comment]
375db68bdf7ebec96d831e429d8cb36b2f28d400
