### ISSUE TITLE
[vkQuake 1.12.0] posenum >= MAXALIASFRAMES

### ISSUE THREAD

**Issue by Riccardoman** [Novum/vkQuake#399]
I'm getting this error when trying to load certain maps, like alk_dancing.bsp from Alkaline (both the original and the 1.1 update)
Your previous release runs the map without problems
I tried to change vid_refreshrate and host_maxfps values without success
(otherwise  your change on the physics consistency is noticeable, really nice)

**Comment by Novum** [comment]
Confirmed. Must be something with the UBSan fixes.

**Comment by Novum** [comment]
e140311b9a3367763b4beafb8146ebef772f4f45
