### ISSUE TITLE
how do we compile it from linux?

### ISSUE THREAD

**Issue by BielBdeLuna** [Novum/vkQuake#4]
what are it's dependencies?

**Comment by birdie-github** [comment]
First of all it's "**its**" dependencies.

So,
it's = it is.
its = belonging to it.

Second of all - have you even tried downloading it?

From Makefile:
```
### Vulkan SDK directory
VULKAN_INCLUDE_DIR=$(VULKAN_SDK)/include

### Enable/Disable SDL2
USE_SDL2=1

### Enable/Disable codecs for streaming music support
USE_CODEC_WAVE=1
USE_CODEC_FLAC=0
USE_CODEC_MP3=1
USE_CODEC_VORBIS=1
USE_CODEC_OPUS=0
# either mikmod (preferred) or modplug, not both
USE_CODEC_MIKMOD=0
USE_CODEC_MODPLUG=0
USE_CODEC_UMX=0
```

**Comment by fabry92** [comment]
i got this error:
quakedef.h:231:27: fatal error: vulkan/vulkan.h: File o directory non esistente
compilation terminated.
Makefile:200: set di istruzioni per l'obiettivo "gl_refrag.o" non riuscito
make: *** [gl_refrag.o] Errore 1

**Comment by BielBdeLuna** [comment]
ok, now I see there is a makefile in the quake folder.

**Comment by ProfessorKaos64** [comment]
@fabry92 You need a GPU with Vulkan support. beyond that, try here:  
https://packages.debian.org/search?keywords=vulkan

Most of those pacakges are in libvulkan-dev:  
https://packages.debian.org/search?suite=stretch&arch=any&mode=exactfilename&searchon=contents&keywords=vulkan.h

**Comment by ProfessorKaos64** [comment]
I am working on Debian packaging tonight. Have some errands to do, but started that here:

https://github.com/ProfessorKaos64/LibreGeek-Packaging/tree/brewmaster/vkquake/debian

@Novum , would you accept Debian packaging, or do you want to keep this distro-agnostic?

**Comment by ProfessorKaos64** [comment]
I have an initial test Debian package at the below link. I haven't tested it (late here, time to settle down for the night). I'll likely have time to give it a test tomorrow. I merged in debian packaging from quakespasm. Probably adjustments to be made yet as well. I link quakspasm to 'vkquake' so you can use that, aside from the desktop file.

http://packages.libregeek.org/steamos-tools/pool/games/v/vkquake/

**Comment by ProfessorKaos64** [comment]
I had @strycore from Lutris test this out for me as well. If you get the gfx.wad error, be sure to make sure the pk3/wads/id folder are in lowercase. See:

https://steamcommunity.com/linkfilter/?url=http://www.tldp.org/HOWTO/Quake-HOWTO-8.html

I might do an AUR arch linux package after some time.

**Comment by Novum** [comment]
Please mind that there are still bugs in the code, I'm not sure if this should be a package already. Will be fixed in time (after Siggraph). But thank you.

**Comment by ProfessorKaos64** [comment]
Point taken. This shall remain in a testing repository of my own for quite a while regardless. I will try to remind anyone that tries it of this state  Thank you.

**Comment by strycore** [comment]
I guess I should also put a warning about this on the Lutris installer I made ;)

**Comment by ProfessorKaos64** [comment]
Well, I would say hold off using it in anything, based on Axel's comment. Up to you. If you want, you could just keep it in your master tree with a warning about it being unfinished.

**Comment by ProfessorKaos64** [comment]
There is also the barrier to entry. Your GPU and GPu driver must support Vulkan. Not everyone falls in to this category. As always alternative, you could offer Debian's quakespasm, which is vkquake, sans Vulkan support.

**Comment by jite** [comment]
A bit off topic but just wanted to mention that there's another quake engine out there called FTE (by Spike) that also has a Vulkan backend (and OGL/DX9/DX11). @Novum If you haven't seen it, you should really take a look. Again, sorry for off topic.

**Comment by ProfessorKaos64** [comment]
@jite , FTE is for Quakeword.. quakespasm is the most faithful to the original as far as I kno. There are lists all over the Internet but this is one of the good ones I have bookmarked:

https://steamcommunity.com/sharedfiles/filedetails/?id=118401000

**Comment by jite** [comment]
@ProfessorKaos64 FTE is a modern high tech engine (and server), and Spike (the guy behind it) is keen on keeping things faithful as far as possible when it comes to Quake. Though FTE can run many different games (Quake single player, Quakeworld, NetQuake, Quake 2, Quake 3, Hexen, etc etc.)

Though my comment about it was meant more like from a developer perspective. :)

**Comment by ProfessorKaos64** [comment]
@jite, well for fun I am going to make a package out of that today :)

**Comment by bviktor** [comment]
I believe 49ffd7d05edd25ccedfb127e0c1c676a58d297ed solves this issue.

**Comment by ProfessorKaos64** [comment]
@bviktor Does that assume/include SDL2 and making the mkpak? Here is what I [have](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/vkquake/debian/) that mostly carried over form quakespasm (the core code here).

**Comment by bviktor** [comment]
I'm not quite sure what mkpak is, couldn't find it anywhere. I tested it on a new, default install of Ubuntu 16.04.1 and yes, SDL2 is there:

~~~
apt install git make gcc libsdl2-dev libvulkan-dev libvorbis-dev libmad0-dev
~~~

**Comment by Novum** [comment]
Closing because of build instructions in readme.md

**Comment by bviktor** [comment]
@ProfessorKaos64 now I see mkpak.sh. But the file it generates is already in the repo, i.e. `Quake\quakespasm.pak`, so what about it?

**Comment by ProfessorKaos64** [comment]
I guess it can be ignored then. This was just anecdotal thoughts from the quakespasm Debian package.

**Comment by ToniaSanzo** [comment]
> 
> 
> First of all it's "**its**" dependencies.
> 
> So,
> it's = it is.
> its = belonging to it.
> 
> Second of all - have you even tried downloading it?

I can't be the only one that thought this was a hilarious way to respond to someone trying to help you. But also low-key I kind of appreciate the explanation.

**Comment by micwoj92** [comment]
Why would you even reply to this, it's been closed for almost 5 years...
