### ISSUE TITLE
unable to play (time)demos in 1.12.1 on Mac

### ISSUE THREAD

**Issue by wiedo84** [Novum/vkQuake#402]
After doing a timedemo and switching to another mod it'll give a fps, but I don't see or hear anything, only looking at the console. This problem wasn't there before in previous versions.

`]timedemo demo1
Playing demo from demo1.dem.
]game ad
3095 frames  15.3 seconds 201.7 fps
"game" changed to "id1;ad"`

**Comment by Novum** [comment]
I doubt this is mac specific

**Comment by ZecChelovek** [comment]
Windows 10 64bit, unable to play any demos whatsoever with the latest vkQuake.

**Comment by QUINTIX** [comment]
This is what I see from my local build from tag 11.1.1 on macOS Big Sur.
Not that it should matter much, but I have an old Intel Iris 540 IGP, per the captured log.

https://user-images.githubusercontent.com/9246060/144157413-e188f7c4-7df9-4795-8116-e65bbb98bf38.mp4

Output video is identical whether `-game hipnotic` is specified or not, so ignore the filename. Not sure if specifying an expansion should reproduce the behavior of "switching to another mod," but per the recording I am not able to reproduce what either wiedo84 or ZecChelovek describe.

Maybe I can reproduce what Zec is seeing on my windows machine another time.
