### ISSUE TITLE
[BUG] Sound no longer works in version-1.12.1 *prebuilt binaries* on Linux (Pop OS 21.04)

### ISSUE THREAD

**Issue by HAMM3REXTREME** [Novum/vkQuake#403]
Sound does not seem work anymore in version 1.12.1 on Pop OS 21.04 based on Ubuntu Hirsute Hippo (Not sure about other distributions). No sound effects, no music.
Terminal Output (only the part about SDL audio pasted):

```
Sound Initialization
Couldn't init SDL audio: 
Failed initializing sound
CDAudio disabled at compile time
```

SDL2 Version (apt-get list --installed | grep sdl2):
```
ibsdl2-2.0-0/hirsute,now 2.0.14+dfsg2-3 amd64 [installed,automatic]
libsdl2-2.0-0/hirsute,now 2.0.14+dfsg2-3 i386 [installed,automatic]
libsdl2-dev/hirsute,now 2.0.14+dfsg2-3 amd64 [installed]
libsdl2-image-2.0-0/hirsute,now 2.0.5+dfsg1-2 amd64 [installed]
libsdl2-mixer-2.0-0/hirsute,now 2.0.4+dfsg1-3 amd64 [installed]
```

**Comment by HAMM3REXTREME** [comment]
Never Mind, I built v1.12.1 from source and sound and music does work now.

**Comment by Novum** [comment]
By prebuilt binaries you mean the appimage, right?

**Comment by billyboo6385** [comment]
I've got the same problem, the game plays with no problems but there's no sound whatsoever if you launch from the appimage. The windows version works as intended launched through wine, but I wish the appimage worked too since it loads much faster.

**Comment by HAMM3REXTREME** [comment]
> By prebuilt binaries you mean the appimage, right?

Yes

**Comment by Novum** [comment]
6e636ae65c4b8479b7ec5f6180b183f94fb39a11

I also updated the release AppImage. Should work now.
