### ISSUE TITLE
[Bug] Arcane Dimensions fails to load and crashes the engine

### ISSUE THREAD

**Issue by Vagankovo** [Novum/vkQuake#405]
## System info
OS - Arch Linux (rolling)
GPU - Radeon RX 5500M & AMD Renoir (integrated graphics)
Vulkan drivers - RADV (part of Mesa graphics libraries)
CPU - Ryzen 7 4800H with Radeon Graphics

vkquake version - latest git commit

## Bug
When attempting to load an Arcane Dimensions save for the first time you will be greeted with an error that an extension isn't active. Attempting to load a save again results in a segfault.

If one starts a new game, then the engine will run for a few seconds before crashing in a segfault as well.

## Reproduction
Attempt to load an AD save twice or create a new AD game

## Logs
Command line logs when trying to load save: [quake_crash.log](https://github.com/Novum/vkQuake/files/7644402/quake_crash.log)
I am unable to find the core dump.

**Comment by Novum** [comment]
I constantly test with AD. Are you sure this is not a local problem?

**Comment by Novum** [comment]
Probably fixed by 16582fe42fee8eef30c9bbccb44165b865a1f0db
