### ISSUE TITLE
Fails to load map horde2 in mg1.

### ISSUE THREAD

**Issue by EtherTyper** [Novum/vkQuake#407]
The map horde2 in mg1 from the latest version of the Quake rerelease fails to load with error `QUAKE ERROR: Texture thordetrime is not 16 aligned`.

**Comment by Novum** [comment]
I kind of have a hard time keeping those bugs open. It's hard to support a moving target that doesn't care about compatibility with the original engine.

**Comment by Novum** [comment]
Fixed this for good, any texture size will be supported.
24ceaa0db94d06fb5b879240ea18ba124d39abda

**Comment by Novum** [comment]
@sezero maybe something to consider for QuakeSpasm too

**Comment by sezero** [comment]
Is this a new update to rerelease or something? I can't find any map named horde* under mg1 in my copy.

**Comment by EtherTyper** [comment]
Yes, this map was added with "horde mode" in update 2 yesterday.

**Comment by sezero** [comment]
> @sezero maybe something to consider for QuakeSpasm too.

Do you have a backport patch?

**Comment by Novum** [comment]
I don't, but I can look at it over the weekend. I'm a bit concerned about the non power of two texture support in OpenGL. Probably need to detect it and if it's not available disable mips.

**Comment by sezero** [comment]
> I don't, but I can look at it over the weekend.

Thanks

> I'm a bit concerned about the non power of two texture support in OpenGL. Probably need to detect it and if it's not available disable mips.
> 
> Edit: Okay, there is already some NPOT detection code in QuakeSpasm. I'll take a look.

Yeah, there is NPOT detection.

We can try an stb_resize() the texture only if it isn't 16 aligned, but whatever you do is most welcome.

**Comment by andrei-drexler** [comment]
@sezero something like [this](https://github.com/andrei-drexler/quakespasm/commit/837c8e3428db4c36f47ede26c76a128da1022f2a) should be enough, I think.

**Comment by sezero** [comment]
> @sezero something like this should be enough, I think.

Thanks, will try shortly. Can any trouble be expected on non-NPOT-capable
hardware? (I don't have any such setup to try with.)

@ericwa: What do you think?

**Comment by Novum** [comment]
DX10 required full npot support, so cards newer than 15 years won't have that problem - although who knows what people run QuakeSpasm on.

**Comment by sezero** [comment]
Applied Andrei's patch (with added missing `\n` and also as plain `Con_Warning` not debug version.)
Also applied Andrei's sky texture size check.

**Comment by sezero** [comment]
> DX10 required full npot support, so cards newer than 15 years won't have that problem - although who knows what people run QuakeSpasm on.

Turns out one of my old netbooks with Intel gpu (running on WinXP)
doesn't support NPOT:
```
Video mode 1024x600x32 60Hz (24-bit z-buffer, 0x FSAA) initialized
GL_VENDOR: Intel
GL_RENDERER: Intel Pineview Platform
GL_VERSION: 1.4.0 - Build 7.15.10.5260
Warning: OpenGL version < 1.5, skipping ARB_vertex_buffer_object check
FOUND: ARB_multitexture
GL_MAX_TEXTURE_UNITS: 8
FOUND: ARB_texture_env_combine
FOUND: ARB_texture_env_add
Warning: vertical sync not supported (SDL_GL_GetAttribute failed)
FOUND: EXT_texture_filter_anisotropic
Warning: texture_non_power_of_two not supported
Warning: OpenGL version < 2, GLSL not available
Warning: GLSL gamma not available, using hardware gamma
Warning: GLSL alias model rendering not available, using Fitz renderer
Intel Display Adapter detected, enabling gl_clear
```
Copied the rerelease files to that machine, horde2 seems to run.

**Comment by andrei-drexler** [comment]
The problematic texture is a power-of-2 one anyway (256x8), and if it weren't it would be [resized](https://github.com/sezero/quakespasm/blob/9502aaff252ffa8c87bd340e78c905644a686b13/Quake/gl_texmgr.c#L1018-L1024) in `TexMgr_LoadImage32`, so there shouldn't be any issues at all.

**Comment by sponge** [comment]
> I kind of have a hard time keeping those bugs open. It's hard to support a moving target that doesn't care about compatibility with the original engine.

Hi! I'm one of the programmers at id on the port. If there are other features or weird things that aren't known how are implemented I can probably at least point you toward the right direction. I'm currently hanging out in the FTE and Quake Mapping Discords, and am also on twitter as mikerubits. Feel free to reach out if there are other issues. We aren't intentionally looking to lock out the new content from other engines. There are some things that we simply had to do differently to support stuff like localization and split screen, so remaining strictly compatible with vanilla wasn't an option.
