### ISSUE TITLE
[vkQuake 1.12.1] Error while loading new horde map

### ISSUE THREAD

**Issue by Riccardoman** [Novum/vkQuake#409]
![Screenshot (1431)](https://user-images.githubusercontent.com/74624503/144671912-228404b2-ea76-445f-9449-afbadcd83475.png)
The map is horde2.bsp from the new update of the quake rerelease
Also a very minor issue but still present, the text in dimension of the machine is displayed incorrectly

**Comment by andrei-drexler** [comment]
Already reported and fixed (#407 and #408).
