### ISSUE TITLE
[Feature request] Support for lightmapped liquid surfaces

### ISSUE THREAD

**Issue by bstordeur** [Novum/vkQuake#413]
Having lightmapped water surfaces in vkQuake would be really great, this feature has been available in the common compilers for ages now (-splitturb on qbsp in ericw tools), but unfortunately very few engines support it (only FTE and recent builds of QSS).

Fullbright water is a real bane for mappers, and we always have to mess around with hacky solutions so that it's not too visually glaring. Even on the id maps it looks quite good recompiled with it on (also helps the scrag be lit better as it's sampling the water surface instead of the floor at the bottom of the lake) : 
![litwater2](https://user-images.githubusercontent.com/5883104/147982921-efeb0c7e-96a4-47c1-8843-021413382871.gif)

I know Spike has it ready for regular QS ( https://github.com/Shpoike/Quakespasm/commit/88384bc3bf4541a9ff222311ceba9245906efdf0 ), but getting it straight into vkQ would be even cooler

Hopefully this isn't outside the scope of your vision for vkQ, to me it feels like one of those "new" features that would be adopted quickly and stay in the spirit of Quake (like distance fog, colored lighting and skyboxes). It's also an opt-in feature as only maps compiled with -splitturb will be affected.

**Comment by Novum** [comment]
Should be fine, I was wondering about this the other day.

**Comment by andrei-drexler** [comment]
Here's a small [test map](https://github.com/andrei-drexler/quakespasm/files/7815945/litwater.zip), in case it helps.

**Comment by Novum** [comment]
I think the change is trivial, just need to have an hour to do it.

**Comment by Novum** [comment]
7b2e0e70bb004998831271308ef89ad27eb17826
![image](https://user-images.githubusercontent.com/112222/148325379-ea40ddc6-059e-41a9-be56-b6ea45da3fb8.png)
