### ISSUE TITLE
[Feature request] Black frame insertion for motion blur reduction

### ISSUE THREAD

**Issue by apoketo** [Novum/vkQuake#420]
***It's easier if you just see it with your own eyes (needs to be viewed at least 90hz but preferably 120hz+)***
https://www.testufo.com/blackframes

#### Why? Because Quake being very fast and dark stands to benefit the most.

Two ways to solve motion blur:
1) Very high (480hz+) sample-and-hold displays (i.e LCD). These don't really exist yet and are hard to drive at 480fps+ (until "DLSS for frame rate" is invented).
2) Low persistence a.k.a strobed displays (i.e CRT and any VR display). Easier to drive but flickers at low refresh rates. Also makes uneven frame pacing more noticeable.

Some modern displays implement this in hardware (DyAc, ULMB, LightBoost, PureXP+, OLED Motion Pro) in various degrees of success. It's not a standard feature unfortunately. While LG's OLED TVs are known for having the best implementation currently (OLED response times and all), there's no mention of it in the upcoming 175hz OLED monitor from Alienware.

Luckily, via software, anyone can emulate a strobed display at half refresh rate:
120hz -> 60hz (***this will have less blur than plain 120hz!***)
144hz -> 72hz (sounds familiar)
240hz -> 120hz (flicker should no longer be visible here)
etc.

Current implementations:
RetroArch
GroovyMAME
Xash3D-strobe (Half-Life 1 source port, uses Strobe API)
StrobeAPI - C++ Library (includes LCD image retention mitigation) https://github.com/fuzun/strobe-api
Everything* but fullscreen exclusives https://github.com/fuzun/desktopbfi (*unreliable and certain apps seem to have an "always on top" behaviour)
Some media players/ffdshow+AviSynth

**Comment by Novum** [comment]
I think this should be done in an external tool, not on a per-app basis. Would be trivial to achieve with a Vulkan layer.

**Comment by Novum** [comment]
That's not my problem. They can write a Vulkan layer instead of using shitty hooks.
