### ISSUE TITLE
[Bug] Multiplayer colours don't seem to work in ProQuake servers?

### ISSUE THREAD

**Issue by KynikossDragonn** [Novum/vkQuake#422]
I saw there was a closed issue about this at #342 

But, while I was briefly testing 1.12.2 to see if I could connect to the server at "fvf.servequake.com", the game actually connects without issue, I can travel to the next map without issue, but my player's colour appears all white regardless of what I had set in the multiplayer setup screen.

The server at "fvf.servequake.com" is running "ProQuake Server Version 3.50" and protocol 15 is used.

My "_cl_color" cvar is set to "22", which as far as I can tell is supposed to match the colours of the original skin before any translation occurs on it to change the shirt/pants colour. All I can see actually on the player skins ingame is white/white though.

Perhaps this is a QSS bug? I don't get this issue in regular QuakeSpasm.

**Comment by Novum** [comment]
Would help if you could test QSS.

**Comment by temx** [comment]
704a17d
