### ISSUE TITLE
cannot set bit depth linux

### ISSUE THREAD

**Issue by CrezyDud** [Novum/vkQuake#443]
i want 8 bpp, but i cant change it, if a change the cvar, it resets back to 24
any way to change?
or is it not inteded?

(i haven't found a port that works on linux well and has so many settings to make it like vanilla quake, i just need this and i'd have vanillla quake asthetic)

**Comment by CrezyDud** [comment]
oh and also demos dont play in the menu, is that normal?

**Comment by Vagankovo** [comment]
Demos don't play by design: you can revert back to the original behaviour with `-fitz` command line option.

**Comment by mjr4077au** [comment]
> Demos don't play by design: you can revert back to the original behaviour with `-fitz` command line option.

I'd recommend against this as it will turn off all the z-fighting fixes as well.

**Comment by CrezyDud** [comment]
startdemos demo1.dem demo2.dem demo3.dem
demos

in autoexec works

**Comment by CrezyDud** [comment]
but i dont think they loop and i have to type demos again

**Comment by Novum** [comment]
Not supported right now. [Ironwail](https://github.com/andrei-drexler/ironwail) has something like this in the options.
