### ISSUE TITLE
[Bug] r_scale makes the screen blurrier, not pixelated.

### ISSUE THREAD

**Issue by Snoucher** [Novum/vkQuake#444]
When incrementing r_scale above 0, (for example r_scale 5) the game does not become pixelated as to be expected, but rather becomes a blurry mess that does not resemble a classic quake feel.

https://i.imgur.com/CjkMPgG.png

This image has r_scale 5 applied to it. Notice how blurry it is than without it (https://i.imgur.com/7H6zdO8.png)

And here's a reference to how it should be looking https://i.imgur.com/EVk0hSW.png

**Comment by Novum** [comment]
By design.
