### ISSUE TITLE
What kind of gl_texturemode does vkQuake use?

### ISSUE THREAD

**Issue by fragmental** [Novum/vkQuake#447]
I see that the gl_texturemode console/cfg command has been removed, and that there is an option to switch between classic or smooth in the video settings.  This is a nice addition.  But what gl_texturemode does this coincide with?  Is smooth gl_linear, gl_linear__mipmap_nearest, or gl_linear_mipmap_linear?  Is classic gl_nearest, gl_nearest_mipmap_nearest, or gl_nearest_mipmap_linear?  I prefer GL_Nearest_Mipmamp_Linear, personally.

**Comment by Novum** [comment]
Please don't open bugs that are not bugs. The options correspond to "linear mipmap linear" or "nearest mipmap linear".

**Comment by fragmental** [comment]
Thank you for the quick response, and thank you for vkQuake.  I'm sorry for creating this github issue.  I did a thorough search for an answer to my question, and couldn't find it.  I didn't know where else to ask.

Also, thank you for the quality of life improvements in the UI.  I usually add these lines to my autoexec.cfg:
`gl_texturemode GL_NEAREST_MIPMAP_LINEAR
r_particles 2
R_viewmodel_quake 1
sensitivity "2.25"
`
With your improvements, the only thing I'll need in my autoexec is my mouse sensitivity.
