### ISSUE TITLE
Alt+tabbing out and back into mods causes ctd

### ISSUE THREAD

**Issue by ZecChelovek** [Novum/vkQuake#448]
This is with the latest vkQuake. Arcane Dimensions, Drake, Violent Rumble, and Alkaline 1.1 will crash upon alt+tabbing out and back in. For some reason Quoth, Rogue, and Hipnotic do not have this issue. 

EDIT: This seems to be an issue solely on my end, but it is resolved by setting fullscreen to no.

**Comment by Novum** [comment]
Bug report is completely useless without any system information.
