### ISSUE TITLE
[Bug] -splitturb breaks liquid texture scaling

### ISSUE THREAD

**Issue by Osporonol** [Novum/vkQuake#449]
When playing a map compiled with -splitturb for lightmapped liquids, all liquid surfaces have their textures scaled incorrectly. Seems to be half of their intended scale.

You can even notice the problem in the [preview screenshot in the feature request](https://github.com/Novum/vkQuake/issues/413#issuecomment-1006262811). Water is normally "bigger" than that.

The problem doesn't occur in Iron Wail or QSS. Also doesn't occur if you compile without -splitturb.

**Comment by andrei-drexler** [comment]
Fixed in 3f5f449055e2bc8cd2e7e0ab52cf3b70e1a077a7.
