### ISSUE TITLE
Re-release Update Today Causes Text Not to Display

### ISSUE THREAD

**Issue by d10sfan** [Novum/vkQuake#453]
Quake on steam had an update today: https://steamdb.info/patchnotes/8507405/

After that, the text on-screen is no longer displaying. The most obvious example is the difficulty portals, where they normally display and make a sound, only the sound happens, not the text.

Attached is a log of it running:
[quake.log](https://github.com/Novum/vkQuake/files/8522900/quake.log)

**Comment by sezero** [comment]
Awesome, another one with breakage again.. Will try looking unless someone else beats me to it.

**Comment by andrei-drexler** [comment]
It looks like they changed the builtins to use id #0 (resolved by name)...

**Comment by sezero** [comment]
Indeed: https://store.steampowered.com/news/app/2310?emclan=103582791433474629&emgid=3177861894960065434

**Comment by sezero** [comment]
And the qc code is now open source (GPL), in case anyone hasn't noticed it: https://github.com/id-Software/quake-rerelease-qc

**Comment by andrei-drexler** [comment]
Fixed in 87b2e56cc21b33876ff678c6d9ee04dc033b939d.

**Comment by d10sfan** [comment]
Very nice, thanks for the quick turn around. Just tried the new build and worked great

**Comment by sezero** [comment]
This will need extra work to fix in mainstream qs (and ironwail, I guess.)

**Comment by andrei-drexler** [comment]
> Very nice, thanks for the quick turn around. Just tried the new build and worked great

Good to know, thanks! Luckily the code already had support for looking up builtins by name, so this was an easy fix.

---

> This will need extra work to fix in mainstream qs (and ironwail, I guess.)

...yup :(

**Comment by sezero** [comment]
For QuakeSpasm (and ironwail, by extension), I ended up with the attached
two patches: first is actually your patch from vkQuake, the second is an
update to it:  [0001-patch.txt](https://github.com/Novum/vkQuake/files/8525363/0001-patch.txt) , [0002-patch.txt](https://github.com/Novum/vkQuake/files/8525365/0002-patch.txt) .

The second also adds further builtins to the list (all unsupported, thus
forwarding to PF_Fixme), and adds a stub for the new CheckPlayerEXFlags().

Please review.

P.S.: We should actually implement a PF_localsound()..

**Comment by andrei-drexler** [comment]
Initially I went for the exact same approach, but since lookup by name seems to be the plan going forward, I thought it might be better to add some minimal support for it (removing the need for manual id remapping). This ends up a bit cleaner IMO.

**Comment by sezero** [comment]
Do you have a patch?

**Comment by andrei-drexler** [comment]
Still working on it. In the meantime I've also applied and tested the 2 patches from earlier in horde mode, and haven't noticed any issues. It looks like CheckPlayerEXFlags really is called, without it the server crashes on weapon pickup. Oddly enough, vkQuake doesn't seem to crash.

**Comment by sezero** [comment]
I applied my patches to QS for the time being so that things work. I'll apply any better solution whenever you make it available.

**Comment by sezero** [comment]
Applied this follow-up patch to qs: [0003-patch.txt](https://github.com/Novum/vkQuake/files/8529745/0003-patch.txt)

A good side effect of it is that it makes sure that the `ex_???` builtins' first_statement is actually 0.

**Comment by andrei-drexler** [comment]
That's pretty similar to [what I ended up doing](https://github.com/andrei-drexler/ironwail/commit/712f7387d5665244aeee7c2fdf61a87c79a93a7e), the main difference being that id's are assigned automatically for builtins that are looked up by name (a simplified version of the QSS/vkQuake method).

**Comment by sezero** [comment]
It seems to lack the check of ext builtin number being 0.

**Comment by andrei-drexler** [comment]
It's [there](https://github.com/andrei-drexler/ironwail/blob/712f7387d5665244aeee7c2fdf61a87c79a93a7e/Quake/pr_edict.c#L1234) (`func->first_statement` check).

**Comment by sezero** [comment]
Oops, my mistake. Will try re-reading again, and maybe I merge it into qs (or keep my version, don't know.)

**Comment by sezero** [comment]
OK, I will keep my solution in QS for the moment -- unless there is something broken and/or fragile with it.

I will later try and implement a PF_localsound.

**Comment by sezero** [comment]
> I will later try and implement a PF_localsound.

It seems like they got the idea from qbism's [super8](https://github.com/qbism/super8)?
It needs a `svc_localsound`, which is `48` in super8 --
anyone knows its value in 2021 re-release?

**Comment by andrei-drexler** [comment]
I don't think localsound is actually called anywhere, though. [Walkpathtogoal](https://github.com/id-Software/quake-rerelease-qc/blob/4a992dc9a38436d0b73eae380fd65325f7db833d/quakec/ai.qc#L616) on the other hand might need a stub.

**Comment by sezero** [comment]
> I don't think localsound is actually called anywhere, though.

Yes, not in 2021 qc, but mods may call it.. Found this documentation:
https://steamcommunity.com/sharedfiles/filedetails/?id=2679459726

**Comment by andrei-drexler** [comment]
> Which value should we return?

I think 0 (PATH_ERROR), since technically we never have any nav nodes available, and all the call sites seem to fall back to the old movetogoal if the return value is anything other than PATH_IN_PROGRESS.

> Yes, not in 2021 qc, but mods may call it

Mods that do should/will probably use pr_checkextension+checkextension ("QUAKE_EX") to determine if they're running under QuakeEX and have that builtin available.

**Comment by sezero** [comment]
Pushed stuff to qs git.

**Comment by sezero** [comment]
Added walkpathtogoal to vkquake, applied one or two other changes in qs too.

Other changes in QS, well there are too many whitespace changes and some other stuff (PF_localsound / svc_localsound) seem to conflict too much -- so I gave up immediately. If someone volunteers for syncing any necessary things with qs, be my guest.

**Comment by sezero** [comment]
Does update/4 have any issues with QS or vkQuake?
https://store.steampowered.com/news/app/2310/view/3337750462906016219

Haven't tried it yet, but looking at the official changelog, there doesn't
_seem_ to be any breaking changes.
