### ISSUE TITLE
[Bug] Every (other) time the game is minimized, the FPS gets capped to 63

### ISSUE THREAD

**Issue by RavenMacDaddy** [Novum/vkQuake#454]
Noticed when I had to do something else on the desktop and came back to the game that the FPS was being capped to 63, so I troubleshooted by trying to minimize and restore to see the behavior, and every other time, this would occur - so the first time that the game is minimized it happens, and then every other time since in between it will run uncapped (or whatever you've set it to externally).

**Comment by Novum** [comment]
Sorry, but this seems a problem with your system. There isn't any code which would cause this.

**Comment by RavenMacDaddy** [comment]
Understood, must be something related to Windows 11.

Closing in the meantime. 

Thank you.
