### ISSUE TITLE
r_gpulightmapupdate sometimes breaks bmodel lighting

### ISSUE THREAD

**Issue by d-bind** [Novum/vkQuake#457]
Seems to be a weird one, possibly related to entity order and texel area of things that aren't supposed to be lightmapped to begin with. Reverting https://github.com/Novum/vkQuake/commit/79f52b6bf72e06c59b673710f1764e099a220974 seems to fix the issue for me.

Here's a minimal reproduction example map: [gpu_lmap.zip](https://github.com/Novum/vkQuake/files/8567059/gpu_lmap.zip)
And how it looks on my end: 

https://user-images.githubusercontent.com/104466974/165397033-a77d92ea-93d1-4d56-a2ae-864ad1ee1ac4.mp4

The middle window is a func_wall. A trigger_hurt with significantly increased texture tiling hangs in the void. The trigger is placed first on the entity list. If I place it last, the map will work. If I decrease its UV tiling, the map will work. If I select the worldspawn room and decrease its UV tiling by half, the map will work.

A "real life" example is nbabs.bsp from Violent Rumble. The cell door lights that are supposed to switch from red to green on silver card pickup instead start yellow and remain yellow. Noclipping out of bounds seems to force a lightmap update (both on the cell doors and on the silver card platform). Also all bmodels ignore muzzle flashes and styled lights.

**Comment by Novum** [comment]
Should be fixed by d1f5850f5ad8f34765c7761e3854b2cbb3ad03ee

**Comment by d-bind** [comment]
Can confirm.
