### ISSUE TITLE
3 suggestions I have for VKQuake

### ISSUE THREAD

**Issue by CricetoYT** [Novum/vkQuake#462]
Apologies if stuff like this isn't allowed in the issues tab. (I also just created a Github account so as a side note, how/can I label this issue?)

1. Add options in the menu for enabling/disabling animation interpolation.
2. Add back the opening demos.
3. Add an option to disable mipmapping on textures. Sometimes this can be very distracting on floor textures.

You can add the first 2 by just putting a few lines in an autoexec but it would be nice to just _have_ them out of the box.

**Comment by Novum** [comment]
Not a bug, please put this under Discussions
