### ISSUE TITLE
2D Scaling in 1.13.1

### ISSUE THREAD

**Issue by dezo2** [Novum/vkQuake#465]
Don't like the new scr_relativescale so tried to set it to 0 and set all scaling scr_* cvars (con, menu, sbar, crosshair) to 3 manually in console. But on restart all scaling cvars are still somehow autoscaled to 3.744 (resolution is 2560x1440) even when scr_relativescale is 0 and other scr_relscale* cvars are 1. So right now I have to set all scaling cvars in autoexec.cfg, otherwise will never get the values I want.

BTW I don't really see a point of non-integer scaling for the 2D elements - it produces uneven line thickness in characters and I think I also saw some white artifacts around letters. I suggest to add a possibility to autoscale 2D elements to the nearest integer (cvar scr_roundscale 0/1 or something like that).

**Comment by Novum** [comment]
This is pretty much what all modern games do including the Quake re-release and I don't intend to scale to just power of two. People can adjust if it really bothers them.

**Comment by dezo2** [comment]
Thats what I wanted to do - adjust it, but it is bugged right now as I wrote above. And why do you think I use vkQuake instead of the rerelease? They screwed the GUI in the rerelease with everything huge as f.ck and no way to adjust it (well, you can adjust scaling in the console, but only for part of the hud, not menus and messages). And don't let me started about the moving "interpolation" full of stuttering they did for refresh rates above 60Hz, input lag etc...

Anyway I am glad that vkQuake is being activelly developed - at least I can adjust things in it (so far). Please don't remove those scaling cvars in the end to make it even more "modern". Btw one more suggestion - what if all the textures/fonts could be (optionally) prescaled with integer factor 2x, 3x etc. and then scaled with bilinear filter to fit the autoscale? It will still look pixelated but without any artifacts - like they added to GZDoom (Full Options -> Display -> Textures -> High quality scaling/NormalNx).

**Comment by Novum** [comment]
Ok, thank you for your opinion. You are free to fork, it's GPL2.
