### ISSUE TITLE
Arcane Dimensions fireball/rocket trail particles are vanilla

### ISSUE THREAD

**Issue by Osporonol** [Novum/vkQuake#466]
QSS:
![spasm](https://user-images.githubusercontent.com/60247009/168694933-2d1e953a-49f0-4467-83b4-02a00e3d435d.png)

vkQ:
![vkquake](https://user-images.githubusercontent.com/60247009/168694958-6c752d08-a3c9-4c63-9e5d-ee6de3b0584f.png)

**Comment by Novum** [comment]
Interesting observation, probably some missing QC hook.

**Comment by temx** [comment]
Brought support in https://github.com/Novum/vkQuake/commit/917f4ed7f37eeffd4ed2b4111c8e641c8d9d2a13

**Comment by bubbleguuum** [comment]
These AD trail/particle incurs a big performance hit on my laptop's Quadro P600 (low end Pascal card, similar to the more common MX 250): firing rockets/grenade repeatedly can cause framerate to drop up to 50%, making the framerate very unstable.
I checked on latest QSS and there is also a similar performance drop.
Is there a toggle to use vanilla particle (which incurs almost no performance drop) ?

**Comment by Novum** [comment]
There is even a menu setting for this?
