### ISSUE TITLE
Compatibility with Slayer's Testament needed

### ISSUE THREAD

**Issue by AndryGoldmann** [Novum/vkQuake#468]

**Comment by AndryGoldmann** [comment]
Tried to run this Quake TC mod and... this is what happened

![sterror](https://user-images.githubusercontent.com/65863291/168929841-edefd276-5ba8-4da6-a057-bbb25931cd7f.PNG)

**Comment by temx** [comment]
It looks like [this](https://github.com/Shpoike/Quakespasm/commit/9058a4fadb8dbc4a173c0284d00d830f21a614f3) is enough to make it load.

**Comment by Novum** [comment]
@temx We probably should cherry pick that commit

**Comment by temx** [comment]
I merged it with a compatibility warning, just in case somebody accidentally uses it outside the particle system.
That said there are still issues (incl. maps not loading such as st3m2), but that's common to other non-QSS/FTE engines.

**Comment by Novum** [comment]
I think the mod author does some really nasty things in QC that assume the engine is specifically QuakeSpasm.

**Comment by sezero** [comment]
> I think the mod author does some really nasty things in QC that assume the engine is specifically QuakeSpasm.

That would be QSS I guess: The mod is unplayable in QS, because you eventually
hit the `Bad builtin call number 335` error with `particleeffectnum` whenever a lost soul
appears, and its known to them but they don't care.

**Comment by Novum** [comment]
I'm closing this, it's basically impossible to deal with this sort of mod.
