### ISSUE TITLE
Audio popping/crackling with version 1.13.1

### ISSUE THREAD

**Issue by zenxero** [Novum/vkQuake#469]
Hi, I noticed that there was some strange audio popping/crackling in the new 1.13.1 version that was not there in the previous version. This seems to happen with sound effects and is most noticeable with the axe "ting" effect and the nailgun firing sound.

As a test, I tried a fresh download and extraction of versions 1.13.0 and 1.13.1 with no external music loaded, no mods, only the `PAK0` and `PAK1` files under the `id1` directory. All audio settings were left at defaults.

Here's a video demonstration with audio that has the crackling:

https://www.youtube.com/watch?v=oGWM9bWph2A

00:00 - Version 1.13.0 with no audio crackling
02:10 - Version 1.13.1 with audio crackling
04:20 - Lowering the game volume doesn't seem to make a difference

You can hear the direct difference most easily from the axe "tings" at timestamps 0:30 and 2:43.

**Comment by sezero** [comment]
Do you think it's related to this SDL2-2.0.22 change?
https://github.com/libsdl-org/SDL/commit/9e264b921b2f81e2c3d55693f76e06d143c2fbb7
Reference issue: https://github.com/libsdl-org/SDL/issues/5538 (also see https://github.com/libsdl-org/SDL/pull/5540)

**Comment by zenxero** [comment]
I tested this on my laptop as well and it exhibits the same behavior. My desktop has an AMD X570 series motherboard with a Realtek audio chip. However, I'm using a USB DAC audio interface instead of the regular audio jack. But the popping still happens over the USB interface as well.

Desktop audio:
![Screenshot 2022-05-18 111729](https://user-images.githubusercontent.com/87404368/169117008-d3e9093d-5e8e-4e28-b5ec-a8550c51b69c.png)


My laptop is also an AMD-based system with a Realtek audio chip. I tested it with some basic earbuds plugged into the audio jack and it has the popping on version 1.13.1. But replacing the `SDL2.dll` file fixes it there as well.

Laptop audio:

![Screenshot 2022-05-18 111627](https://user-images.githubusercontent.com/87404368/169117039-146eece1-5f48-441c-b65a-a9baffed952d.png)

**Comment by zenxero** [comment]
That SDL file (I used the 64-bit one), paired with 1.13.1 sounds fine. No popping or crackling.

**Comment by sezero** [comment]
So 2.0.22 has the issue -- possibly due to the change I mentioned [above](https://github.com/Novum/vkQuake/issues/469#issuecomment-1130310076)?

**Comment by zenxero** [comment]
Seems plausible. Unfortunately, I'm no developer so I can't really comment on such things.

**Comment by Riccardoman** [comment]
I'm experiencing the same issue

**Comment by zenxero** [comment]
@Riccardoman 

Seems like the solution for the moment is to either use the `SDL2.dll` file that came with version 1.13.0, or download it from the link below and put it into the vkQuake directory.

http://libsdl.org/release/SDL2-2.0.20-win32-x64.zip

**Comment by Novum** [comment]
@sezero Where are we with this? Should we revert to 2.0.21 in the meantime?

**Comment by sezero** [comment]
> @sezero Where are we with this? Should we revert to 2.0.21 in the meantime?

Waiting for @icculus' response for the time being.

**Comment by sezero** [comment]
Can you reproduce the issue, btw?

**Comment by zenxero** [comment]
Ok, so I tested vkQuake 1.13.1 on the Steam Deck (Linux) and it does NOT have the audio crackling or popping issue that my Windows machines have.

**Comment by zenxero** [comment]
Ah, well now I feel stupid. Turns out if I force my audio device to use 44100 Hz instead of 48000 Hz, the popping/crackling goes away. I'm sorry for the trouble, this seems to have solved the issue.

@Riccardoman Is your audio device set to use 48000 Hz in the Windows sound settings? If so, try setting it to 44100 Hz instead.

**Comment by icculus** [comment]
So this is an SDL issue, and we're working on it, but this vkQuake bug can probably be closed.

**Comment by Novum** [comment]
Thanks @icculus
