### ISSUE TITLE
scr_sbarscale scr_menuscale dont seem to do anything.

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#471]
They can only be effected by the inbuild menu option. As of latest archlinux build i am receiving this error.

**Comment by dezo2** [comment]
You have now to set scr_relativescale to zero before you interact with those cvars.
It is described in 1.13.1 changes (also see #465).

**Comment by LethalManBoob** [comment]
> You have now to set scr_relativescale to zero before you interact with those cvars. It is described in 1.13.1 changes (also see #465).

Thank you.
