### ISSUE TITLE
Some textures don't draw beyond a certain distance

### ISSUE THREAD

**Issue by Vagankovo** [Novum/vkQuake#472]
## System specifications
OS - Arch Linux (rolling)
GPU - Radeon RX 5500M & AMD Renoir (integrated graphics)
Vulkan drivers - RADV (part of Mesa graphics libraries)
CPU - Ryzen 7 4800H with Radeon Graphics

vkquake version - latest git commit

## Description
Cobblestone floor texture near the bridge on `sm217_shades` doesn't draw beyond a certain distance:

![Screenshot from 2022-05-21 14-12-26](https://user-images.githubusercontent.com/90520453/169667815-b630a59b-732e-42dc-83d1-1f9daf3f9881.png)

![Screenshot from 2022-05-21 14-12-29](https://user-images.githubusercontent.com/90520453/169667819-9dd0bf49-6b71-4af1-990f-6bc3cd9aa4d6.png)

**Comment by andrei-drexler** [comment]
The disappearing texture is part of a bmodel that's very close to the surface below it. which interferes with the built-in fix for the z-fighting in the id1 maps. You can use `gl_zfix 0` to disable that. The same issue is present in the Kex port (which also has a built-in z-fighting fix), except it's much more severe there:
![20220522022548_1](https://user-images.githubusercontent.com/5121829/169672257-94abdf2c-b241-483d-9684-c891c1b0bd9d.jpg)
It *might* be possible to further lower the slope bias factor enough to minimize this particular issue, but that might also make the fix less effective when it's actually needed. I'd say that having surfaces that close to one another is probably not a good idea in general, though.

**Comment by Novum** [comment]
won't fix
