### ISSUE TITLE
Windows build failure

### ISSUE THREAD

**Issue by alexey-lysiuk** [Novum/vkQuake#474]
Since 308a28b26906404bf459a80053388085a8d1d26d, Windows build fails with the following errors:
```
Quake\gl_sky.c(683,44): error C2057: expected constant expression [Windows\VisualStudio\vkquake.vcxproj]
Quake\gl_sky.c(683,87): error C2466: cannot allocate an array of constant size 0 [Windows\VisualStudio\vkquake.vcxproj]
Quake\gl_sky.c(683,14): error C2133: 'poly_storage': unknown size [Windows\VisualStudio\vkquake.vcxproj]
```
[This is failed build](https://github.com/alexey-lysiuk/vkQuake/runs/6636826947?check_suite_focus=true#step:4:150), and [this one is successful](https://github.com/alexey-lysiuk/vkQuake/runs/6636860667?check_suite_focus=true), with the given commit reverted.

Variable length arrays are still not supported by Visual Studio, probably because of being optional feature of C11.

**Comment by Novum** [comment]
I know.
