### ISSUE TITLE
copper:   crash in start map

### ISSUE THREAD

**Issue by j4reporting** [Novum/vkQuake#475]
game crashes when going through a portal to play  one of the original Quake episodes

win64   latest git version   happens with  binaries compiled with VS2022  and  mingw64 (msys2)
works with vkQuake  1.13.1

**Comment by Novum** [comment]
I can't reproduce. Do you have a callstack?

**Comment by andrey-budko** [comment]
mingw, gcc 11.2:

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff6c6e37646 in SCR_DrawNotifyString ()
(gdb) bt
#0  0x00007ff6c6e37646 in SCR_DrawNotifyString ()
#1  0x00007ff6c6e37949 in SCR_UpdateScreen.part.0 ()
#2  0x00007ff6c6ea1a69 in _Host_Frame ()
#3  0x00007ff6c6ed04d8 in SDL_main ()
#4  0x00007ff6c6ed1bdd in main_getcmdline ()
#5  0x0000000000000000 in ?? ()

**Comment by j4reporting** [comment]
commit  1bc98cd7c72a5cc7a39c81564549013d49c132fd  seems to have fixed this issue when binaries are compiled with VS2022. Binaries built with mingw  crash in vanilla ID1  when player begins to move.

**Comment by Novum** [comment]
Ok yeah that seems like the error. I got crashes on load too before sporadically.
