### ISSUE TITLE
QUAKE ERROR: Hunk_Alloc:

### ISSUE THREAD

**Issue by mrturcot** [Novum/vkQuake#488]
Compiled currect master branch & getting this error doing anything in game, it just crashes.

```
ERROR-OUT BEGIN

Shutting down SDL sound

QUAKE ERROR: Hunk_Alloc: failed on 1048608 bytes


```
./vkquake 
Command line: ./vkquake
Found SDL version 2.0.20
Detected 16 CPUs.
Built with GCC 11.3.0
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.94.5 (c) Ozkan Sezer, Eric Wasylishen & others
QuakeSpasm-Spiked (c) Spike
vkQuake 1.20.0 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP4 Initialized
UDPv6 Initialized
Server using protocol 999+ (FTE-RMQ)
Exe: 00:17:39 Jun 18 2022
384.0 megabyte heap

Vulkan Initialization
Using Vulkan 1.1
Using VK_KHR_surface
Using VK_KHR_xlib_surface
Using VK_KHR_get_surface_capabilities2
Using VK_KHR_get_physical_device_properties2
Vendor: AMD
Device: AMD RADV POLARIS10
Using subgroup operations
Using VK_KHR_swapchain
Using VK_KHR_get_memory_requirements2
Using VK_KHR_dedicated_allocation
Using VK_EXT_subgroup_size_control
Using A2B10G10R10 color buffer format
Using D32_S8 depth buffer format
Creating command buffers
Initializing staging
Creating descriptor set layouts
Reallocating dynamic VBs (256 KB)
Reallocating dynamic IBs (1024 KB)
Reallocating dynamic UBs (256 KB)
Initializing samplers
Texture lod bias: 0.000000
Creating pipeline layouts
Using IMMEDIATE present mode
Creating color buffer
AA disabled
Creating depth buffer
Creating render passes
Creating frame buffers
Creating pipelines
Allocating lightstyles buffer (0 KB)
Allocating lights buffer (4 KB)

Sound Initialization
SDL audio spec  : 44100 Hz, 1024 samples, 2 channels
SDL audio driver: pulseaudio - Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] Digital Stereo (HDMI 5), 65536 bytes buffer
Audio: 16 bit, stereo, 44100 Hz
CDAudio disabled at compile time

Language initialization
Couldn't load 'localization/loc_english.txt'
from '/home/mrturcot/stuff/github/test/vkQuake/Quake'

========= Quake Initialized =========

execing quake.rc
execing default.cfg
couldn't exec config.cfg
couldn't exec autoexec.cfg
3 demo(s) in loop
Playing demo from demo1.dem.

the Necropolis
Using protocol 15
Allocating lightmap compute surface data (332 KB)
You got the shells
You got the Grenade Launcher
Reallocating dynamic VBs (512 KB)
Using IMMEDIATE present mode
Creating color buffer
AA disabled
Creating depth buffer
Creating render passes
Creating frame buffers
Creating pipelines
Initializing samplers
Texture lod bias: 0.000000

ERROR-OUT BEGIN

Shutting down SDL sound

QUAKE ERROR: Hunk_Alloc: failed on 1048608 bytes
```

**Comment by Novum** [comment]
Memory management has known issues currently. I'm working on it. Try launching with `r_tasks 0` in the cfg file and see if it helps.

**Comment by Novum** [comment]
85d526cc297b446d7b03d0415776d700ac2ac353
