### ISSUE TITLE
Cannot bind CAPS LOCK

### ISSUE THREAD

**Issue by daftmugi** [Novum/vkQuake#489]
I cannot bind CAPS LOCK.

I think this is a universal Quake engine issue, though.

The scenario is that I'm using vkQuake on Linux and have `XKBOPTIONS="ctrl:nocaps"` with the intention of using CAPS LOCK as CTRL. Most apps see the CAPS LOCK as a CTRL key, but vkQuake does not. Other games have this issue as well -- seeing CAPS LOCK as CAPS LOCK instead of CTRL -- but those games allow binding CAPS LOCK.

Is there anything I can do to make binding CAPS LOCK possible in vkQuake?

**Comment by daftmugi** [comment]
Quick update.

https://github.com/Novum/vkQuake/blob/009c959064faf3c0d87beb0fd01f3c5bcbdd7195/Quake/in_sdl.c#L763

I added two lines:
```diff
        case SDL_SCANCODE_LCTRL:
                return K_CTRL;
+       case SDL_SCANCODE_CAPSLOCK:
+               return K_CTRL;
        case SDL_SCANCODE_RCTRL:
                return K_CTRL;
```

That gave me behavior that is close enough for now. When I bind CTRL in vkQuake, CAPS LOCK acts as CTRL.

**Comment by Novum** [comment]
Why not. 8bfb38e34e8890005b83bbb4aa841315fd05bddf

I would find it way to annoying because it also still changes your keyboards capslock state, but you do you.

**Comment by daftmugi** [comment]
Your patch looks like the way to go. Thanks! Above, I did the quickest change that would work for me in limited time without familiarity with the codebase, but your change is how it should be done. I appreciate it!

With `XKBOPTIONS="ctrl:nocaps"` set my caps lock key acts like ctrl without the light indicator and without upcasing. With your patch, I can bind CAPSLOCK now and it works as expected in vkQuake! In other words, caps lock is now another bindable key without any other weird behavior.
