### ISSUE TITLE
Cant boot vkquake as of latest git on archlinux

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#493]
[joseph@archlinux ~]$ vkquake
Command line: vkquake
Found SDL version 2.0.22
Detected 16 CPUs.
Built with GCC 12.1.0
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.94.5 (c) Ozkan Sezer, Eric Wasylishen & others
QuakeSpasm-Spiked (c) Spike
vkQuake 1.20.0 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP4 Initialized
UDPv6 Initialized
Server using protocol 999+ (FTE-RMQ)
Exe: 12:26:57 Jun 26 2022

Vulkan Initialization
Using Vulkan 1.1
Using VK_KHR_surface
Using VK_KHR_xlib_surface
Using VK_KHR_get_surface_capabilities2
Using VK_KHR_get_physical_device_properties2
Vendor: NVIDIA
Device: NVIDIA GeForce RTX 3070
Using subgroup operations
Using VK_KHR_swapchain
Using VK_KHR_get_memory_requirements2
Using VK_KHR_dedicated_allocation
Using VK_EXT_subgroup_size_control
Using A2B10G10R10 color buffer format
Using D32_S8 depth buffer format
Creating command buffers
Initializing staging
Creating descriptor set layouts
Reallocating dynamic VBs (256 KB)
Reallocating dynamic IBs (1024 KB)
Reallocating dynamic UBs (256 KB)
Initializing samplers
Texture lod bias: 0.000000
Creating pipeline layouts
Using IMMEDIATE present mode
Creating color buffer
AA disabled
Creating depth buffer
Creating render passes
Creating frame buffers
Creating pipelines
Allocating lightstyles buffer (0 KB)
Allocating lights buffer (4 KB)

Sound Initialization
SDL audio spec  : 44100 Hz, 1024 samples, 2 channels
SDL audio driver: pulseaudio - Sound Blaster X7 Analog Stereo, 65536 bytes buffer
Audio: 16 bit, stereo, 44100 Hz
CDAudio disabled at compile time

Language initialization
Couldn't load 'localization/loc_english.txt'
from '/home/joseph'

========= Quake Initialized =========

execing quake.rc
execing default.cfg
Segmentation fault (core dumped)
[joseph@archlinux ~]$

**Comment by LethalManBoob** [comment]
the non -git vkquake on the aur wont compile anymore. i use paru so its 100% the packages fault

**Comment by Novum** [comment]
Insufficient data to act on. I need a call stack from a debugger.

I don't care if some third party packaging does not compile, talk to the maintainer.

**Comment by micwoj92** [comment]
> I don't care if some third party packaging does not compile, talk to the maintainer.

Hello, it turns out the culplit was using -march=native, but this is not set in Makefile so I don't know if this is worth making another bug report here.

**Comment by sezero** [comment]
`-march=native` should not be responsible for a core dump. If you'd provide a stack trace, maybe people can help with it.

**Comment by micwoj92** [comment]
Sorry, I only meant that build failure mentioned in https://github.com/Novum/vkQuake/issues/493#issuecomment-1166518124

**Comment by LethalManBoob** [comment]
Turns out somthing in my makepkg.cfg was munted
I am not sure what but getting a fresh copy fixed everything. you can
ignore me now :P

**Comment by Novum** [comment]
Default build is now meson + ninja f9df8516d3027da854186c74d36243f2d11cb8ad

This should avoid stale builds in the future.

**Comment by micwoj92** [comment]
Do you plan to deprecate makefile in future?

**Comment by Novum** [comment]
It is already deprecated and that is stated in `readme.md`
