### ISSUE TITLE
Handle CSQC crashes

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#495]
As per discussion here https://github.com/Novum/vkQuake/commit/a9cc376f0d191ed63d6671ba3a539f8fea3089ee:
> Well, if `Host_Error ()` was reached the `longjmp` was happening one way or another (with tasks, it'd crash; without it'd hang).
> This is hit if you create an Arcane Dimensions deathmatch game from the menu (e.g. `vkQuake -game ad +deathmatch 1 +viewsize 100 +map start`)

The longjmp solution right now is not going to work with tasks, need to find a better way

**Comment by Novum** [comment]
I tried and somehow this doesn't crash. No idea, my debugger can't even follow the longjmp.

But I went ahead and just implemented the missing QC extension e79378e32ed5279664e3c55fb64778499000227e

**Comment by temx** [comment]
Sorry I wasn't clear - it crashed before https://github.com/Novum/vkQuake/commit/a9cc376f0d191ed63d6671ba3a539f8fea3089ee as it used the main `host_abortserver` jump, which is set from the main thread but was called from a worker (and even with no tasks, you had the problem of aborting while `in_update_screen`). After a9cc376 there's a new, second `screen_error` jmp_buf in `SCR_DrawGUI` for CSQC exclusively, so as long as there's a single task calling that it should be OK.
