### ISSUE TITLE
Add alpha test support commit breaks open source vulkan drivers

### ISSUE THREAD

**Issue by vrodic** [Novum/vkQuake#50]
We currently have two open source vulkan drivers, one better known is in mainline mesa for intel GPUs. The other is radv from Dave Airlie for Radeon Tonga and Fiji (http://airlied.livejournal.com/81460.html). They share some common infrastructure. 

The Intel one worked good on vkQuake prior to the commit https://github.com/Novum/vkQuake/commit/cb1f468b320ee756a51db29887cd46969d004887

and Radeon one did too (except for the weapons not being show for some reason, but that's another issue). With the mentioned commit parts of the game render black like this
![image](https://cloud.githubusercontent.com/assets/368968/17460835/f3fd48ce-5c76-11e6-8984-93d1858e98cb.png)

I know this is a driver issue, but I'm hoping someone could shed light on why it breaks like this so we can maybe get the drivers fixed. 

(the latest versions break because there is no support for InputAttachment in the open source vulkan code, but that's another issue too)

**Comment by Novum** [comment]
My bet is on the specialization constants. Otherwise the changelist looks pretty innocent.

**Comment by vrodic** [comment]
You are right, when replace 
```glsl
if (use_alpha_test && out_frag_color.a < 0.666f)		
```
with 
```glsl
if (true && out_frag_color.a < 0.666f)
```
in world.frag the problem goes away on both Intel and Radeon

**Comment by vrodic** [comment]
You are right, if I replace

```glsl
if (use_alpha_test && out_frag_color.a < 0.666f)
``` 
with 
```glsl
if (true && out_frag_color.a < 0.666f)
```
in world.frag then the problem goes away on both Radeon and Intel

**Comment by Novum** [comment]
Driver issue.

**Comment by vrodic** [comment]
Reported bug upstream here: https://bugs.freedesktop.org/show_bug.cgi?id=97233
