### ISSUE TITLE
menu glitches after quitting mods on 1.20 if basedir is a different folder than vkquake's

### ISSUE THREAD

**Issue by ianharmon** [Novum/vkQuake#502]
Experienced on Windows 10. If I run vkquake from a separate directory as my quake basedir, e.g. `D:\vkquake\vkQuake.exe -basedir D:\quake -game dopa` and then select Quit from the menu and then open the menu again, the menu graphics glitch, usually like this:

![vkquake0000](https://user-images.githubusercontent.com/43733064/176322450-65840198-a8ec-4ce4-b950-ff244a45ac2b.jpg)

(this also happens if I pass `-game id1`)

However, if vkquake is in the same folder as the basedir, this issue doesn't happen.

**Comment by ianharmon** [comment]
Most mods result in the same glitched appearance, but I noticed quitting Alkaline 1.1 (which has a custom sidebar, menu font, etc) results in the menu being invisible instead:

![vkquake0001](https://user-images.githubusercontent.com/43733064/176323506-f8ceefff-f883-4bc2-90a8-e6c5da0988d3.jpg)

But the Alkaline Jam, which does the same customizations, shows the same as in the first screenshot.

**Comment by Novum** [comment]
Is the updated `vkquake.pak` in the directory basedir points to?

**Comment by Novum** [comment]
This has already been fixed by @temx 5130ab7432cfb74ec9b258d5776459c2aee8d6e3
