### ISSUE TITLE
Random deadlock on Linux/X11

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#504]
I get very low repro rate random deadlocks in e.g. `alk_dancing` on a RTX 3080 on Ubuntu 22.04, driver 515.48.

`Task_Join` is hanging in `SCR_UpdateScreen` waiting for `draw_done_task`. Might be a problem exposed by the Linux driver or by aggressive compiler optimizations.

77a883a6d6fbdb322654a1354c0781a8c1080642 was an attempted fix, but didn't actually fix it.

**Comment by Novum** [comment]
I have been unsuccessful reproducing this on Windows with [cuzz](https://www.microsoft.com/en-us/research/project/cuzz-concurrency-fuzzing/)

**Comment by sezero** [comment]
Maybe ThreadSanitizer (tsan) can help? (I can't be of help myself - one of my linux setups doesn't support vulkan, the other is a very old one where vkquake core dumps at start.)

**Comment by Novum** [comment]
I tried tsan and it just gets completely confused because of how the task processor works.

**Comment by Novum** [comment]
So it's actually just hanging on `vkWaitForFences` in `GL_BeginRenderingTask` which then causes the task to never complete, hence `Task_Join` waiting forever.

**Comment by sezero** [comment]
Is `current_cb_index` thread-safe?

**Comment by Novum** [comment]
Yes, all rendering is executed between `GL_BeginRenderingTask` and `GL_EndRenderingTask` and there is no overlap between those two.

**Comment by Novum** [comment]
And my intuition was correct c90eda2e43473b71fea55fcb409ad557efa78aa4

**Comment by Novum** [comment]
Third time is the charm: ecfe0851b23ab1168eb34000389b5547c20948f5

Argh.
