### ISSUE TITLE
[Feature request] QSS advanced particle nearest neighbour filtering

### ISSUE THREAD

**Issue by BreakPoints** [Novum/vkQuake#505]
I play with classic texture filtering and particles but the advanced particle system still uses a bilinear filter which mismatches the style of the rest of the game.

I propose that the "classic" particle option should also swap the advanced particle system to nearest neighbour filtering. I believe this is already an option in QSS.

**Comment by Novum** [comment]
I don't think this is the case?

**Comment by Novum** [comment]
Okay, so it currently respects what the particle system author requested and then sets TEXPREF_LINEAR which causes it to use linear filtering. Guess I could override that if "classic" is selected in the menu.

**Comment by BreakPoints** [comment]
Ah, it's likely an earlier version of AD didn't request a filter back when I was using QSS.

I personally would love an easy way to override it and a separate option might just be clutter for a niche option. Is it a safe assumption that someone who wants square Quake particles would also want square/pixelated advanced particles?

**Comment by Novum** [comment]
So I actually tried this and I have no idea what you mean by "swap the advanced particles to nearest neighbor". I can do that, but the difference is imperceptible because the textures are so high res.

E.g. this is with point sampling:
![vkquake0003](https://user-images.githubusercontent.com/112222/176844912-41651bc4-63a5-461d-bd68-c1b465734236.png)

**Comment by BreakPoints** [comment]
Maybe my terminology is causing confusion, nearest neighbour filtering, point sampling and no filtering are sometimes used interchangeably. I mean for the advanced particles to stay sharp and pixelated when scaled, to match the other textures when the "texture" setting is set to "classic".

At a distance, it's not going to make as much of a difference, yeah. When particles are close to the screen such as shooting something up close or walking through a mist it's much more apparent:

![Screenshot 2022-07-01 140528](https://user-images.githubusercontent.com/11966090/176900666-fa4c0913-8d85-49e9-a48f-5e7a89ef5094.jpg)
![Screenshot 2022-07-01 140609](https://user-images.githubusercontent.com/11966090/176900682-bc2a7e74-8357-4104-938a-585fc7da6b0a.jpg)

**Comment by temx** [comment]
There's a slight difference if you stick your face close enough (albeit in motion it's a lot subtler - practically you can't even tell):
![](https://user-images.githubusercontent.com/24851409/176904784-736f2e22-9c1a-4ec9-8ebd-f3b2462fa99d.png)
![](https://user-images.githubusercontent.com/24851409/176904790-615ea8f4-d215-4d44-9491-c5311e3f1933.png)
Grenade trails have a larger visual difference:
![](https://user-images.githubusercontent.com/24851409/176904933-dfafe94a-9f73-453c-a608-6d44812829ea.png)
But I'm not sure, AD's particles don't seem to be designed around this.

**Comment by Novum** [comment]
The fix is trivial, so I'll probably do it, but I still don't really see the point

**Comment by BreakPoints** [comment]
It would be greatly appreciated. It's the last smooth/blurry looking thing in a game which I strongly prefer the sharp, crunchy look of the unfiltered art. It's not something I can unnotice.

**Comment by Novum** [comment]
6a8a467b583d23e28bc91b14b78224dd7ced5494
