### ISSUE TITLE
Missed FTE Particles ON/OFF Video Options entry?

### ISSUE THREAD

**Issue by andrey-budko** [Novum/vkQuake#506]
![image](https://user-images.githubusercontent.com/6490190/176784152-f9ba9ca4-56e6-4276-8490-d338e5c39201.png)

**Comment by Novum** [comment]
Can you please rephrase what the issue is?

**Comment by andrey-budko** [comment]
You can put cursor on an empty line between "Particles" and "Test changes" entries and it will react to Left/Right/Enter keys with sound. Looks like missed menu entry and handler for VID_OPT_FTE_PARTICLES

**Comment by Novum** [comment]
huh, okay, that's weird.

**Comment by Novum** [comment]
ecce2d573311d4e64406079d7d355f0143ff212e
