### ISSUE TITLE
Couldn't create Vulkan device

### ISSUE THREAD

**Issue by sezero** [Novum/vkQuake#511]
Getting this error on windows x64 with a mingw build from git/master.

**Comment by sezero** [comment]
This is with Nvidia 398.26 drivers.

**Comment by sezero** [comment]
If I remove `VK_KHR_driver_properties` commits e06a5bab00c351db4b57c4200f7d2d4b8769733f and its follow-up b73a07e0497586169a0d658c1136158697f98840, then it works.

**Comment by sezero** [comment]
Seems to be fixed by https://github.com/Novum/vkQuake/commit/33fa35689d7a066b00d856b8da8a5f41c38ab048

**Comment by Novum** [comment]
Good to know it runs on a 4 year old driver to begin with ;)
