### ISSUE TITLE
[bug?] In palettised mode the colours should be applied per texel

### ISSUE THREAD

**Issue by theptoing** [Novum/vkQuake#517]
In the original software Quake versions the lightmap never bisects a texture pixel, meaning any given texel can only be 1 of the 256 indices. This actually makes the lighting look a lot more integrated with the textures (and imo it would be nice to have a feature that allowed to toggle this on and off even in 24 bit lighting mode, namely because of the added coherency of the resulting texture+light)

**Comment by Novum** [comment]
It's way more complicated to implement, but technically this is true.

**Comment by temx** [comment]
Since textures and lightmaps are aligned (and lightmaps are 1/16 of the texture size), the quick and dirty way to do this is just quantize the lightmap coordinates in the world frag shader:

```
	ivec2 lm_size = textureSize(lightmap_tex, 0).xy;
	vec2 uv_exp = floor(lm_size * in_texcoords.zw * 16) / 16 / lm_size;
	vec3 light = texture(lightmap_tex, uv_exp).rgb * 2.0f;
```

**Comment by Novum** [comment]
2e29b2a01db9aae0bd74b02c378f9cd43d575f11 mostly addressed this, thanks @temx 

Fog will still cause it to go wrong, but I think this is acceptable.
