### ISSUE TITLE
CMDLINES was increased from 32 to 64, but actual lines count limit for history.txt is still 32

### ISSUE THREAD

**Issue by andrey-budko** [Novum/vkQuake#519]
need to replace 31 with (CMDLINES - 1) in keys.c

https://pastebin.com/1LL3peG4

**Comment by Novum** [comment]
Nice catch, ebc920d9a59caf4c92332bef18d06c77a66133e5

**Comment by andrey-budko** [comment]
@Novum Why did you apply only part of the fix? Up/Down/Right keys in console still don't work propertly.

Create history.txt:
1
2
...
...
40

start vkQuake, ~,  Up. Expected value is 40 (last line), not 8 (40-32)

**Comment by mjr4077au** [comment]
> @Novum You applied only part of the fix. Up/Down/Right keys don't work correctly after [ebc920d](https://github.com/Novum/vkQuake/commit/ebc920d9a59caf4c92332bef18d06c77a66133e5).

Why didn't you just do a PR instead of a patch? It wouldn't have been much more effort...

**Comment by andrey-budko** [comment]
@mjr4077au not able to test it right now (no vulkan support here), but I tried
https://github.com/Novum/vkQuake/pull/528

**Comment by temx** [comment]
Seems to work fine, merged. Thanks
