### ISSUE TITLE
Crash on startup using Reshade

### ISSUE THREAD

**Issue by DukeSkinny** [Novum/vkQuake#521]
I have verified that I'm using a clean install of the latest version of Reshade. vkQuake nonetheless crashes before showing anything, and there is no error message. This occurs both with my old presets & shaders which used to work with vkQuake, as well as a completely clean slate. If I uninstall Reshade everything works as expected.

**Comment by Novum** [comment]
File a bug with reshade. They need to fix their Vulkan integration.
