### ISSUE TITLE
Reduce loading time on large maps

### ISSUE THREAD

**Issue by daftmugi** [Novum/vkQuake#522]
Ironwail loads large maps, such as ad_sepulcher and ad_tears, quite quickly, noticeably quicker than vkQuake.
For those two maps, Ironwail is usually around 0.5 seconds and vkQuake is around 2.0 seconds on my machine.

One of the features listed on Ironwail's README is "reduced loading time for jumbo maps."

Could the same or similar load optimizations be added to vkQuake?

**Comment by Novum** [comment]
I think we can live with 2s loading times.
