### ISSUE TITLE
Bug: Specific rendered content or high FPS causes microstuttering 

### ISSUE THREAD

**Issue by RavenMacDaddy** [Novum/vkQuake#525]
I can see the microstuttering when looking at the frametime graph of RTSS.

It results in visual freezes and all sorts of clipping audio, already when letting the standard demo play out.

I could confirm it was isolated to vkQuake as a source port since [Ironwail](https://github.com/andrei-drexler/ironwail) isn't exhibiting the same issues.

In case it plays a role, I'm letting the framerate run free (mainly for input lag purposes), and using a GTX 1080 that means between 1500-2500 FPS.

CPU: AMD Ryzen 3600

**Comment by Novum** [comment]
Does this happen with 1.13?

**Comment by RavenMacDaddy** [comment]
It does happen with 1.13.0.

r_tasks 0 doesn't change the result.

I've tested a bit and it seems to indeed be an issue with unlocked framerate - interestingly though, specifically for `id1` content.

I haven't noticed cause I've only played Arcane Dimensions while playing unlocked.

**Comment by Novum** [comment]
I also noticed stuttering with the newest NV driver, I think this isn't a vkQuake bug

**Comment by RavenMacDaddy** [comment]
By now I've reverted to 457 that's provided by Windows Update which fixes heavy stuttering overall (and seemingly the SDL error, both reported to NVIDIA)...

But...

This issue specifically is still there, and as mentioned, using the in-game cap, even if it's at 1000 FPS, stops the microsuttering for `id1` content. 

And again, something like Ironwail running unlocked (which also easily surpasses 1000 FPS), doesn't microsutter for `id1` content.

**Comment by RavenMacDaddy** [comment]
> Ironwail uses OpenGL, it is not affected by Vulkan driver issues.

Fair point

**Comment by Novum** [comment]
Just to be clear, this specific issue does _not_ happen with 1.13, correct?

**Comment by RavenMacDaddy** [comment]
I've now tested from 1.0 and up.

Only once the 500 FPS cap was removed and the port is able to use almost all the power of the GPU the issue started, so from like 1.10 and up or something like that.

I never noticed this issue before cause I've always played capped (172 and 277 FPS depending on the monitor for G-Sync purposes) no matter the version of vkQuake - now I play uncapped with backlight strobing and V-Sync off cause it results in better input lag and an even better picture - so I noticed the issue being there.

Other ports/games that use Vulkan and have the same utilization while running uncapped, like Yamagi Quake 2, has no microstuttering.

Doesn't mean it's not a driver issue, but it doesn't look like it.

**Comment by Novum** [comment]
Are you sure it's not the RTSS overlay itself causing this issue? This is constantly an issue with third party injection.

**Comment by RavenMacDaddy** [comment]
Nope, turning off RTSS completely doesn't help.

**Comment by Novum** [comment]
Not turning it off, REMOVING it from the system.

**Comment by RavenMacDaddy** [comment]
Uninstalled it all. 

Reshade
MSI Afterburner
RTSS

Here we go:

![image](https://user-images.githubusercontent.com/67732686/179386186-20990cad-d775-491a-a6ea-762694ad330a.png)

**Comment by Novum** [comment]
Wait, that's not a microstutter, it's a GPU crash. Is your GPU overclocked?

**Comment by RavenMacDaddy** [comment]
Not anymore, MSI Afterburner was uninstalled.

**Comment by dezo2** [comment]
Tried that with latest vkQuake on id1 content and didn't see any stutter whatsoever.
FPS was in range of 1200-2500 on RTX2080, i7-9700, NV driver 512.15, win10.
Maybe something else on your PC running in the background is causing this?

Anyway why would you push your GPU like that? It just causes more power consumption, more heat and more problems like a coin whine or this one. If you have a VRR monitor (GSync/Freesync) just cap vkQuake a few FPS bellow the max. monitor refresh (while still in VRR range) and enjoy the smooth framerate without any tearing and virtually no input lag. At least I can't detect any lag difference on my 144Hz VRR monitor when using 142FPS cap or fully uncapped framerate.

**Comment by RavenMacDaddy** [comment]
I've spoken on the matter of G-Sync vs strobing and input lag, but that's besides the point.

It's likely a matter of Vulkan drivers on Windows 11 being wonky with your setup being so similar where it matters.

**Comment by Novum** [comment]
Vulkan on my Windows 11 machines is fine.

**Comment by RavenMacDaddy** [comment]
Fair enough - luckily 1000 FPS still results in very good input lag.

**Comment by Novum** [comment]
I'm not saying there isn't a bug in my code btw. But it's weird that it only happens with this configuration.

**Comment by RavenMacDaddy** [comment]
Also good points - as well as what was discussed in another, I've chosen to run pre-release version of Windows to get the latest features, and it's a very likely reason for very weird behavior, this being one potential one; the other being SDL crashes.

**Comment by RavenMacDaddy** [comment]
Doing some more testing.

![image](https://user-images.githubusercontent.com/67732686/179419266-3954b363-3780-4243-84fb-e95c52dfdbd9.png)

![image](https://user-images.githubusercontent.com/67732686/179419269-f7ee4a5d-0085-4b56-a5fd-6c1faa04ce1c.png)

This is when standing at the start of id1 with the three portals.

After about 10-15 seconds it crashes.

The system uptime is about 21 hrs.

No overlay, no injection, no overclock.

Gonna reboot and try again.

**Comment by Novum** [comment]
Funny thing is, I wrote the Vulkan code for Eternal and Wolfenstein ;)

**Comment by RavenMacDaddy** [comment]
I promise this isn't a joke, Wolfenstein would just freeze while on the menu, which was why I went on to try HL2 with the -vulkan switch, and before that the Quake remaster. 

Also, that's very cool, cause Eternal is one of the most performant games I know, including this source port.

**Comment by Novum** [comment]
Did you enable "Hardware-accelerated GPU scheduling"?

**Comment by RavenMacDaddy** [comment]
Yes, AFAIK it's default in Windows 11. 

I'll test disabling it later today.

**Comment by RavenMacDaddy** [comment]
So the results are...interesting.

The microstuttering is different.

Before in the demo (HAGS On), the stutters were very frequent and small with occasional big stutters, now with HAGS Off, it's become the behavior that was observed in the beginning of id1 where it's only big, spaced out stutters.

Scarily frankly here, since the crashes didn't happen when I began this issue, I think what's being stressed specifically by the instructions here compared to other Vulkan apps like the 2021 remaster, is so severe that (1) the stuttering is occurring on my personal GPU, and (2) letting it run that stressed out for longer periods, like standing still at the beginning id1, grinds it to a halt, leading to crashes shot above.

It was even more apparent as I turned off the sound of the game cause I could hear the coil whine going up and down depending on the amount of FPS that was being pumped out.

That's it folks - thanks for all of your inputs. 

If you're actually able to find what's stressing my GPU so much, awesome, maybe some other soul out there needed that as well, but the results are too scary for me personally - I want to use my GPU for a while longer while NVIDIA and the market calm down.

**Comment by Novum** [comment]
So it is a faulty GPU? Not quite convinced still.

**Comment by Novum** [comment]
Keeping this open for now, it's still odd to me that this only happens with vkQuake and nothing else. On the other hand, the code looks good, I don't have any tools report race conditions and validation layers are clean. Might still be something that is timing sensitive and doesn't get detected.

**Comment by RavenMacDaddy** [comment]
I would guess it's a component that's not adequately cooled on the GPU. 

The model is MSI GTX 1080 Gaming X.

**Comment by RavenMacDaddy** [comment]
After doing a clean install of NVIDIA driver v512.95, this issue didn't happen anymore during a test session - which is more than enough, cause even if it happens after that, as the author for the issue, I consider it far too inconsistent in that case to investigate further.

Again, thank you for your time, if anyone else experiences weird things like this, do a clean install (I did it with the great tool NVCleanstall, then imported my customized settings with the FoulPlay fork for NVIDIA Profile Inspector) of the driver of your choice - at the time of writing, I recommend the driver that's mentioned, cause I also didn't experience stuttering issues when for example starting processes, which was also a very big issue previously.

Lastly a side-note... Even if playing unlocked works, as mentioned it obviously puts unnecessary stress on the components for what you're getting in the end - but more importantly, even with a game with such a stable foundation as Quake, the FPS will fluctuate so much and have intermittent frame-pacing dips, which means that whatever the case, the response time will still be inconsistent as long as the FPS is uncapped.

Just cap it.

Issue closed.
