### ISSUE TITLE
Feature request: Improved symbolic link support

### ISSUE THREAD

**Issue by RavenMacDaddy** [Novum/vkQuake#526]
Noticed when trying out [Ironwail](https://github.com/andrei-drexler/ironwail) that simply making (a) symbolic link(s) for the `id1` PAK file(s) makes the source port read everything from the corresponding root dir, e.g. the `rerelease` subfolder of the Steam Quake installation.

Whether that's intentional or not, it makes things very convenient.

This means you could theoretically create a single repository, no matter which source port you feel like playing (which also saves space and administration).

It even makes you able to select Original or Remastered upon startup if the mentioned `rerelease` PAK is being used - and on-screen text like "This selects the easy skill" doesn't show up broken (which happens otherwise if the `rerelease` PAK is used locally).

Oh yeah, you can also use `sndspeed 44100` with the `rerelease` PAK since it has remastered audio.

**Comment by Novum** [comment]
I need a better explanation. I read your text three times and still don't understand.

**Comment by RavenMacDaddy** [comment]
Ah, I see, thanks for the explanation.
