### ISSUE TITLE
Bug: Using -basedir disables the Mods menu

### ISSUE THREAD

**Issue by RavenMacDaddy** [Novum/vkQuake#529]
It boots fine, pointing to the Steam rerelease dir, but the mod menu is not available.

Booting local content, the mods menu is available as expected.

Version at the time of writing: 1.20.3

**Comment by temx** [comment]
It's likely not finding `vkquake.pak`. Does your console background look like [Quake's](https://user-images.githubusercontent.com/24851409/178338389-df7075e1-b638-4366-ad24-b3d55437f3e6.png) or like [vkQuake's](https://user-images.githubusercontent.com/24851409/178338453-1c0ec7dc-492e-4b4e-bc8e-7914c74e02d8.png)?

**Comment by Novum** [comment]
Latest code will also look for vkquake.pak in the executable folder.
