### ISSUE TITLE
Mouse scroll during gameplay only works in one direction

### ISSUE THREAD

**Issue by xyz32** [Novum/vkQuake#53]
I got the latest code (yesterday-ish) and even though both directions of the mouse scroll work in the menu, while assigning the mouse scroll to the next and prev weapon. During gameplay only one direction of the scroll works.

**Comment by Novum** [comment]
Could you maybe try what happens in QuakeSpasm?

**Comment by xyz32** [comment]
It was working the first time I got the code to compile. It broke after, but I don't remember when. I will try a git-bisect to try to find the bad commit.

**Comment by Novum** [comment]
Works fine here?

**Comment by xyz32** [comment]
I will do some more tests when I get home, but I think that what triggers it is reassigning the next/prev weapons to only have the mouse scroll.

Also I am on Fedora linux 24 on 64bit.

**Comment by Novum** [comment]
Could you please compare with latest QuakeSpasm? I can't debug on Linux. If it does happen with QS as well you should report the bug to them.

**Comment by ProfessorKaos64** [comment]
I have wheel up and down assigned to my Steam Controller as Next Weapon/Prev Weapon. Sometimes I do get a false positive message from the console at the time, but it works for me there. I can try this later tonight with my actual mouse.

**Comment by xyz32** [comment]
I can reproduce it with just the keyboard as well. Turns out is the Prev-weapon action that does not work (keyboard or mouse).

**Comment by Novum** [comment]
I checked the input code against QuakeSpasm and it's identical minus the removal of SDL1. I'm pretty sure this came from upstream.

**Comment by neogeographica** [comment]
Probably not engine-related...

Impulse 12 as an input for "previous weapon" was not originally supported in the Quake progs.dat. It was introduced in 1.06. If you're using old Quake progs (maybe including the shareware?) or if you're playing an early mod based on those older progs, then impulse 12 will do nothing.

**Comment by xyz32** [comment]
That is correct, the version of pak0.pak is to blame. I got a newer version and it works ok now.

Please close.

Thanks.

**Comment by stevenhoving** [comment]
Maybe its worth mentioning in the readme.md
