### ISSUE TITLE
[feature request] portable mode to store config files and savegame files  in basedir/game folders 

### ISSUE THREAD

**Issue by j4reporting** [Novum/vkQuake#530]
the recent changes to the savedir lkocation have <del>one</del> <del>two</del> several  disadvantages

1. leave traces  on 'öther' computers  in  %APPDATA%\vkquake 
2. makes sharing configurations  and game saves across the different source engine ports cumbersome
3. only one  config file  shared by all kind of  game mods, 
 
preferably the portable mode could be switched on with a file portablemode or portable.ini in basedir or in the same directory as the executable?

**Comment by Novum** [comment]
I already had this planned.

**Comment by Novum** [comment]
0c18963d9dda76d342fd457f4ad7f880457d0ce0
