### ISSUE TITLE
Switch for classic animations in menu

### ISSUE THREAD

**Issue by lilo-san** [Novum/vkQuake#532]
This Vulkan source port gets surprisingly close to the software renderer when options are set to classic.

A similar option to have the classic animations would be welcomed.

**Comment by garoto** [comment]
`r_lerpmodels 0`

**Comment by Novum** [comment]
The menu is getting a bit crowded, maybe I need to add more sub-menus for game settings like this.

**Comment by lilo-san** [comment]
I would maybe put on the main settings menu a shortcut “Graphics Look”: Software Renderer, openGL and Enhanced that automatically sets all options for you. Then hide all graphic and animation options under a sub menu “Graphics” for who wants to tweak. This is the first time I see a modern source port looking right. I feel it could serve well to both purists and who want pretty graphics, having Vulkan underneath is such a good foundation. Thank you so much!

**Comment by lilo-san** [comment]
r_lerpmodels 0 seem to work, but oddly enough gets removed from the config file by vkquake

**Comment by Novum** [comment]
You need to put it in `autoexec.cfg`.

**Comment by TMHKR** [comment]
I had a similar wish way back when I used OG QuakeSpasm, but it was the other way around. I wanted everything smooth.
r_lerpmodels 2 worked great, but not for the movement of buzzsaws in Rogue MP and floating Sentinel robots in AD.
Necros from Func_Msgboard said it has nothing to do with the engine, but QuakeC instead.
I wonder if it could somehow be done in vkQuake regardless.

**Comment by vide0hanz** [comment]
@novum can this be closed now? 

I really like these new menu options btw, some fine QOL improvements.

**Comment by garoto** [comment]
If people playing fricking "Quake" doesn't undertand the concept of an pure ASCII file  named `autoexec.cfg` being read at every start-up, then it is an issue.

**Comment by Novum** [comment]
Yep, can be closed.
