### ISSUE TITLE
Changing resolution and refresh on Arch Linux build seems to mess up my monitor.

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#538]
I am using the latest arch build. 
I have a setting on my acer monitor called ultra low latency, if it isn't turned on it feels like the monitor only runs at 60hz dispite being 165hz. However, changing the resolution and refresh rate seems to force it off every time. Even if I use a setting called free sync which forces it to be on and fixed those issues I was having on Windows where some apps in full screen would disable it. I have not had this issues with Linux in any way, ever. This game, however, forces me to turn the setting off and on for it to work again.

**Comment by Novum** [comment]
You provided literally zero information about driver or GPU. I'm just closing issues like this from now on.

**Comment by LethalManBoob** [comment]
NVIDIA GeForce RTX 3070 Lite Hash Rate 
Driver version 515.57
AMD Ryzen 5700X
Kernel 5.18.9-lqx1-linux-lqx
