### ISSUE TITLE
Audio feature request: Doppler effects

### ISSUE THREAD

**Issue by RavenMacDaddy** [Novum/vkQuake#541]
Similar to what can be enabled in [Yamagi Quake II](https://github.com/yquake2/yquake2) (see [here](https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md#audio)), and what's seemingly enabled by default in [Ironwail](https://github.com/andrei-drexler/ironwail), the doppler effects give a good sense of positioning and 3D audio space.

Having the option available in the source port would be a nice touch.

**Comment by Novum** [comment]
You are hallucinating support for this in Ironwail. I checked the source.
