### ISSUE TITLE
HUD feature request: Selection of different HUDs

### ISSUE THREAD

**Issue by RavenMacDaddy** [Novum/vkQuake#542]
Similar to [Ironwail](https://github.com/andrei-drexler/ironwail) which uses the same HUD that's default for [Arcane Dimensions](https://www.moddb.com/mods/arcane-dimensions) - but more importantly has the option to select between different HUDs.

![image](https://user-images.githubusercontent.com/67732686/181825210-7e197e6b-5a29-44fd-9fea-da23c95733ff.png)

Is this something that can be implemented?

**Comment by Novum** [comment]
Happy to accept patches, not interesting in doing this myself

**Comment by Novum** [comment]
Keeping this open, it's a legitimate request.

**Comment by Novum** [comment]
8f3a68af621112bef490257ff4aa965d50c80d42
