### ISSUE TITLE
Unlocked framerate suffers from occasional frametime dips

### ISSUE THREAD

**Issue by RavenMacDaddy** [Novum/vkQuake#543]
I'm not expecting this to be a priority, nor something that's easy to fix - only an opportunity for further optimization. 

I've noticed that the frametimes, if running the port with an unlocked framerate, will dip from time to time severely - something that's not happening on OpenGL, e.g. with [Ironwail](https://github.com/andrei-drexler/ironwail) when doing the same test-runs (letting the id1 demo play out).

On an NVIDIA GTX 1080, an unlocked framerate ends up being more or less 2000 FPS, or a frametime of ~0.5 ms when running the standard id1 content.

The dips could make the frametime go from that ~0.5 ms response time to 1-2 ms if not more momentarily, which is obviously ridiculously low as it's - but that's not the point here. 

A frametime jump of that magnitude, corresponds to going from 2000 FPS to 1000 or 500 FPS, if not lower, which is quite a jump.

This jump doesn't show up on a real-time graph, but it does show up in the digits which made me able to get those numbers - it's that quick of a dip.

More than anything I just found this interesting.

**Comment by Novum** [comment]
Again, what OS, driver etc. Not going to keep those open without proper info.
