### ISSUE TITLE
players missing from scoreboard on FTE server

### ISSUE THREAD

**Issue by timbergeron** [Novum/vkQuake#546]
This is probably somewhat related to these:

https://github.com/Novum/vkQuake/commit/4d34bde46271277c40c1e1228fe8db664610440e -- Handle userinfo updates
https://github.com/Novum/vkQuake/commit/fc320b8ed7d5caaf2da0239663d3bcd7fe09f919 -- Update cl.scores properly on connect and disconnect (#360)

Players will jump in and out of the scoreboard:
Server tested: crxquake.com or denver.crxquake.com

![vkquake0000](https://user-images.githubusercontent.com/68674590/182052175-06ce0f6f-af1c-44f9-a861-1547bae1c9cd.png)

**Comment by Novum** [comment]
@temx 
I have no idea about the MP stuff

**Comment by temx** [comment]
I can't reproduce this locally, and the crxquake.com servers seem to be down at the moment.
When do the players "jump in and out of the scoreboard"? Is it during some event (frag, rename...)?
It'd probably be useful if you could record a demo while this is happening.

**Comment by temx** [comment]
de476ce may or may not fix this (it fixes colors reseting when changing names on FTE servers with protocol base666, QSS seems to have the same problem).
It will fix an empty name (= disappearing from the scoreboard) if the server sends player information as svc_updates when logging in, but then sends an UserinfoUpdate.

**Comment by timbergeron** [comment]
I will try to get some more data. Sometimes I can't find a pattern to it happening.

**Comment by temx** [comment]
Now I managed to reproduce it, and 61c8a0b should fix it for good. Feel free to reopen if you see it happening again.
