### ISSUE TITLE
[Feature request] Double click demo file to play it

### ISSUE THREAD

**Issue by timbergeron** [Novum/vkQuake#548]

**Comment by temx** [comment]
Assuming this is from the OS shell, you can set your `.dem` handler to launch vkQuake with the appropriate parameters. For example in Windows you can use a `cmd` file like
```
for %%F in ("%~1\..") do set modname="%%~nxF"
cd /D "%~dp0"
vkQuake -game %modname% +playdemo "%~nx1"
```
place it along vkQuake and assign `.dem` files to it (or just drop them on top of it).

I do like the feature some Doom source ports have where they do the right thing when you directly pass a file as a parameter. Quake could interpret directories as mods, `map` files as `game` + `map`, and `dem` files as `game` + `playdemo` requests.

**Comment by timbergeron** [comment]
added this for dragging a demo into windowed mode:

https://github.com/timbergeron/QSS-M/commit/a1ee1d29e5c44ff9f8f25c22b6c8d6c2f0e6c9c6

**Comment by timbergeron** [comment]
Found this:
https://github.com/timbergeron/Engine-X/blob/1f368b93ccc2ef2a489f1767f26fad977851479c/Engine_X550_source/sys_win_interact.c#L434

**Comment by vsonnier** [comment]
Not interested in adding this.
