### ISSUE TITLE
Linux: current build does not complete vk ext. undeclared

### ISSUE THREAD

**Issue by ProfessorKaos64** [Novum/vkQuake#55]
The [debug extension addition](https://github.com/Novum/vkQuake/commit/1b2ad86a6ddaab7a8b260bace1daa3e43e990b38) seems to have introduced errors when making Linux binaries. The following error is thrown:

```
gl_vidsdl.c:674:15: error: ‘VK_EXT_DEBUG_MARKER_EXTENSION_NAME’ undeclared (first use in this function)
    if (strcmp(VK_EXT_DEBUG_MARKER_EXTENSION_NAME, device_extensions[i].extensionName) == 0)
               ^
```

Log: http://sprunge.us/NMAY

Steps to reproduce:

```
sudo apt-get install git make gcc libsdl2-dev libvulkan-dev libvorbis-dev libmad0-dev
git clone https://github.com/Novum/vkQuake/
cd vkQuake/QUake
make

```

**Comment by SaschaWillems** [comment]
Are you using a recent Vulkan header? The extension has been added to the Vulkan headers [some time ago](https://github.com/KhronosGroup/Vulkan-Docs/commit/648049f625c956068495192447e3ef99772c8947).

**Comment by ProfessorKaos64** [comment]
I backported [libvulkan-dev](https://packages.debian.org/stretch/libvulkan-dev) and have been using that for some time. I can build 0.50 ok. Is this library version too old?

**Comment by SaschaWillems** [comment]
Afair the debug marker extension was introduced with 1.0.12.0 and it seems that package is only 1.0.8.0.

**Comment by ProfessorKaos64** [comment]
Lovely :) I guess I'll have to look into building a package for that version. Thank you for the heads up. If this is true @Novum, this definitely should be noted in the readme for the master tree.

**Comment by ProfessorKaos64** [comment]
I updated my  libvulkan-dev package in my pool to 1.0.2, merged the Debian patches, and after some tinkering got that built. After installing this during a pbuilder chroot build, everything completed ok.  @SaschaWillems thank you for the heads up (and for your Vulkan work).

Testing the resulting binary now.

**Comment by ProfessorKaos64** [comment]
Confirmed working.
