### ISSUE TITLE
Cannot play Shareware version after fresh compilation.

### ISSUE THREAD

**Issue by homeisfar** [Novum/vkQuake#551]
Following the instructions for building on Linux, I cloned and built vkQuake through meson. I downloaded the shareware pak0.pak and placed it into the build directory under id1.

Here is an extremely simplified tree layout of my build dir.

```
├── id1
│   └── pak0.pak
├── vkquake
```
In spite of this correct layout I kept getting this message:
`You must have the registered version to use modified games.`

I traced it down to this condition https://github.com/Novum/vkQuake/blob/45d7080a8a2efdf768487bc603f76f23b74a1df4/Quake/common.c#L2002 which seemingly always executes, and always ends up setting the `com_modified` variable to true. Clearly it's searching for vkquake.pak (which has an unclear purpose), but whether I copy that file into the id1 directory, or the build directory, the end result is com_modified is set to true. My current workaround is to neuter the COM_CheckRegistered function, which lets me run the shareware game and explore the Vulkan code.

**Comment by temx** [comment]
796c3a1 should have fixed this

**Comment by Novum** [comment]
@temx I'm wondering why this code even exists in the first place. I don't think we have to retain some ancient DRM under GPL conditions?

**Comment by temx** [comment]
I don't think we have, but it prevents nondescriptive error messages if somebody tries to run mods as almost all will fail to load with the shareware data. An argument for removing it is enabling total conversions.

**Comment by Novum** [comment]
Ah, that makes sense. I thought it's just a nag.
