### ISSUE TITLE
Compilation failure on on openSUSE 15.4

### ISSUE THREAD

**Issue by bubbleguuum** [Novum/vkQuake#558]
Compiling git master as of the date of this report on openSUSE 15.4 fails with output below.

https://build.opensuse.org/package/live_build_log/home:bobbie424242/vkquake-git/15.4/x86_64

Stock gcc on this distro is kind of oldish, being v7.5.0.

**Comment by sezero** [comment]
`SDL_PRIxxx` macros were added in SDL2-2.0.16: maybe vkquake should update its requirements.

**Comment by bubbleguuum** [comment]
Indeed. openSUSE 15.4 uses an older SDL2.
It cannot be changed unfortunately as it is "stable" (in the sense that things are software versions are mostly frozen until next distro version).
Not a big deal, as I reported this to see if it could be easily fixed. I myself use openSUSE Tumbleweed for which vkquake compiles just fine and that I package git snapshots in the OBS repo I linked to.

**Comment by Novum** [comment]
Hm, maybe I can replace them with non-SDL2 variants.

**Comment by sezero** [comment]
> Hm, maybe I can replace them with non-SDL2 variants.

Yes: assuming that MSVC has inttypes.h which you rely on, you can use plain PRIu32, PRIu64, etc.
