### ISSUE TITLE
csqc sound builtins.

### ISSUE THREAD

**Issue by Shpoike** [Novum/vkQuake#559]
vkquake's csqc implementation lacks the sound:8 builtin (defined as PF_Fixme in pr_cmds.c), while pointsound exists it lacks channel replacements which makes stuff awkward.

additionally localsound:177 is missing (not to be confused with ssqc's ex_localsound:0 from the rerelease), making it harder to provide sound effects in csqc menus etc.

**Comment by Novum** [comment]
I implemented them in 28d7b165db2827b02248ff1b5f763b141a2dc39a, but I'm not sure that's going to fix menu sounds. I don't implement the menu CSQC stuff at all.
