### ISSUE TITLE
csqc text scaling

### ISSUE THREAD

**Issue by Shpoike** [Novum/vkQuake#560]
vkquake's DrawQC_CharacterQuad disregards its w and h args, using hardcoded values of 8 for each, preventing csqc from drawing titles and the like.
`https://github.com/Novum/vkQuake/blob/master/Quake/pr_ext.c#L4345`
looks like a trivial fix.

**Comment by Novum** [comment]
Thanks for reporting, will check

**Comment by temx** [comment]
It was, should be fixed now.
