### ISSUE TITLE
Support for Nehahra

### ISSUE THREAD

**Issue by malespiaut** [Novum/vkQuake#561]
Hello,

I've tried to play Nehahra using vkQuake v1.20.3, and the git revision cb45d8452e94be934084fe35b5a91052b10fef40.

Nehahra is available to download here: https://www.quaddicted.com/reviews/nehahra.html

Using v1.20.3, vkQuake throws an error:

```
the Necropolis
Using protocol 15
Allocating lightmap compute surface data (332 KB)

ERROR-OUT BEGIN

Shutting down SDL sound

QUAKE ERROR: sprites/explode1.spr32 has wrong version number (32 should be 1)
```

while revision cb45d8452e94be934084fe35b5a91052b10fef40 simple crashes:

```
the Necropolis
Using protocol 15
Allocating lightmap compute surface data (332 KB)
vkquake: ../Quake/gl_texmgr.c:642: TexMgr_Downsample: Assertion `(out_width >= 1) && (out_width < in_width)' failed.
Aborted (core dumped)
```

I don't know if Nehahra can be supported, as it seems to come with a custom engine.

Best regards.

**Comment by Novum** [comment]
It cannot.
