### ISSUE TITLE
Bright lights look dimmer in vkQuake

### ISSUE THREAD

**Issue by lemarden** [Novum/vkQuake#563]
Some bright lights look dim in vkQuake: https://i.imgur.com/p118ZYl.png

Compare to the Machinegames rerelease: https://i.imgur.com/lGLbt5k.png

And Ironwail: https://i.imgur.com/jhpg5Cs.png

This is in the mge2m2 level near the start.

**Comment by Novum** [comment]
1bf250dd6ab7476bd0c17d189110f91f520a5416
