### ISSUE TITLE
Display monster counts > 3 digits in intermission

### ISSUE THREAD

**Issue by Flecked42** [Novum/vkQuake#564]
Commit for it on Ironwail https://github.com/andrei-drexler/ironwail/commit/85d042a2ccca4277d190cfa19c9a0699f8ecae0c

**Comment by temx** [comment]
Merged, plus https://github.com/andrei-drexler/ironwail/commit/c143922513910e46cd4a14e08c6ee5e7753ef0b6 for good measure.
