### ISSUE TITLE
Assertion failed when loading qbj_grue

### ISSUE THREAD

**Issue by Perlence** [Novum/vkQuake#567]
Hello! I built vkQuake at 7d7f025 on Apple M1 and tried loading Grue's map from [Quake Brutalist Jam](https://www.slipseer.com/index.php?resources/quake-brutalist-jam.126/). Unfortunately, it crashed with the following:

```
]map qbj_grue 
Assertion failed: ((out_width >= 1) && (out_width < in_width)), function TexMgr_Downsample, file gl_texmgr.c, line 642.
fish: Job 1, 'build/vkquake -basedir ~/Games/…' terminated by signal SIGABRT (Abort)
```

I've noticed it's the same assertion error that was mentioned in issue https://github.com/Novum/vkQuake/issues/561.

**Comment by temx** [comment]
That map includes a 0x0-sized texture "`__TB_empty`" which I believe is invalid. I've added a check to avoid loading such textures, but whatever tool was used to compile the map should be fixed.

@andrei-drexler Ironwail also gets API errors with this (`GL api error [#1282/high]: GL_INVALID_OPERATION error generated. Texture and sampler are inconsistent.` & `GL api error [#1282/high]: GL_INVALID_OPERATION error generated. Not a valid texture.`)

**Comment by sezero** [comment]
Is the following good as a backport to QS? Anything missing?
```diff
diff --git a/Quake/gl_model.c b/Quake/gl_model.c
index 00f5b8ad..05224f26 100644
--- a/Quake/gl_model.c
+++ b/Quake/gl_model.c
@@ -496,6 +496,12 @@ static void Mod_LoadTextures (qmodel_t *mod, byte *mod_base, lump_t *l)
 		for (j=0 ; j<MIPLEVELS ; j++)
 			mt->offsets[j] = LittleLong (mt->offsets[j]);
 
+		if (mt->width == 0 || mt->height == 0)
+		{
+			Con_Warning ("Zero sized texture %s in %s!\n", mt->name, mod->name);
+			continue;
+		}
+
 		if ( (mt->width & 15) || (mt->height & 15) )
 		{
 			if (loadmodel->bspversion != BSPVERSION_QUAKE64)
```

**Comment by temx** [comment]
It should be OK, it's the same code path as when `dataofs == -1`.

**Comment by sezero** [comment]
OK, will apply the patch shortly.

**Comment by Perlence** [comment]
Awesome, thanks @temx!

I just wanted to note, probably not really relevant, that the map loaded fine on vkQuake 1.12.2.

**Comment by andrei-drexler** [comment]
> @andrei-drexler Ironwail also gets API errors with this (`GL api error [#1282/high]: GL_INVALID_OPERATION error generated. Texture and sampler are inconsistent.` & `GL api error [#1282/high]: GL_INVALID_OPERATION error generated. Not a valid texture.`)

Thanks for letting me know!
