### ISSUE TITLE
Add automated Travis CI testing

### ISSUE THREAD

**Issue by ProfessorKaos64** [Novum/vkQuake#57]
Would you be willing to add Travis CI automated build tests? If you have not used this service before, see: https://travis-ci.org/.

Example:

https://github.com/ProfessorKaos64/vkQuake

This will build on each commit. If this isn't ideal, issue will be closed. [Windows support](https://github.com/travis-ci/travis-ci/issues/2104) on Travis is not yet implemented. I believe this may be doable by running a secondary build pass with mingw compilation.

**Comment by Novum** [comment]
Sure, why not. But do you really think it's necessary? It's not a huge code base.

**Comment by ProfessorKaos64** [comment]
Meh you're right. If it was a bigger project, I'd make more sense.
