### ISSUE TITLE
Arch Linux: QUAKE ERROR: Couldn't find any Vulkan devices

### ISSUE THREAD

**Issue by ProfessorKaos64** [Novum/vkQuake#58]
I know you do not mainly deal with Arch Linux, so this likely is a "help wanted" tag/issue. The window flashes for a moment, then dumps back to the CLI. I was sure how to use the [new debug extension](http://www.saschawillems.de/?page_id=2017) either.

I tried to trace it, but the CLI just hangs:

```
vktrace -p vkquake -o vkquake.vktrace -w ${PWD}
```

Steps to reproduce on Arch Linux

```
git clone https://github.com/Novum/vkQuake
cd vkQuake/Quake
make
cp ../id1 ${PWD}
./vkquake
```

* OS: Arch Linux
* System Vulkan info: http://sprunge.us/TZKX
* Driver: nvidia 367.35-2 (with required [vulkan-icd-loader](https://wiki.archlinux.org/index.php/Vulkan))
* Error: http://slexy.org/view/s20ct8MF3g
* ldd: http://slexy.org/view/s2fFW2gUXl

**Comment by Novum** [comment]
Does the stuff from the Vulkan SDK run? I doubt this has anything to do with vkQuake, it's simply not finding any Vulkan devices.

**Comment by ProfessorKaos64** [comment]
Seems [some folks](https://bbs.archlinux.org/viewtopic.php?id=215727) have some issues.  Grr... not sure what's going on then. You're correct, likely isn't vkquake then if the below steps work for you.

Steps

```
wget https://github.com/LunarG/VulkanSamples
./update_external_sources.sh
cmake -H. -Bdbuild -DCMAKE_BUILD_TYPE=Debug
cd dbuild
make
cd Sample-Programs/Hologram
./Hologram
```

Error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to find any capable Vulkan physical device
Aborted (core dumped)
```

**Comment by ProfessorKaos64** [comment]
My fault, my card upstairs on this box, is a GTX 560, which is [not capable]9https://developer.nvidia.com/vulkan-driver) after checking.

**Comment by Translator5** [comment]
Same error, but GTX 760 ...
by the way for me the game worked well till yesterday. But than I tried to isntall Vulkan SDK (whyever)

some ways to fix it?

[(here some information)](https://gist.github.com/Translator5/c0a439f7e757b341fa429a3440926578/edit)
