### ISSUE TITLE
Alt-tab crash

### ISSUE THREAD

**Issue by AAS** [Novum/vkQuake#581]
64-bit vkquake.exe crashes on alt-tabing, just alt-tab to desktop and return to the game.

Windows 11 x64 / GeForce 3060Ti / 527.37 driver version, also tried on 526.86

**Comment by vsonnier** [comment]
I got that for some time too ( weeks / months ?) with the `master` commits. I didn't try to either report the bug nor investigate because I never use alt-tabbing.
Here :
 Windows 10x64 22H2 up to date / GeForce 1050Ti Mobile / 526.98  or Intel HD630 / 31.0.15.2698 so it doesn't seem to be tied to a driver problem at first glance. 
Currently I use an up-to-date VS2022 to build together with a VulkanSDK 1.3.231.1.

**Comment by vsonnier** [comment]
@temx your commit https://github.com/Novum/vkQuake/commit/6a8af82b461f8db32f648da82f36dd6dc942bd8f did the trick on my side, alt-tab now works.

**Comment by temx** [comment]
Sorry about this, I assumed GL_CreateRenderResources was not fallible but GL_CreateSwapChain can fail (it took ~20 attempts for me).

**Comment by vsonnier** [comment]
Funny, if I alt-tab on a running game, the game seems to continue to think somehow (Ex a rotaing brush shows a completely different angle after unfreeze, hope I make myself clear). Alt-tabing in menu looks perfectly normal and freeze / unfreeze the game  as-is. 

Don't know if it is relevant. Thanks @temx by the wau for all your recent work.

**Comment by Novum** [comment]
There isn't any game pausing when alt+tabbing, that has always been the case for Quake.

**Comment by Novum** [comment]
@temx Still getting a validation error:
`Validation Error: [ VUID-vkCmdDispatch-mipmapMode-04770 ] Object 0: handle = 0x78e915000000036d, name = surfindices0000000 compute desc set, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0x2723ba0000000037, name = point, type = VK_OBJECT_TYPE_SAMPLER; Object 2: handle = 0x72432b000000036b, name = surfindices0000000 image view, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x3019e15a | Descriptor set VkDescriptorSet 0x78e915000000036d[surfindices0000000 compute desc set] encountered the following validation error at vkCmdDispatch time: Sampler (VkSampler 0x2723ba0000000037[point]) is set to use VK_SAMPLER_MIPMAP_MODE_LINEAR with compareEnable is set to VK_FALSE, but image view's (VkImageView 0x72432b000000036b[surfindices0000000 image view]) format (VK_FORMAT_R32_UINT) does not contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT in its format features. The Vulkan spec states: If a VkSampler created with mipmapMode equal to VK_SAMPLER_MIPMAP_MODE_LINEAR and compareEnable equal to VK_FALSE isInitializing samplers`

**Comment by temx** [comment]
Is that related to alt-tab? I don't get that error, and that's the compute lightmap indices texture which shouldn't have changed.

**Comment by Novum** [comment]
Nevermind, that is actually my bug.

**Comment by temx** [comment]
I don't know if it'll fix it, but it should be possible to remove TEXPREF_LINEAR from lines 1742 and 1749 (**NOT 1736**) in r_brush.c. But again I don't think I have touched that code.

**Comment by Novum** [comment]
@temx It's fixed now
