### ISSUE TITLE
Graphical glitches when using r_indirect 1

### ISSUE THREAD

**Issue by Konkonfaux** [Novum/vkQuake#583]
Using a Nitro 5 laptop with an Nvidia 1650 GPU. When using the default value for r_indirect, it will produce visual glitches like textures becoming black spaces.

**Comment by Konkonfaux** [comment]
![vkquake0003](https://user-images.githubusercontent.com/67092414/205412783-69127936-f9d6-4ce6-b8cc-a99b32bdf04e.png)

**Comment by temx** [comment]
Does this flicker or is it stable? Does anything change if you set r_novis 1 before loading?
What driver version are you using? Can you run `condump` in the console and then attach condump.txt here?

**Comment by Konkonfaux** [comment]
It does flicker. If r_novis is set to 1, the black parts become transparent. I've attached an image with r_novis set to 1, and a condump.

[condump.txt](https://github.com/Novum/vkQuake/files/10145319/condump.txt)
![vkquake0005](https://user-images.githubusercontent.com/67092414/205415568-49247a50-d12c-48f4-b7ee-59bbc71b9ab6.png)

**Comment by temx** [comment]
Thanks. The driver you're using is 2 years old, if possible you should update it.
Two more questions: does it still flicker with `r_novis 1`? Does `r_tasks 0` change anything?

**Comment by Konkonfaux** [comment]
It still flickers with r_novis 1, and r_tasks 0 will make the world not transparent. I guess I'll try isntalling Nvidia experience because when I try my device panel it says this is the most recent driver.

![vkquake0006](https://user-images.githubusercontent.com/67092414/205416252-89dc252d-a1da-4937-91cb-5a23ca9fc46b.png)

**Comment by temx** [comment]
Sorry, to be clear, does `r_tasks 0` fix it completely? Does `r_novis 0` and `r_tasks 0` work well?

**Comment by Konkonfaux** [comment]
No. That still leaves it flickering.

**Comment by Konkonfaux** [comment]
With r_indirect 1 that is.

**Comment by temx** [comment]
No, it's good to know that fixed it.
Not sure if we want to do do anything like blacklisting old drivers for indirect or displaying a warning. 
I did test with 2-3 year old drivers on AMD and Intel and they worked fine. That version doesn't seem to be a public Nvidia release, maybe it was a customized driver.

**Comment by Konkonfaux** [comment]
I believe you should make the new behaviour a toggle. r_indirect that is.

**Comment by Novum** [comment]
Na, it's not doing anything that's not spec conformant. This is not worth saving to disk.
