### ISSUE TITLE
"Swim down" bind menu entry invisible

### ISSUE THREAD

**Issue by TMHKR** [Novum/vkQuake#584]
A quick note for future releases - the "swim down" keyboard bind entry is invisible in the menu, but you can still configure it. Probably "quick zoom" took its place. A minor issue. Version 1.22.1

![image](https://user-images.githubusercontent.com/6874649/206016622-27905023-3d21-4dbb-a47e-382dc9ceab70.png)

**Comment by Novum** [comment]
@temx We might need to split this up into multiple sub menus, there is also still the PR for weapon bindings that I eventually wanted to address.

**Comment by temx** [comment]
I added a scrollbar and threw in the weapons. Feel free to tweak or suggest tweaks.

**Comment by Novum** [comment]
Thanks @temx. I cleaned it up a little bit too.
