### ISSUE TITLE
No HUD Visible

### ISSUE THREAD

**Issue by Vash63** [Novum/vkQuake#59]
Running the 0.50 Linux binaries on Arch Linux w/ Nvidia 367.35 - the game runs fine from ./vkquake but there is no visible HUD. The main menu and pause menus work fine, and I do get status message for pickups, but there's no health, weapon, ammo, etc.

Unfortunately not seeing any errors in the terminal.

**Comment by ProfessorKaos64** [comment]
The readme notes you should be using vkquake-launch.sh.  Let me pop in my other graphics card tomorrow and I'll take a look for you.

**Comment by Vash63** [comment]
This might need a different bug but vkquake-launch.sh crashes on me. I've uploaded a core dump:

https://trekker.guru/core.vkquake.1000.689d80a6faa6450095c5e12781222123.1730.1471132847000000000000.lz4

**Comment by ProfessorKaos64** [comment]
Ok, noted. If this ends up being that troubsome, I will end up doing a AUR package outside the scope of this repository.

**Comment by ProfessorKaos64** [comment]
I have never worked with .lz4 before, can you please attach an common archive format or the output to a pastebin service?

**Comment by Novum** [comment]
You very likely have "screen size" set to maximum in the options menu.

**Comment by ProfessorKaos64** [comment]
@Vash63 I just loaded Antegros and ran ./vkquake. It runs fine with the hud. You'll need to, like Novum said, check the screen sizing in the options.
