### ISSUE TITLE
vkQuake not running with SDL 2.24.2

### ISSUE THREAD

**Issue by Dizzy611** [Novum/vkQuake#597]
```
Command line: ./vkquake
Found SDL version 2.24.2

ERROR-OUT BEGIN


QUAKE ERROR: Your version of SDL library is incompatible with me.
You need a library version in the line of 2.0.0


```

This started happening after I upgraded from Debian Stable to Testing and to a newer version of SDL

**Comment by temx** [comment]
What version of vkQuake are you trying to run? That check was [removed](https://github.com/Novum/vkQuake/commit/4c7c2c3a42ec84d32c243c2bb6d4a7ef41f1d9c2) long ago. Any version starting from 1.20.0 should work.

**Comment by Novum** [comment]
Yes, please update to latest. AppImage should work on any reasonably modern Linux.
