### ISSUE TITLE
vkquake fails to start

### ISSUE THREAD

**Issue by un4va1l4bl3** [Novum/vkQuake#604]
I'm using Arch linux and since vkquake 1.22.1, the game fails to run from the application menu or if I type vkquake in a terminal I get this error:  

 ```
QUAKE ERROR: W_LoadWadFile: couldn't load gfx.wad

 Basedir is: /home/carp
```

The game only runs with " vkquake --basedir ~/.vkquake "
Was there a change made to the source code that caused this?

Here is the package on AUR:
[https://aur.archlinux.org/packages/vkquake](https://aur.archlinux.org/packages/vkquake)

**Comment by Novum** [comment]
This never worked. You either run from the Quake directory or you have to specify basedir.

**Comment by micwoj92** [comment]
I suspect this is because in 1.22.1 vkquake on AUR changed build system from using make (which had DO_USERDIRS=1 specified in PKGBUILD) to meson.

@Novum is there a way to do "DO_USERDIRS=1" for meson build?

**Comment by Novum** [comment]
Honestly I never looked at that. That was an import from QuakeSpasm. Sure, you can do compile defines in meson.

**Comment by Novum** [comment]
8875ada7dfe2809f4fead2f3881749f231961005 adds a meson option for this, syntax would be `meson setup -D do_userdirs=enabled builddir`

**Comment by un4va1l4bl3** [comment]
Thank you for looking into the issue.
