### ISSUE TITLE
Vkquake fails with latest Nvidia 370.23 driver for Linux

### ISSUE THREAD

**Issue by oscarbg** [Novum/vkQuake#61]
~/vkq/vkQuake/Quake$ ./vkquake 
Command line: ./vkquake
Found SDL version 2.0.4
Detected 4 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.92.0 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 0.60.0 (c) Axel Gneiting
Host_Init
Playing shareware version.
Console initialized.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 18:17:07 Aug 16 2016
256.0 megabyte heap

Vulkan Initialization
Vendor: NVIDIA
Device: GTX 970
Creating command buffers
Creating swap chain
Creating render passes
Creating color buffer
Creating depth buffer
Creating frame buffers
Initializing staging
Creating descriptor set layouts
Initializing dynamic vertex buffers
Initializing dynamic index buffers
Initializing dynamic uniform buffers
Initializing samplers
Creating pipeline layouts
Creating pipelines
detected controller: PS4 Controller

Sound Initialization
SDL audio spec  : 44100 Hz, 512 samples, 2 channels
SDL audio driver: pulseaudio - GM204 High Definition Audio Controller Digital Stereo (HDMI 2), 32768 bytes buffer
Audio: 16 bit, stereo, 44100 Hz
CDAudio disabled at compile time

========= Quake Initialized =========

LTRIGGER is unbound, hit F4 to set.
RTRIGGER is unbound, hit F4 to set.
execing quake.rc
execing default.cfg
execing config.cfg
Unknown command "gl_texture_anisotropy"
Initializing samplers
couldn't exec autoexec.cfg

ERROR-OUT BEGIN

Shutting down SDL sound

QUAKE ERROR: vkWaitForFences failed

**Comment by ProfessorKaos64** [comment]
I remember seeing  vkWaitForFences errors only with a prior level crash.  What Linux distribution are you using? Did you compile this manually, or try the precompiled binary?

**Comment by Novum** [comment]
That does sound like a driver bug again. The fence code is pretty simple and should work.

**Comment by ShabbyX** [comment]
I see issues with the 370 Nvidia driver (not with vkQuake, but within my own projects) when vertical syncing is disabled. More in particular, `VK_PRESENT_MODE_FIFO_KHR` seems to be ok in my case, but `VK_PRESENT_MODE_IMMEDIATE_KHR` problematic.

**Comment by Novum** [comment]
Good observation. You should tell NVIDIA. They are not even exposing IMMEDIATE on Windows, only MAILBOX.

**Comment by ShabbyX** [comment]
That's funny! On Linux, they don't allow MAILBOX, but they do IMMEDIATE!
