### ISSUE TITLE
Flathub build

### ISSUE THREAD

**Issue by mooreye** [Novum/vkQuake#610]
**Is your feature request related to a problem? Please describe.**
vkQuake is not packaged for Linux distros, uploading it to Flathub would solve having to download it manually/compile.

**Describe the solution you'd like**
Make an automated build to flathub.org

**Describe alternatives you've considered**
Downloading release tar.gz manually

**Comment by Novum** [comment]
Don't really see the big advantage vs. just running the appimage?

**Comment by micwoj92** [comment]
Appimage can be also added to https://www.appimagehub.com and/or https://appimage.github.io

**Comment by Novum** [comment]
And what exactly is the advantage of that vs. just the github AppImage download? Simply installing won't work because the game files are not in a standard location.

**Comment by sezero** [comment]
Everyone can either download the appimage, or can build themselves - just a simple action of running `make`. I don't see the point in this.

**Comment by Novum** [comment]
You mean meson ;)

**Comment by sezero** [comment]
> You mean `meson` ;)

No, I don't :)
