### ISSUE TITLE
Dosen't build on Mac

### ISSUE THREAD

**Issue by UnBeatWaterGH** [Novum/vkQuake#615]
**Describe the bug**
IT DOESN'T BUILD

**To Reproduce**
Try to build on a Mac

**Expected behavior**
IT BUILDS

**Screenshots**
![Screenshot 2023-01-15 at 01 13 12](https://user-images.githubusercontent.com/120745925/212502693-8902da49-2328-44a4-895b-4cd4520bb799.png)

**Desktop:**
 - OS: MacOS
 - GPU vendor and model: Apple M1
 - Driver version: THE BUILT IN ONE

**Additional context**
../Quake/quakedef.h:292:10: fatal error: 'vulkan/vulkan_core.h' file not found
#include <vulkan/vulkan_core.h>

And yes, I did follow ALL the steps in the Mac build guide.

**Comment by Novum** [comment]
It does build on MacOS just fine. You are somehow missing the Vulkan SDK. Something about your brew is not correctly set up.

**Comment by Novum** [comment]
You can download binaries for each check in from "Actions" if that's easier, e.g. https://github.com/Novum/vkQuake/actions/runs/3920222341

**Comment by UnBeatWaterGH** [comment]
Thx will run brew doctor

**Comment by UnBeatWaterGH** [comment]
A lot of warnings. Time to run brew cleanup

**Comment by UnBeatWaterGH** [comment]
Manually fixing everything...

**Comment by UnBeatWaterGH** [comment]
Too many warnings... Will have to come back to it later.

**Comment by UnBeatWaterGH** [comment]
Have fixed my build environment, will try to build.

**Comment by UnBeatWaterGH** [comment]
Nope same error.

**Comment by UnBeatWaterGH** [comment]
Which makes no sense.
