### ISSUE TITLE
Raspberry Pi 4B + Mesa V3DV rendering errors

### ISSUE THREAD

**Issue by danmons** [Novum/vkQuake#616]
On a Raspberry Pi 4B running X11 and GCC12, I've tested the following combinations:

* Raspberry Pi OS dist-upgraded to Debian "Bookworm", RPiOS-provided kernel 5.15.76, Debian-provided Mesa 22.3.2
* Same as above, but compiled in Mesa from git, currently 23.1.0-devel
* Armbian Jammy, kernel 6.1.5, Mesa 23.1.0-devel

And compiling vkQuake directly from git (I've been pulling and re-testing both vkQuake and Mesa for about a month now).

The various text overlays, weapon models, and character models all look fine.

Walls, columns, floors etc all have texture rendering errors, as captured in the attached screenshots.  Changing different lighting, rendering and texture options in `vkQuake.cfg` makes no different to the outcome that I can find.  Likewise, no difference if fullscreen, borderless fullscreen or windowed. 

Unsure if it's a Mesa problem or a vkQuake problem, however other Vulkan demos (Sascha Willems demos, vkcube, vkmark2, etc) all render as expected.  

[edit] If I follow the exact same build process on my Ryzen laptop with Radeon 5600 video card running Arch Linux and Mesa, no problems.  Renders as expected. 

![2023-01-15_15-25_2](https://user-images.githubusercontent.com/7758354/212525011-f2b7e34f-4478-4910-9f21-e7d692239550.png)
![2023-01-15_15-25_3](https://user-images.githubusercontent.com/7758354/212525013-c6549cdb-c475-42a5-ac93-c54c5a774398.png)
![2023-01-15_15-25_4](https://user-images.githubusercontent.com/7758354/212525015-9165df02-7912-4aeb-ad15-1f4f74aee7be.png)
![2023-01-15_15-25_5](https://user-images.githubusercontent.com/7758354/212525017-c2f1d526-efe4-4d3e-aff4-d30cf363cd7b.png)

**Comment by Novum** [comment]
You should report that to the driver people, I doubt there is an actual vkQuake issue. I couldn't test it anyway.

**Comment by danmons** [comment]
OK thanks, I'll report it to the Mesa developers.
