### ISSUE TITLE
[Feature request] r_scale 3 in console

### ISSUE THREAD

**Issue by MattHorn25** [Novum/vkQuake#618]
This of course depends a lot on monitor DPI and such, but I think r_scale steps are a bit too coarse right now - for example, for me personally a 3x scaling would work well with my screen to get large but not too large pixels.

So, broadly speaking it might be good to make r_scale more granular in general, but specifically a Render Scale setting of 1/3 would be great. To keep it simple this _doesn't_ need to be available in the menu setting! I'd just like 'r_scale 3' (or any other value) in console to scale to that exact multiple instead of rounding down to the nearest available setting.

**Comment by Novum** [comment]
Can't be performantly inplemented due to technical reasons.
