### ISSUE TITLE
QUAKE ERROR: vkWaitForFences failed

### ISSUE THREAD

**Issue by btegs** [Novum/vkQuake#62]
I'm getting this error with the 0.60+ series with my Nvidia GTX 970 running Ubuntu 16.04. I'm running the 370 drivers from https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

Here's what I am getting in the terminal when starting a new single player game:

Command line: /usr/games/vkquake -basedir /usr/share/quake
Found SDL version 2.0.4
Detected 8 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.92.0 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 0.60.0 (c) Axel Gneiting
Host_Init
Playing registered version.
Console initialized.
UDP Initialized
Server using protocol 666 (FitzQuake)
Exe: 13:09:31 Aug 19 2016
256.0 megabyte heap

Vulkan Initialization
Vendor: NVIDIA
Device: GTX 970
Creating command buffers
Creating swap chain
Creating render passes
Creating color buffer
Creating depth buffer
Creating frame buffers
Initializing staging
Creating descriptor set layouts
Initializing dynamic vertex buffers
Initializing dynamic index buffers
Initializing dynamic uniform buffers
Initializing samplers
Creating pipeline layouts
Creating pipelines

Sound Initialization
SDL audio spec  : 44100 Hz, 512 samples, 2 channels
SDL audio driver: pulseaudio - GM204 High Definition Audio Controller Digital Stereo (HDMI 2), 32768 bytes buffer
Audio: 16 bit, stereo, 44100 Hz
CDAudio disabled at compile time

========= Quake Initialized =========

execing quake.rc
execing default.cfg
execing config.cfg
Initializing samplers
execing autoexec.cfg
Unknown command "gl_texturemode"
Unknown command "gl_texture_anisotropy"
Unknown command "r_oldwater"
Unknown command "r_quadparticles"
3 demo(s) in loop

FITZQUAKE 0.85 SERVER (24778 CRC)


Introduction
Using protocol 666
Shutting down SDL sound

QUAKE ERROR: vkWaitForFences failed

**Comment by ProfessorKaos64** [comment]
Vkfences is a basic level thing. Try running see Vulkan examples fr the SDK. 

On August 19, 2016 6:37:09 PM EDT, btegs <notifications@github.com> wrote:
>I'm getting this error with the 0.60+ series with my Nvidia GTX 970
>running Ubuntu 16.04. I'm running the 370 drivers from
>https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa
>
>I have attached an error log.
>[bteg_vkquake_fences.txt](https://github.com/Novum/vkQuake/files/427995/bteg_vkquake_fences.txt)
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Novum/vkQuake/issues/62

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by btegs** [comment]
I resorted back to the 364 driver and the game works as it should. I wonder if this is happening due to 370 still in beta on Nvidia's side. Maybe this is something Axel can discuss with Nvidia since he has the power by working at id. :-)

**Comment by Novum** [comment]
Failing on fence wait is usually a sign that the GPU locked up.

**Comment by Vash63** [comment]
Same error here on the same driver. The Talos Principle on Vulkan still works without issue.

**Comment by Novum** [comment]
Talos is not indicative. It's not using input attachments or sub passes. I still think this is a driver bug.

**Comment by damienleone** [comment]
Thanks for reporting this issue.  I do confirm that this is a bug in the NVIDIA 370 beta release.  It will be fixed in the 370 public release.
