### ISSUE TITLE
MD5 player model crash

### ISSUE THREAD

**Issue by temx** [Novum/vkQuake#622]
`GL_DrawAliasFrame` will crash due to null `tx` with `chase_active 1` (or in multiplayer when you see another player). I suspect this needs some special handling due to player colors but I haven't checked.

**Comment by Novum** [comment]
I... don't really ever test multiplayer

**Comment by temx** [comment]
https://github.com/Novum/vkQuake/commit/1d344170f35b3adc2fb831945d8c7980f2c11833

**Comment by Novum** [comment]
Thanks
