### ISSUE TITLE
-Warray-bounds warning

### ISSUE THREAD

**Issue by sezero** [Novum/vkQuake#623]
Emitted by gcc-7, but not by gcc-9. Possibly a false positive, but just letting you know.

```
r_brush.c: In function ‘R_UpdateLightmapsAndIndirect’:
r_brush.c:2900:38: error: array subscript is above array bounds [-Werror=array-bounds]
        if (lightmap_regions[j][y + h][i] != type)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```

**Comment by temx** [comment]
I don't see any issue; maybe it's related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59124 ?
Just in case I also added
```
assert (j >= 0 && j < UPDATE_LIGHTMAP_BATCH_SIZE && 
	y + h >= 0 && y + h < LMBLOCK_HEIGHT / LM_CULL_BLOCK_H && 
	i >= 0 && i < LMBLOCK_WIDTH / LM_CULL_BLOCK_W);
```
before that access and it doesn't fire (even if `lightmap_regions` is constant and != 0).

Maybe checking `i < LMBLOCK_WIDTH / LM_CULL_BLOCK_W` would silence it, but it's extra code and I don't know if we want to support old compilers out of the box (I think MSVC 2019 also needs some additional warning suppressions now).

**Comment by sezero** [comment]
> I don't see any issue; maybe it's related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59124 ?

Possibly,

> Just in case I also added
> 
> ```
> assert (j >= 0 && j < UPDATE_LIGHTMAP_BATCH_SIZE && 
> 	y + h >= 0 && y + h < LMBLOCK_HEIGHT / LM_CULL_BLOCK_H && 
> 	i >= 0 && i < LMBLOCK_WIDTH / LM_CULL_BLOCK_W);
> ```
> 
> before that access and it doesn't fire (even if `lightmap_regions` is constant and != 0).
> 
> Maybe checking `i < LMBLOCK_WIDTH / LM_CULL_BLOCK_W` would silence it, but it's extra code and I don't know if we want to support old compilers out of the box (I think MSVC 2019 also needs some additional warning suppressions now).

We _can_ ignore this: gcc-9 doesn't warn. What do you guys say?

**Comment by temx** [comment]
I'd either disable that specific warning for gcc < 9, or ignore it.

**Comment by sezero** [comment]
My vote is ignoring it as it looks like working around it adds unnecessary complexity. Feel free to close this.

**Comment by Novum** [comment]
I don't want to disable the warning and I personally don't compile with older GCC versions. I guess we can close this. If someone wants to compile with older GCC versions they can suppress the warning.
