### ISSUE TITLE
MD5 lightning mismatch

### ISSUE THREAD

**Issue by temx** [Novum/vkQuake#624]
The textures have identical brightness, and in the rerelease models have the same apparent brightness.
In vkQuake, in the start hall, the MD5 viewmodel looks darker, the zombies in the right wall lighter, and the zombies in the left wall darker.
It's likely the normals and/or vertex color calculation are off.

**Comment by Novum** [comment]
Could be the normal calculations. They looked fishy when I copied code from QSS.

**Comment by Novum** [comment]
b5eef77744ce5ff9aa9e73e240ee2d7b4b4a3f89 fixes the seams, but the MD5 models are still brighter. I wonder if the old models actually have slightly short normals?

**Comment by Novum** [comment]
@temx I also tried normalizing the normals in `alias.vert` and I get the same output. That means it's not the length, but orientation of the normals. I wonder if the original models just have bad normals?

**Comment by temx** [comment]
Don't the normals need to get pose transformed and lerped too? Using `in_normal.zyx` certainly looks a lot closer for the viewmodel at least, even though the facing is wrong.

**Comment by Novum** [comment]
The difference is already there in the t-pose. Theoretically yes, you have to transform normals, but it's not a trivial problem and lots of games just skip it.

**Comment by Novum** [comment]
Looking further, it seems like the old models only use a specific set of normals defined in `anorms.h`. Probably not extremely precise. Would be interesting what happens if the normals are properly computed on them.

**Comment by Novum** [comment]
Nevermind, I checked the normals in RenderDoc and they are definitely completely different. Something is wrong with the normal calculation imported from QSS (wrong output space perhaps).

**Comment by Novum** [comment]
Seems like they were just completely flipped d8c8101b8b56d5e0fb8dd25d49237bec811e84da
Good eye.
