### ISSUE TITLE
viewsize greater than 100 crash the game

### ISSUE THREAD

**Issue by djleon83** [Novum/vkQuake#625]
**Describe the bug**
i just installed the fbx++ bot, in vkquake.cfg, i bind "+" "impulse 100" to add bot.
when in multiplayer game i press + key add 1 bot. it works.
but when i quit game and restart, the game can not run and crash.
then i check the cfg file, find that the "viewsize" is set to "110", when i change the value back to "100", the game runs well.

**Desktop (please complete the following information):**
 - OS: WIN10
 - GPU GTX3060 notebook

**Comment by djleon83** [comment]
vkquake version is vkQuake-1.22.3_win64.

**Comment by Novum** [comment]
Cannot reproduce.

**Comment by djleon83** [comment]
> 

driver version is 528.49
