### ISSUE TITLE
please move the scroll bar in the mod menu further to the right

### ISSUE THREAD

**Issue by powerpuffboysz** [Novum/vkQuake#628]
Vkquake and its ingame mod menu is amazing but seeing the scroll bar overlap longer mod names is a bit of an eyesore and was wondering if this could be adjusted.

**Comment by Novum** [comment]
What mods specifically have such long names?

**Comment by powerpuffboysz** [comment]
No particular mod but in general. I like using proper names for mod folders instead of whatever shortname the map maker used.
![20230214_185245_1](https://user-images.githubusercontent.com/11527009/218889645-8b2108d9-3868-425f-aab5-695c5528649b.gif)

**Comment by Novum** [comment]
Okay, I didn't think people would use such names. I guess we need to elide them with `...` if they are too long. Also can probably make it a bit wider.

**Comment by vide0hanz** [comment]
What about just moving the scroll bar to the left instead?

**Comment by vide0hanz** [comment]
Actually, what about calculating the X position of the scrollbar relative to the longest string printed in-menu?

**Comment by Novum** [comment]
I'm working on this as part of a bigger change.

**Comment by Novum** [comment]
54368656739f1857eadbf6e238c138ecfb5f3dbe
