### ISSUE TITLE
QUAKE ERROR: Couldn't create Vulkan instance

### ISSUE THREAD

**Issue by Mellosaurio** [Novum/vkQuake#629]
Hi, this is probably an error on my system, not on vkquake itself but i couldn't find anyone with this same erro. Basically when i ran the the binaries or the appimage (I'm on a freshly install of arch linux) it spits out this error

Found SDL version 2.26.1
Detected 8 CPUs.
Initializing vkQuake v1.22.3
Built with GCC 7.5.0
Host_Init
Playing registered version.
Console initialized.
UDP4 Initialized
UDPv6 Initialized
Server using protocol 999+ (FTE-RMQ)
Exe: 08:11:47 Dec 12 2022

Vulkan Initialization
Using Vulkan 1.1

ERROR-OUT BEGIN

QUAKE ERROR: Couldn't create Vulkan instance

I'm not sure what is missing or what i'm doing wrong but any help is appreciated

Thanks

**Comment by Novum** [comment]
You need to install the Vulkan runtime. It's not a vkQuake bug.
