### ISSUE TITLE
Some textures are green on AMD

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#63]
Checking with RenderDoc shows G channel to be completely white. Haven't investigated further yet.

**Comment by SaschaWillems** [comment]
![vkquake](https://cloud.githubusercontent.com/assets/10283127/17836463/0baa17fe-6794-11e6-9726-061348f733aa.jpg)
I can confirm this with a R9 390 using the latest beta drivers (16.98.2). Only happens on certain objects like health creates and gibs.

**Comment by Srandista** [comment]
I can confirm that as well, still presenting in vkQuake 0.70.0. (Radeon RX 470 - Crimson 16.8.2)

**Comment by Novum** [comment]
Fixed by https://github.com/Novum/vkQuake/commit/9d66d0e716921391c1707e5333ccb32144c9fdbb
