### ISSUE TITLE
Rendering bugs in Dwell 2

### ISSUE THREAD

**Issue by penasea** [Novum/vkQuake#631]
**Describe the bug**
The transparent water in Dwell 2 d2m6.bsp shows rendering bugs when moving around:
[Video 1](https://user-images.githubusercontent.com/126418320/221432720-8417b8cf-7c45-4862-b0fb-9374561a09e8.webm)
And some of the stones always look odd:
[Video 2](https://user-images.githubusercontent.com/126418320/221432744-d377f551-2de9-4da6-a4ce-a3058a83bd91.webm)

**To Reproduce**
Load Dwell 2 (game dwellv2p2), load the map (map d2m6), look around.

**Expected behavior**
Correct rendering.

**Screenshots**
See above.

**Desktop**
 - OS: Windows 10
 - Nvidia GeForce 1060 6 GB
 - Driver version 528.49

**Comment by Novum** [comment]
What version is this? There has been a bug fix already that sounds like it's the same problem: https://github.com/Novum/vkQuake/commit/4c89ff1059906f36e51fd9a3929814776b18dbb4

**Comment by temx** [comment]
4c89ff1 shouldn't affect this. The flickering is due to entities being added in the order of their first visible leaf; if they span more than one leaf the order depends on visibility (incl. frustum culling). The other stuff is just alpha drawn in the wrong order.

**Comment by Novum** [comment]
Why does this not happen in Quakespasm then? Or does it?

**Comment by temx** [comment]
It does affect QuakeSpasm, I think it renders exactly the same there.
IW has three modes (OIB, distance sorted, and "QS-like" but stable). The rerelease also uses OIB.

**Comment by Novum** [comment]
ef8260517e68e4f523c0305aa482677aa53849f8
