### ISSUE TITLE
'vkBindImageMemory failed' error with mingw x64 builds

### ISSUE THREAD

**Issue by sezero** [Novum/vkQuake#634]
MinGW x64 builds error out with 'vkBindImageMemory failed' since the new heap changes. gcc is 7.5.0 if it matters. The msvc builds from CI runs seem to be fine. Nvidia driver is version 512.95. Haven't tested x86 builds.

**Comment by sezero** [comment]
I _think_ the culprit is https://github.com/Novum/vkQuake/commit/aed941aaa4aa08a1753791f1a6e80a9596969224 where `__builtin_clz` is used wrongly: `_BitScanReverse` is just `bsr`, but `__builtin_clz` is `31 ^ bsr`. Testing a patch in a few minutes.

**Comment by Novum** [comment]
Yeah, those might be wrong. Oops.

**Comment by sezero** [comment]
https://github.com/Novum/vkQuake/commit/b6890117151de1d6f0e07049b4711841112ee921

**Comment by sezero** [comment]
One issue with https://github.com/Novum/vkQuake/commit/aed941aaa4aa08a1753791f1a6e80a9596969224 is that bad things would happen if Q_log2 or Q_nextPow2 is ever called with 0 -- although their current uses don't seem to be..

**Comment by Novum** [comment]
log(0) is undefined anyway, it doesn't make any sense. I considered adding an assert.

**Comment by andrey-budko** [comment]
btw, trunk gcc (and clang _before_ 13 for some reason) can recognize clz  code patterns
https://godbolt.org/z/vs8E3bWsc

another funny example:
https://godbolt.org/z/W5YdWoTE4

**Comment by sezero** [comment]
Bad thing is, gcc < 12 doesn't reduce its output with `31 - __builtin_clz (val)`
only `31 ^ __builtin_clz (val)` -- clang is good

**Comment by Novum** [comment]
I find relying on pattern matching unreliable if I definitely want a single instruction.
