### ISSUE TITLE
Incorrect lighting in AD_AZAD

### ISSUE THREAD

**Issue by Macil** [Novum/vkQuake#639]
When you go to the final boss chamber in Arcane Dimension's AD_AZAD (1.80p1), there are some white cutout surfaces that instantly turn black when you get close to them.

![vkquake0002](https://user-images.githubusercontent.com/577345/223070595-a13d7058-b879-4144-b9a9-8627577e8b70.jpg)
![vkquake0003](https://user-images.githubusercontent.com/577345/223070613-610b324a-288f-496e-b3cb-7b9302be5349.jpg)

Here's a save file right at the place the issue triggers: [s11.sav.zip](https://github.com/Novum/vkQuake/files/10896425/s11.sav.zip)

The issue first showed up in ef8260517e68e4f523c0305aa482677aa53849f8. The issue goes away if `r_alphasort 0` is set.

**Desktop:**
 - OS: reproduced on both MacOS and Linux Steam Deck

**Comment by temx** [comment]
Thanks for the report, 21ad336 should take care of it.
