### ISSUE TITLE
QUAKE ERROR: Couldn't create swap chain

### ISSUE THREAD

**Issue by salvadorp2001** [Novum/vkQuake#64]
Compiled from code cloned today
`Command line: ./vkquake`
`Found SDL version 2.0.4`
`Detected 6 CPUs.`
`Quake 1.09 (c) id Software`
`GLQuake 1.00 (c) id Software`
`FitzQuake 0.85 (c) John Fitzgibbons`
`FitzQuake SDL port (c) SleepwalkR, Baker`
`QuakeSpasm 0.92.0 (c) Ozkan Sezer, Eric Wasylishen & others`
`vkQuake 0.70.0 (c) Axel Gneiting`
`Host_Init`
`Playing shareware version.`
`Console initialized.`
`UDP Initialized`
`Server using protocol 666 (FitzQuake)`
`Exe: 18:02:57 Aug 29 2016`
`256.0 megabyte heap`

`Vulkan Initialization`
`Vendor: AMD`
`Device: AMD Radeon (TM) R7 300 Series`
`Creating command buffers`
`Creating swap chain`
`Using IMMEDIATE present mode`

`ERROR-OUT BEGIN`

`QUAKE ERROR: Couldn't create swap chain`

**Comment by boltronics** [comment]
I'm getting this too, however the problem in intermittent. I usually have to try to run the `vkquake` command a bunch of times before it eventually starts without the above error. Makes it hard to regression test (which I was originally trying to do).

Tested setup:
* vkquake 14fa407480a0865ef4ce3945ad91b8d06d97e05a (master HEAD at time of posting, and can also reproduce with the tagged `0.71` release).
* Ubuntu 16.04.1 LTS fully updated.
* Vulkan https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/a72588228fcdb9e4187be912d88595e9fedea416 (master HEAD at time of posting) - API version 1.0.30 reported from `vulkaninfo`
* Two Fury X GPUs.
* AMDGPU-Pro 16.30.3-315407 (latest at time of posting)

**Comment by Novum** [comment]
This is very likely a driver bug.

**Comment by boltronics** [comment]
I think you might be right. It does seem to have went away after updating Mesa master, and reverting to libvulkan 1.0.26 as packaged in Debian testing.

**Comment by kaadmy** [comment]
I'm getting this error now, latest Arch Linux. Didn't happen a month or so ago.

**Comment by LethalManBoob** [comment]
Anyone here tried manually updating to latest vulkanrt version?

**Comment by mikae1** [comment]
Can’t launch vkQuake 1.31.1. Haven’t been able to launch earlier versions either. I get:
~~~
Found SDL version 2.30.4
Detected 8 CPUs.
Initializing vkQuake 1.31.1
Built with GCC 9.4.0
Host_Init
Playing registered version.
Console initialized.
UDP4 Initialized
UDPv6 Initialized
Server using protocol 999+ (FTE-RMQ)
Exe: 16:44:42 Aug  2 2024

Vulkan Initialization
Using Vulkan 1.1
Instance extensions:
 VK_KHR_surface
 VK_KHR_xlib_surface
 VK_KHR_get_surface_capabilities2
 VK_KHR_get_physical_device_properties2

Vendor: NVIDIA
Device: NVIDIA GeForce GTX 970M
Driver: NVIDIA 545.29.06
Using subgroup operations
Device extensions:
 VK_KHR_swapchain
 VK_KHR_get_memory_requirements2
 VK_KHR_dedicated_allocation
 VK_EXT_subgroup_size_control
Using A2B10G10R10 color buffer format
Using D32_S8 depth buffer format

Creating command buffers
Initializing staging
Creating descriptor set layouts
Reallocating dynamic vertex buffers (256 KB)
Reallocating dynamic index buffers (1024 KB)
Reallocating dynamic uniform buffers (256 KB)
Initializing samplers
Texture lod bias: 0.000000
Creating pipeline layouts
Allocating lightstyles buffer (0 KB)
Allocating lights buffer (8 KB)

Sound Initialization
Using IMMEDIATE present mode

ERROR-OUT BEGIN


QUAKE ERROR: Couldn't create swap chain
~~~
