### ISSUE TITLE
Nehahra mod crash on startup

### ISSUE THREAD

**Issue by Placo** [Novum/vkQuake#641]
When selected in the mods menu, vkQuake crashes to desktop with the error:
"sprites/explode1.spr32 has wrong version number (32 should be 1)."
This is with vkQuake 1.22.3 on windows.

The problem might be inherited from quakespasm, I have the same error in Ironwail 0.7.0.
FWIW the mod works in Mark V.
The mod is ancient at this point, not sure if you still want to support it.

**Comment by Novum** [comment]
Not a bug. Nehara always required its own custom engine.
