### ISSUE TITLE
Interface Scale only adjusts the HUD while using the mouse

### ISSUE THREAD

**Issue by vide0hanz** [Novum/vkQuake#644]
- OS: Arch Linux
- Nvidia GeForce RTX 2080 SUPER
- Driver version 525.89.02

Playing around with the new menus recently implemented and noticed some inconsistent behavior with the Interface Scale option:

- Adjusting the scale with the keyboard arrow keys increases both menu text as well as the in-game HUD.
- Adjusting the scale with the mouse only affects the HUD, while menu text remains the same.

I'm guessing this is a bug since one would probably expect the behavior to be consistent. That said, it is kinda nice to be able to adjust the HUD and menu scaling independently even if this is an unintended side-effect... perhaps this could be seen as a feature :)

**Comment by Novum** [comment]
Thanks for reporting, it is likely a bug.

**Comment by temx** [comment]
Does it not resize the menus once you release the mouse? It waits so that the slider doesn't move around while you're adjusting it, but the scale should apply once you're no longer grabbing it.

**Comment by vide0hanz** [comment]
Just checked, and yeah the scale does get applied correctly after releasing the mouse button. 

I guess I didn't even think to try that, and I didn't notice before reporting because I would just move the slider all the way to the left before releasing the mouse button, which is my personal preference. 

Is there a reason why the HUD scales instantly but the menu does not? I think that it would feel nicer to have instant feedback on both while using the slider.

**Comment by Novum** [comment]
You would be resizing the slider that you are currently dragging causing a feedback loop because the mouse cursor positon does not scale with it.

**Comment by temx** [comment]
If you're curious you can apply this patch and see for yourself:
``` diff --git a/Quake/menu.c b/Quake/menu.c
index 0eb7f0d3..00842118 100644
--- a/Quake/menu.c
+++ b/Quake/menu.c
@@ -128,10 +128,7 @@ M_GetScale
 */
 float M_GetScale ()
 {
-       static float latched_menuscale;
-       if (!slider_grab)
-               latched_menuscale = scr_menuscale.value;
-       return latched_menuscale;
+       return scr_menuscale.value;
 }
```

**Comment by vide0hanz** [comment]
That makes perfect sense. I'm sorry for jumping the gun and reporting a non-issue, I'll be more thorough next time I file a bug report.

**Comment by Novum** [comment]
I have no issue with filing bug reports if they are not completely low effort.
