### ISSUE TITLE
Mouse can move cursor immediately on menu open

### ISSUE THREAD

**Issue by Macil** [Novum/vkQuake#647]
When you press escape to open the main menu or you pick a menu option to enter a new menu, if the mouse happens to show up on a menu option then it gets highlighted. The place the mouse shows up tends to be pretty random to the user, and if the user is used to using keyboard keys to control the menu, then their muscle memory of how to quick get through the menu will be useless and lead to the wrong options being activated if they quickly input some keypresses.

This issue is a bit more prevalent on MacOS since https://github.com/sezero/quakespasm/pull/49 centers the cursor whenever a menu is *closed*, so a user who closes a menu and then reopens it before moving will always find their cursor in the dead center of the screen, which means every menu (not just the main menu) will start with the middle option highlighted.

I think an ideal behavior (which is similar to what many games do to hide the mouse when controller input is being used) would be that the mouse would only highlight a menu option if my last keyboard or mouse interaction was with the mouse (and maybe the mouse would be hidden otherwise). If I press escape to open a menu, the mouse position should be ignored until I either move or click the mouse. If I open a new menu through pressing enter, then in the new menu the mouse position should continue to be ignored until I either move or click it. But if I open a new menu through clicking a menu option, then I expect the mouse position to be acknowledged immediately when I go into the new menu.

The Kex port does some things a little different that helps address this issue that I think are interesting to compare against:
1. The menu cursor location isn't actually updated by the mouse. (If you open the menu, position the menu cursor on the first option using keyboard/controller, mouse over the third option, then press down, the *second* option becomes highlighted.) When you move the mouse, the game switches from rendering using the true menu cursor location to just rendering the menu as if the cursor is at the option under the mouse if any. This fixes the muscle memory issue, but it does treat keyboard input as a second class citizen: it is a little confusing to open the menu, see a specific option highlighted because the mouse happened to land on it, press an arrow key, and see the cursor move from a different location. (If the mouse either didn't show up until moving, or if it always started at a spot not over a menu option, then it would be pretty great.)
2. The mouse only shows up on menu open if it's been interacted with at all since the last time the mouse was captured, otherwise it doesn't show up until it's clicked/moved. It doesn't address this issue when mouse&keyboard are in use, but it does actually address this issue when a controller is used alone. If this behavior were cloned by itself (without 1) and then extended for mouse&keyboard case so the mouse doesn't show up in the menu until interacted with, then that includes the behavior of my suggestion above and addresses this issue.

**Comment by Novum** [comment]
Patches welcome :)

**Comment by Novum** [comment]
So I've looked at the remastered version and it just renders two different blinking cursors: One for the mouse and one for the current keyboard location. Probably a good way to deal with this.

**Comment by Novum** [comment]
b120683a917866d87e4e30cd3164c8850a176046
