### ISSUE TITLE
Teleporters/liquids disappear on map restart

### ISSUE THREAD

**Issue by Macil** [Novum/vkQuake#655]
If you start a new game (using the rerelease basedir), and then either start a new game again or die and respawn, then the teleporter surfaces and lava will be missing:

![vkquake0000](https://user-images.githubusercontent.com/577345/224613445-64f65424-cc23-4f68-bce1-12fc115cda4f.jpg)

This reliably occurs for me in both MacOS and Linux.

The issue is introduced in 810725bcb482f00f2cd9c4548600e9beb3b58abe.

**Comment by Novum** [comment]
Can reproduce this trivially

**Comment by Novum** [comment]
Reverted by cf3d322a7a066734b5230d76312183b7f51b12fb
@temx not opposed to the change, just want to keep top of tree bug free. Feel free to re-apply if fixed.
