### ISSUE TITLE
Key icon in modern HUD

### ISSUE THREAD

**Issue by dezo2** [Novum/vkQuake#659]
Can we also have key icon in modern HUD? Like in Ironwail above the ammo icon, that would be great.
![start_2023-03-13_18-27-33](https://user-images.githubusercontent.com/33813081/224781083-161cf48e-6ed4-45c3-9860-4d2696ee556c.png)

**Comment by Novum** [comment]
66a559d96a9ac14740d02882ccf6c671305e07a3
