### ISSUE TITLE
Skybox glitching in some maps (version 1.30.0)

### ISSUE THREAD

**Issue by Noryokusha** [Novum/vkQuake#663]
Some maps has the skybox appears to be glitched out like following the player's mouse input. Rolling back to version 1.22.3 seems to fix the issue

Tested on maps: qbj_rabbit7250, ad_swampy
HW: RX 6750 XT driver 23.2.2
![skybox_glitch_AdobeExpress](https://user-images.githubusercontent.com/127869965/225045989-4d51d535-3a7e-4afa-9cc2-1735bb5c46ce.gif)

**Comment by temx** [comment]
This only happens on AMD cards. Not sure if related, but I get the following validation error on startup **only when using the AMD driver**:

`Validation Error: [ VUID-VkBufferCreateInfo-usage-requiredbitmask ] Object 0: handle = 0x25116569d90, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7a4eee71 | vkCreateBuffer: value of pCreateInfo->usage must not be 0. The Vulkan spec states: usage must not be 0 (https://vulkan.lunarg.com/doc/view/1.3.236.0/windows/1.3-extensions/vkspec.html#VUID-VkBufferCreateInfo-usage-requiredbitmask)`

Stack: `Host_Init()` -> `VID_Init()` -> `R_CreatePaletteOctreeBuffers()` -> `R_CreatePaletteOctreeBuffers()` -> `vkCreateBuffer()` line 4092

**Comment by Novum** [comment]
Okay, will fix this later today.

**Comment by temx** [comment]
The issue is unrelated to usage flags, it's validation clean now.

**Comment by temx** [comment]
@Noryokusha Can you test the build from https://github.com/Novum/vkQuake/suites/11556845572/artifacts/598366111 and confirm it fixes the issue for you?

**Comment by Noryokusha** [comment]
@temx yep it totally fix the issue for me. thank you
