### ISSUE TITLE
in game messages are still broken when using remastered paks

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#665]
linux build 1.30

**Comment by Novum** [comment]
Please be more specific. Low effort bug reports will be closed.

**Comment by LethalManBoob** [comment]
> Please be more specific. Low effort bug reports will be closed.
![vkquake0000](https://user-images.githubusercontent.com/30273211/225120498-0a1833cd-2a59-430c-ad00-8bde7e5b0265.png)

**Comment by Novum** [comment]
Works fine here.

**Comment by LethalManBoob** [comment]
> Works fine here.
I downloaded the appimage and put in the files from the remaster and then I get this

**Comment by Novum** [comment]
You very likely are missing `QuakeEX.kpf` in the Quake root folder.

**Comment by LethalManBoob** [comment]
> You very likely are missing `QuakeEX.kpf` in the Quake root folder.

My bad. Fixed.

**Comment by Novum** [comment]
Install instructions says to copy the executable into the rerelease folder. That works just fine.

**Comment by LethalManBoob** [comment]
> Install instructions says to copy the executable into the rerelease folder. That works just fine.

ah crap I forgot to mention it was build in arch. That changes it to where you need to drag the relevant quake files into the .vkquake file in the home directory.
