### ISSUE TITLE
"Animation" setting resets to "Smooth" when game is restarted.

### ISSUE THREAD

**Issue by the-big-cool** [Novum/vkQuake#667]
**Describe the bug**
When the game is quit and then booted up again, the "Animation" setting will be reset to "Smooth" no matter what it was set to when the game was closed.

**To Reproduce**
Set the "Animation" setting to "Classic", restart the game, and observe that the setting is changed to "Smooth".

**Expected behavior**
The "Animation" setting should remain as it was when the game was closed.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - GPU: RTX 3060 Ti
 - Driver Version: GeForce Game Ready Driver Version 531.29

**Comment by Novum** [comment]
d772268add54c7fffa6e94d5e0e4c5f0da6da8f9

**Comment by Novum** [comment]
Thanks for the report
