### ISSUE TITLE
I seem to be phasing through medkits on nightmare mode.

### ISSUE THREAD

**Issue by LethalManBoob** [Novum/vkQuake#670]
I used the arch build and the app image. Even reset the config and made new games but they all have medkits that randomly don't work. Im on the remaster btw.

**Comment by LethalManBoob** [comment]
[s0.zip](https://github.com/Novum/vkQuake/files/10990842/s0.zip)
Here is a save file for quick testing. Just go to the right behind the boxes for 2 medkits.

**Comment by temx** [comment]
The remaster changed nightmare skill to limit health to 50 (though for some reason, it doesn't decay when you select it, or in the start -> e1m1 transition).

**Comment by Novum** [comment]
So not a bug?

**Comment by LethalManBoob** [comment]
Seems more like a poorly implemented change by the looks of it. 
Would be nice for the option to restore default behaviour. I always run nightmare but this has me reconsidering.

**Comment by sezero** [comment]
Not a bug.
