### ISSUE TITLE
1.30.1 - QUAKE ERROR: Couldn't create Vulkan device Linux

### ISSUE THREAD

**Issue by JoshuaPettus** [Novum/vkQuake#671]
When I try to launch the executable I get this out put from the commandline 

> Found SDL version 2.26.2
> Detected 12 CPUs.
> Initializing vkQuake v1.30.1
> Built with GCC 7.5.0
> Host_Init
> Playing registered version.
> Console initialized.
> UDP4 Initialized
> UDPv6 Initialized
> Server using protocol 999+ (FTE-RMQ)
> Exe: 03:00:17 Mar 15 2023
> 
> Vulkan Initialization
> Using Vulkan 1.1
> Instance extensions:
>  VK_KHR_surface
>  VK_KHR_xlib_surface
>  VK_KHR_get_surface_capabilities2
>  VK_KHR_get_physical_device_properties2
> 
> Vendor: NVIDIA
> Device: NVIDIA GeForce RTX 2080 Ti
> Driver: NVIDIA 470.161.03
> Using subgroup operations
> Using ray queries
> 
> ERROR-OUT BEGIN
> 
> QUAKE ERROR: Couldn't create Vulkan device

Using Fedora 37

I don't get any other information as to why it failed.  It did work with 1.22.3.   Not sure what else I can provide

**Comment by Novum** [comment]
Does other applications that use Vulkan ray tracing work? Very likely a borked driver.

**Comment by j4reporting** [comment]
I have no issue with the driver installed from rpmfusion.org  (RTX 2060) on Fedora37,   driver version is 525.89.02.  I'm not using the appimage, though. But this should  not make any difference.

**Comment by Novum** [comment]
It's not an application issue. If I would have to guess it's likely that `libnvidia-rtcore` isn't correctly installed.

**Comment by JoshuaPettus** [comment]
Thank you everyone. I agree, it must be that,  Thank you for pointing me in the right direction and  your suggestions.  I'll give it a try when I can take a look at it.    In answer to the vulkan ray tracing, I'm not sure i have any other applications that make use of ray tracing.

**Comment by JoshuaPettus** [comment]
Thanks again,  I managed to clean the slate, and get the rpmfusion.org drivers working.  It's working great now.  Thanks again for pointing me in the right direction!

**Comment by Novum** [comment]
Glad that it works

**Comment by JoshuaPettus** [comment]
Their point is it's a setup issue.  There is nothing wrong with the app itself.  I myself had to do some digging online, totally clear out all NVIDIA drivers and reinstall from scratch.  Made more difficult as I need it to work with SecureBoot but not impossible.

**Comment by Novum** [comment]
@jgb I'm not your Linux distro support person. It's not an app bug and I will not remove the RT code because some people have corrupted systems.

**Comment by jgb** [comment]
> @jgb I'm not your Linux distro support person. It's not an app bug and I will not remove the RT code because some people have corrupted systems.

Amazing response! The friendliness really oozes from my screen.
I'm running debian (and have been for over 20 years), with the official nvidia binary drivers, and my system works just fine, with games and anything else.
Reinstalling the drivers from scratch didn't help either, neither did installing libnvidia-rtcore.
I'll get back to my "corrupted system" now.
