### ISSUE TITLE
[Feature request] Support for set and seta commands for registering custom cvars

### ISSUE THREAD

**Issue by ilikebreadtoomuch** [Novum/vkQuake#676]
`registercvar()` by itself doesn't allow for cvars to be saved into a config, so `seta` could be extremely useful for modders. Sourceports with `seta` support seem to simply put `seta` commands in the config on exit rather than doing anything too fancy.

P.S.: As of right now, vkQuake seems to report `DP_CON_SET` and `DP_CON_SETA` as supported extensions, even though the commands don't exist. Perhaps they could be removed from the list of supported extensions for the time being while the commands aren't implemented?

**Comment by ilikebreadtoomuch** [comment]
QSS and FTE both have it

**Comment by temx** [comment]
62b308f
