### ISSUE TITLE
Framestutter after v1.30.x. But not allways

### ISSUE THREAD

**Issue by ELFswe** [Novum/vkQuake#677]
There are framestutter since after version 1.30.x. (I went from 1.20.3 to 1.30.1).
This was not a problem in version 1.20.3.
It's not a low fps issue as I'm running the game at a stable 144 fps. But it looks like the game is running at maybe 30fps.

It's not "random" when playing. It only happens when loading a level or a save.
But it can also be fixed by restarting the level or reloading the save. This may have to be done multiple times.

I'm running:
Windows 11 and a AMD gpu.

**Comment by Novum** [comment]
That's not really something I can work with. Are you sure nothing else has changed? Does downgrading solve the problem even with the current system?

**Comment by Novum** [comment]
Closing because of lack of response.

**Comment by ELFswe** [comment]
I reverted back to vkQuake v1.20.3. But I still had the issue.
I might have updated to the latest (at the time) AMD gpu driver before using vkQuake 1.30.1. Not sure though. Updating to the now latest gpu driver didn't help.

But yeah, the problem can't be vkQuake.
