### ISSUE TITLE
[Feature Request] Glquake reflections.

### ISSUE THREAD

**Issue by powerpuffboysz** [Novum/vkQuake#683]
Would it be possible to implement glquake reflections or an alternative that achieves a similar effect?

**Comment by Novum** [comment]
There are no reflections in glQuake. What are you talking about?

**Comment by Novum** [comment]
I have never heard of this before. Do you have a screenshot of the effect in question?

**Comment by powerpuffboysz** [comment]
Unfortunately no. Documentation on the effect amounts to it "existed". Stain glash reflections and mirrors would be Controlled by the r_mirroralpha command. And getting glquake to run on my system has been an absolute no go. Although from what little i could gleam the effect wasnt super well implement and was kinda hacky in glquake

**Comment by temx** [comment]
These were removed by Fitzquake 0.6. They were hardcoded for certain glass textures.

https://user-images.githubusercontent.com/24851409/230679921-7a2c5d44-bbf6-4aba-927c-73a80616d16d.mp4

**Comment by Novum** [comment]
I see. It's kind of unlikely that I will add this obscure feature. Was this even enabled by default? Probably not?

**Comment by garoto** [comment]
GLREADME.TXT says:

```
r_mirroralpha 0.3
This changes one particular texture (the stained glass texture in the EASY 
start hall) into a mirror.  The value is the opacity of the mirror surface.
```

**Comment by Novum** [comment]
So a obscure cvar, as I thought.

**Comment by vsonnier** [comment]
Not interested in adding this super-niche feature.
