### ISSUE TITLE
Much lower FPS on Fullscreen Mode

### ISSUE THREAD

**Issue by ZenixTheNoob** [Novum/vkQuake#690]
**Bug description**
When running the game on anything but Windowed mode, the FPS will be much worse

**To Reproduce**
Compare the FPS between Windowed and Fullscreen mode

**Expected behavior**
Performance should be similar between the two display modes

**Desktop**
 - OS: Windows 10 LTSC 21H2
 - GPU: AMD Radeon RX 6400
 - Driver: 23.4.2

**Additional context**
I tried enabling and disabling Fullscreen Optimizations, but it made no difference. Having MSI Afterburner or OBS opened in the background partially solves this issue.

In the video attached, I'm switching between Windowed and Fullscreen using the ALT + ENTER hotkey.

https://user-images.githubusercontent.com/66651831/235445001-347c3cb6-5407-4734-8a29-b12900e5877c.mp4

**Comment by Novum** [comment]
I can't really do much about this besides tell you to talk to the AMD driver team.
