### ISSUE TITLE
Double barrelled shotgun stuck in the air at the start of ad_gibtropolis (Master branch only (no release yet))

### ISSUE THREAD

**Issue by Placo** [Novum/vkQuake#694]
While testing changes imported from vkquake-vso, I have encountered this issue in ad_gibtropolis (https://www.slipseer.com/index.php?resources/gibtropolis.334/):

At the very start of the map (not the difficulty-select/tutorial map), after the knight on the top of the roof kills the shambler, a double barrelled shotgun appears and normally drops to the ground for the player to collect. In the latest version of the master branch (commit a64ce8c), the shotgun stays in the air, blocking level progression.
It is not an issue in the 1.30.1 release, it works fine there.

After further testing, it appears it is also an issue in vkquake-vso (https://github.com/vsonnier/vkQuake-vso), so it was a little bug introduced during this last year. Strange that it escaped me as I mostly played AD maps in vkquake-vso this last year.

I use windows x64 binaries compiled with VisualStudio2022 for my tests.

![vkquake0000](https://github.com/Novum/vkQuake/assets/26550610/f0794269-7631-4b39-be50-cb75d96c71cf)

**Comment by vsonnier** [comment]
@Placo  Yeah, I've noticed this, and there are other places were it occurs in this map. I've not invastigated this yet, and lack the knowledge here to be honest. For now at least.

For those cases, I just use `noclip` to capture those arial weapons.

Still, I've reassign this issue to myself : I cannot speak for @Novum, but I'm quite sure re-opening the Project doesn't mean he is going to be actively involved in it for fixing bugs or other. 
Instead, the goal is essentially to allow the rest of the community to contribute and make the project live again.

**Comment by vsonnier** [comment]
> It is not an issue in the 1.30.1 release, it works fine there.

Good to know, hopefully this will allow to bisect the culprit. I'll definitety try to find the problem before releasing 1.31.0.

**Comment by vsonnier** [comment]
https://github.com/Shpoike/Quakespasm/blob/e0bae4bce412b8619a4c97ffde492ab354329009/Quake/sv_phys.c#L760-L761

**Comment by vsonnier** [comment]
I've just reverted the above snipset, the other part of  https://github.com/Shpoike/Quakespasm/commit/e0bae4bce412b8619a4c97ffde492ab354329009 looks valid.

Thanks @Placo !

**Comment by Placo** [comment]
That was fast, thanks @vsonnier!
And again, thank you for keeping this awesome engine alive!

Also, new issues are still auto-assigned to @Novum (I did not do the assignement). I don't know if they mind or if it should be turned off or if new issues should be assigned to you.

**Comment by vsonnier** [comment]
Thanks @j4reporting  it worked, thanks for the suggestion.
