### ISSUE TITLE
Link warning when LTO is enabled

### ISSUE THREAD

**Issue by bubbleguuum** [Novum/vkQuake#697]
vkQuake compiled with `gcc 13.3.0` on openSUSE TW, using Meson this time, and lto enabled (`-flto=auto`) which is the default on that distro, makes the linker output this warning:

```
[   12s] ../Quake/mimalloc/segment.c: In function ‘mi_segment_span_free_coalesce’:
[   12s] ../Quake/mimalloc/segment.c:664:30: warning: ‘__atomic_load_8’ writing 8 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
[   12s]   664 |   const bool is_abandoned = (segment->thread_id == 0); // mi_segment_is_abandoned(segment);
[   12s]       |                              ^
[   12s] lto1: note: destination object is likely at address zero
``` 

[Full compilation traces](https://build.opensuse.org/build/home:bobbie424242:branches:games/openSUSE_Tumbleweed/x86_64/vkquake/_log)

The produced binary seems to be working fine (briefly tested) and this is probably benign but I'm mentioning this warning for reference or in case it denotes a real problem and it would be best to disable LTO.

**Comment by vsonnier** [comment]
This is in mimalloc so as long as it is just a warning I'm no going to support any OSS included in vkQuake, and simply assume 'they' know what they are doing :)
