### ISSUE TITLE
AppImage SDL2 version is still 2.28.5

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#699]
Just a PSA, if you update SDL2 you also should update it in the Dockerfile here, otherwise AppImages will use the old SDL2 version:
https://github.com/Novum/vkQuake/blob/f1a54fbdf403f0b2f54dd89879b82e68d5f08fcf/Packaging/AppImage/docker/Dockerfile#L42
Same applies to the clang format version if you want to use `./format.sh`
https://github.com/Novum/vkQuake/blob/f1a54fbdf403f0b2f54dd89879b82e68d5f08fcf/format.sh#L2

**Comment by vsonnier** [comment]
Thanks !
