### ISSUE TITLE
My vk quake doesn't play the demo on start

### ISSUE THREAD

**Issue by reignerdeustcher** [Novum/vkQuake#702]
It just shows the menu, how can i enable the demo level for the base game and all expansions?

**Comment by vsonnier** [comment]
Go to Options => Game => Startup demos = ON. On the next start, demos will be played.

**Comment by reignerdeustcher** [comment]
> Go to Options => Game => Startup demos = ON. On the next start, demos will be played.

i don't have that option in my vkquake...

![20240628_182627 (Medium)](https://github.com/Novum/vkQuake/assets/79814905/5418a05e-675d-4450-9f1f-e5a13055079c)

**Comment by vsonnier** [comment]
Your vk version is juste too old. If you type `version` on the console, or on the console itself in the low-right corner, you should see `vkQuake 1.31.0` otherwise it is an old version.
