### ISSUE TITLE
MINGW/MSYS2 : Fetch binary dependencies from the build environnement itself instead of relying on binaries kept in Git

### ISSUE THREAD

**Issue by vsonnier** [Novum/vkQuake#703]
A follow-up of https://github.com/Novum/vkQuake/commit/7cf09be32046c812ad94e45a9eabcc84587a6188 :  

We added `libwinpthread-1.dll` as a binary dependency for MSYS2/MINGW and stored a given version (MSYS2) in `/Windows/misc/[x64|x86]`, in the same way we keep SDL2 and audio codec binaries.

As @j4reporting reported (pun intended) this is not very clean because this dll may have an adherence on the undelaying Mingw/MSYS2 runtime, even built static, so strictly speaking is not "portable" from one build to another.

An improvement would be to fetch 'libwinpthread-1.dll' from the current Mingw distribution used in `Makefile.w[32|64]` to garantee conststency.

**Comment by vsonnier** [comment]
@j4reporting Using `$MINGW_PREFIX` to find the installation looks OK, including for the CI. Is it good on your side ?

**Comment by sezero** [comment]
gcc in a mingw-w64 toolchain can be configured to not rely on winpthreads (e.g. my own linux-to-windows mingw-w64 cross-toolchains are as such), therefore, the unconditional copying of it in the makefiles can result in failures.

**Comment by sezero** [comment]
> @sezero mingw compilers distributed by the msys2 project, w64devkit, or provided by fedora and probably others are using posix threads.

That I already know. But what they provide isn't the universal truth, that's what I'm saying.

**Comment by sezero** [comment]
>   Are there any disadvantages by using posix threads?

Unnecessary dependence to winpthreads dll itself is a disadvantage, imo.

> ```
> 	if [ -f $(LIBWINPTHREAD) ]; then \
> 		cp $(LIBWINPTHREAD)  . ; \
> 	fi
> ```

Existence check looks ok to me

**Comment by vsonnier** [comment]
I've commited @j4reporting suggestion:

> If you want to link the shared library then something like this should work, I would not use MINGW_PREFIX though. Make it specific for MSYS2 for now.

```c
- MINGW_PATH = ${MINGW_PREFIX}
+LIBWINPTHREAD = $(MSYSTEM_PREFIX)/bin/libwinpthread-1.dll


dll:
	if [ -f $(LIBWINPTHREAD) ]; then \
		cp $(LIBWINPTHREAD)  . ; \
	fi
```

For now, this is Good Enough (TM) for me. Feel free to improve later if you feel like it.

Thanks for your help !
