### ISSUE TITLE
map 'A day like no other'    can crash on map load  and  load savegame

### ISSUE THREAD

**Issue by j4reporting** [Novum/vkQuake#709]
this [map](https://www.slipseer.com/index.php?resources/a-day-like-no-other.372/ ) has def. a few issues 

```
map maj
Mod_LoadTexinfo: 34 texture(s) missing from BSP file

```

but quite often `map maj`   or  loading a savegame  can crash the application  

Exception thrown at 0x00007FF68E349A23 in vkQuake.exe: 0xC0000005: Access violation reading location 0x000002002301002C.

>	vkQuake.exe!ResampleSfx(sfx_s * sfx, int inrate, int inwidth, unsigned char * data) Line 73	C
 	vkQuake.exe!S_LoadSound(sfx_s * s) Line 159	C
 	vkQuake.exe!S_PrecacheSound(const char * name) Line 348	C
 	vkQuake.exe!CL_ParseServerInfo() Line 1033	C
 	vkQuake.exe!CL_ParseServerMessage() Line 1840	C
 	vkQuake.exe!CL_ReadFromServer() Line 950	C
 	vkQuake.exe!_Host_Frame(double time) Line 957	C
 	vkQuake.exe!Host_Frame(double time) Line 1003	C
 	vkQuake.exe!SDL_main(int argc, char * * argv) Line 122	C
 	vkQuake.exe!SV_movestep()	C
 	vkQuake.exe!invoke_main() Line 107	C++
 	vkQuake.exe!__scrt_common_main_seh() Line 288	C++
 	vkQuake.exe!__scrt_common_main() Line 331	C++
 	vkQuake.exe!WinMainCRTStartup(void * __formal) Line 17	C++
 	kernel32.dll!00007ffd02fa7374()	Unknown
 	ntdll.dll!00007ffd0491cc91()	Unknown

the sound file seems to be always gram1.wav

**Comment by vsonnier** [comment]
Resample can overflow with such huge .wav. Poke @sezero @Shpoike @andrei-drexler, same problem in all other QS derivatives.

**Comment by vsonnier** [comment]
Thanls @j4reporting for reporting this !

**Comment by sezero** [comment]
>  so far l have not managed to crash the old ironwail 0.7.0 release from March 2023

It can only be due to some dumb luck.

**Comment by sezero** [comment]
Patch applied to qs as https://github.com/sezero/quakespasm/commit/2e6c7d769454e4456026ed052a6596d70fe33553

**Comment by andrei-drexler** [comment]
Thanks for the heads up!
