### ISSUE TITLE
possible race in staging upload for lightmaps

### ISSUE THREAD

**Issue by airlied** [Novum/vkQuake#71]
I was debugging vkquake on radv, and I think I spotted a race condition with the staging upload and main command buffers, for the lightmaps.

R_UploadLightmap allocates a staging buffer and uploads to it,
that gets called 
R_DrawTextureChains
R_DrawWorld
R_RenderScene
R_RenderView
V_RenderView
SCR_UpdateScreen

SCR_UpdateScreen calls GL_BeginRendering which calls R_SubmitStagingBuffers
before all of that.

So the lightmap gets updated but not submitted.

Let me know if I've missed something, I'm not overly familiar with the codebase.

**Comment by Novum** [comment]
I'm not sure if I understand. The lightmap only needs to be uploaded before the command buffer is executing on the GPU in the next frame. Is that not the case?

**Comment by airlied** [comment]
Oh so the lightmap update lags by a frame, oh if so then it it's fine, I though it was update the lightmap for the current frame and thus failing to actually upload it.

**Comment by Novum** [comment]
Define "current frame"?

GPU rendering is inherently asynchronous. While the CPU is recording command buffers for the next frame, the GPU is executing the ones recorded a frame earlier.

**Comment by airlied** [comment]
So in this case you are preparing two command buffers, one staging to upload the lightmap, and one main command buffer. The staging command buffer doesn't get submitted before the main command buffer does. So current frame I mean what the CPU is going to submit next.

So current order is
- frame 1
Submit Staging
Update Staging with lightmap
Submit Main Command
- frame 2
Submit Staging

The staging lightmap update won't have any effect on the current main command buffer being uploaded.

If that is how quake works, that is fine, it just seemed confusing to be updating the lightmap mid-frame when the results aren't used until next frame.

**Comment by Novum** [comment]
I will double check the logic if I find time. If there is an issue it would just delay the update by a frame.

**Comment by Novum** [comment]
You are right, the buffer submit has to be done in end frame, not begin frame. No idea what I was thinking there. Fixed by a6dbe10152f52229fb7bc7ac40e6269e7d7f1e65
