### ISSUE TITLE
Old Style Status Bar But Widescreen Layout?

### ISSUE THREAD

**Issue by Big-the-Fat** [Novum/vkQuake#711]
I've no idea if this is possible but I'd love to have the original status bar and items bar side by side as opposed to the standard on top of each other.  

![SBAR IBAR](https://github.com/user-attachments/assets/2a5ca072-2e96-4abb-aff1-379d5020afee)

The status bar is a big part of the nostalgia for me (and I'm sure others) but its ratio is awkward on modern displays.  I think my solution above would make it more widescreen friendly and illicit the same vibe.

Is this something you'd consider?

**Comment by vsonnier** [comment]
> Is this something you'd consider?

I'm sorry, but no. I'm not interesting in anything Status Bar related. Either the default, hardcoded ones are OK or mods can customize their own with CSQC (Alkaline, Arcane Dimensions). I'm not going to bring anything new from Ironwail for instance. 

There is still https://github.com/Novum/vkQuake/issues/698 where I could welcome some addition on the existing "modern" HUD but Im not going to do it myself, it is not worth it IMHO.
