### ISSUE TITLE
Bounding Boxes enhancements based on Ironwail

### ISSUE THREAD

**Issue by SinaelDOverom** [Novum/vkQuake#712]
Hello. Ironwail has several cool features pertaining to how it shows bounding boxes with r_showbboxes command:
1) they are color coded with red being enemies/shootable switches, purple for secrets and triggers and so on.
2) "r_showbboxes_filter" can accept multiple parameters like "r_showbboxes_filter secret button" which will show all of them, not just one and ignoring the rest like vkQuake does now

It will be really cool if such features could be implemented in vkQuake

**Comment by vsonnier** [comment]
I'm not planing to add anything fancy there and the existing `r_showbboxes_filter` is good enough.
