### ISSUE TITLE
Multiple quicksaves and quicksave rotation

### ISSUE THREAD

**Issue by SinaelDOverom** [Novum/vkQuake#713]
Raze/GZDoom source port has an amazing feature called "quicksave rotation" where it has several quicksave slots, and upon quicksaving it makes a new one or overwrites the oldest of them if the limit is reached.
AFAIK no Quake engine has replicated such feature yet and I'd really love to have it.

**Comment by vsonnier** [comment]
I'm not interested at adding this, too much work for too little value.
