### ISSUE TITLE
vkQuake 1.31.0 crashes upon startup with no displayed error. 7900xtx / 24.6.1 or 24.7.1

### ISSUE THREAD

**Issue by thesockninja** [Novum/vkQuake#714]
**Describe the bug**
vkQuake.exe will open a console window for about two seconds, appear to be hunting for a file or driver, and immediately close without an error displayed. Window is not open long enough for me to read what it says.

**To Reproduce**
Attempt to open vkQuake.exe after installing in both ways:

Drag / drop installation utilizing [vkQuake-1.31.0_win64.zip](https://github.com/Novum/vkQuake/releases/download/1.31.0/vkQuake-1.31.0_win64.zip) into directory structure: C:\users\ (username)\Desktop\vkQuake - vkquake files are all here, with an id1 subdirectory inside with PAK0/PAK1 files pulled from either the Nightdive rerelease (Steam) or an OG Quake CDrom install.

Attempting to open vkQuake.exe after installation using [vkQuake-Installer-x64-1.31.0.exe](https://github.com/Novum/vkQuake/releases/download/1.31.0/vkQuake-Installer-x64-1.31.0.exe) and pointing to the same sourced PAK files (keeping them in the Steam subdirectory) produces the same situation 

**Expected behavior**
vkQuake.exe will load from PAK files and start the attract mode / game menu.

**Screenshots**
This is a recent crash in Windows Event Viewer:

![image](https://github.com/user-attachments/assets/b8975e8b-bd83-413e-9387-ba6be034e75b)

I have attached the associated WER file as well as associated vkQuake crash dump found in C:\Users\(USER)\AppData\Local\CrashDumps in:

[vkQuakeBugReport.zip](https://github.com/user-attachments/files/16402229/vkQuakeBugReport.zip)

**Desktop:**
7800x3d
ASrock B650 Livemixer
32GB DDR5-6000 @ 36cl or so
1000w EVGA PSU
1TB Crucial M.2 / NVME (Install Drive / C:)
 - OS: Windows 11
 - GPU: Powercolor Hellhound AMD 7900xtx (stock configuration)
 - issue persists similarly on 24.6.1 and 24.7.1

**Mod**
Nightdive rerelease sourced (classic, rerelease) PAK files, also tried with PAK files sourced from a Quake retail CD, no other mods.

**Additional context**
I did read [this bug report](https://github.com/Novum/vkQuake/issues/710), however, I am not sure what "If I add r_rtshadows 0 to my autoexec.cfg, the game does indeed launch correctly." entails specifically or where to perform similar actions for a testable fix.

No issues with any other programs, crashes, or bluescreens. Other sourceports work with the same PAK files. I have a second computer (10700k, RX580 using 24.6.1 and also 24.7.1 later as I was troubleshooting, Windows 10) where this install structure, 1:1 same sourced files, works fine.

Attempted a complete reinstall of the 64-bit vkquake files with both the installer and the raw files. I attempted uninstalling using both windows uninstaller and Wise Program Uninstaller to remove prior, no change in any regard. (This is the cleanest uninstallation method that I can find. If there is a better one, please advise.)
Attempted running vkQuake.exe as administrator, no change.
Uninstalled (w/ DDU) video drivers, reinstalled, no change.
Updated from 24.6.1 to 24.7.1 and both drivers produce the same issue.
No settings in the 7900xtx different than the RX580 as far as I can tell from AMD Adrenalin Software.

Please let me know if anything else is needed.

**Comment by vsonnier** [comment]
No need for another issue for buggy AMD drivers, #710 is perfectly fine to continue discuss issues. 

Also:
>  "If I add r_rtshadows 0 to my autoexec.cfg, the game does indeed launch correctly." entails specifically or where to perform similar actions for a testable fix.

So I assume you didn't test it ? Well, simply create a text file `autoexec.cfg` in your `id1` directory and put the line `r_rtshadows 0` in it. Now if you start vkQuake, RayTracing Shadows will be disabled.
 
Closing this as dupplicate.

**Comment by thesockninja** [comment]
Thank you!
