### ISSUE TITLE
Key bindings options limited

### ISSUE THREAD

**Issue by cutting6** [Novum/vkQuake#716]
The current keys 8 and 9 does not allow me to select of select the Mjolnir or Laser cannon from the Quake dlc Scourge of Armagon. It also does not show the key binds for these items so I am unable to change them. The is also the case of Slayer's Testaments as the default key binds are not registered to the keys indicated so I am unable to throw grenades, use the chainsaw or use weapon alt fires. I you could please look into this that would be much appreciated.

**Comment by vsonnier** [comment]
I think @j4reporting has answered the question. 
The predefined keybind list is a limitation of QS, and I'm not going to add anything specific for mods, even the initial canonic 
ones. ( Which are not that great anyway)
