### ISSUE TITLE
Broken bones(?) on certain custom MD5 models

### ISSUE THREAD

**Issue by LOL-DUDE-64** [Novum/vkQuake#718]
**Description:**
These MD5 models (intended for `rerelease`) are all mangled. See screenshots, since I can't describe it ery well.

**To Reproduce:**
Install the mod below, set `-basedir "C:\Program Files (x86)\Steam\steamapps\common\Quake\rerelease"`, and enable enhanced models.

**Expected behavior:**
For the models to, uh, not be mangled. Every other model in this mod looks correct, as well as the enhanced models from the `rerelease`.

**Screenshots**
![vkquake0001](https://github.com/user-attachments/assets/40079cf5-ad27-47fb-9752-62956081e93c)
![vkquake0002](https://github.com/user-attachments/assets/660919f3-8e47-4f03-9904-77c60f38c1d2)

**Desktop:**
 - OS: Windows 10
 - GPU: NVIDIA GeForce RTX 4070 Ti SUPER
 - Driver version: GeForce Game Ready Driver 560.70

**Mod:**
[Half-Dead](https://www.moddb.com/members/half-dead2)'s [Quake Right Handed Weapons](https://www.moddb.com/games/quake/addons/quake-right-handed-weapons). Map pictured is from [Copper](http://lunaran.com/copper/), though this problem happens independently of the selected `-game`.

**Additional context:**
These same models worked fine in [QuakeSpasm-Spiked](https://triptohell.info/moodles/qss/), so I assumed that this is a problem on the end of this particular port, and not the mod itself.

**Comment by vsonnier** [comment]
Does it work with [1.30.1](https://github.com/Novum/vkQuake/releases/tag/1.30.1) ?

**Comment by LOL-DUDE-64** [comment]
I tried 1.30.1 just now, and these don't work there, neither. I'm admittedly unsure how to install that build of IronWail, though.
Found one more messed-up model, from `hipnotic`:
![vkquake0001](https://github.com/user-attachments/assets/4bec7672-7712-4923-8ab2-62e1bfd5ad8a)

**Comment by vsonnier** [comment]
[Noesis](https://richwhitehouse.com/index.php?content=inc_projects.php&showproject=91) seems to load the models OK, and Ironwail seems (more) OK also so maybe I could compare Ironwail  MD5 handling and our to see if there is something to improve.

**Comment by pbdot** [comment]
One lead might be that these models have more than one mesh defined, the release meshes all have one, so might be a bug with multi-mesh support 

```
MD5Version 10

numJoints 8
numMeshes 2
```

**Comment by vsonnier** [comment]
> One lead might be that these models have more than one mesh defined, the rerelease md5 all have one mesh, so might be a bug with multi-mesh support

Many thanks @pbdot, that was it ! The rendering is now the same as in Ironwail.

**Comment by vsonnier** [comment]
Right, this is not done yet. Ironwail now correcty displays the exemple models, following the commit https://github.com/andrei-drexler/ironwail/commit/98ac065bd58d0418edda475fe9978a941b199047

I'll have to do something similar for vkQuake.
