### ISSUE TITLE
Default gamma and colours are incorrect

### ISSUE THREAD

**Issue by PoloniumRain** [Novum/vkQuake#720]
I don't know how accurate vkQuake is trying to be compared to the original game, so this gamma/brightness increase might be intentional (i'm guessing it is?)...

But occasionally i still play the original software rendered DOS Quake, which has a default gamma setting of 1.0. Where as vkQuake uses 0.9, which makes it look brighter, and when this is combined with the default contrast setting (which doesn't exist in the original game) it further raises the overall brightness of vkQuake. But the original Quake is a purposely dark game, almost as dark as Doom 3. It adds to the atmosphere.

Gamma also affects colour saturation. Colours will look more and more washed out as the gamma value is reduced. The slight gamma reduction from 1.0 to 0.9 wont make a huge difference here, but it will still make the colours look a tiny bit less vibrant. 

So it would be nice to have a Colour Saturation slider in the Options menu which allows for fine control. This way if people were to use lower gamma values then they could increase the colour saturation to help compensate. Maybe there's already a command for this, but a slider would be ideal.

![Quake_Comparison](https://github.com/user-attachments/assets/12dfd78d-04d9-419e-b173-283f27815d9e)

And lastly, when GLQuake released in 1997 it introduced a yellow-green-ish tint to all the textures. Since then this tint has persisted with many (or all) Quake source ports that i've seen which make use of a GPU. So if you look at DOS Quake (1996) in the above image, it's not just darker due to the 1.0 gamma and not having any contrast boost, it also doesn't look as yellow/green. It's as if GLQuake, vkQuake and many others have increased the RGB green colour channel and decreased the red channel. So when using something like RetroArch with DOSBox-Pure, it's possible to mostly fix this tint by using shaders (basically filters) and adjusting the RGB channels. This tint problem may just be a side effect of GPU acceleration or whatever, but again it's not accurate to the software rendering used in the original release.

All these changes make vkQuake look considerably different to Quake. Maybe Quakespasm is the same but i haven't tried that in years.

**Comment by Sunspark-007** [comment]
I moved the gamma notch 1 tick to the left (still 0.9, there are 3 ticks all marked 0.9, weird). It makes the look richer and less washed out.

**Comment by Novum** [comment]
You want this https://github.com/cyanbun96/qrustyquake
Also ships with the Steam rerelease already in the folder.
