### ISSUE TITLE
Mouse cursor remains visible when using AppImage version.

### ISSUE THREAD

**Issue by robojerk** [Novum/vkQuake#721]
**LOW EFFORT BUG REPORTS WILL BE CLOSED**

**Describe the bug**
Using wayland version of kwin, mouse cursor remains visible when using AppImage. I didn't try a non AppImage binary.

**To Reproduce**
Launch vkquake appimage using kwin or gamescope. I didn't try Mutter or other compositors.  I didnt try in X.

**Expected behavior**
Mouse cursor should be visible ONLY when in the menu, once a game starts it hides.

**Screenshots**
I tried but spectacle and other screenshot apps wouldn't capture the cursor.  It's there though.

**Desktop (please complete the following information):**
 - OS: Linux (Bazzite 40) 6.9.12-203.fsync.fc40.x86_64
 - GPU vendor and model
  Optimus Laptop
      AMD Ryzen 7 4800H (Renoir series AMD Radeon RX Vega 7)
      Nvidia RTX 2060 Mobile
 - Driver version
      Nvidia driver  560.31.02
      AMD Driver 24.1.5

**Mod**
In vanilla version of games and all mods

**Additional context**
When running under kwin the Plasma feature to grow mouse on mouse shake is entertaining.

**Comment by sezero** [comment]
> introduced in this commit? [libsdl-org/SDL@c39f86c](https://github.com/libsdl-org/SDL/commit/c39f86c28a54c3f108c31a58ff610fe9508d03c4)
> 
> Ubuntu 20.04 doesn't support wayland. Maybe compiling on 22.04 could resolve this? Otherwise maybe downgrade SDL2 to 2.28.5 for linux binaries for now.

Report this to SDL please

**Comment by Kontrabant** [comment]
Should be fixed upstream now.

**Comment by robojerk** [comment]
> @robojerk could you pls try if this artifact fixes the mouse issue for you? https://github.com/j4reporting/vkQuake/actions/runs/10431663762
> 
> This appimage was created from the current vkQuake git master with latest SDL2 from the release-2.30.x branch. So it's not exactly 1.31.1.

No more mouse cursor :)

**Comment by robojerk** [comment]
I quickly ran the new build as normal with and setting the SDL_VIDEODRIVER to wayland.  Mouse cursor is gone in both. :)

Thanks...

**Comment by robojerk** [comment]
Mine seemed locked into 60

Also the cursor reappeared when setting SDL_VIDEODRIVER=wayland

**Comment by robojerk** [comment]
I had more time to play with it.  I nuked the vkQuake.cfg and that solved some things. Mouse Cursor is gone again.

For awhile there I was getting this error  "Couldn't init SDL video: wayland not available"

Anyways it's working now. When I go full screen with those settings you asked me to plug in it seems to max out at whatever the displays refresh rate is..  My display does 60 and 144 and that's what it seems to go to depending on what I have it set to.

**Comment by robojerk** [comment]
I'll admit it was late when I doing things when I was getting the SDL errors about wayland not availabe. I might have been doing something dumb..  However I redownloaded the newer build a few times to make sure and I was getting that error.  I did do a combination of things and it went away but I couldn't tell which one resolved it.

I'm on KDE Plasma 6.1.4 and the option to enable/disable VRR I cannot find.  Older versions show it in under Display.

Ran it under the iGPU

```
$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json SDL_VIDEODRIVER="wayland" $HOME/.steam/steam/steamapps/common/Quake/vkquake.AppImage  -basedir $HOME/.steam/steam/steamapps/common/Quake

Found SDL version 2.30.6
Detected 16 CPUs.
Initializing vkQuake 1.31.2
Built with GCC 11.4.0
Host_Init
Playing registered version.
Console initialized.
UDP4 Initialized
UDPv6 Initialized
Server using protocol 999+ (FTE-RMQ)
Exe: 15:06:12 Aug 18 2024

Vulkan Initialization
Using Vulkan 1.1
Instance extensions:
 VK_KHR_surface
 VK_KHR_wayland_surface
 VK_KHR_get_surface_capabilities2
 VK_KHR_get_physical_device_properties2

Vendor: AMD
Device: AMD Radeon Graphics (RADV RENOIR)
Driver: radv Mesa 24.1.5
Using subgroup operations
Device extensions:
 VK_KHR_swapchain
 VK_KHR_get_memory_requirements2
 VK_KHR_dedicated_allocation
 VK_EXT_subgroup_size_control
Using A2B10G10R10 color buffer format
Using D32_S8 depth buffer format
```

I get 200 fps with that.  :) When rerun  with nvidia it's still locked to 60 or 144

**Comment by robojerk** [comment]
If I run the game under gamescope it will go to 200 if I turn VRR off in the game menu..  If I leave it on it's allover the place 90's but never over 144 but can get to 144.

Running game in gamescope there's mouse control issues.  I wouldn't recommend playing it.

I find gamescope doesn;t like any arguments applied to the appimage so I need to run it from inside the Quake Dir.  Adding basedir argument makes gamescope complain.

`user@localhost ~/.steam/steam/steamapps/common/Quake:$ SDL_VIDEODRIVER="wayland" gamescope -f -W 1920 -H 1080 ./vkquake.AppImage`
