### ISSUE TITLE
No music in vkquake on macos

### ISSUE THREAD

**Issue by AlexanderwithaA** [Novum/vkQuake#724]
**Describe the bug**
Music does not play in Quake or Mods for quake.

**To Reproduce**
Boot up vkquake in the directory where you store your id1 folder and other such quake items and listen as the demo starts.

**Expected behavior**
You'd hear music.

**Screenshots**
(turn on audio)

https://github.com/user-attachments/assets/292b2a75-aa8a-4dec-afc1-c90ce3325838

**Desktop (please complete the following information):**
 - OS: macOS 11.7.10
 - Intel HD Graphics 5000
 - Driver version 0.2.2014

**Additional context**
This is my folder layout
![Screen Shot 2024-08-20 at 10 13 54 PM](https://github.com/user-attachments/assets/5273eb41-e1fb-47e2-a846-45494436d117)
These are my configs.

[vkQuake.txt](https://github.com/user-attachments/files/16685110/vkQuake.txt)

Also this error is appearing in the console 
![Screen Shot 2024-08-20 at 10 19 59 PM](https://github.com/user-attachments/assets/e57786a2-a5ae-4621-9d28-33f7487a8389)

**Comment by AlexanderwithaA** [comment]
I can’t run either of those commands, I get the error `Unhandled extension for track02.ogg` same for mp3

**Comment by sezero** [comment]
That means whoever built your vkquake for mac, he or she didn't build against ogg/vorbis for *.ogg and libmad or mpg123 for *.mp3.

**Comment by AlexanderwithaA** [comment]
I built it myself, do I have to download and rebuild the file with those libs? I don’t know how to do that.

**Comment by AlexanderwithaA** [comment]
That worked and I was able to install libmad, flac, and libogg via brew.
Vorbis and opus aren’t there though

**Comment by AlexanderwithaA** [comment]
Thanks a lot, that worked
