### ISSUE TITLE
Particles visible through walls on Steam Deck

### ISSUE THREAD

**Issue by SorayaProtera** [Novum/vkQuake#725]
**Describe the bug**
Maps with enhanced particle effects, such as Arcane Dimensions maps, render particles through level geometry.

**To Reproduce**
- Load into the latest version of Arcane Dimensions
- Start a new game
- Observe particle effects showing through geometry in the initial hub map.

**Expected behavior**
Particle effects should be blocked by level geometry.

**Screenshots**
![vkquake0001](https://github.com/user-attachments/assets/70e37df7-10f8-4794-a991-a7fdb71ee2d1)

**Desktop (please complete the following information):**
 - OS: SteamOS Holo version 3.5.19, kernel version 6.1.52-valve16-1-neptune-61
 - GPU: AMD Van Gogh
 - Driver version: 4.6 (Compatibility Profile) Mesa 23.1.3 (git-87ebaf765d)

**Mod**
As stated above, the latest version of Arcane Dimensions. The behavior was observed on both the initial hub map, and Tears of the False God (ad_tears).

**Additional context**
A terminal log is available here: 
[vkquake ad output.txt](https://github.com/user-attachments/files/16717014/vkquake.ad.output.txt)

The error is consistent regardless of whether the game is run through Steam, and regardless of whether the AppImage is used or the Windows executable is run through a compatibility layer.

Please let me know if any further information would be helpful.

**Comment by vsonnier** [comment]
It has reported in https://github.com/Novum/vkQuake/issues/732 that now it is working on Steam Deck. So, is there still a problem for Steam Deck on the particular issue of particles on latest `1.31.3` ?

**Comment by vsonnier** [comment]
Let's suppose it has been fixed together with the last Steam updates like the other problems.
