### ISSUE TITLE
Release 0.72 archive for Linux is broken

### ISSUE THREAD

**Issue by artyomk3d** [Novum/vkQuake#73]
The archive is broken
https://github.com/Novum/vkQuake/releases/download/0.72/vkquake-0.72.0_linux_64.tar.gz

Says "Unexpected end of data vkquake-0.72.0_linux_64.tar".
*****
tar -xf vkquake-0.72.0_linux_64.tar.gz 

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
*****

**Comment by ProfessorKaos64** [comment]
Is this when you issue `tar -xf vkquake-0.72.0_linux_64.tar.gz` ?

**Comment by artyomk3d** [comment]
Thanks,

Best regards

**Comment by ProfessorKaos64** [comment]
Ok, please download again from the releases page.

**Comment by Svetomech** [comment]
But now the release doesn't contain vkquake binary at all.

**Comment by ProfessorKaos64** [comment]
There is a new ticket open fro the release. I will fix this soon today. Thank you for your patience.
