### ISSUE TITLE
vkquake compiled from source on arch linux / steam deck version doesn't show doors, elevators etc

### ISSUE THREAD

**Issue by d-p-y** [Novum/vkQuake#732]
**Describe the bug**

I've tried to use Immortal Lock v1.9 with vkquake 1.31.1.1 compiled from vanilla source code. It compiled cleanly but it was missing doors and elevators in the very first level. I've tried E1M1 and run into exactly same issue. I see others reported by trying native windows binary over proton:
https://github.com/Novum/vkQuake/issues/717
and when they tried AppImage:
https://github.com/Novum/vkQuake/issues/725

I've decided to compile and run several older versions hoping to find which particular change caused this phenomenon. I wasn't able to find it because older version don't seem compile. Maybel additional info gathered here helps finding out bug.

* `vulkaninfo` output showing full vulkan info including extensions:
[vulkaninfo.txt](https://github.com/user-attachments/files/16921878/vulkaninfo.txt)

* E1M1 on 1.31.1.1 strangely reported as 1.31.1...
![e1m1_1 31 1](https://github.com/user-attachments/assets/557d8744-4f76-4eb2-b0df-2e5415951577)

... despite compilation source being 1.31.1.1:
![e1m1_1 31 1 1_proof](https://github.com/user-attachments/assets/1585f30c-d99e-48a4-af93-0e5926dd32bd)

* E1M1 on 1.31.0
![e1m1_1 31 0](https://github.com/user-attachments/assets/43a1c87c-9dd2-40f5-891a-2507157e2d50)

* E1M1 on 1.20.3 which is an earliest version that I was able o compile
![e1m1_1 20 3](https://github.com/user-attachments/assets/ae222741-b3d3-454c-8e53-936e4f7c2d1a)

Not sure if it matters but initially I couldn't compile it due to warnings:
![compilation_1 20 3_vanilla](https://github.com/user-attachments/assets/588dc539-3707-4405-99c5-3db5059e879f)

...but I forced it by disabling warnings-as-errors:
![compilation_1 20 3_forced_how](https://github.com/user-attachments/assets/5200fe34-77c3-4ed0-86f5-d3ee8dc8c799)

* 1.13.1 I wasn't able to compile

vanilla `make -j` outcome:
![compilation_1 13 1_vanilla](https://github.com/user-attachments/assets/810b960a-e34b-47d0-b16b-dc234551a5ab)

..forcing it with:
![compilation_1 13 1_forced_how](https://github.com/user-attachments/assets/8a364d61-f9db-4eba-9ec7-5d64115d389a)

..but it doesn't help:
![compilation_1 13 1_forced](https://github.com/user-attachments/assets/7970c813-d695-40e7-957b-afdda8f33ada)

**Desktop (please complete the following information):**
 - OS: Linux Steam Deck Arch based "Holo OS"
 - GPU vendor and model: steam deck LED model "AMD Custom GPU 0405 (RADV VANGOGH)"
 - Driver version 23.2.99 (from `vulkaninfo --summary`)

**Mod**

Quake 1 retail from GOG.
Immortal Lock v1.9 on top of Quake 1 retail from GOG.

**Comment by vsonnier** [comment]
Hello @d-p-y, your issue is a dupplicate of #717, most likely. 

Since you are able to compile from source though, please try the current `master` because there were some Vulkan-related fixes there not present in 1.31.1 that mau (or not) change something on that issue.

**Comment by d-p-y** [comment]
Hi @vsonnier,
yes, I indeed believe that my issue and linked two issues are triggered by the same underlying problem. I created new issue as I wish I can help narrow it down as now we are sure it's not a problem of emulation (=proton) or packaging (=AppImage). 

As requested, I tried up-to-date master `5bdb71a99495bf416a504690af6895965a218c91` and outcome is the same:
![vkquake0001](https://github.com/user-attachments/assets/141620aa-bc2d-47f9-9ae6-68e27b342589)

Please let me know if I can further help with it somehow. I can e.g. compile&run some special extra branch verbose version if needed.
Thanks

**Comment by andrey-budko** [comment]
Did you try with r_indirect 0? Doors are fine on  my GT 710 on Windows10 with r_indirect 1, but:

No lamps, for example:
![image](https://github.com/user-attachments/assets/f32e2086-7795-4bdf-a058-e77db7520219)

And this:
![image](https://github.com/user-attachments/assets/550765e7-26bf-427a-8a9c-c9e76519f991)

**Comment by andrey-budko** [comment]
`r_gpulightmapupdate 0` (with `r_indirect 1`) also fixes all glitches for me

**Comment by d-p-y** [comment]
Thanks for ideas. I fiddled with options (putting them into autoexec.cfg to be sure they are active during level load) and unfortunately to no avail:

* `r_indirect 0`
![vkquake0002](https://github.com/user-attachments/assets/df758f3a-8ea7-4a34-b8bb-16fdb2076f1b)

* `r_gpulightmapupdate 0` +  `r_indirect 1`
![vkquake0003](https://github.com/user-attachments/assets/4d25d777-f506-4eec-a036-523cb706bc77)

**Comment by thegrafanloon** [comment]
This seems to have been fixed for Steam Deck in the latest release 1.31.3, at least it is working for me now.

**Comment by vsonnier** [comment]
@thegrafanloon Good to know, thanks for the report !

**Comment by vsonnier** [comment]
Got also a confirmation in #717, let's close this.

**Comment by vsonnier** [comment]
@d-p-y fine, but it works for @thegrafanloon and one another. What are the difference though ? Drivers ? distribs ? it points more and more towards a driver issue...

**Comment by d-p-y** [comment]
Hi,
It looks like I was missing the latest system update from Valve (released few days ago). Now it indeed works perfectly. I checked both E1M1 and Immortal Lock. Thanks!

**Comment by vsonnier** [comment]
Good @d-p-y , thanks for your persistence in puusuing this problem. Have fun !
