### ISSUE TITLE
Error "vkBindImageMemory failed"

### ISSUE THREAD

**Issue by V00id** [Novum/vkQuake#737]
Hello Quake developers,

OS: Windows

I get an error "vkBindImageMemory failed".
This is the case since vkQuake 1.31.0 win64
Everything was fine before. I havent change my hardware.

Thanks in advanced, V0id.

**Comment by V00id** [comment]
Hello again,

I will add some more infos on the error.

1. This happened with the Drake Mod (http://quaddicted.com/filebase/drake290111.zip)
2. My command-line:
`vkQuake.exe -heapsize 2048000 -zone 4096 -basedir -game drakebeta`

**Comment by V00id** [comment]
Hello,

let's focus on point 3 first. Answer for custom pak etc. is: Yes.
But I tell you what I have done:
- Created a new folder and copied all 12 files of the 1.31.2 package into it.
- Copied the Steam\SteamApps\common\Quake\id1 folder with the two PAK files (org Ouake game from 1996) into it.
- Started the vkQuake.exe with -heapsize 2048000 -zone 4096 and the menu comes up with the demos running in the background. I switched off startup demos in game options. Started a new game and got into the map start.
- Copied the Arcane Dimensions 1.8 p1 files into the sub folder AD.
- Started the vkQuake.exe with -heapsize 2048000 -zone 4096 -game AD and the menu comes up. Started a new game and got into the map start of the AD package.
- Started the above mentioned maps from the console and everything runs fine without any perfomance issues on 200 fps, flying through the maps with noclip. So this answered the question 2.
- Copied the Something Wicked files (link above) into the sub folder swicked.
- Started the vkQuake.exe with -heapsize 2048000 -zone 4096 -game swicked and the menu comes up. Then clicked menu single player->new game and the game shows a modal windows with the following text:
  <Error_new_game_swicked.png>
- So this answered the question 1.

All in all no custom content is involved. No even an autoexec.cfg file.
I started other mods like Dimension of the Machine, Alkaline 1.2, Dwell and Underdark Overbright. I had no problems with them.

As for point 4:
- Windows 10 german edition, german region with all current updates, 64GB Mem.
- GPU:
  Here is a screen shot of AMD software system tab. Every optimizations are OFF. It is in german, but all important infos are readable.
  <AMD_Software.png>
  A screen shot of the vkQuake console after initialization with map start:
  <console_id1_new_game_map_start.png>

As for point 5 and 6, see <vp_gpuinfo_amd_radeon__tm__r9_380_series.json>

I put every file in an attached ZIP 737_02.zip

[737_02.zip](https://github.com/user-attachments/files/17350150/737_02.zip)

**Comment by V00id** [comment]
Here are the Windows explorer screenshots for all three folders:
<vkQuake_1.31.2.png>
<vkQuake_1.31.2_id1.png>
<vkQuake_1.31.2_something_wicked.png>

Starting vkQuake.exe without parameters, starting a new game, the map start of the original game is starting without any issues.
Starting vkQuake.exe with -game something_wicked parameter, starting a new game, the error window is displayed. After pushing OK the game quits.

Files see 737_03.zip

[Uploading 737_03.zip…]()

**Comment by V00id** [comment]
> Please try both versions.
I tried both builds, and both bring up the error.

I suggest to not waste anybodys time any more with this issue, cause it turns out that the issue only occurs on my computer setup.
I be fine to use vkQ version 1.30 for the Drake-mods and the current version for the rest.

Many thanks for yout support and your time!

**Comment by V00id** [comment]
Closed.

**Comment by vsonnier** [comment]
Not reproduced here either, but I'm on Nvdia hardware. Last chance, are you ruining a 32 bit build ?

**Comment by V00id** [comment]
> Not reproduced here either, but I'm on Nvdia hardware. Last chance, are you runing a 32 bit build ? The other option is to downgrade your driver version, to see if something improves...

No, it's vkQuake 64-bit.
Sorry, but I won't downgrade anything. As I said, I'm fine with my setup now. You can close this issue please, if no one else has that issue.

**Comment by vsonnier** [comment]
OK, at least we tried :)

**Comment by V00id** [comment]
> @V00id could you pls try the relaase x64 binary from this [commit](https://github.com/Novum/vkQuake/actions/runs/12631310699) does it produce the same error message?

Hello j4,

this works!

See <vkQ_132_Drake_Wicked.jpg>

The map "wixked" is running in the background.

![vkQ_132_Drake_Wicked](https://github.com/user-attachments/assets/f827163a-8079-411c-a4e6-9cede9d190dd)
