### ISSUE TITLE
Dynamic lights and shadows of the official "Enhanced" version

### ISSUE THREAD

**Issue by Kappa971** [Novum/vkQuake#738]
**Is your feature request related to a problem? Please describe.**

Hi, just a question if there will be dynamic light and shadow support in vkQuake in the future.
I see vkQuake already supports levels, fog and new models from Enhanced version. Thanks.

**Comment by vsonnier** [comment]
Sorry, not interested in adding this.

**Comment by Kappa971** [comment]
> Sorry, not interested in adding this. Dynamic RT shadows are already there if you have a RT-capable card.

No RTX card. Ok no problem.
