### ISSUE TITLE
Option to change the position of the weapon model

### ISSUE THREAD

**Issue by Kappa971** [Novum/vkQuake#739]
**Is your feature request related to a problem? Please describe.**

An option to change the position of the weapon model would be useful, as I find the default option hides the model too much.
Setting the `r_viewmodel_quake` variable to `1` doesn't help because the positioning is affected by the value of `HUD Detail`, even if `HUD Style` is set to `Modern`.

**Describe the solution you'd like**

A new option in the game menu to change the position of the weapon model.

**Additional context**

**vkQuake**
![vkQuake](https://github.com/user-attachments/assets/f7705fef-39b3-4bf0-81b6-d4b309b4bb75)

**Quake Enhanced**
![QuakeEnhanced](https://github.com/user-attachments/assets/bbe5689a-8de4-4bcb-a9d5-40eb3f934e10)

**Comment by vsonnier** [comment]
Sorry, not interested in adding this.

**Comment by Kappa971** [comment]
Is there a technical reason, i.e. that it is difficult to implement and not worth wasting time on it, or is it just your personal choice?

**Comment by vsonnier** [comment]
> Is there a technical reason, i.e. that it is difficult to implement and not worth wasting time on it, or is it just your personal choice?

All of the above. I won't wasting the little time I have in a niche feature I have no intertest in.
