### ISSUE TITLE
Broken saves in Mjolnir mod 1.00.1

### ISSUE THREAD

**Issue by NurglesHogweed** [Novum/vkQuake#740]
I have the latest (master branch as it is now) Linux version of vkQuake. It crashes on attempt to save game on any map, including vanilla ones. I get`vkquake: ../Quake/pr_edict.c:854: ED_Write: Assertion type < NUM_TYPE_SIZES && ((type == ev_vector && type_size[type] == 3) || (type != ev_vector && type_size[type] == 1))' failed.`in terminal emulator. No such problem with no mods or Arcane Dimensions, or when using Ironwail instead.

**Comment by alexey-lysiuk** [comment]
It's https://github.com/JosiahJack/Keep/issues/14. Because of this, skipping of unknown types were added to QuakeSpasm.

**Comment by vsonnier** [comment]
Thanks @alexey-lysiuk for the head-up, I've added the commit fixing this problem.
