### ISSUE TITLE
Question on code location

### ISSUE THREAD

**Issue by johnalanwoods** [Novum/vkQuake#742]
Hi, 

Sorry to create an issue, but can't see where else to ask the question - I've looked over the code for a good 40mins and can't find where the weapon damage is defined, could anyone point me in the right direction?

**Comment by alexey-lysiuk** [comment]
Such things are defined inside `progs.dat`. For example, search for `T_Damage()` function in [re-release QuakeC source code](https://github.com/id-Software/quake-rerelease-qc/blob/7bcbd29c9934e8523974263de50b3ae90b5d2605/quakec/weapons.qc).

**Comment by johnalanwoods** [comment]
Gotcha thanks! But how is that code imported or included in vkQuake?

I can't see `progs.dat` nor `weapons.qc` in the repo.

**Comment by sezero** [comment]
Look at e.g. pr_edict.c, pr_exec.c, pr_cmds.c to see how progs.dat is loaded, interpreted and executed.

**Comment by sezero** [comment]
And no, you won't find qc (quakec) code in here: this is only the engine source.

**Comment by johnalanwoods** [comment]
Thank you!

**Comment by vsonnier** [comment]
> I can't see progs.dat nor weapons.qc in the repo.

Neither `progs.dat` nor any `*.qc` QuakeC code is part of Quake source code writthen in C language.

The programming logic of Quake is done in another language called QuakeC (`*.qc`) compiled separatly by dedicated tools, and injected in the Quake engine in compiled form : `*progs.dat`.

There are plenty of resources over the Internet on how to handle and program in QuakeC. 

Most of the mods (more than simple maps) you can found for Quake have their own version of modified QuakeC, derived from the one Id made for the game originally: https://github.com/id-Software/Quake/tree/master/qw-qc

**Comment by johnalanwoods** [comment]
Thanks for the detail @vsonnier!
