### ISSUE TITLE
"Got a NaN velocity on player" when walking to map corners?

### ISSUE THREAD

**Issue by HonkTwentySix** [Novum/vkQuake#744]
**Describe the bug**
Hi, i found this console message the first time when playing the Dissolution of Eternity Mission Pack (R1M1), it just seems to be a error message

**To Reproduce**
Walking towards two walls that are leaning forward seems to be enough to trigger the message
![vkquake0000](https://github.com/user-attachments/assets/0cc3b6ae-06cd-49ce-ad7e-a04c799eacf7)
![vkquake0001](https://github.com/user-attachments/assets/f38abcfd-e45e-4d33-860b-1b2f03391985)

**Expected behavior**
The message not appearing.

**Screenshots**
Also tested in a similar corner in Arcane Dimensions (Map Ad_Grendel)
![vkquake0001 (2)](https://github.com/user-attachments/assets/d8af29b7-0e25-4668-b382-72a8d4a71f65)
![vkquake0002 (2)](https://github.com/user-attachments/assets/013a1183-7412-49dc-88f2-b0d49645c84c)
![vkquake0000 (2)](https://github.com/user-attachments/assets/52de48ff-ea29-4857-b36f-dd9b523ddb75)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - GPU vendor and model: Sentey RX 570 4GB 
 - Driver version: 24.9.1

**Mod**
Dissolution of Eternity (rogue) on Map R1M1 and Arcane Dimensions on map Ad_Grendel

**Additional context**
A video showing the issue:
https://youtu.be/cMa1Bs9_Eew

**Comment by vsonnier** [comment]
This has existed for basically forever on all QS derivatives, it is there to signal an abnormal situation  with collision in very specific circumstances, and this situation is dealed with anyway.  

It has no consequence for gameplay, so I've  hiden this message behind the CVAR `developer`.
