### ISSUE TITLE
Dunnos ?

### ISSUE THREAD

**Issue by inukaze** [Novum/vkQuake#754]
Hi there i have an older computer and i cant upgrade my hardware yet, i am GNU/Linux distro user, my current main distro is Slackware(64) 15.0

To Solve the thing with FUSE in this distros is very ease with the follow commands like your user : 
```
user=$(whoami)

su -c "\
slackpkg {reinstall,install} fuse ; \
groupadd fuse ; \
modprobe fuse ; \
usermod -a -G fuse $user ; \
mkdir -p /etc/modules-load.d ; \
echo "fuse" > /etc/modules-load.d/fuse.conf" root
```

Dunno 1 -> How i can force disable the AA Mode ? i really need disable MultiSampling / SuperSampling

Dunno2 -> Why from the Version 1.13.0 i can reach menu but when i try to play a new game i see the follow output on terminal

> vkQuake 1.13.0 Server (59507 CRC)
> 
> 
> 
> Introduction
> Using protocol fte999
> Allocating lightmap compute surface data (386 KB)
> PHI node operands are not the same type as the result!
>   %1233 = phi { float, float, float, float } [ %.texmerge466, %texmerge.from.bgnloop309 ], [ %.texmerge465, %texmerge.from.texblock ], [ %.texmerge464, %texmerge.from.texblock340 ], [ %.texmerge463, %texmerge.from.texblock341 ], [ %.texmerge462, %texmerge.from.texblock342 ], [ %.texmerge, %texmerge.from.texblock343 ]
> PHI node operands are not the same type as the result!
>   %1246 = phi { float, float, float, float } [ %.texmerge344471, %texmerge344.from.texmerge ], [ %.texmerge344470, %texmerge344.from.texblock345 ], [ %.texmerge344469, %texmerge344.from.texblock346 ], [ %.texmerge344468, %texmerge344.from.texblock347 ], [ %.texmerge344467, %texmerge344.from.texblock348 ], [ %.texmerge344, %texmerge344.from.texblock349 ]
> PHI node operands are not the same type as the result!
>   %1259 = phi { float, float, float, float } [ %.texmerge350476, %texmerge350.from.texmerge344 ], [ %.texmerge350475, %texmerge350.from.texblock351 ], [ %.texmerge350474, %texmerge350.from.texblock352 ], [ %.texmerge350473, %texmerge350.from.texblock353 ], [ %.texmerge350472, %texmerge350.from.texblock354 ], [ %.texmerge350, %texmerge350.from.texblock355 ]
> PHI node operands are not the same type as the result!
>   %1272 = phi { float, float, float, float } [ %.texmerge356481, %texmerge356.from.texmerge350 ], [ %.texmerge356480, %texmerge356.from.texblock357 ], [ %.texmerge356479, %texmerge356.from.texblock358 ], [ %.texmerge356478, %texmerge356.from.texblock359 ], [ %.texmerge356477, %texmerge356.from.texblock360 ], [ %.texmerge356, %texmerge356.from.texblock361 ]
> Call parameter type does not match function signature!
>   %1268 = extractelement <4 x i32> %1226, i32 3
>  <4 x i32>  %2182 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload569, float* %.reload623, i32 %1268, i32 %1269, i32 0)
> Call parameter type does not match function signature!
>   %1255 = extractelement <4 x i32> %1226, i32 2
>  <4 x i32>  %2187 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload579, float* %.reload633, i32 %1255, i32 %1256, i32 0)
> Call parameter type does not match function signature!
>   %1242 = extractelement <4 x i32> %1226, i32 1
>  <4 x i32>  %2192 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload589, float* %.reload643, i32 %1242, i32 %1243, i32 0)
> Call parameter type does not match function signature!
>   %1229 = extractelement <4 x i32> %1226, i32 0
>  <4 x i32>  %2197 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload599, float* %.reload653, i32 %1229, i32 %1230, i32 0)
> LLVM ERROR: Broken function
> Abortado

Dunno 3 : Why from vkQuake version 1.13.1 to vkQuake 1.31.3 in every try i got the follow output : 

> Command line: ./vkquake.AppImage
> Found SDL version 2.0.22
> Detected 2 CPUs.
> Built with GCC 5.4.0
> Quake 1.09 (c) id Software
> GLQuake 1.00 (c) id Software
> FitzQuake 0.85 (c) John Fitzgibbons
> FitzQuake SDL port (c) SleepwalkR, Baker
> QuakeSpasm 0.94.5 (c) Ozkan Sezer, Eric Wasylishen & others
> QuakeSpasm-Spiked (c) Spike
> vkQuake 1.20.0 (c) Axel Gneiting & others
> Host_Init
> Playing registered version.
> Console initialized.
> UDP4 Initialized
> UDPv6 Initialized
> Server using protocol 999+ (FTE-RMQ)
> Exe: 07:37:56 Jun 28 2022
> 
> Vulkan Initialization
> Using Vulkan 1.1
> Using VK_KHR_surface
> Using VK_KHR_xlib_surface
> Using VK_KHR_get_surface_capabilities2
> Using VK_KHR_get_physical_device_properties2
> Vendor: Unknown (0x10005)
> Device: llvmpipe (LLVM 13.0.0, 128 bits)
> WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
> Using VK_KHR_swapchain
> Using VK_KHR_get_memory_requirements2
> Using VK_KHR_dedicated_allocation
> Using A2B10G10R10 color buffer format
> Using D32_S8 depth buffer format
> Creating command buffers
> Initializing staging
> Creating descriptor set layouts
> Reallocating dynamic VBs (256 KB)
> Reallocating dynamic IBs (1024 KB)
> Reallocating dynamic UBs (256 KB)
> Initializing samplers
> Texture lod bias: 0.000000
> Creating pipeline layouts
> Using IMMEDIATE present mode
> Creating color buffer
> AA disabled
> Creating depth buffer
> Creating render passes
> Creating frame buffers
> Creating pipelines
> detected controller: X360 Controller
> Allocating lightstyles buffer (0 KB)
> Allocating lights buffer (4 KB)
> 
> Sound Initialization
> SDL audio spec  : 44100 Hz, 1024 samples, 2 channels
> SDL audio driver: pulseaudio - ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) , 65536 bytes buffer
> Audio: 16 bit, stereo, 44100 Hz
> CDAudio disabled at compile time
> 
> Language initialization
> Couldn't load 'localization/loc_english.txt'
> from '/home/inukaze/Programas/Videojuegos/Disparos/Quake'
> 
> ========= Quake Initialized =========
> 
> execing quake.rc
> execing default.cfg
> couldn't exec config.cfg
> couldn't exec autoexec.cfg
> 3 demo(s) in loop
> Playing demo from demo1.dem.
> 
> 
> 
> the Necropolis
> Using protocol 15
> Allocating lightmap compute surface data (326 KB)
> PHI node operands are not the same type as the result!
>   %1233 = phi { float, float, float, float } [ %.texmerge466, %texmerge.from.bgnloop309 ], [ %.texmerge465, %texmerge.from.texblock ], [ %.texmerge464, %texmerge.from.texblock340 ], [ %.texmerge463, %texmerge.from.texblock341 ], [ %.texmerge462, %texmerge.from.texblock342 ], [ %.texmerge, %texmerge.from.texblock343 ]
> PHI node operands are not the same type as the result!
>   %1246 = phi { float, float, float, float } [ %.texmerge344471, %texmerge344.from.texmerge ], [ %.texmerge344470, %texmerge344.from.texblock345 ], [ %.texmerge344469, %texmerge344.from.texblock346 ], [ %.texmerge344468, %texmerge344.from.texblock347 ], [ %.texmerge344467, %texmerge344.from.texblock348 ], [ %.texmerge344, %texmerge344.from.texblock349 ]
> PHI node operands are not the same type as the result!
>   %1259 = phi { float, float, float, float } [ %.texmerge350476, %texmerge350.from.texmerge344 ], [ %.texmerge350475, %texmerge350.from.texblock351 ], [ %.texmerge350474, %texmerge350.from.texblock352 ], [ %.texmerge350473, %texmerge350.from.texblock353 ], [ %.texmerge350472, %texmerge350.from.texblock354 ], [ %.texmerge350, %texmerge350.from.texblock355 ]
> PHI node operands are not the same type as the result!
>   %1272 = phi { float, float, float, float } [ %.texmerge356481, %texmerge356.from.texmerge350 ], [ %.texmerge356480, %texmerge356.from.texblock357 ], [ %.texmerge356479, %texmerge356.from.texblock358 ], [ %.texmerge356478, %texmerge356.from.texblock359 ], [ %.texmerge356477, %texmerge356.from.texblock360 ], [ %.texmerge356, %texmerge356.from.texblock361 ]
> Call parameter type does not match function signature!
>   %1268 = extractelement <4 x i32> %1226, i32 3
>  <4 x i32>  %2182 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload569, float* %.reload623, i32 %1268, i32 %1269, i32 0)
> Call parameter type does not match function signature!
>   %1255 = extractelement <4 x i32> %1226, i32 2
>  <4 x i32>  %2187 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload579, float* %.reload633, i32 %1255, i32 %1256, i32 0)
> Call parameter type does not match function signature!
>   %1242 = extractelement <4 x i32> %1226, i32 1
>  <4 x i32>  %2192 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload589, float* %.reload643, i32 %1242, i32 %1243, i32 0)
> Call parameter type does not match function signature!
>   %1229 = extractelement <4 x i32> %1226, i32 0
>  <4 x i32>  %2197 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload599, float* %.reload653, i32 %1229, i32 %1230, i32 0)
> LLVM ERROR: Broken function
> Abortado

1.31.3 Output : 

> Command line: ./vkquake.AppImage
> Found SDL version 2.30.9
> Detected 2 CPUs.
> Initializing vkQuake 1.31.3
> Built with GCC 9.4.0
> Host_Init
> Playing registered version.
> Console initialized.
> UDP4 Initialized
> UDPv6 Initialized
> Server using protocol 999+ (FTE-RMQ)
> Exe: 16:04:20 Nov  8 2024
> 
> Vulkan Initialization
> Using Vulkan 1.1
> Instance extensions:
>  VK_KHR_surface
>  VK_KHR_xlib_surface
>  VK_KHR_get_surface_capabilities2
>  VK_KHR_get_physical_device_properties2
> 
> Vendor: MESA
> Device: llvmpipe (LLVM 13.0.0, 128 bits)
> Driver: llvmpipe Mesa 21.3.5 (LLVM 13.0.0)
> WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
> Device extensions:
>  VK_KHR_swapchain
>  VK_KHR_get_memory_requirements2
>  VK_KHR_dedicated_allocation
> Using A2B10G10R10 color buffer format
> Using D32_S8 depth buffer format
> 
> Creating command buffers
> Initializing staging
> Creating descriptor set layouts
> Reallocating dynamic vertex buffers (256 KB)
> Reallocating dynamic index buffers (1024 KB)
> Reallocating dynamic uniform buffers (256 KB)
> Initializing samplers
> Texture lod bias: 0.000000
> Creating pipeline layouts
> detected controller: X360 Controller
> Allocating lightstyles buffer (0 KB)
> Allocating lights buffer (8 KB)
> 
> Sound Initialization
> Using IMMEDIATE present mode
> Creating color buffer
> AA disabled
> Creating depth buffer
> Creating render passes
> Creating frame buffers
> Creating pipelines
> SDL audio spec  : 44100 Hz, 1024 samples, 2 channels
> SDL audio driver: pulseaudio - ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) , 65536 bytes buffer
> Audio: 16 bit, stereo, 44100 Hz
> 
> Language initialization
> Couldn't load 'localization/loc_english.txt'
> from '/home/inukaze/Programas/Videojuegos/Disparos/Quake'
> 
> ========= Quake Initialized =========
> 
> execing quake.rc
> execing default.cfg
> execing config.cfg
> Unknown command "gl_subdivide_size"
> Unknown command "gl_triplebuffer"
> Unknown command "joy_deadzone"
> Unknown command "vid_bpp"
> couldn't exec autoexec.cfg
> 3 demo(s) in loop
> Playing demo from demo1.dem.
> 
> 
> 
> the Necropolis
> Using protocol 15
> Allocating lightmap compute surface data (326 KB)
> Allocating indirect draw data (1 KB, 72 draws)
> Allocating indirect IBs (165 KB)
> Allocating visibility buffers (1 KB)
> PHI node operands are not the same type as the result!
>   %1781 = phi { float, float, float, float } [ %.texmerge647, %texmerge.from.bgnloop468 ], [ %.texmerge646, %texmerge.from.texblock ], [ %.texmerge645, %texmerge.from.texblock501 ], [ %.texmerge644, %texmerge.from.texblock502 ], [ %.texmerge, %texmerge.from.texblock503 ]
> PHI node operands are not the same type as the result!
>   %1794 = phi { float, float, float, float } [ %.texmerge504651, %texmerge504.from.texmerge ], [ %.texmerge504650, %texmerge504.from.texblock505 ], [ %.texmerge504649, %texmerge504.from.texblock506 ], [ %.texmerge504648, %texmerge504.from.texblock507 ], [ %.texmerge504, %texmerge504.from.texblock508 ]
> PHI node operands are not the same type as the result!
>   %1807 = phi { float, float, float, float } [ %.texmerge509655, %texmerge509.from.texmerge504 ], [ %.texmerge509654, %texmerge509.from.texblock510 ], [ %.texmerge509653, %texmerge509.from.texblock511 ], [ %.texmerge509652, %texmerge509.from.texblock512 ], [ %.texmerge509, %texmerge509.from.texblock513 ]
> PHI node operands are not the same type as the result!
>   %1820 = phi { float, float, float, float } [ %.texmerge514659, %texmerge514.from.texmerge509 ], [ %.texmerge514658, %texmerge514.from.texblock515 ], [ %.texmerge514657, %texmerge514.from.texblock516 ], [ %.texmerge514656, %texmerge514.from.texblock517 ], [ %.texmerge514, %texmerge514.from.texblock518 ]
> Call parameter type does not match function signature!
>   %1816 = extractelement <4 x i32> %1774, i32 3
>  <4 x i32>  %3133 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload779, float* %.reload831, i32 %1816, i32 %1817, i32 0)
> Call parameter type does not match function signature!
>   %1803 = extractelement <4 x i32> %1774, i32 2
>  <4 x i32>  %3137 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload787, float* %.reload839, i32 %1803, i32 %1804, i32 0)
> Call parameter type does not match function signature!
>   %1790 = extractelement <4 x i32> %1774, i32 1
>  <4 x i32>  %3141 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload795, float* %.reload847, i32 %1790, i32 %1791, i32 0)
> Call parameter type does not match function signature!
>   %1777 = extractelement <4 x i32> %1774, i32 0
>  <4 x i32>  %3145 = call fastcc { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @texfunc_res_0_sam_0_24({ [16 x float*], [16 x i32], [128 x { i32, i32, i32, i8*, [15 x i32], [15 x i32], i32, i32, [15 x i32], i32, i32 }], [32 x { float, float, float, [4 x float], float }], [32 x { i32, i32, i32, i8*, i32, i32, i32, i32 }], [16 x i32*], [16 x i32], i8*, i32, float* }* %.reload803, float* %.reload855, i32 %1777, i32 %1778, i32 0)
> LLVM ERROR: Broken function
> Abortado
> 

Well i can start the game using vkQuake 1.12.2, and well my hardware is very old and is very slow, i want try disabling AA Mode.

Some one engine can support Arcane mods ?

**Comment by Novum** [comment]
Your Vulkan GPU driver isn't working. llvmpipe is the Mesa3D software renderer.

**Comment by inukaze** [comment]
> vkquake.cfg

What should be the default absolute path of the file vkquake.cfg under GNU/Linux ?
