### ISSUE TITLE
libvulkan.so.1 seems to be missing?

### ISSUE THREAD

**Issue by Svetomech** [Novum/vkQuake#76]
I get this error when trying to run the binary (either by itself or using a **vkquake-launch.sh** wrapper):
`error while loading shared libraries: libvulkan.so.1: cannot open shared object file: No such file or directory
`

I googled the error. Most answers say I must have VulkanSDK installed. Is that correct? I thought that a Vulkan-supported videocard w/ updated drivers are enough to run the game.

This is what I have:
![screenshot](https://cloud.githubusercontent.com/assets/7114815/20800297/174a3f32-b7f6-11e6-84d1-62aa3369d604.png)

**Comment by ProfessorKaos64** [comment]
Ok, I may have missed adding that lib. I will check the libs folder for the library.

**Comment by Svetomech** [comment]
Don't. It is present, but doesn't seem to load properly.

**Comment by ProfessorKaos64** [comment]
Can you please provide your Linux distirubtion details? I can try to reproduce the error when I get home in a few hours. It's possible I made a mistake somewhere.

**Comment by Svetomech** [comment]
My distro is **Linux Mint 18**. Also, I got the libraries to load (**export** was behaving weird for some reason), but now all I get is an uninformative `Segmentation fault`.

**Comment by ProfessorKaos64** [comment]
I tried `./vkquake-launch` on my Debian VPS, and it loads up until the point where it is trying to load the WAD files. I will setup a VM later this evening for Mint to reproduce. If this does not work for you in the end, I will host vkquake on my PPA here: https://launchpad.net/~mdeguzis/+archive/ubuntu/libregeek-games  . The owner here does not wish to support/provide distro packages.

**Comment by Svetomech** [comment]
Hmm, I think I know what is the problem here. I downloaded **vulkan-utils** package and ran **vulkaninfo**: `Cannot create Vulkan instance.
/build/vulkan-1P8eOh/vulkan-1.0.8.0+dfsg1/demos/vulkaninfo.c:633: failed with VK_ERROR_INCOMPATIBLE_DRIVER`

So, what driver are you using exactly on your Debian VPS? [Compatibility page](https://en.wikipedia.org/wiki/Vulkan_(API)#Compatibility) says **Mesa** is supported, but **vulkaninfo** says otherwise, it seems. Do I have to pull it from some PPA and not from official repositories?

**Comment by ProfessorKaos64** [comment]
You need to check your driver version with `lspci -v`.  You could also check http://vulkan.gpuinfo.org/ for more. I often will tell people to check their driver against the release notes page, or the manufacturers listing as well. For instance, Nvidia has a page such as: https://developer.nvidia.com/vulkan-driver

**Comment by Svetomech** [comment]
I've installed latest Mesa drivers from [here](https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa). **vulkaninfo** output is now diferrent: [stdout.txt](https://github.com/Novum/vkQuake/files/625517/stdout.txt), [stderr.txt](https://github.com/Novum/vkQuake/files/625518/stderr.txt)

Here is info from the site you mentioned for my device
![screenshot](https://cloud.githubusercontent.com/assets/7114815/20807948/dfd4ce8e-b811-11e6-835f-8042c41e261d.png)

vkQuake still gives me a `Segmentation fault`.

**Comment by Novum** [comment]
This is not the official "my driver installation is broken" support page.

**Comment by Svetomech** [comment]
`Segmentation fault` might not be related to that (I tried some other Vulkan demos, like **vkcube** - they do work).
But okay, you're the repo owner, you can close the issue regardless of its ‌state.

**Comment by Novum** [comment]
Please report to Intel, the seg fault is 99% likely a driver bug.

**Comment by Svetomech** [comment]
Okay.

**Comment by Svetomech** [comment]
Wait. I installed vkQuake from the PPA given by @mtdeguzis and now seg fault is no more.
```
Command line: vkquake .
Found SDL version 2.0.4
Detected 4 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.92.1 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 0.72.0 (c) Axel Gneiting
Host_Init
Playing shareware version.

ERROR-OUT BEGIN


QUAKE ERROR: W_LoadWadFile: couldn't load gfx.wad
```
Where should I put game files? Is there a command line parameter to set a base directory?

**Comment by mtdeguzis** [comment]
@Svetomech , since you are not using a hand-compiled version here, this is outside the scope of this issue. Feel free to contact me via libregeek.org or LaunchPad. It is not Novum's court now that you are using a different installation method.

**Comment by Svetomech** [comment]
> to contact me via libregeek.org or LaunchPad

Didn't even know it is possible w/ the latter and never heard of the former. But okay, sure.

@Novum, sorry for all the inconvenience.
