### ISSUE TITLE
Shaders/Compiled/screen_warp_comp.o does not exist

### ISSUE THREAD

**Issue by mtdeguzis** [Novum/vkQuake#78]
The latest Makefile swaps out a shader object, but if you don't pass "make" alone, you will get the below error. The object file is not found within the directory as the others. Seems it was not uploaded to the Shaders dir.

```
make: *** No rule to make target 'screen_warp_comp.o', needed by 'vkquake'.  Stop.
make: *** Waiting for unfinished jobs....
make: Leaving directory '/home/desktop/package-builds/build-vkquake-tmp/vkquake-0.90.0/Quake'
make: Entering directory '/home/desktop/package-builds/build-vkquake-tmp/vkquake-0.90.0/Misc/vq_pak'
./mkpak.sh gfx/conback.lmp maps/e1m1.ent maps/e1m2.ent maps/e1m4.ent maps/e2m2.ent maps/e2m3.ent maps/e2m7.ent default.cfg > vkquake.pak
make: Leaving directory '/home/desktop/package-builds/build-vkquake-tmp/vkquake-0.90.0/Misc/vq_pak'
```

**Comment by Novum** [comment]
Fixed by 5871289

**Comment by mtdeguzis** [comment]
Pushing this into the .90 release or adding a new tag?

**Comment by Novum** [comment]
I don't think github allows me to do that

**Comment by mtdeguzis** [comment]
You're free to remove and readd attached binaries /files. If not, tag a new release. 

On December 5, 2016 9:06:53 PM EST, Axel Gneiting <notifications@github.com> wrote:
>I don't think github allows me to do that
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Novum/vkQuake/issues/78#issuecomment-265039586

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mtdeguzis** [comment]
Regardless of what you decided, I uploaded a Linux binary release with the fixed code.

**Comment by Novum** [comment]
Took me a while but the tag & release should be fixed now

**Comment by sezero** [comment]
The linux tarball is broken: gunzip reports unexpected end of file for it.

**Comment by mtdeguzis** [comment]
Will fix. Probably a faulty upload. 

On December 6, 2016 3:33:04 AM EST, sezero <notifications@github.com> wrote:
>The linux tarball is broken: gunzip reports unexpected end of file for
>it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Novum/vkQuake/issues/78#issuecomment-265090887

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mtdeguzis** [comment]
@sezero , now the archive is the expected 6.95 MB it should be. Tested from GitHub and locally. Original files are hosted at: http://packages.libregeek.org/linux-binaries/stable/

**Comment by sezero** [comment]
Yes, it is good now, thanks.
