### ISSUE TITLE
Provide Windows binaries

### ISSUE THREAD

**Issue by adolfintel** [Novum/vkQuake#8]
Please consider uploading precompiled Windows binaries, nobody wants to compile stuff on Windows, especially if it involves installing Visual Studio

**Comment by bviktor** [comment]
Actually, I'd still be happy to compile it on my own, except I can't figure out how to obtain vulkan.h. A guide would help.

**Comment by adolfintel** [comment]
There's a vulkan-headers package in the Arch Linux repos, you might be able to use it to cross compile

**Comment by adolfintel** [comment]
Or maybe here https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/vulkan/vulkan.h

**Comment by bviktor** [comment]
I doubt that would work. There's no libraries to link against. I think an SDK is needed, maybe LunarG, but that requires a Khronos account.

**Comment by Novum** [comment]
The port still has bugs and is generally unfinished. I will not provide binaries until I am confident it runs well.

The Vulkan SDK download does not require a Khronos account, download is at the bottom of vulkan.lunarg.com

**Comment by bviktor** [comment]
Oh I'm blind **and** dumb, thanks. Successfully compiled and running it already :)

http://i.imgur.com/4ve7cdW.png

Pretty awesome, thanks for your work, good luck with the project :)
