### ISSUE TITLE
No support for CD Audio?

### ISSUE THREAD

**Issue by Svetomech** [Novum/vkQuake#80]
`CDAudio disabled at compile time`
Do I have to compile vkQuake manually to enable CD Audio support?

**Comment by mtdeguzis** [comment]
Did you try adding the audio tracks per the readme? Or is this just a message you noticed and are concerned about?

**Comment by Svetomech** [comment]
No, I tried .mp3 and .ogg formats - no noticeable changes.

**Comment by mtdeguzis** [comment]
Are you sure you installed all the dependencies? [Here](https://launchpadlibrarian.net/296669153/buildlog_ubuntu-yakkety-amd64.vkquake_0.90~yakkety1-1_BUILDING.txt.gz) is a build log for Ubuntu. The text "SDL CDAudio support disabled" does appear, but this should not affect the tracks ability to play.  If you have followed the readme exactly as written for CD Audio, you could try seeing if the files are owned by another user (say root), or are not readable.

**Comment by Novum** [comment]
SDL2 has no support for CD audio. MP3, Ogg etc. should work like in QuakeSpasm.

**Comment by Svetomech** [comment]
> Are you sure you installed all the dependencies?

I was, but it never hurts to double check. What is the name of the package I should install for vkQuake to read .ogg files? There's only a library name in the readme.

And no, all files are owned by the current user and are perfectly readable (e.g. in a music player).

**Comment by Novum** [comment]
It works perfectly fine, I just checked.
