### ISSUE TITLE
UnderwaterFX setting is forgotten upon each start

### ISSUE THREAD

**Issue by Svetomech** [Novum/vkQuake#81]
Just what it says in the title. The setting always resets to "Classic" when restarting the game.

Also, if I try to "Test changes" after changing it, nothing will happen (as if no setting was changed).

**Comment by Novum** [comment]
Thanks, forgot about dealing with that. Will be fixed in the next release.

**Comment by Novum** [comment]
Fixed by a14318f6ddeca2b3127c07930c3bfde55c685079
