### ISSUE TITLE
Antialiasing is too slow

### ISSUE THREAD

**Issue by Svetomech** [Novum/vkQuake#86]
Please, allow setting different MSAA values. 

8x is too high for a laptop equipped w/ Ivy Bridge integrated videocard (FPS < 15). ~~Either that or the algorithm is not implemented properly :)~~

**Comment by Novum** [comment]
I suspect a driver bug, even that potato should be fast enough for Quake even with MSAA.

**Comment by Svetomech** [comment]
> Even that potato should be fast enough for Quake with MSAA.

That's what I thought too, so was a bit surprised when it didn't.

Still, 4x option would be nice to at least try and see if anything changes.

**Comment by Novum** [comment]
I feel like this is going to be a won't fix. I don't see the value when everybody would just turn it to max anyway in such an old game.

**Comment by Svetomech** [comment]
I tried running Talos Principle (Vulkan beta) today. Strange, but I do get around the same FPS (15-25) in it w/o antialiasing as in vkQuake w/ antialiasing :D

**Comment by Novum** [comment]
You are probably really bandwidth limited with MSAA, but Quake is very low poly and bandwidth compression should be almost perfect, so I do not expect those performance numbers. So either it's not implemented in their driver or their hardware just doesn't have compression, which would be super odd.

**Comment by Novum** [comment]
It does indeed exist, there is a patch for OpenGL adding it to mesa:
https://lists.freedesktop.org/archives/mesa-dev/2012-July/023707.html

Closing this. You should complain at Intel to fix this.

**Comment by Svetomech** [comment]
Just did.

**Comment by Novum** [comment]
I added support to choose number of samples in d0f5c8c5879d92b4edf4a436068729649b2eeb4e

**Comment by Svetomech** [comment]
Thank you. When will the new binary be available? Also, it seems @mdeguzis has abandoned his PPA.

>Even some Skylake HD graphics are too potato to run 1080p at 8x AA at 60 Hz

Wow. It seems I either was right or this is a common issue on videocards with low memory and Vulkan.
