### ISSUE TITLE
Have vkQuake pull from the QuakeSpasm svn at compile

### ISSUE THREAD

**Issue by shoober420** [Novum/vkQuake#88]
Nvidia is supposedly releasing drivers that will allow Vulkan without the use of X.org. I would love to try out vkQuake on Wayland when it's released. I normally use QuakeSpasm svn on Arch Linux. I just do svn pulls very often. I was wondering if you could make it possible at compile time to pull from the QuakeSpasm svn everytime you do a git pull of vkQuake. Is this possible? I always use the latest development version of source ports when I can.

**Comment by Novum** [comment]
No.
