### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#89]
Code changes should be minor, but I don't have a machine to test this. Needs support for VK_KHR_wayland_surface

**Comment by mdeguzis** [comment]
I am willing to test once code is added. If you want to use another branch, that is fine.

**Comment by Novum** [comment]
This is more like a suggestion for other people to write it. I don't have a Linux machine and I don't want to write code blindly I can't even compile.

**Comment by Novum** [comment]
Although thinking about it a bit more, I don't know what the status on SDL & Wayland is.

**Comment by mdeguzis** [comment]
The Arch Linux wiki is usually a good place to start, since they are bleeding edge. It seems support is merely [experimental](https://wiki.archlinux.org/index.php/wayland#SDL) at the moment. Advancements have been pouring in this year, but I don't believe it is quite complete yet. The [wayland landing page](https://wayland.freedesktop.org/toolkits.html) usually keeps an overview.

**Comment by shoober420** [comment]
I would also test this once Nvidia releases drivers that support vulkan under Wayland without xorg.

**Comment by Novum** [comment]
I don't need tests, I need somebody to write the code.

**Comment by Novum** [comment]
Should be fixed by a69c20b348e42623e3ad056c07c30fb87fac6618. The SDL2 Vulkan code has Wayland support.

**Comment by myfreeweb** [comment]
Doesn't seem to be working. With `SDL_VIDEODRIVER=wayland` the game window just does not appear. The console output is like normal, quake initialized and everything. But there's no window. SDL2's `testvulkan` demo does work fine with `SDL_VIDEODRIVER=wayland`…

**Comment by mooreye** [comment]
On Wayland I get:

`QUAKE ERROR: Couldn't create window: Vulkan support is either not configured in SDL or not available in current SDL video driver (offscreen) or platform`

with `SDL_VIDEODRIVER=wayland` I get:

`QUAKE ERROR: Couldn't init SDL video: wayland not available`

on X11 it works fine.

**Comment by valpackett** [comment]
@mooreye check your SDL2 build. vkquake itself doesn't have any issues since way back when

**Comment by Novum** [comment]
QuakeSpasm doesn't use Vulkan.
