### ISSUE TITLE
Validation Error: Invalid Pipeline Layout Object

### ISSUE THREAD

**Issue by nanley** [Novum/vkQuake#92]
When starting a new game (Single Player -> New Game) with validation layers enabled, the following error appears on the commandline:
ObjectTracker(ERROR): object: 0x2b type: 17 location: 348 msgCode: 994: Invalid Pipeline Layout Object 0x2b. For more information refer to Vulkan Spec Section '13.2.6. Push Constant Updates' which states 'layout must be a valid VkPipelineLayout handle' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#vkCmdPushConstants)

**Comment by Novum** [comment]
What driver? I don't get any validation errors.

**Comment by nanley** [comment]
I'm using the VK_LAYER_LUNARG_standard_validation layer (Vulkan version 1.0.39, layer version 1). This was built today from the VulkanTools repository https://github.com/LunarG/VulkanTools.git , commit 9cb738e779ba54dc9c6b4fb4688622e60c342e74. I'm still able to reproduce this issue, which leads to a segmentation fault in the Mesa Intel Vulkan driver.

I'm running the validation layer with a commandline script that is similar to the following:
VKVAL_BUILD=$REPOS/github/VulkanTools
LAYER=VK_LAYER_LUNARG_standard_validation
VK_LAYER_PATH=$VKVAL_BUILD/dbuild/layers \
VK_INSTANCE_LAYERS=$LAYER \
VK_DEVICE_LAYERS=$LAYER \
LD_LIBRARY_PATH=$VKVAL_BUILD/dbuild/loader \
$MESA_BUILD_LOADER ./vkQuake

**Comment by Novum** [comment]
Please use the layers shipped with the SDK and not some random commit.

**Comment by nanley** [comment]
Thank you for your patience. It seems like gnu make failed to recompile files that were updated via git pull. This seems to have caused me to run the validation layers on an older version of vkQuake. 'make clean && make' solved this for me.
