### ISSUE TITLE
couldn't load gfx.wad Ubuntu 

### ISSUE THREAD

**Issue by gameslayer** [Novum/vkQuake#95]
I just git cloned vkquake and compiled it on Ubuntu and I can't run it because it couldn't load "gfx.wad" is it missing or did something go wrong? nothing in the make logs show any errors.

**Comment by mdeguzis** [comment]
https://github.com/Novum/vkQuake/issues/4#issuecomment-235151961

**Comment by gameslayer** [comment]
This doesn't fix the issue I cd to ./vkQuake/Quake/ than did ./vkquake and got the same error

**Comment by mdeguzis** [comment]
You have .pk3, not .pak.pk3

```
mikeyd@archboxmtd id1 $ file pak0.pak
pak0.pak: Quake I or II world or extension, 21696 entries

mikeyd@archboxmtd id1 $ file /usr/share/gzdoom/brightmaps.pk3
/usr/share/gzdoom/brightmaps.pk3: Zip archive data, at least v2.0 to extract
```

PK3 files are merely archives.

**Comment by gameslayer** [comment]
I got my pak files from my ioquake which works fine so what do I nee to do?

**Comment by gameslayer** [comment]
Sorry I meant ioquake3 which I downloaded the quake pak files to use ioquake3, here is a screenshot of all my pak files in ioquake3

http://i.imgur.com/3bAt3Vq.png

**Comment by mdeguzis** [comment]
This project is Quake 1 only. There nothing here compatible with Quake 3.

**Comment by gameslayer** [comment]
oh right so I need to get quake 1 pak files, you might want to explain that on the github page so no one gets confused on what pak files you even need since it doesn't explain what version quake it is

**Comment by mdeguzis** [comment]
If it was meant for anything else, it would say Quake 2 or Quake 3. Quake is Quake.

**Comment by gameslayer** [comment]
Well yes but vkquake as a name could mean any of the versions haha anyways I am downloading the shareware pak file and I will let you know how it goes

**Comment by mdeguzis** [comment]
Oh the link to shareware? That is just one someone snuck in there, there may be other links on the net.  I'll see if I can find an alternative when I get home later.

**Comment by gameslayer** [comment]
I unpacked it, it made a ID1 folder with the pak file, copied over the whole folder into the quake folder and I still get the same error :(

**Comment by slim-one** [comment]
did you make sure id1 foldername and pak-filenames are lowercase?

**Comment by gameslayer** [comment]
Yes all working thanks for the help, sorry I wasn't understanding what I needed to do to get the game working :D

**Comment by Novum** [comment]
Not a vkQuake bug

**Comment by rykerOnGithubDotCom** [comment]
Linux is case-sensitive, all ports of quake look for pak0.pak and pak1.pak and the steam version and possible every official version have the pak files PAK0.PAK and PAK1.PAK. Make them lowercase and it will work.

**Comment by coreybruce** [comment]
Oh ok I'll try that and report back any issue.
